### ISSUE TITLE
Add a type annotation to all jOOQ API that accepts explicit string types

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10030]
There are currently 4 types of `String` in jOOQ's API:

- Bind values
- Plain SQL templates
- Identifiers
- Keywords

Since Java 8, it is possible to create new types of `String` by annotating them with a type annotation. We should introduce (name and namespacing to be defined):

- `@Stringly.Param` (for `org.jooq.Param`)
- `@Stringly.SQL` (for `org.jooq.SQL`)
- `@Stringly.Name` (for `org.jooq.Name`)
- `@Stringly.Keyword` (for `org.jooq.Keyword`)
- `@Stringly.Comment` (for `org.jooq.Comment`)

For example:

- `DSL.repeat(@Stringly.Param String field, int count)`
- `DSL.table(@Stringly.SQL String sql)`
- `DSL.createTable(@Stringly.Name String name)`
- `DSL.keyword(@Stringly.Keyword String keyword)` (that's probably the only instance)
- `DSL.commentOnTable(...).is(@Stringly.Comment String comment)`

Alternatively, we could also just add more Javadoc, everywhere, but the annotations might help with additional static code analysis (to be discovered).

**Tasks**

- [x] Add the annotations
- [x] Annotate generated API (see #9163)
- [x] Annotate other API

----
See also:
https://blog.jooq.org/2020/04/03/whats-a-string-in-the-jooq-api/

**Comment by lukaseder** [comment]
In jOOQ 3.15, a lot of standardisation of DSL APIs is taking place in the context of #9163. This may be a good opportunity to implement this feature!

**Comment by lukaseder** [comment]
This will be another epic task, which won't be completed 100% until all of #9163 has been implemented. The good thing is, it will be completed automatically.
