### ISSUE TITLE
Add support for SQL Server MERGE .. WHEN NOT MATCHED BY { SOURCE | TARGET }

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10059]
SQL Server supports the very useful `MERGE` extension `WHEN NOT MATCHED BY { SOURCE | TARGET }`. While `BY TARGET` is the default behaviour and corresponds to what all other dilalects implement, `BY SOURCE` is a really useful addition that turns the `MERGE`'s usual `RIGHT JOIN` into a more useful `FULL JOIN`, which is especially useful for deletions.

In order to emulate this clause, we'd have to `FULL JOIN` the `MERGE` target table to the source table without modifying the source table's semantics. Might be worth a try.

### Tasks

- [x] Parser support
- [x] https://github.com/jOOQ/jOOQ/issues/10715
  - [ ] Investigate emulations / dialect support
- [ ] Test interactions with policies

----
See: https://blog.jooq.org/the-many-flavours-of-the-arcane-sql-merge-statement/

**Comment by lukaseder** [comment]
Currently, the order of `WHEN MATCHED` and `WHEN NOT MATCHED` clauses is fixed. This feature here requires flexibility of the ordering, which is fine, but will probably lead to incompatible changes and/or deprecations, as we'll have to fix the API

**Comment by lukaseder** [comment]
PostgreSQL 17 will have these clauses as well:

- https://www.postgresql.org/docs/17/sql-merge.html

Let's investigate this

**Comment by strindberg** [comment]
Now that PostgreSQL 17 has been released, this would be of great use to us.

**Comment by lukaseder** [comment]
Emulation seems possible in principle:

- https://github.com/jOOQ/jOOQ/issues/17775

I'll consider this in a second step. Native support has priority, as always.

**Comment by lukaseder** [comment]
Implemented in version 3.20.0
