### ISSUE TITLE
Generate dialect specific rendering information in manual

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10127]
Our documentation about function / feature emulations is notoriously outdated. We need a way to automate the generation of dialect specific information in manual and Javadoc. For example, the MD5() function:
https://github.com/jOOQ/jOOQ/issues/10126

As of jOOQ 3.14, it is annotated with:

```java
@Support({ AURORA_MYSQL, AURORA_POSTGRES, COCKROACHDB, MARIADB, MEMSQL, MYSQL, ORACLE, POSTGRES, SQLDATAWAREHOUSE, SQLSERVER })
```

We should have an example that calls e.g.

```java
md5("abc");
```

And generates automatically:

```sql
AURORA_MYSQL        :md5('abc')
AURORA_POSTGRES     :md5('abc')
COCKROACHDB         :md5('abc')
MARIADB             :md5('abc')
MEMSQL              :md5('abc')
MYSQL               :md5('abc')
ORACLE              :lower(standard_hash('abc', 'MD5'))
POSTGRES            :md5('abc')
SQLDATAWAREHOUSE    :lower(convert(varchar(32), hashbytes('MD5', cast('abc' as varchar(8000))), 2))
SQLSERVER           :lower(convert(varchar(32), hashbytes('MD5', cast('abc' as varchar(max))), 2))
```

If this is automated, it will always be up to date with integration tested functionality, on a per-version basis.

### Subtasks:

- [x] Provide a canonical implementation based on the api-diff's `.jar` download and ASM introspection API to find `SQLDialect` per API method
- [x] Allow for using generated code
- [x] ~Provide a few default columns, such as `A`, `B`, `C` (strings), `X`, `Y`, `Z` (numbers)~
- [x] Generate the SQL with the appropriate jOOQ minor release, instead of the latest build (will be done separately: #10141)
- [x] Group SQL by generated string, aggregating dialects into a CSV
  - [x] Don't list all dialects, if all dialects support a feature and also all dialects produce the same string
  - [x] List also all unsupported dialects
- [x] Better formatting / indentation
- [x] ~Do this also for the condition section~

**Comment by lukaseder** [comment]
We'll do this for the manual first. Building the manual already provides some infrastructure where we can load pre-built `jar` files to read the `@Support` annotation on specific functions, to see which dialects support it.

Might implement for Javadoc separately

**Comment by lukaseder** [comment]
The current implementation checks the correct `.jar` file per minor release for `@Support` annotations, but uses the latest one to generate the SQL.

We'd have to play around with class loaders to make sure we have version-specific content, which would be nice, because we sometimes change the emulation of some functionality per version.

**Comment by lukaseder** [comment]
This is already very cool:

![image](https://user-images.githubusercontent.com/734593/80389372-43699700-88ab-11ea-898d-bf1118ccbbe9.png)

But even better if the renderings were grouped like this:

```sql
-- ASE, HSQLDB, SQLDATAWAREHOUSE, SQLSERVER, SYBASE
(1 * cast(power(2, 4) as int))

-- AURORA_MYSQL, AURORA_POSTGRES, COCKROACHDB, CUBRID, MARIADB, MEMSQL, MYSQL, POSTGRES, SQLITE, VERTICA
(1 << 4)

-- DB2, INFORMIX
(1 * cast(power(2, 4) as integer))

-- FIREBIRD
bin_shl(1, 4)

-- H2
lshift(1, 4)

-- ORACLE
(1 * cast(power(2, 4) as number(10)))

-- TERADATA
shiftleft(1, 4)
```

**Comment by lukaseder** [comment]
Clearly, the formatting can be improved for some longer expressions

![image](https://user-images.githubusercontent.com/734593/80404740-ea592d80-88c1-11ea-843f-58c065f77e1d.png)

**Comment by lukaseder** [comment]
jOOQ version specific renderings will be done separately: #10141
