### ISSUE TITLE
Get HANA dialect support up to date

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10153]
A few features have been added to jOOQ, which may be supported by HANA as well. These include (list will be amended):

**DML**:

- [x] `WITH` clause
- [x] ~Collection derived table (`UNNEST`). Seems only supported in SQLScript contexts~
- [x] `MERGE`
- [x] `GROUP BY ()` doesn't work. Emulate with equivalent `GROUP BY GROUPING SETS (())` instead
- [x] `ARRAY` types don't work as bind variables. We have to inline them, always: https://stackoverflow.com/a/40119424/521799

**DDL**:

Many of these already work, but are lacking `@Support({ HANA })` annotations

- [x] `ON DELETE NO ACTION` (the default in most dialects) is not supported by HANA. It is almost the same thing as `ON DELETE RESTRICT`, which is the default in HANA. We could emulate it using `RESTRICT`
- [x] `ALTER TABLE .. ALTER COLUMN` support
- [x] `ALTER TABLE .. ADD` multi column support
- [x] `ALTER TABLE .. DROP` multi column support
- [x] `ALTER TABLE .. DROP PRIMARY KEY` support
- [x] `COMMENT` support
- [x] `CREATE GLOBAL TEMPORARY TABLE`
- [x] `CREATE OR REPLACE VIEW`
- [x] `CREATE SCHEMA` and `DROP SCHEMA` support
- [x] `RENAME` statement support: https://help.sap.com/viewer/7c78579ce9b14a669c1f3295b0d8ca16/Cloud/en-US/20fbadb2751910148b24d8d93aff01d4.html
- [x] `IF [ NOT ] EXISTS` emulation using `DECLARE EXIT HANDLER`
- [x] `GENERATED BY DEFAULT AS IDENTITY` support

**Functions**:

- [x] `JSON_TABLE`: https://help.sap.com/viewer/7c78579ce9b14a669c1f3295b0d8ca16/Cloud/en-US/f8f6916b5c434a6fbd1bb7e0dc65acd4.html
- [x] `XMLTABLE`: https://help.sap.com/viewer/7c78579ce9b14a669c1f3295b0d8ca16/Cloud/en-US/2bb8ab119e384b5f94635696bb9f68b5.html
- [x] `EXTRACT()`: Support all the date parts from #2132
- [x] Better date time arithmetic support (e.g. `Field.add(Interval)`)

**Window functions**:

- [x] `NTH_VALUE`

**Procedural language support**:

- [x] `DO BEGIN .. END`: https://help.sap.com/viewer/7c78579ce9b14a669c1f3295b0d8ca16/Cloud/en-US/52103853351841f6a1e87f40b2686da9.html
- [x] `IF`: https://help.sap.com/viewer/6f5d6e0450784ed59cc844f0b9680bb8/Cloud/en-US/46e875a0d4e446ae9ab08334f13cd1aa.html
- [x] `WHILE`: https://help.sap.com/viewer/6f5d6e0450784ed59cc844f0b9680bb8/Cloud/en-US/6b2f29bbddcc431da72d9602a3049d93.html
- [ ] `FOR`: https://help.sap.com/viewer/6f5d6e0450784ed59cc844f0b9680bb8/Cloud/en-US/76ff9f7d7cb24eaa8645f26e4b47c47f.html
  - Caveat: In HANA, the `FOR` loop operates on a previously declared local variable, which by consequence, is in scope outside of the loop and will receive the loop's last increment. We have two options of how to handle this here:
    - Wrap the `FOR i` loop in `BEGIN DECLARE i .. FOR .. END` block to emulate the behaviour of other dialects
    - Generate the `FOR` loop exactly as the user writes it, assuming they *want* HANA's behaviour
  - Both of the above options can be combined with new, synthetic API that makes this choice explicit.
- [x] `BREAK` and `CONTINUE`: https://help.sap.com/viewer/6f5d6e0450784ed59cc844f0b9680bb8/Cloud/en-US/f5f57f41699f4a9ebfea210552dca429.html

**Code generation**

- [x] `CHECK` constraint sources
- [x] `TableOptions` and `VIEW` sources
- [x] `COMMENT`
- [x] ~`ARRAY` types in stored procedure and function parameters~: Implemented separately: #10216
- [ ] Table valued functions

**Data types**

- [ ] `TINYINT` is unsigned in HANA: #10297

**Comment by lukaseder** [comment]
To be continued in 3.15: #10437
