### ISSUE TITLE
Add a way to filter out objects from org.jooq.Meta instances

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10204]
Users can query `org.jooq.Meta` instances for specific catalogs, schemas, or tables, but it is currently not possible to produce new instances with a filter based on existing ones for further processing.

For example, when using `DSLContext.meta()`, we will always get all the catalogs and all the schemas for inclusion in method calls like `Meta.migrateTo()` when in fact, we would like to be able to exclude e.g. the `INFORMATION_SCHEMA`.

We should add:

```java
public interface Meta {
    Meta filterCatalogs(Predicate<? super Catalog>);
    Meta filterSchemas(Predicate<? super Schema>);
    Meta filterTables(Predicate<? super Table<?>>);
    Meta filterDomains(Predicate<? super Domain<?>>);
    Meta filterSequences(Predicate<? super Sequence<?>>);
    Meta filterPrimaryKeys(Predicate<? super UniqueKey<?>>);
    Meta filterIndexes(Predicate<? super Index>);
}
```

The resulting `Meta` instance is a view on the original one.

### Tasks:

- [x] Filter `Catalog`, `Schema`, `Table`, `Domain`, `Sequence`
- [x] Filter `PrimaryKey`, `Index`
- [x] Refactor existing implementations, including `CatalogMetaImpl`, `SchemaMetaImpl`, `TableMetaImpl`
- [x] Make sure that `Meta.getTables().get(0).getSchema().getTables()` reproduces the same filtered list (see also: #9396, #10276)

**Comment by lukaseder** [comment]
Increasing the priority. I've been doing some work on jOOQ's JDBC `DatabaseMetaData` backed `Meta` API recently. Hard to believe how long we've been loading the `master` and other system databases in our slow integration tests all the time, in SQL Server.

**Comment by lukaseder** [comment]
We could refactor some of our existing implementations to use this new `filter` API, including:

- `CatalogMetaImpl`
- `SchemaMetaImpl`
- `TableMetaImpl`

**Comment by lukaseder** [comment]
A first implementation draft has been added, and already speeds up integration tests e.g. for SQL Server to run in 110 seconds rather than 380 seconds.
