### ISSUE TITLE
Add missing <includeXYZ/> flag documentation to manual

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10246]
There are quite a few `<includeXYZ/>` flags that are still undocumented from the XSD: https://www.jooq.org/xsd/jooq-codegen-3.13.0.xsd

These include

- [x] includeEmbeddables, added partially in 3.12: https://github.com/jOOQ/jOOQ/issues/2530
- [x] includeTriggerRoutines, added in 3.11: https://github.com/jOOQ/jOOQ/issues/6951
- [x] includeSystemIndexes, added in 3.13: https://github.com/jOOQ/jOOQ/issues/9601
- [x] includeSystemCheckConstraints, added in 3.13: https://github.com/jOOQ/jOOQ/issues/9600
- [x] includeInvisibleColumns, added in 3.12: https://github.com/jOOQ/jOOQ/issues/5969
