### ISSUE TITLE
Add more Settings to enable / disable DefaultRecordMapper mapping algorithms

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10349]
The `DefaultRecordMapper` combines a few useful features out of the box in a specific order. Specifically, we're currently checking if:

7. [x] `Settings.mapConstructorProperties` (see #11123): `E` has a `@ConstructorProperties` constructor, then we use `ImmutablePOJOMapperWithParameterNames`
8. [x] `Settings.mapConstructorParameterNamesInKotlin` (already implemented): `E` is a Kotlin class, then we use `ImmutablePOJOMapperWithParameterNames` with parameter names detected using Kotlin reflection (#7324)
9. [x] `Settings.isMapConstructorParameterNames` (already implemented) `E` has a constructor with matching number of parameters, use `ImmutablePOJOMapperWithParameterNames` (#4627) or `ImmutablePOJOMapper` otherwise (#1837) (#6598)
10. [x] `Settings.isMapConstructorParameterNames` (already implemented) Use `ImmutablePOJOMapperWithParameterNames`

Some of these algorithms can already be turned off using settings. Others cannot. It would be useful to be able to have a setting for each one of these algorithms.

More settings implemented later: https://github.com/jOOQ/jOOQ/issues/11974

**Comment by eriklumme** [comment]
👍   on #7.

In my case, I want to use different names for some columns in my DTOs, which is easy enough with index-based constructor matching:

```
public class FooDTO {
    private final String foo;
    private final Integer bar;

    public FooDTO(String foo, Integer bar) {
        this.foo = foo;
        this.bar = bar;
    }
    ...
}

...

context.select(FOO.FOO, FOO.BAZ).fetchInto(FooDTO.class);
```

I want to keep my DTOs immutable. To allow for JSON serialization and deserialization with Jackson, I made Lombok generate `@ConstructorProperties`. But now the jOOQ queries don't work anymore, because it doesn't do the `bar` => `baz` mapping.

I don't want to use aliases when selecting with jOOQ, as I feel it's error prone and an extra step. I don't want to have to match the column names in my DTO, because they aren't always that descriptive.

So just being able to turn that mapper off would be great.

**Comment by lukaseder** [comment]
Thanks for the feedback and the use-case @eriklumme. That makes sense. I'll expedite the implementation of that particular flag: https://github.com/jOOQ/jOOQ/issues/11123, which is more immediately useful than the others.

**Comment by eriklumme** [comment]
Thank you @lukaseder , much appreciated!

**Comment by lukaseder** [comment]
Additional settings will be implemented later: https://github.com/jOOQ/jOOQ/issues/11974
