### ISSUE TITLE
Add support for CockroachDB 20.1 features

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10382]
CockroachDB 20.1 has introduced a variety of features that we can support:

### In scope for jOOQ 3.14:

- [x] #10381: `FOR UPDATE` clarification: https://www.cockroachlabs.com/docs/v20.1/select-for-update.html
- [x] Nested transactions: https://www.cockroachlabs.com/docs/v20.1/transactions.html#nested-transactions (nothing needs to be changed, the integration tests all pass)
- [x] #10383: `WITH RECURSIVE`: https://www.cockroachlabs.com/docs/v20.1/common-table-expressions.html#recursive-common-table-expressions
- [x] #10384: `CREATE TEMPORARY TABLE`: https://www.cockroachlabs.com/docs/v20.1/temporary-tables.html

### Out of scope for jOOQ 3.14:

- [x] #10380: A new `ALTER PRIMARY KEY` clause: https://www.cockroachlabs.com/docs/v20.1/alter-primary-key.html
- [x] #10385: `SYSTEM_TIME` versioning: https://www.cockroachlabs.com/docs/dev/as-of-system-time.html

----
See also:
https://www.cockroachlabs.com/docs/releases/v20.1.0.html
