### ISSUE TITLE
Default implementation of AbstractTable.getIdentity() should check Table.fields() for any Field with DataType.identity()

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10397]
There is redundancy in a table's identity meta data information. It can be obtained via:

- `Table.getIdentity()` (which is used internally to implement / emulate `RETURNING` clauses)
- `Stream.of(Table.fields()).filter(f -> f.getDataType().identity())`

The code generator produces this information redundantly, but if users create `TableImpl` instances manually, the redundancy might be forgotten. This is why the default implementation of `Table.getIdentity()` should traverse (and cache) the fields for any identity data types.

### Tasks

- [x] Add default implementation
- [x] Remove generated code
- [x] Fix `<syntheticIdentities/>` https://github.com/jOOQ/jOOQ/issues/10398
- [x] ~Check if implementation can be made final (perhaps, there's no need to provide this information redundantly, even in generated code)~. It could be, but to make upgrading to 3.14 more convenient (i.e. no new compilation errors, if code is not re-generated), let's keep it non-final for now.

----
See also:
- https://github.com/jOOQ/jOOQ/issues/2943: Add support for returning clause, when running plain SQL

**Comment by lukaseder** [comment]
These implementations were already implemented this way:

- `MetaTable.getIdentity()`
- `SnapshotTable.getIdentity()`

**Comment by lukaseder** [comment]
If code generator no longer generates `Table.getIdentity()` overrides, we'll lose the `<T>` type information on `Identity<R, T>`.

In order to avoid such a potential regression in client code, we could generate an override that calls the super implementation but casts the result.
