### ISSUE TITLE
Get ASE dialect support up to date

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10406]
A few features have been added to jOOQ, which may be supported by Sybase ASE as well. These include (list will be amended):

**DML**:

- [x] `UPDATE .. FROM`
- [x] `UPDATE .. LIMIT`
- [x] `INSERT .. DEFAULT VALUES` emulation trouble when identity columns are involved: https://github.com/jOOQ/jOOQ/issues/10408
- [x] `INSERT INTO` aliased table emulation
- [x] No `TOP` clause generated with `UNION`: https://github.com/jOOQ/jOOQ/issues/10409
- [x] Wrong SQL generated when there are unions in derived tables: https://github.com/jOOQ/jOOQ/issues/10410
- [x] Wrong SQL generated when there are set operations in correlated subqueries: #10412

**DDL**:

- [x] `CREATE OR REPLACE VIEW` (16.0+)
- [x] `ALTER TABLE .. ADD` with multiple columns
- [x] `GRANT` support
- [x] `REVOKE` support

**Expressions**:

- [x] `row IS NULL` predicate
- [x] `row BETWEEN` predicate
- [x] `EXTRACT(EPOCH FROM ...)` should use `DATEDIFF(SS, ...)`, not `DATEDIFF(S, ...)` - the latter being supported only in SQL Server
- [x] Casting numbers to `TEXT`: #10417

----
Similar to https://github.com/jOOQ/jOOQ/issues/10153
