### ISSUE TITLE
Improve Settings.parseWithMetaLookups

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10514]
Continuing https://github.com/jOOQ/jOOQ/issues/7163 and #9061, which have been implemented incompletely. Continuation in https://github.com/jOOQ/jOOQ/issues/11967

----

In some situations, it might be useful for the parser to be able to discover actual objects from the catalog through a `MetaProvider` (see #5296). For instance:

- Does a schema / table / column really exist?
- What's the data type of the object?

We need to add a setting with the following options:

- No lookups (current behaviour, default)
- Lookups, ignoring failures
- Lookups, throwing errors on failures

### Tasks:

- [x] Everything implemented in #7163 and #9061
- [x] Unions with "ambiguities" (#10968)
- [x] Aliased column references (e.g. in `ORDER BY` #10970)
- [x] Looking up unqualified columns from 2 tables by same name but different schema qualification (#11000)
- [x] Infer bind variable types where possible (#11061)
- [x] Wrong projection produced from self joins (#11132)
- [x] Wrong column lookup in certain cases (#11134)

The caveats exposed here make it clear that perhaps we cannot achieve all the parsing in a single go as we did until now, but will need to run two passes. The first one can already resolve all table references, whereas we will have to wait for the second pass to resolve the column references.

**Comment by lukaseder** [comment]
More work has been extracted to #11967, for 3.16
