### ISSUE TITLE
Fix known limitations of embeddable types

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10527]
This is a continuation of #8353, which fixed a lot of issues already in jOOQ 3.14. Continued in #11975

### Runtime library (known issues)

- [x] `ORDER BY` issues
  - [x] `ORDER BY <column index>` may referenece the wrong logical column index
unmappers that also don't work. This also affects other types of nested records (see https://github.com/jOOQ/jOOQ/issues/11812): https://github.com/jOOQ/jOOQ/issues/11904
- [x] SQL Server `INSERT .. RETURNING` emulation, see https://github.com/jOOQ/jOOQ/issues/10760
- [x] HSQLDB / Oracle `INSERT .. RETURNING` emulation, see https://github.com/jOOQ/jOOQ/issues/10834

### Code generator (known issues)

- [x] POJOs are not generated in synthetic schemas: https://github.com/jOOQ/jOOQ/issues/11185
- [x] DAOs
  - [x] `<replacesFields/>` does not work with DAOs: https://github.com/jOOQ/jOOQ/issues/11179
  - [x] Generate correct `fetchXYZ()` methods in DAOs: https://github.com/jOOQ/jOOQ/issues/11182
- [x] Generate POJOs if requested
