### ISSUE TITLE
Improve procedural language abstraction API

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10528]
This issue continues the work of #6475, #8450 from version 3.12, 3.14, to be continued with #11878 in 3.16

### Done:

- [x] #6956 `CREATE TRIGGER`
- [x] #8166 `SELECT .. INTO <variables>` support
- [x] #8230 `SIGNAL` statement support
- [x] #8284 `LEAVE` (no label) and `ITERATE` (no label) emulation for DB2, HSQLDB
- [x] #9190 `CREATE PROCEDURE` and `CREATE FUNCTION`
- [x] #9191 `DROP PROCEDURE` and `DROP FUNCTION`
- [x] #9953 Work around lack of Firebird's nested variable declarations
- [x] #11356 `CALL` statement
- [x] #11360 `CustomStatement` 
- [x] #11408 `DECLARE` with multiple variables
- [x] #11410 HSQLDB `<multiple variable assignment>`
- [x] #11508 Emulate `RETURN (SELECT ...)`

**Comment by lukaseder** [comment]
Further work is all moved to #11878
