### ISSUE TITLE
Add { Schema, Meta } . { getUniqueKeys(), getForeignKeys(), getIndexes() }

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10546]
On both `Schema` and `Meta` types, it would be useful to be able to navigate `UniqueKey` and `Reference` types.

A simple, initial implementation would just browse all the tables and collect their objects.

### Tasks

- [x] `Schema.getPrimaryKeys()` (including overloads accepting `String` and `Name` filters)
- [x] `Schema.getUniqueKeys()` (including overloads accepting `String` and `Name` filters)
- [x] `Schema.getKeys()` (including overloads accepting `String` and `Name` filters)
- [x] `Schema.getForeignKeys()` (including overloads accepting `String` and `Name` filters)
- [x] `Schema.getIndexes()` (including overloads accepting `String` and `Name` filters)
- [x] `Meta.getUniqueKeys()` (including overloads accepting `String` and `Name` filters)
- [x] `Meta.getForeignKeys()` (including overloads accepting `String` and `Name` filters)
- [x] `Meta.getIndexes()` (including overloads accepting `String` and `Name` filters)
- [x] `Meta.filterUniqueKeys()`
- [x] `Meta.filterForeignKeys()`

See also #10883 for the new distinction between `getKeys()` and `getUniqueKeys()`
