### ISSUE TITLE
Known issues with new FOR XML, FOR JSON features

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10565]
This issue collects known issues related to the newly introduced `FOR XML` and `FOR JSON` features from jOOQ 3.14 (#9923)

### Missing features

- [x] A set of missing features is listed here: #10170

### API issues

- [x] `Select.getSelect()` returns the actual projection (as it should), but that can cause issues where we expect a scalar subquery to yield only one row, when `select (select 1 as "a", 2 as "b" for xml raw) as "xml")` is valid SQL (see below parser issues). The parser issue can be fixed easily, but there may be other problems. This affects at least (places currently calling `Select.getSelect().size()` or just `Select.getSelect()`):
  - [x] Parsing scalar subqueries with more than one column
  - [x] ~Parsing unions with `FOR XML` or `FOR JSON`~ (see #10571)
  - [x] Parsing `CREATE VIEW` with `FOR XML` or `FOR JSON` (column list sizes must match)
  - [x] Interpreting `CREATE VIEW`
  - [x] The newly introduced `AliasedSelect` (#10540)
  - [x] Creating correlated subqueries directly from the newly introduced `SelectCorrelatedSubqueryStep` (#10176)
  - [x] Auto-wrapping of `Select` as `Field` (#6362, #8220)
  - [x] `SelectQueryImpl.asField()`
  - [x] Usage in CTEs doesn't work
  - [x] `DerivedTable::fields`

- [x] ~Cannot use `FOR XML` or `FOR JSON` with set operators in SQL Server.~ Will be solved separately #10570

### Parser issues

- [x] Parser doesn't recognise scalar subqueries containing `FOR XML` as scalar. This query:

    ```sql
    select (select 1 as "a", 2 as "b" for xml raw) as "xml";
    ```

    produces this error:

    > Select list must contain exactly one column: [1:48] select (select 1 as "a", 2 as "b" for xml raw) [*]as "xml";

- [x] Parser doesn't recognise correct degree of `CREATE VIEW .. AS (SELECT .. FOR XML)` statements. This qurey:

    ```sql
    create view v (xml) as (select 1 as "a", 2 as "b" for xml raw)
    ```

    produces this error:

    > Select list size (2) must match declared field size (1): [1:63] ...v (xml) as (select 1 as "a", 2 as "b" for xml raw)[*]

- [x] ~Parser cannot parse `FOR XML` as a union subquery.~ Will be solved separately #10571

More issues will be collected here to fix before or after the release of jOOQ 3.14
