### ISSUE TITLE
Various parser bugs / missing features

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10572]
This is a continuation of https://github.com/jOOQ/jOOQ/issues/9775 and will be continued in #11966

----

Some features were not yet supported in the jOOQ 3.9 parser. We'll fix them all in this single issue in order not to create too many issues. Here's the list of fixed things:

### SELECT features

- [x] Teradata undocumented `SELECT .. GROUP BY .. WHERE` syntactic ordering (https://github.com/jOOQ/jOOQ/issues/11403)
- [x] `<explicit table>` support (see https://github.com/jOOQ/jOOQ/issues/11382)
- [x] MySQL `VALUES` constructor syntax (#11420)
  - [x] Add a check to the parser validating that all rows are of the same degree (#11421)
- [x] `QUALIFY` clause (Teradata filtering on window functions. Support in jOOQ first: #5810)
- [x] `CONNECT BY` placed after `WHERE`
- [x] `FOR UPDATE OF <tables>` (see #11535)
- [x] `WITH` in parenthesised set operations or derived tables (see #11602):
  - [x] `select (with a as (select 1 x) select * from a) t;`
  - [x] `select * from (with a as (select 1 x) select * from a) t cross join (with a as (select 1 y) select * from a) u;`
  - [x] `with t (c) as (with t (c) as (select 1) select c from t) select c from t;` (see #11603)

### Procedural statements

- [x] `RETURN` https://github.com/jOOQ/jOOQ/issues/11390
- [x] `BEGIN [ [ NOT ] ATOMIC ]` https://github.com/jOOQ/jOOQ/issues/11414
- [x] Correct distinction between PL/SQL `DECLARE .. BEGIN .. END` and standard SQL `BEGIN .. DECLARE .. END` (#11417)
- [x] `EXECUTE IMMEDIATE` support #11429
- [x] MariaDB `FOR` loop syntax: #11629
- [x] Empty blocks: #11630

### Other statements

- [x] `TRUNCATE [ TABLE ] x` (optional `TABLE` keyword)
- [x] Teradata `UPDATE .. FROM .. SET` syntax (https://github.com/jOOQ/jOOQ/issues/11402)
- [x] `DEFAULT nextval('<id>_seq'::regclass)` is an identity in old PostgreSQL versions, see #10963
- [x] `DELETE` and `UPDATE` with aliasing (see #11045)
- [x] `ALTER TABLE .. DROP .. DROP` (#11430)
- [x] `ALTER TABLE .. ADD .. ADD` (#11433)
- [x] `UPDATE .. SET row = (SELECT ...)` (#11436)
- [x] `CREATE INDEX indexName (colNames) ON tableName` syntax (Teradata style)
- [x] `CREATE TABLE` with Vertica `IDENTITY` type (#11651)
- [x] `MERGE .. USING` clause can specify a derived column list (e.g. `USING (...) AS t(a, b)` in SQL Server) (see #11050)
- [x] `DELETE` and `UPDATE` with `JOIN` (see https://github.com/jOOQ/jOOQ/issues/11926)
- [x] JDBC escape syntax for procedure calls: `{call ... }` (#11415)

### Table expressions

- [x] `SYSTEM_RANGE`, which is H2's version of `GENERATE_SERIES`

### Column expressions (and predicates)

- [x] `JSON_ARRAYAGG` and `JSON_OBJECTAGG` as window functions (#11422)
- [x] `LISTAGG` without `WITHIN GROUP` (as in Db2) (#11432)
- [x] SQLite `MIN()` and `MAX()` functions (their version of `LEAST()` and `GREATEST()`) (#11449)
- [x] SQLite `IS [ NOT ]` (their version of `IS [ NOT ] DISTINCT FROM`) (#11450)
- [x] Alternative names for `OCTET_LENGTH` (see #11494)
- [x] `NTH_VALUE(field, field)` instead of just `NTH_VALUE(field, integer literal)`
- [x] MySQL `DATE_ADD()` function (see #11452)
- [x] HANA `MAP` function (alias for `DECODE`) 
- [x] Teradata `OTRANSLATE` 
- [x] `NOT(?)` (see #11631)
- [x] `NOT NOT expr` (see #11632)
- [x] `STDDEV` as an alias for `STDDEV_POP` (Db2)
- [x] `ARRAY` constructor (by query) (support this in jOOQ, first: #6024, #3985, #11831)
- [x] PostgreSQL JSON functions
  - [x] `JSON_AGG` / `JSONB_AGG()` (see #11474)
  - [x] `JSON_OBJECT_AGG` / `JSONB_OBJECT_AGG()`
  - [x] `JSON_BUILD_ARRAY()` / `JSONB_BUILD_ARRAY()`
  - [x] `JSON_BUILD_OBJECT()` / `JSONB_BUILD_OBJECT()`
- [x] All sorts of vendor-specific functions
  - [x] MySQL (and others?) `IF` function (see https://github.com/jOOQ/jOOQ/issues/10160)
  - [x] Oracle's `CHR()` function (support in jOOQ first: #7290)
  - [x] `DATEDIFF` (SQL Server version) https://docs.microsoft.com/en-us/sql/t-sql/functions/datediff-transact-sql (support in jOOQ first: #7900)
sql/functions/logical-functions-iif-transact-sql

### Operators

- [x] Oracle operators containing whitespace e.g. `! =` (see #11699)
- [x] `a ** b` exponentiation operator (see #11712)

### Literals and data types

- [x] Interval precision (ignored for now, see #10452)

### Language features

- [x] Escaped quotes in identifiers, such as `"aa""bb"`, or `` `aa``bb` ``, or `[aa]]bb]` (see #11435)
- [x] Support optional semicolons (T-SQL), i.e. a semicolon is not required in a batch to separate statements (this is valid T-SQL! `SELECT 0 SELECT 1 SELECT 2 BEGIN SELECT 1 END`) (see #10164)
- [x] T-SQL column alias (but not table alias) as string literals syntax, e.g. `SELECT 1 AS 'abc'` (using apostrophes)

### Other improvements

- [x] Make all methods private, not package private
