### ISSUE TITLE
Add new <syntheticObjects/> configuration, and deprecate / replace existing functionality

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10588]
Our existing functionality for synthetic keys doesn't suffice, if we want to support this also for unique keys (#7860) and foreign keys (#7155). We need to be able to specify:

- A key name
- A column set *per key* (this wasn't necessary with primary keys, because each column set *per table* describes the entire primary key, but there can be multiple unique / foreign keys per table)
- A referenced key or referenced column set for foreign keys
- In the future, we might also want additional features, like `ON DELETE` clauses

**To support all this, we need to:**

- [x] Deprecate the existing functionality
  - [x] `<syntheticIdentities/>`
  - [x] `<syntheticPrimaryKeys/>`
  - [x] `<overridePrimaryKeys/>`
  - [x] Issue a deprecation warning if someone is using it
  - [x] Translate existing configurations to the new configuration syntax
- [x] Add a new `<syntheticKeys/>` configuration. Details below:
- [x] Issue warnings when a configuration never matches
- [x] Apply to some `jOOQ-meta` dictionary views and use implicit joins
- [x] Update configuration to allow for explicit ordering of key columns (we cannot assume key columns are ordered the same as table columns)
- [x] Add documentation

**Related things that are implemented separately:**

- [x] Find a way to reverse engineer synthetic keys from interpreted views by looking at their meta data. This would be an awesome feature to have automatically: #10590
- [x] We need runtime information about synthetic keys, and a `Settings` that allows for excluding it from `Meta::ddl` and `Meta::informationSchema` output: #10591
- [x] Synthetic `NOT NULL` constraints would help produce implicit inner joins (#7507): #10611

**Discussed but rejected:**

- [x] ~When a `NOT NULL` (?) FK and a UK overlap, we effectively have a one-to-one relationship. We could generate a synthetic FK in the inverse direction, which might help solve https://github.com/jOOQ/jOOQ/issues/8667.~ This is not the responsibility of synthetic keys, but of implicit join code generation, which can be governed for all FK/UK overlaps, not just the synthetic ones.
- [x] ~Combine this with `<embeddablePrimaryKeys/>` and `<embeddableUniqueKeys/>` and apply to some `jOOQ-meta` dictionary views.~ Won't do this for now.

**Example XML config:**

```xml
<database>
  <syntheticKeys>
    <identities>
      <identity>
        <tables>REGEX_MATCHING_TABLES</tables>
        <fields>REGEX_MATCHING_COLUMNS</fields>
      </identity>
    </identities>
    <primaryKeys>
      <primaryKey>
        <name>T_PK</name>
        <tables>REGEX_MATCHING_TABLES</tables>
        <fields><field>REGEX_MATCHING_COLUMN(S)</field></fields>
        <key>T_UK</key>
      </primaryKey>
    </primaryKeys>
    <uniqueKeys>
      <uniqueKey>
        <name>T_UK</name>
        <tables>REGEX_MATCHING_TABLES</tables>
        <fields><field>REGEX_MATCHING_COLUMN(S)</field></fields>
      </uniqueKey>
    </uniqueKeys>
  </syntheticKeys>
  <foreignKeys>
    <foreignKey>
        <name>T_FK</name>
        <tables>REGEX_MATCHING_TABLES</tables>
        <fields><field>REGEX_MATCHING_COLUMN(S)</field></fields>
        <referencedTable>REGEX_MATCHING_TABLES</referencedTable>
        <referencedFields><field>REGEX_MATCHING_COLUMN(S)</field></referencedFields>
        <referencedKey>T_UK</referencedKey>
    </foreignKey>
  </foreignKeys>
</database>
```

Comments:

- In all key types, `<name/>` is optional. If omitted, we don't generate a name for the key
- In `<primaryKey/>`, `<keyFields/>` and `<key/>` are mutually exclusive, one must be provided.
- In `<foreignKey/>`, `<referencingFields/>` and `<referencingKey/>` are mutually exclusive, and both optional. If none are provided, the primary key is referenced implicitly, just like with the DDL syntax

The suggestion might be improved as we discover issues

**Comment by lukaseder** [comment]
Renaming this from `<syntheticKeys/>` to `<syntheticObjects/>` to be more forward compatible, as we might want to add more capabilities of generating synthetic objects.
