### ISSUE TITLE
Speed up implicit join path generation algorithm

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10609]
Implicit joins have a few caveats in terms of performance in their current form.

There may be some low hanging fruit when optimising them, especially:

- [x] ~The `TableImpl.childPath` property requires aliasing of the `ForeignKey`, which has been fixed with #10603, but not optimally~ (see #11116)
- [x] ~The `TableImpl.name` property is created as a "path alias" every time someone calls a `Table.joinPath1().joinPath2()` method via `Internal::createPathAlias`. This path alias could be cached somewhere~ (see #11116)
- [x] ~The join tree algorithm could be reviewed~ (see #8762)

The first two being relatively low hanging fruit.

----
See also: #8762

**Comment by lukaseder** [comment]
This issue is duplicated by #8762 and #11116
