### ISSUE TITLE
Default schema version provider should auto-discover Flyway and Liquibase schema version tables

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10630]
A useful feature to speed up builds is the catalog / schema version provider feature, which allows for users to provide jOOQ-codegen with current schema versions:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-version-providers/

The code generation stops immediately if the currently generated code's `@Generated` annotation already matches the schema version, which can save quite some time with large databases.

When users use Flyway or Liquibase, and don't change their defaults, then we can auto-discover the Flyway or Liquibase schema version tables:

- `"schema_version"` in case of Flyway
- `DATABASECHANGELOG` in case of Liquibase

If those tables are available, we should read their content and provide the schema version.

### Tasks

- [ ] Implement the above functionality
- [ ] Add a code generator configuration that allows for turning off this functionality, reverting to having no schema version provider, in case our implementation can be flawed or not up-to-date with the latest version of Flyway/Liquibase.
- [ ] A message should be logged to help debug this case, if the above logic applies
- [ ] The `@Generated` annotation should contain a reference to where the schema version came from
