### ISSUE TITLE
Support and emulate Oracle's TO_CHAR() function

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10641]
Oracle's useful `TO_CHAR` function is frequently used in Oracle to format dates with explicit format literals. We should support this as well and translate the literals to other dialects, if possible.

### Tasks

- [x] Add a `ToChar` querypart implementation
  - [x] Native implementation for:
    - [x] H2
    - [x] Oracle
    - [x] PostgreSQL (including Aurora and Redshift, not yet CockroachDB: https://github.com/cockroachdb/cockroach/issues/3781)
  - [x] Emulations
    - [x] Without a format literal, just translate to `CAST(x AS VARCHAR)` (existing parser behaviour)
    - [x] in case the format is a string literal (will be implemented later: #10642)
  - [x] Dynamic emulations (format is a column expression) will not be supported (yet)
- [x] Pull up API from `OracleDSL` to `DSL` (see #8381)
- [x] Adapt parser support, which currently translates single-argument `TO_CHAR(x)` calls to `CAST(x AS VARCHAR)` (see #7292), since jOOQ 3.11
