### ISSUE TITLE
Address known issues of Settings.transformTableListsToAnsiJoin

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10697]
jOOQ 3.14 introduced the `Settings.transformTableListsToAnsiJoin` flag (https://github.com/jOOQ/jOOQ/issues/7312). There are numerous known issues and limitations which need to be addressed, still (to be continued with https://github.com/jOOQ/jOOQ/issues/11996):

### Implemented

**Stylistic issues**

- [x] Table order is reversed within a tree. E.g. `FROM T1, T2, T3 WHERE T1.C = T2.C AND T1.C = T3.C` leads to `FROM T1 JOIN T3 ON T1.C = T3.C JOIN T2 ON T1.C = T2.C`.
- [x] Likewise, joins are nested when they don't have to be e.g. `FROM T1, T2, T3 WHERE T1.C = T2C AND T2.D = T3.D` leads to `FROM T1 JOIN (T2 JOIN T3 ON T2.D = T3.D) ON T1.C = T2.C`. The reason is the same as for the above issue

**Bugs / missing features**

- [x] `COL(+) = 1`
- [x] `T1.I = T2.I(+) AND T1.I = 1` works, but `T1.I = 1 AND T1.I = T2.I(+)` does not
- [x] Try to look up unqualified `TableField` from `TableList`'s `Table.fields()`
- [x] We're currently not resolving aliased tables!
- [x] Wrong outer to inner join optimisation depending on predicate order (see https://github.com/jOOQ/jOOQ/issues/10983)

### TODO

- More issues in a later release: https://github.com/jOOQ/jOOQ/issues/11996

### Related work

- [x] ~Not all RDBMS support `RIGHT JOIN`, so we need to be able to transform them further~. Will be done separately:  https://github.com/jOOQ/jOOQ/issues/10650

### Oracle's own limitations:

- https://www.salvis.com/blog/2015/12/07/outer-join-operator-restrictions-in-12-1-0-2/

**Comment by datocrats-org** [comment]
Here's a demo for something that does this reasonably well and I think a link to the same source you can download via their site.  
http://www.dpriver.com/blog/list-of-demos-illustrate-how-to-use-general-sql-parser/rewrite-oracle-propriety-joins-to-ansi-sql-compliant-joins/ 
https://github.com/yingzhox/qmapper/blob/f77a6a688eeb29c6a4c5cd3d5f45c7943883a644/QMapper/src/demos/joinConvert/oracleJoinConverter.java

**Comment by lukaseder** [comment]
Thanks for your feedback, @datocrats-org. I'm aware of this product. We used to work together a long time ago to create the now deprecated SQL 2 JOOQ translator: https://www.jooq.org/doc/3.6/manual/tools/sql2jooq

What's your motivation of sharing these links? Anything particular you think we should be looking at?

**Comment by lukaseder** [comment]
Fixing a few things for 3.15.0 and 3.14.4 (#10948)...

**Comment by lukaseder** [comment]
To be continued: https://github.com/jOOQ/jOOQ/issues/11996
