### ISSUE TITLE
Fix known issues of Settings.transformRownum

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10716]
jOOQ 3.14 introduced `Settings.transformRownum` with #9017. It works decently for simple cases, offering already quite some value, but still suffers from quite a few caveats as the transformation is far more complex than one would wish.

These are known issues that need to be addressed (to be continued in 3.16: #11997):

**Bugs and limitations:**

- [x] In the presence of `GROUP BY`, we cannot just use `LIMIT`. The `FROM` and `WHERE` clauses must be nested in a derived table: https://github.com/jOOQ/jOOQ/issues/9017#issuecomment-698174506
- [x] In the presence of `DISTINCT`: #11661
- [x] When nesting into derived tables (see above), we must avoid problems with ambiguous column names (this should be fixed automatically with https://github.com/jOOQ/jOOQ/issues/5810, as the two transformations use the same transformation logic)

More issues in 3.16: #11997

**Comment by lukaseder** [comment]
To be continued: #11997
