### ISSUE TITLE
Meta.migrateTo(Meta) should not produce any diff when timestamp default precision is specified

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10807]
When creating a diff between:

```sql
create table t (t timestamp);
create table t (t timestamp (6));
```

The following statements are currently being produced:

```sql
alter table t alter t type timestamp(6);
alter table t alter t type timestamp;
```

Which is correct if we don't know the default precision for timestamps in a database. But we do, and we should use this information to avoid unnecessary diffs.

### Tasks

- [x] Add `Settings.migrationIgnoreDefaultTimestampPrecisionDiffs` to opt out of this improvement (in case we get it wrong, or in case it matters)
- [x] Define the default `TIMESTAMP` precision per dialect in an internal API
- [x] Ignore the diffs between `TIMESTAMP` and `TIMESTAMP(default)`
