### ISSUE TITLE
Remove jOOQ-refaster from distributions

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10803]
`jOOQ-refaster` has been an experiment. I think it failed:

- It caused quite a few JDK compatibility headaches when we developed it
- It continues to cause such headaches when we try to build jOOQ with JDK 14+ (see #10150)
- We've had no user feedback about it yet

While the idea is interesting, we were "first movers" in an area that is poorly supported and adopted by the community, something we usually don't do (see offering support for reactive query execution models, which would be far more popular: https://github.com/jOOQ/jOOQ/issues/6298).

With this in mind, we won't ship any `jOOQ-refaster` updates in the future.

### Tasks

- [x] Remove the modules from 3.15 builds
- [x] Deactivate the builds in 3.13 and 3.14
- [x] Remove the manual sections (replacing them with a deprecation notice, similar to the jOOQ Console): https://www.jooq.org/doc/latest/manual/tools/refaster/
- [x] Update the blog post: https://blog.jooq.org/2020/02/25/use-the-jooq-refaster-module-for-automatic-migration-off-of-deprecated-jooq-api/
