### ISSUE TITLE
Add a DSL.currentCatalog() function

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10827]
In some dialects, it would be useful to have a `CURRENT_CATALOG` function, similar to the standard SQL `CURRENT_SCHEMA` function. It would translate to, for example:

- [x] CockroachDB: `current_database()`
- [x] Informix: `dbinfo('dbname')`
- [x] PostgreSQL: `current_database()`
- [x] SQL Server: `db_name()` (there are existing calls from `CREATE SCHEMA` and `DROP SCHEMA`, see #10271)

### Tasks

- [x] Add API
- [x] Add dialect support (see above)
- [x] Add parser support for different dialects (see above)

**Comment by lukaseder** [comment]
Implemented in jOOQ 3.15.0. Additional dialect support may be added later.
