### ISSUE TITLE
Implement MetaImpl.getSequences()

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10844]
We now have some infrastructure to reuse queries from `jOOQ-meta` in the core `jOOQ` library, without moving all the logic between modules, see #5179. This means we can finally offer querying a database's sequence types via `MetaImpl` as well.

### Tasks:

- [x] Add relevant queries to `MetaSQL` for:
  - [x] Db2
  - [x] Derby
  - [x] Firebird
  - [x] H2
  - [x] HSQLDB
  - [x] Informix
  - [x] Oracle
  - [x] PostgreSQL
  - [x] SQL Server
- [x] More dialect support in #10854
- [x] Produce results in `Meta.getSequences()` calls
