### ISSUE TITLE
Add support for the Db2, H2, Firebird 4 DECFLOAT data type (HANA: SMALLDECIMAL)

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10880]
Db2, H2 (not yet released), and possibly others support a `DECFLOAT` data type which is not exactly the same as `DECIMAL` / `NUMERIC`. Differences include:

- [x] `DECFLOAT` supports the usual floating point `+Inf`, `-Inf`, `NaN` values

### Tasks

- [x] Add `org.jooq.Decfloat`, a wrapper for this type
  - [x] With normalising `hashCode()` and `equals()` implementations, similar to `JSONB`
  - [x] It should extend `java.lang.Number`
    - [x] With conversion options to `Float`, `Double`, `BigDecimal`
- [x] Add the type to `SQLDataType`
- [x] Add a `DefaultBinding` implementation
- [x] Add `DefaultConverterProvider` support
- [x] Add new methods to `DataType` to distinguish between ordinary decimals and this new type
  - A new method for this type isn't necessary. It's just the intersection of `DataType.isFloat()` and the new `DataType.isDecimal()` (see https://github.com/jOOQ/jOOQ/issues/17061)
- [x] Review all internal usage of `DataType.getType() == BigDecimal.class` to see if it's still correct (see e.g. incorrect usage in `Diff.java`: https://github.com/jOOQ/jOOQ/issues/10864#issuecomment-722470982)
- [x] Code generation option `/configuration/generator/generate/decfloatTypes` to opt out of recognising this type, for backwards compatibility in case there are custom bindings.

### Test coverage

- [x] Code generation
  - [x] Configuration (see above)
  - [x] Dialect support
    - [x] Db2
    - [x] Firebird
    - [x] H2
    - [x] HANA
      - `NaN` and `Infinity` aren't supported, see: https://help.sap.com/docs/SAP_HANA_PLATFORM/4fe29514fd584807ac9f2a04f6754767/4ee2f261e9c44003807d08ccc2e249ac.html 
    - [x] Emulate this on other dialects using `FLOAT` might be done later: https://github.com/jOOQ/jOOQ/issues/17080
- [x] DDL
- [x] `Meta` API queries
- [x] `ResultSetMetaData`
- [x] Casting
- [x] Binding and fetching of values
- [x] Usage in `MULTISET`
- [x] Interacting with tables containing the data type

**Comment by katzyn** [comment]
@lukaseder
There is also a problem with `Inf`, `-Inf`, and `NaN`, they cannot be represented as `BigDecimal`.

**Comment by lukaseder** [comment]
Thanks for the heads up, @katzyn. That will be good to keep in mind when implementing this. Perhaps, a new wrapper type, similar to `org.jooq.JSON` will do the trick here.

**Comment by lukaseder** [comment]
In HANA, this is the `SMALLDECIMAL` type:

- https://github.com/jOOQ/jOOQ/issues/16975

**Comment by lukaseder** [comment]
At least Firebird has a maximum precision of 34 in decimal digits with its `Decimal128` type, so our own `org.jooq.Decfloat` implementation needs to be implemented as

- `coefficient` (`significand`), a `BigInteger`
- `exponent`, an `int`
- an enum type for the special values, such as `Inf`, `-Inf`, or `Nan`

**Comment by lukaseder** [comment]
An alternative implementation will just store the string, and evaluate it on demand. To be defined...

**Comment by lukaseder** [comment]
On precisions:

- H2 supports precisions up to `100000`: https://www.h2database.com/html/datatypes.html#decfloat_type
- Firebird up to `34`: https://firebirdsql.org/file/documentation/chunk/en/refdocs/fblangref40/fblangref40-datatypes-floattypes.html
- HANA only up to `16`: https://help.sap.com/docs/SAP_HANA_PLATFORM/4fe29514fd584807ac9f2a04f6754767/4ee2f261e9c44003807d08ccc2e249ac.html

But we should expect other implementations to follow suit with H2. So perhaps, the `String` storing variant is the best one, to play it safe.

**Comment by lukaseder** [comment]
I'm marking this as an incompatible change as:

- Out of the box, existing `Binding<Object, U>` bindings will break and will have to be rewritten as `Binding<Decfloat, U>` (unless opting out of the feature with the code generation flag)
- We've already bound `DECFLOAT` to `BigDecimal` in Db2, which was wrong

**Comment by lukaseder** [comment]
The new `org.jooq.Decfloat` type will implement the new `org.jooq.Data` interface:

- https://github.com/jOOQ/jOOQ/issues/17060

**Comment by lukaseder** [comment]
Implemented for jOOQ 3.20.0

**Comment by lukaseder** [comment]
I just realised that HANA's `DECIMAL` type is really not a SQL `DECIMAL` type, but a larger `DECFLOAT`:
https://help.sap.com/docs/SAP_HANA_PLATFORM/7e4aba181371442d9e4395e7ff71b777/6baaff2407a8421e91fcfce7f62f3de7.html?version=2.0.00&locale=en-US

I suspect we could change that at some point. I won't do this right away:

- https://github.com/jOOQ/jOOQ/issues/17087

**Comment by lukaseder** [comment]
It appears that  `DECIMAL(p)` in Informix is, in fact, `DECFLOAT`:
https://www.ibm.com/docs/en/informix-servers/14.10?topic=types-adjustable-precision-floating-point-decimalp

**Comment by lukaseder** [comment]
Moving the Informix part of this feature request into a separate issue:

- https://github.com/jOOQ/jOOQ/issues/17133
