### ISSUE TITLE
Add <includeSystemSequences/> to code generator configuration

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10899]
The code generator configuration currently tries to exclude system sequences in some dialects, e.g. in H2:

```java
 .and(upper(SEQUENCES.SEQUENCE_NAME).notLike(inline("SYSTEM!_SEQUENCE!_%"), '!'))
```

In other dialects, no such exclusion is happening. Our integration tests haven't cought this, because the system sequences may have a name that we've excluded anyway, e.g. in PostgreSQL, they're called `[table_name]_[identity_column_name]_seq`.

We should clean up the situation by introducing a new flag `<includeSystemSequences/>`, which defaults to `false`, and can be opted into explicitly. This flag will also be used by the runtime configuration flag #10898 "Add Settings.metaIncludeSystemSequences"

### Tasks

- [x] Add configuration flag
- [x] Update existing implementations to use this flag:
  - [x] H2 (`NOT LIKE 'SYSTEM!_SEQUENCE!_%'`)
  - [x] Oracle (#6523: `NOT LIKE 'ISEQ$$%')
- [x] Add additional implementations:
  - [x] PostgreSQL

The list above will be amended

**Comment by lukaseder** [comment]
In PostgreSQL, we can check if:

```sql
sequence_name not in (
  select table_name || '_' || column_name || '_seq'
  from information_schema.columns
  where table_schema = 'public'
  and column_default is not null
  and column_default = 'nextval(''' || table_name || '_' || column_name || '_seq''::regclass)'
)
```

**Comment by lukaseder** [comment]
Some dialects similar to PostgreSQL (e.g. CockroachDB) may require adaptations for that query. We'll discover them when integration testing #10898. I'll update this issue accordingly.
