### ISSUE TITLE
Add Settings.renderDefaultNullability

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10937]
Historically, jOOQ generates explicit `NULL` clauses even when nullability in a DDL statement is implicit. The currently generated SQL of these statements (using new API from #10936):

```java
ctx.createTable("t1").column("c", INTEGER);
ctx.createTable("t2").column("c", INTEGER.null_());
ctx.createTable("t3").column("c", INTEGER.notNull());
```

... is:

```sql
create table t1 (c int null);
create table t2 (c int null);
create table t3 (c int not null);
```

The user's intent may have been to profit from implicit nullability or not-nullability. In a future H2 version, this may even be the only one to have nullable columns (#10819)

We should have a new `Settings.renderImplicitNullability` that produces the current behaviour, but the new default will be `false`, to produce this instead:

```sql
create table t1 (c int);
create table t2 (c int null);
create table t3 (c int not null);
```

The flag will have these values:

- [x] `IMPLICIT_DEFAULT` will not produce any nullability clause for `Nullability.DEFAULT`, and thus produce the dialect specific default behavior, irrespective of whether that is `NULL` or `NOT NULL` on a given dialect.
- [x] ~`EXPLICIT_DEFAULT` will produce the dialect specific default behaviour, but generates it explicitly.~ (not be implemented yet, may be implemented in the future)
- [x] `IMPLICIT_NULL` (new default) will produce implicit nullability for `Nullability.DEFAULT` if the default nullability is `NULL`, or explicit `NULL` if not (e.g. Sybase ASE, Sybase SQL Anywhere).
- [x] `EXPLICIT_NULL` (current default) will produce explicit nullability for `Nullability.DEFAULT`, irrespective of the context (e.g. if the column is a primary key)

In all cases, if a dialect doesn't support explicit nullability (e.g. Derby, Firebird, HSQLDB, and perhaps H2, in the future), then this flag has no effect, and we produce `IMPLICIT_DEFAULT` behaviour, which we already do today.

This flag only affects `CREATE TABLE` and `ALTER TABLE .. ADD` statements, not `ALTER TABLE .. SET TYPE` statements, where `Nullability.DEFAULT` means that we don't modify the nullability

### Tasks:

- [x] Add the flag
- [x] Implement the flag
- [x] Add formatting, parsing, interpreter tests, etc.
- [x] Add integration tests (we already had one)
- [x] Make this flag available on https://www.jooq.org/translate: See #10941

### Related tasks:

- [x] #10938 Change of behaviour in code generator
- [x] #10811 Change of behaviour in interpreter
- [x] Change of behaviour in `MetaImpl`
- [x] Change of behaviour in parser
- [x] Elsewhere?

**Comment by lukaseder** [comment]
Integration tests have shown a regression in at least MariaDB where these are equivalent:

```sql
create table t (ts timestamp);
create table t (ts timestamp not null current_timestamp());
```

A curious default, which may be reproduced with `IMPLICIT_DEFAULT` and `EXPLICIT_DEFAULT`, but should be avoided with `IMPLICIT_NULL` and `EXPLICIT_NULL`!

**Comment by lukaseder** [comment]
MariaDB:

```sql
create table t (d date, ts timestamp);
insert into t values (null, null) returning *;
```

Output:

```
d|ts                 |
-|-------------------|
 |2020-11-14 12:22:47|
```

**Comment by lukaseder** [comment]
Maybe, we should reconsider our mapping of `TIMESTAMP` to `TIMESTAMP` vs `DATETIME` in MariaDB and MySQL, independently of this default behaviour:

- https://mariadb.com/kb/en/datetime/
- https://mariadb.com/kb/en/timestamp/
