### ISSUE TITLE
Support MySQL 8.0.16 CHECK constraints

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10932]
MySQL 8.0.16 introduced support for `CHECK` constraints:
https://mysqlserverteam.com/mysql-8-0-16-introducing-check-constraint

The DDL syntax has been supported for a long time for compatibility reasons, but the constraint was never enforced before.

### Tasks:

- [x] Amend `@Support` annotations where relevant, adding `SQLDialect.MYSQL_8_0_19`
- [x] Add the support for the `[ NOT ] ENFORCED` flag and the relevant DDL statements, as well as parser and interpreter support to the OSS Edition
- [x] Enable integration tests
