### ISSUE TITLE
Add support for the MySQL FIELD() function

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11009]
MySQL has a useful `FIELD()` function:
https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_field

It is like a short version of the `CASE` expression where these two are equivalent:

```sql
FIELD(x, a, b, c)
```

And

```sql
CASE x WHEN a THEN 1 WHEN b THEN 2 WHEN c THEN 3 ELSE 0 END
```

It is useful as an implementation of sort indirection:
https://blog.jooq.org/2014/05/07/how-to-implement-sort-indirection-in-sql/

E.g.

```sql
SELECT *
FROM t
WHERE id IN (4, 1, 3, 2)
ORDER BY field(id, 4, 1, 3, 2)
```

Which we're offering in jOOQ using `Field.sortAsc()`:

```sql
ctx.selectFrom(T)
   .where(T.ID.in(4, 1, 3, 2))
   .orderBy(T.ID.sortAsc(4, 1, 3, 2))
   .fetch();
```

### Tasks

- [x] Add `DSL.field(Field<T>, T...)` and `DSL.field(Field<T>, Field<T>...)` overloads (check if there are any conflicts with existing `field()` functions)
- [x] Retrofit `sortAsc()` and similar functions to use this for MySQL
- [x] Retrofit parser to parse `FIELD` into `DSL.field()`
