### ISSUE TITLE
Parser should parse all Names.* values at least once

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11232]
We probably have a few more functions that we know how to render but not parse, like #11231.

A new test should be able to discover all `Names.*` identifiers, and heuristically try to parse them using some common syntax, e.g. iterate through `ASCII(null)`, `ASCII(null, null)`, etc. and assert that at least one syntax parses just fine. This isn't a robust unit test, there are enough other tests. But this test serves to discover accidental omissions.

The improvements thus discovered will be listed here:

**Trivial cases**

- [x] `ASCII_CHAR` (oversight from #11231)
- [x] `ATN` (alias for `ATAN` in Access)
- [x] `BOOLAND_AGG` (alias for `BOOL_AND` in Snowflake)
- [x] `BOOLOR_AGG` (alias for `BOOL_OR` in Snowflake)
- [x] `COVAR_POP` (oversight from https://github.com/jOOQ/jOOQ/issues/11157)
- [x] `COVAR_SAMP` (oversight from https://github.com/jOOQ/jOOQ/issues/11157)
- [x] `HEX` (now supported: https://github.com/jOOQ/jOOQ/issues/11656)
- [x] `LOCATE` (alias for `POSITION` in Db2, Derby (`LOCATE(search, in)`) and Hana, Ingres, Sybase SQL Anywhere (`LOCATE(in, search)`))
- [x] `LOGN` (alias for `LN` in Informix)
- [x] `MAXVALUE` (alias for `GREATEST` in Firebird)
- [x] `MINVALUE` (alias for `LEAST` in Firebird)
- [x] `REPLICATE` (alias for `REPEAT` in SQL Server and Sybase)
- [x] `SGN` (alias for `SIGN` in Access)
- [x] `STDDEV` (alias for `STDDEV_POP` in Db2)
- [x] `STDEV_SAMP` (alias for `STDDEV_SAMP` in Informix)
- [x] `STRREVERSE` (alias for `REVERSE` in Access)
- [x] `TRUNCATE` (alias for `TRUNC(number, decimals)` in H2, MariaDB, MemSQL, MySQL)
- [x] `TRUNCNUM` (alias for `TRUNC(number, decimals)` in Sybase SQL Anywhere)
- [x] `VAR` (alias for `VAR_SAMP` in HANA and SQL Server)
- [x] `VARIANCE` (alias for `VAR_POP` in Db2 and Informix)
- [x] `VARIANCE_SAMP` (alias for `VAR_SAMP` in Db2 and Informix)
- [x] `VARP` (alias for `VAR_POP` in SQL Server)

**Moved to separate issue**

**To be reviewed**

- [ ] `ADD_DAYS`
- [ ] `ADD_MONTHS`
- [ ] `ADD_SECONDS`
- [ ] `ARRAY_LENGTH`
- [ ] `COLLECT`
- [ ] `COUNTSET`
- [ ] `CURRENT_BIGDATETIME`
- [ ] `DATALENGTH`
- [ ] `DATEADD`
- [ ] `DATEPART`
- [ ] `DATE_ADD`
- [ ] `DATE_DIFF`
- [ ] `DATE_TRUNC`
- [ ] `DAYS`
- [ ] `DAYS_BETWEEN`
- [ ] `GEN_ID`
- [ ] `HASHBYTES`
- [ ] `ISJSON`
- [ ] `JSONB_AGG`
- [ ] `JSONB_BUILD_ARRAY`
- [ ] `JSONB_OBJECT`
- [ ] `JSONB_OBJECTAGG`
- [ ] `JSONB_OBJECT_AGG`
- [ ] `JSONB_PATH_EXISTS`
- [ ] `JSONB_PATH_QUERY_FIRST`
- [ ] `JSON_AGG`
- [ ] `JSON_BUILD_ARRAY`
- [ ] `JSON_CONTAINS_PATH`
- [ ] `JSON_EXTRACT`
- [ ] `JSON_MERGE`
- [ ] `JSON_OBJECT_AGG`
- [ ] `JSON_QUOTE`
- [ ] `JSON_TABLE`
- [ ] `JSON_VALID`
- [ ] `LENGTHB`
- [ ] `LIST`
- [ ] `LISTAGG`
- [ ] `NANO100_BETWEEN`
- [ ] `RAWTOHEX`
- [ ] `RND`
- [ ] `SCHEMA_NAME`
- [ ] `SECONDS_BETWEEN`
- [ ] `STANDARD_HASH`
- [ ] `STATS_MODE`
- [ ] `STRFTIME`
- [ ] `STRING_AGG`
- [ ] `TIMESTAMPADD`
- [ ] `TO_CLOB`
- [ ] `USER`
- [ ] `WEEKDAY`
- [ ] `ZEROBLOB`

**Comment by lukaseder** [comment]
This is an ongoing task and doesn't need to be kept as an open issue.
