### ISSUE TITLE
Add Trigger runtime meta model

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11248]
#6956 introduces DDL statement support on `TRIGGER`.

A separate task is to implement the entire runtime meta model, import, export, and interpretation of it

### Tasks

- [x] Create an `org.jooq.Trigger` meta model
  - [x] Add `Schema::getTriggers` access
  - [x] Add `Table::getTriggers` access
  - [x] Add `Meta::getTriggers` access
    - [x] Generated code implementation
    - [x] Interpreted implementation
    - [x] XML implementation
    - [x] `DatabaseMetaData` implementation
      - [x] Make `jOOQ-meta` queries available to `MetaSQL`
      - [x] Run queries and fetch triggers in `MetaImpl`
      - [x] Special implementation needed for SQLite, again: Will be done later https://github.com/jOOQ/jOOQ/issues/15890
    - [x] Implement `filterTriggers()`
  - [x] DDL export: Separate issue: https://github.com/jOOQ/jOOQ/issues/15392
  - [x] XML representation
    - [x] `XMLGenerator`
    - [x] `XMLDatabase`
  - [x] Runtime meta representation
  - [x] Code generation representation. Dialect support:
    - [x] Db2
    - [x] Derby
    - [x] Firebird
    - [x] HSQLDB
    - [x] MariaDB
    - [x] MySQL
    - [x] Oracle
    - [x] PostgreSQL
    - [x] SQLite
    - [x] SQL Server
    - [x] YugabyteDB
    - [x] Postponed: https://github.com/jOOQ/jOOQ/issues/15891
      - H2
      - Informix
      - Snowflake
      - Sybase ASE
      - Sybase SQL Anywhere
      - Teradata
      - Vertica
  - [x] Code generation languages:
    - [x] Java
    - [x] Kotlin
    - [x] Scala
  - [x] Export meta model
    - [x] As DDL
    - [x] As InformationSchema
- [x] Interpret DDL
  - [x] `CREATE`
  - [x] `DROP`
- [x] Update DSL to accept `org.jooq.Trigger` in addition to `Name|String`. This is an incompatible change of the `QOM` API and thus needs a separate issue: https://github.com/jOOQ/jOOQ/issues/15872

### Follow up tasks

- [x] Use this information for various `RETURNING` emulations:
  - [x] https://github.com/jOOQ/jOOQ/issues/13912
  - [x] https://github.com/jOOQ/jOOQ/issues/15316

### References:

- Db2: https://www.ibm.com/support/knowledgecenter/SSEPGG_11.5.0/com.ibm.db2.luw.sql.ref.doc/doc/r0000931.html
- MySQL: https://dev.mysql.com/doc/refman/8.0/en/create-trigger.html
- Oracle: https://docs.oracle.com/en/database/oracle/oracle-database/19/lnpls/CREATE-TRIGGER-statement.html#GUID-AF9E33F1-64D1-4382-A6A4-EC33C36F237B
- PostgreSQL: https://www.postgresql.org/docs/current/sql-createtrigger.html
- SQL Server: https://docs.microsoft.com/en-us/sql/t-sql/statements/create-trigger-transact-sql?view=sql-server-ver15

----
See also:
https://stackoverflow.com/q/47969132/521799
