### ISSUE TITLE
Deprecate XYZFinalStep types

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11329]
The current version of jOOQ has 36 types named `XYZFinalStep`:
https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/package-summary.html

![image](https://user-images.githubusercontent.com/734593/106023880-84573c00-60c7-11eb-895a-8d9234b3114b.png)

These types have once been added for two reasons:

- Being able to add auxiliary methods to the end of the actual DSL call chain, which may not have anything to do with the DSL itself. This was never actually done.
- To make sure all paths lead to the same final type, if there are multiple paths to reach that type. This is to make sure that all paths end up with the same common type, such as `DDLQuery`. This can be done through testing the API instead.

All of these interfaces have to be class loaded when the statements are being used. As we're adding more statements (e.g. `CREATE / DROP` of `TRIGGER / PROCEDURE / FUNCTION` and more), it would be good if at the same time we could remove a few unnecessary types.

This is a backwards incompatible change, obviously. While users may be declaring or referencing these types, they don't get any benefit out of it. They might as well just reference each of the `XYZFinalStep` types' super type. E.g. `DDLQuery` or `Query` instead of `AlterDatabaseFinalStep`

### Tasks

- [x] Deprecate the types
- [x] ~Remove the types~
- [x] ~Write a blog post and a stack overflow Q&A documenting all the replacements to help people migrate~

**Comment by lukaseder** [comment]
The `SelectFinalStep` type has a method that people are probably using heavily, still: `SelectFinalStep.getQuery():SelectQuery`. Let's deprecate the types, first, and remove them much later, as always.

**Comment by lukaseder** [comment]
All but `SelectFinalStep` have been deprecated.
