### ISSUE TITLE
MariaDB add support for CHANGE COLUMN

### ISSUE THREAD

**Issue by Kidlike** [jOOQ/jOOQ#11332]
### Expected behavior
change column query should work (https://mariadb.com/kb/en/alter-table/#change-column)

### Actual behavior
throws ParserException

### Steps to reproduce the problem
1. sample code: 
```
DSL.using(SQLDialect.MARIADB).parser().parse("ALTER TABLE t1 CHANGE COLUMN c1 c1_renamed bigint null")
```
2. throws exception:
```
org.jooq.impl.ParserException: ADD, ALTER, COMMENT, DROP, MODIFY, OWNER TO, or RENAME expected: [1:16] ALTER TABLE t1 [*]CHANGE COLUMN c1 c1_renamed bigint null
	at org.jooq.impl.ParserContext.expected(ParserImpl.java:12242)
	at org.jooq.impl.ParserImpl.parseAlterTable(ParserImpl.java:4573)
	at org.jooq.impl.ParserImpl.parseAlter(ParserImpl.java:2618)
	at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:906)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:618)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:605)
```

### Versions

- jOOQ: 3.14.6
- Java: 
```
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.21.0, JRE 11 Linux amd64-64-Bit Compressed References 20200715_697 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - 95bb504fbb based on jdk-11.0.8+10)
```
- Database (include vendor): MariaDB

**Comment by lukaseder** [comment]
Thanks a lot for your suggestion. This `CHANGE COLUMN` clause is a relict from MySQL. I'm happy that MariaDB cleaned up this messy statement and separated concerns into individual statements. It's rare that someone would want to change all properties of a column in one go (name, type, constraints, default expressions), and much more common to accidentally get this wrong. In your case, you could probably use `ALTER TABLE t1 RENAME COLUMN c1 TO c1_renamed`
https://mariadb.com/kb/en/alter-table/#rename-column

Nevertheless, for compatibility with older versions of MariaDB / MySQL, it's certainly worth thinking about supporting this clause - at least in the parser.

**Comment by Kidlike** [comment]
interesting backstory - had no idea :)

**Comment by lukaseder** [comment]
Doing this now for jOOQ 3.21.

### Tasks:

- [x] Add DSL API support
- [x] Add parser support
- [x] Add interpreter support
- [x] Emulations
  - [x] Use `ALTER TABLE .. SET TYPE` if `oldName` and `newName` are the same
  - [x] Generate an anonymous block, otherwise

Will be done separately:

- https://github.com/jOOQ/jOOQ/issues/18565

Out of scope:

- Add `QOM` API support (`ALTER TABLE` isn't supported yet)

**Comment by lukaseder** [comment]
Implemented in jOOQ 3.21.0
