### ISSUE TITLE
Add support for 3-argument REGEXP_LIKE

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11340]
Oracle (and probably a few other dialects) support a 3-argument `REGEXP_LIKE` function of the form:

```
REGEXP_LIKE(source_char, pattern [, match_param ])
```

We currently only support the first two arguments in `Field.likeRegex(pattern)`

### Tasks

- [ ] Support this in the AP
- [ ] Add dialect support and emulations
- [ ] Add parser support

----
See also:
https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/Pattern-matching-Conditions.html#GUID-D2124F3A-C6E4-4CCA-A40E-2FFCABFD8E19
