### ISSUE TITLE
Refactor internal ScopeMarkers functionality

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11367]
The internal `ScopeMarkers` functionality has proven quite useful again for fixing this bug:

- https://github.com/jOOQ/jOOQ/issues/11366
- https://blog.jooq.org/2021/02/04/jooq-internals-pushing-up-sql-fragments/

The current implementation deserves some refactoring, though.

- [x] `DefaultRenderContext::scopeEnd0` should not contain any use-case specific logic
- [x] ~An SPI should be defined where `QueryParts` can register `ScopeMarkers` as well as rendering logic dynamically~ (the more I used this feature, the more it became clear that ultimately, we need to perform expression tree transformations instead, in the long run. So, while this string insertion approach still works decently for now, let's not overengineer it yet, given that we might get rid of it again)

Use cases profiting from this:

- [x] Top level CTEs (existing)
- [x] Top level declarations (existing, https://github.com/jOOQ/jOOQ/issues/11366)
- [x] Nested level declarations (fix for https://github.com/jOOQ/jOOQ/issues/11374)
- [x] Procedure `RETURN` emulation for HSQLDB, MariaDB, MySQL using `LEAVE <label>` (pushing up the label, if needed)
- [x] Emulate label-less iterate and leave in DB2, HSQLDB (existing, https://github.com/jOOQ/jOOQ/issues/8284)
