### ISSUE TITLE
Add R2DBC support

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11700]
R2DBC is likely going to be the standard reactive RDBMS connectivity API in Java. A lot of jOOQ can work out of the box if we implemented a bit of glue code in our internals, and add the dependency on `r2dbc-spi`.

These areas will need to be adapted (see also #11717 for future work and known issues):

- [x] Add the dependency
  - [x] ~There is room for making it optional. Unlike the reactive streams dependency, which is required by the `Query` class hierarchy, this dependency is only needed for method parameters and return types. If users don't call the methods, they don't run into trouble.~ (it doesn't seem to work this way if we have it in `Configuration` etc.
  - [x] We have to ship the `r2dbc-spi.jar` file with our ZIP file, just like the reactive streams jar file
  - [x] The documentation needs to be adapted if someone wants to use jOOQ in a standalone way (without maven / gradle to resolve dependencies)
- [x] Define interaction between `Configuration.connectionFactory()` and `Configuration.connectionProvider()`: Done via `Settings`, see below
- [x] Support working with `ConnectionFactory` or with `Connection` directly
- [x] Offer a `ParsingConnectionFactory` implementation
  - [x] A `Settings.parseNamedParamPrefix` flag will be required here to support R2DBC's `$1` and `$name` style parameter markers (#8821)
- [x] Add `org.jooq.Publisher` that extends both reactive-streams and `Flow.Publisher`, implementing the bridge
- [x] Implement `ResultQuery.subscribe()` via a `ConnectionFactory` (this is the most interesting part)
  - [x] To fetch `Record[N]` types
  - [x] To fetch `TableRecord` types
  - [x] To fetch `Record` types from unknown projections (e.g. plain SQL)
- [x] Implement `RowCountQuery.subscribe()` via a `ConnectionFactory`
- [x] A ton of tests to make sure all converters and data types also work.
  - [x] Make sure `ConverterProvider` works correctly (e.g. to nest collections with JSON). This works via ordinary `Record.map` calls
  - [x] Custom `Converter` (these work as expected)
  - [x] Custom `Binding` (these work because we wrap R2DBC behind a JDBC API, so existing bindings can still be used (to some extent))
- [x] Data types
  - [x] Numeric (including unsigned)
  - [x] String
  - [x] Binary
  - [x] Boolean
  - [x] Temporal types (the JDBC types won't work)
  - [x] Arrays (some arrays work, others don't: https://github.com/pgjdbc/r2dbc-postgresql/issues/394, https://github.com/pgjdbc/r2dbc-postgresql/issues/391)
  - [x] Other types, especially UDTs, might be supported in a future release: #11717
- [x] Conversion of R2DBC types in `ConverterProvider`
  - [x] `ByteBuffer` <-> `byte[]`: https://github.com/jOOQ/jOOQ/issues/11772
- [x] Wrap R2DBC types in JDBC types to re-use jOOQ's internals
  - [x] `R2DBCPreparedStatement` wraps `io.r2dbc.spi.Statement` 
  - [x] `R2DBCResultSetMetaData` wraps `io.r2dbc.spi.RowMetadata`
  - [x] `R2DBCResultSet` wraps `io.r2dbc.spi.Row`
- [x] Support various `Settings`
  - [x] `Settings.fetchSize`
- [x] Add `DSL.using()` methods
  - [x] The resourceful ones should delegate to `ConnectionFactories` to create a `ConnectionFactory`
  - [x] The ones supporting a `ConnectionProvider` should be overloaded with a `ConnectionFactory` or a `Connection`
- [x] Updates to SPIs including
  - [x] `Binding` (doesn't seem necessary thanks to those JDBC-over-R2DBC wrapping types)
- [x] Other types of subscriptions
  - [x] `Batch` API
    - [x] `BatchSingle`
    - [x] `BatchMultiple`
  - [x] `RETURNING` / generated keys (see https://github.com/jOOQ/jOOQ/issues/11190)
    - [x] Native `RETURNING` or `FINAL TABLE (...)` etc support
    - [x] Emulation via generated keys
- [x] Documentation update
- [x] Add integration tests for official R2DBC drivers for:
  - [x] H2 (we might need to set up the test database twice to work around the exclusive locks)
  - [x] MariaDB
  - [x] MySQL
  - [x] Oracle
  - [x] PostgreSQL
  - [x] SQL Server
- [x] Update `JDBCUtils` with some URL parsing, etc. (the URLs parse the same way, we don't care about the `jdbc:` or `r2dbc:` prefix. The major / minor versions won't be parsed for now: https://github.com/r2dbc/r2dbc-spi/issues/204)
- [x] Pass the TCK. A special testing focus lies on:
  - [x] Thread safety
  - [x] Correct `Connection` management
  - [x] ~Check for blocking calls~ (will be done separately: https://github.com/jOOQ/jOOQ/issues/11970)
  - [x] The blocking (JDBC backed) legacy implementation: https://github.com/jOOQ/jOOQ/issues/10245

Other tasks may be added. More work will be done in a future release: #11717

----
A previous idea was to abstract over drivers via an SPI trying to unify different APIs to make sure all life cycle management SPIs work the same way: https://github.com/jOOQ/jOOQ/issues/6298. That is quite a big project, perhaps not even possible. Adding direct support might offer a much quicker win.

**Comment by akarnokd** [comment]
I'd be glad to help with that [odd looking](https://t.co/RhPuRX6Hq3?amp=1) specialized `Subscriber` classes. Is there a branch I should target with my PR? The request management is almost certainly out-of-spec and not thread safe.

**Comment by lukaseder** [comment]
@akarnokd I've just started. I knew I shouldn't have sent you any link. :) Please don't (yet). I'll look into passing the actual TCK later.

**Comment by lukaseder** [comment]
In particular, please disregard the "`BlockingSubscriber`". It is likely to be removed.

**Comment by lukaseder** [comment]
And yes, that `connection` cache is obviously not thread safe...

**Comment by lukaseder** [comment]
This is ready for jOOQ 3.15.0. Early feedback very welcome (release due within a few weeks)

**Comment by lukaseder** [comment]
Known limitations here: https://github.com/jOOQ/jOOQ/issues/11717
