### ISSUE TITLE
Use floating point literals for inline DOUBLE, FLOAT, and REAL literals

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11711]
In a lot of RDBMS, the literal `1.1` is a literal of type `NUMERIC`, not a floating point literal as in Java. This may lead to unexpected behaviour:

- Types and arithmetic may be promoted to `NUMERIC` where undesired
- The wrong (slow) function overloads may be chosen
- Conversions might not work correctly, e.g. while in JDBC, it's possible to fetch a `NUMERIC` value as `REAL` using `ResultSet.getFloat()`, in R2DBC, it may not (yet) be possible

This is not a problem with bind values, in case of which the JDBC or R2DBC driver already passes along the correct type information to the server, but when generating inline literals using `DSL.inline()` or `StatementType.STATIC_STATEMENT`, etc., the behaviour may be wrong.

### Tasks

- [x] Generate vendor specific scientific notation or some other floating point notation everywhere
- [x] Parse the same syntax for all dialects (see https://github.com/jOOQ/jOOQ/issues/9475)

Dialect specific behaviour (almost all dialects require scientific notation!):

**Scientific notation**

- [x] Access: Scientific notation: https://support.microsoft.com/en-us/office/type-conversion-functions-8ebb0e94-2d43-4975-bb13-87ac8d1a2202
- [x] BigQuery: Ordinary notation would suffice, but for the avoidance of doubt, let's use scientific notation: https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical#numeric_literals
- [x] Db2: Scientific notation: https://www.ibm.com/support/knowledgecenter/SSEPGG_11.5.0/com.ibm.db2.luw.sql.ref.doc/doc/r0000731.html
- [x] Derby: Scientific notation https://db.apache.org/derby/docs/10.0/manuals/reference/sqlj124.html
- [x] Exasol: Scientific notation https://docs.exasol.com/sql_references/literals.htm#NumericLiterals
- [x] Firebird: Scientific notation https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref30/firebird-30-language-reference.html#fblangref30-structure-literals
- [x] HANA: Scientific notation https://help.sap.com/viewer/7c78579ce9b14a669c1f3295b0d8ca16/Cloud/en-US/4ee2f261e9c44003807d08ccc2e249ac.html
- [x] HSQLDB: Scientific notation http://hsqldb.org/doc/guide/sqlgeneral-chapt.html
reference/sql-conformance
- [x] Informix: Scientific notation https://www.ibm.com/support/knowledgecenter/SSGU8G_11.50.0/com.ibm.sqls.doc/ids_sqs_1606.htm
- [x] MySQL: Scientific notation https://dev.mysql.com/doc/refman/8.0/en/number-literals.html
- [x] PostgreSQL: Both notations are possible, but a literal syntax like `REAL '1.23'` seems to be useful: https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-CONSTANTS
- [x] Redshift: Scientific notation: https://docs.aws.amazon.com/redshift/latest/dg/r_numeric_literals201.html
- [x] SQL Server: Scientific notation: https://docs.microsoft.com/en-us/sql/t-sql/data-types/constants-transact-sql?view=sql-server-ver15#float-and-real-constants
- [x] Sybase ASE: Scientific notation: http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.dc36271_1251/html/blocks/blocks10.htm
- [x] Teradata: Scientific notation: https://docs.teradata.com/r/S0Fw2AVH8ff3MDA0wDOHlQ/KP9JAKQ6D5ybYxIg1qPhqQ
- [x] Vertica: Scientific notation: https://www.vertica.com/docs/9.2.x/HTML/Content/Authoring/SQLReferenceManual/LanguageElements/Literals/Number-typeLiterals.htm

**Something else or to be verified**

- [x] CockroachDB: Both decimal and scientific notations are equivalent: https://www.cockroachlabs.com/docs/v20.2/sql-constants#numeric-literals. A cast is required!
- [x] H2: Either notation is possible, and a cast is required! http://www.h2database.com/html/grammar.html#decimal
- [x] Ignite: Hard to say from documentation: https://ignite.apache.org/docs/latest/sql
- [x] MariaDB: Documentation isn't clear: https://mariadb.com/kb/en/numeric-iterals/
- [x] Oracle: Both notations are supported, but a suffix `d` or `f` is required to turn `NUMBER` into `BINARY_FLOAT` and `BINARY_DOUBLE`: https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/Literals.html#GUID-083FEFEA-B33F-436B-AEBF-9101A49EF189
- [x] SingleStore: Documentation isn't clear: https://docs.singlestore.com/v7.3/reference/sql-reference/datatypes/#
- [x] Snowflake: Documentation isn't clear: https://docs.snowflake.com/en/sql-reference/data-types-numeric.html#numeric-constants
- [x] SQLite: Is being SQLite: https://sqlite.org/datatype3.html
- [x] Sybase SQL Anywhere: Only documents string and binary literals: http://dcx.sap.com/1200/en/dbreference/sqllanguage-s-5280421.html

N.B: Scientific notation can be achieved in Java using `new DecimalFormat("0.######E0").format(i)`. To be reviewed to find appropriate syntax that does not generate 1) too much 2) too little precision

- [x] Add `Context.doubleFormat()` and `Context.floatFormat()` for that purpose

If in doubt, the following test should help make sure we get it right:

```sql
create view v(x, y) as select 1.1, 1.1e3
```

Now we can introspect the `Meta` data types and see if the columns are of the expected type

**Comment by lukaseder** [comment]
This is a significant change, which won't be backported.
