### ISSUE TITLE
Known limitations of the R2DBC integration

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11717]
jOOQ 3.15 added support for R2DBC: #11700.

There are a few known limitations in this area, which will be fixed in a later release, including:

### Bugs

- [x] https://github.com/jOOQ/jOOQ/issues/12104
- [x] https://github.com/jOOQ/jOOQ/issues/12373

### Features

- [ ] Offer a `DiagnosticsConnectionFactory` implementation
- [ ] Offer a `MockConnectionFactory` implementation
- [ ] Data types
  - [ ] Arrays (some arrays work, others don't: https://github.com/pgjdbc/r2dbc-postgresql/issues/394, https://github.com/pgjdbc/r2dbc-postgresql/issues/391)
  - [ ] Enums
  - [ ] UDTs
  - [ ] Nested records
  - [ ] Embedded records
  - [ ] Binary types (some dialects still have issues):
    - [ ] Oracle has some uncertainty wrt how binary types should be fetched, see https://github.com/r2dbc/r2dbc-spi/issues/210, https://github.com/oracle/oracle-r2dbc/issues/17
- [ ] Large object management
  - [ ] `ByteBuffer` / `byte[]` conversions should be avoided if possible. We do not yet offer a way to work around excess efforts in this area.
- [ ] Fetching of `Results` (via `fetchMany()`). See https://github.com/r2dbc/r2dbc-spi/issues/27, https://github.com/r2dbc/r2dbc-mssql/issues/196
- [ ] Other types of subscriptions
  - [ ] `UpdatableRecord.store()`
  - [ ] `BatchCRUD`
  - [ ] `Loader` API
  - [ ] `DAO`
- [ ] Existing `Settings`
  - [ ] `Settings.statementType` 
- [ ] New `Settings`
  - [ ] To turn on/off the usage of `ConnectionFactory` for `Publisher` (default is use if available, block if not)
  - [ ] To turn on/off the usage of `ConnectionFactory` for `CompletionStage` (default is use if available, block if not)
  - [ ] `Settings.queryTimeout` (not yet available via R2DBC: https://groups.google.com/g/r2dbc/c/bb-FP1r2Wjw, https://github.com/r2dbc/r2dbc-spi/issues/173)
- [ ] Updates to SPIs including
  - [ ] `TransactionListener` and `TransactionProvider`
  - [ ] `ExecuteListener`
    - [ ] See also: https://github.com/jOOQ/jOOQ/issues/12528 (doesn't work yet)
- [ ] Execution of stored procedures
- [ ] Named parameter support
- [ ] Proxy other R2DBC types, such as `Result` in order to introduce our `ConverterProvider` logic to `Row.get()` calls as a workaround for things like https://github.com/mirromutth/r2dbc-mysql/issues/178
- [x] Transactions (see https://github.com/jOOQ/jOOQ/issues/13502)
- [ ] Oracle AQ support (see also: https://github.com/oracle/oracle-r2dbc/issues/27)

**Comment by Inego** [comment]
Why are there 2 different items "A transaction API" and "Transactions"?

**Comment by lukaseder** [comment]
Because adding a new API is different from supporting the existing APIs or the concept itself.

**Comment by saibotma** [comment]
Looking forward for transactions/transactions API!

**Comment by lukaseder** [comment]
Thanks, @saibotma. I'm looking forward to it as well 😁

**Comment by lukaseder** [comment]
Of course, anyone is invited to comment on the suggested API in #13502 directly.

**Comment by lukaseder** [comment]
Work will be continued in jOOQ 3.18: https://github.com/jOOQ/jOOQ/issues/13590
