### ISSUE TITLE
Add Settings.renderCoalesceToEmptyStringInConcat

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11757]
When migrating from Oracle to other RDBMS, the fact that `'' IS NULL` in Oracle gets in the way, especially when concatenating strings. In Oracle this produces a meaningful value

```sql
-- Produces 'ab'
select 'a' || null || 'b' from dual
```

But in other RDBMS (e.g. PostgreSQL), we keep getting `null`:

```sql
-- Yields null
select 'a' || null || 'b'
```

While Oracle's `NULL` and empty string equivalence is very debatable, the concatenation behaviour is useful (even if wrong and inconsistent with other operators according to the standard), and as such, many people rely on this behaviour. When translating between dialects, it would be very useful to have `Settings.renderCoalesceToEmptyStringInConcat` to auto-coalesce all possibly nullable arguments to `Concat`. I.e. the above concatenation would translate to:

```sql
-- Yields what Oracle produces
select 'a' || coalesce(null, '') || 'b'
```

We cannot yet rely on nullability information of data types as we don't yet properly propagate nullability through all of jOOQ (including outer joins, derived tables, etc.), see https://github.com/jOOQ/jOOQ/issues/11070.

But we can add a utility that traverses `QueryPart` trees to collect whether we *know* that the tree is `NOT NULL`, e.g.

- [x] `DSL.inline()` expressions that do not inline the `NULL` literal.
- [x] `DSL.function()` calls and other types of functions whose arguments are all known to be `NOT NULL`, recursively. We'll fix this via #11070

### Tasks

- [x] Add `Settings` flag
- [x] Implement `Settings` flag
- [x] ~Offer flag to https://www.jooq.org/translate~
- [x] Offer flag to `ParserCLI`

### Further work

A quick non-representative Twitter poll didn't produce many other cases than concatenation, where `null` vs empty string causes issues in queries: https://twitter.com/lukaseder/status/1379387147078270976
