### ISSUE TITLE
Add Records class with common record mapping utilities

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11804]
Some repetition seems inevitable in the jOOQ API when mapping records, such as:

```java
record Book (int id, String title, int authorId);

List<Book> book =
ctx.select(BOOK.ID, BOOK.TITLE, BOOK.AUTHOR_ID)
   .from(BOOK)
   .fetch(r -> new Book(r.get(BOOK.ID), r.get(BOOK.TITLE), r.get(BOOK.AUTHOR_ID));
```

It seems redundant to repeat the projection twice. All the information is already there! Some ideas where we derive the `SELECT` clause from the mapped class have been mentioned here: https://github.com/jOOQ/jOOQ/issues/9126. Those ideas are not simple to implement, because client side mapping can interfere with SQL semantics in various ways. However, we don't have to go this far to offer value. What if we had:

```java
interface Function3<T1, T2, T3, R> {
    R apply(T1 t1, T2 t2, T3 t3);
}

static <T1, T2, T3, R extends Record3<T1, T2, T3>, Q> RecordMapper<? super R, Q> mapping(
    Function3<? super T1, ? super T2, ? super T3, ? extends Q> function
) {
    return r -> function.apply(r.value1(), r.value2(), r.value3());
}
```

This utility could now be used as follows:

```java
record Book (int id, String title, int authorId);

List<Book> book =
ctx.select(BOOK.ID, BOOK.TITLE, BOOK.AUTHOR_ID)
   .from(BOOK)
   .fetch(mapping(Book::new));
```

- Completely type safe
- No reflection involved
- No duplication

It can't be implemented directly on `ResultQuery<R>`, because we can't access the various column types `<T1, T2, ..., T[N]>` of the `<R>` type using ordinary Java generics, unless we use a generic method that captures the types. Of course, this implies we add 22 function types, similar to those in the jOOλ library. 

### Tasks

- [x] Create `Function[N]` types, or add a formal dependency on jOOλ (could be done for jOOU and jOOR as well!)
  - [x] In a draft version, create the `Function[N]` types in the `org.jooq` package
  - [x] In a final version, decide whether to keep the above, or add a formal dependency on jOOλ, see #3184
- [x] Add `Records` class with those utilities
- [x] Refer to new utilities from various Javadoc
  - [x] From `RecordMapper`

----
See also:
https://twitter.com/lukaseder/status/1371961110304325636/photo/1

**Comment by lukaseder** [comment]
Implemented this using draft `Function[N]` types in `org.jooq`. The external dependency discussion will be held here: #3184
