### ISSUE TITLE
Let Row[N]<T1, T2, ..., TN> extend SelectField<Record[N]<T1, T2, ..., TN>>

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11812]
We don't need `DSL.rowField()` for most purposes! Instead, why not just let `Row[N]<T1, T2, ..., TN>` extend `SelectField<Record[N]<T1, T2, ..., TN>>`?

E.g. `Row2`:

```java
public interface Row2<T1, T2> extends Row, SelectField<Record2<T1, T2>> { ... }
```

That way, we can write:

```java
Result<Record2<Integer, Record2<String, String>>> result =
ctx.select(
      AUTHOR.ID,
      row(AUTHOR.FIRST_NAME, AUTHOR.LAST_NAME)
)
.from(AUTHOR)
.fetch();
```

Obviously, users would not denote the `result` type, but use `var` instead, or even profit from new functionality, such as:

- #7100 ad-hoc conversion
- #11804 turning constructor references into `RecordMapper` types

To get:

```java
record Name (String firstName, String lastName) {}
record Author (int id, Name name) {}

List<Author> result1 =
ctx.select(
      AUTHOR.ID,
      row(AUTHOR.FIRST_NAME, AUTHOR.LAST_NAME).convert(mapping(Name::new))
)
.from(AUTHOR)
.fetch(mapping(Author::new));
```

### Tasks

- [x] Deprecate `DSL.rowField()` it will no longer be needed
  - [x] Instead, offer some conversion methods on `Row`
  - [x] ~Think about accepting `SelectField` in `DSLContext.newRecord()` (?)~ (out of scope for now)
  - [x] ~Create specialised versions of `ARRAY_AGG()` or `LEAD()`, `LAG()`, etc. with proper emulations~ (there exist issues already)
- [x] Add parser support
- [x] Pull up `Field.convert()` to `SelectField.convert()`
- [x] Pull up `Field.as()` to `SelectField.as()` (?)
- [x] Review all `instanceof` checks on a `SelectFieldOrAsterisk` type, possibly refactor to make it exhaustive
  - [x] There are only 3 cases so far. Let's not overengineer exhaustiveness checks (yet)
  - [x] Support `ROW` syntax also for `RETURNING`
- [x] Other "known issues" extracted here: https://github.com/jOOQ/jOOQ/issues/11824
- [x] More tasks here: https://github.com/jOOQ/jOOQ/issues/11998

**Comment by lukaseder** [comment]
Let's first make sure that nested `row()` expressions work correctly on all dialects, including in scalar subqueries, not just the ones with native support.

**Comment by lukaseder** [comment]
A related task will be to support `ROW` nesting: https://github.com/jOOQ/jOOQ/issues/6080

**Comment by lukaseder** [comment]
Remaining work to be done in #11824 and #11998
