### ISSUE TITLE
Improve procedural language abstraction API

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11878]
This issue continues the work of #6475, #8450, #10528 from version 3.12, 3.14, 3.15

### TODO:

- [ ] #2558 SQL session variables
- [ ] #8177 `FOR` loops (implicit cursor) support
- [ ] #8200 `GOTO` statement emulation
- [ ] #8202 `EXIT <label>` and `CONTINUE <label>` emulation for SQL Server
- [ ] #8216 Record types support
- [ ] #8228 Record types emulation
- [ ] #8229 Exception handling support
- [ ] #8307 Variable block scope emulation
- [ ] #8314 Work around lack of T-SQL's block scope
- [ ] #8526 Local `PROCEDURE` and `FUNCTION` declarations
- [ ] #8747 `EXECUTE` support in H2
- [ ] #9951 `USING` with `EXECUTE IMMEDIATE`
- [ ] #9957 `PREPARE`, `EXECUTE`, and `DEALLOCATE`
- [ ] #11396 Emulate dynamic `SIGNAL` SQLSTATE values where not supported
- [ ] #11407 `CURSOR` variables and operations on cursors
- [ ] #11434 Fix emulation of `SELECT .. INTO .. ORDER BY` ordering by aliases, in SQL Server

### To be investigated

- [ ] Table variables (HSQLDB, T-SQL)
- [ ] Print statements to log to the console
- [ ] A way to access update counts, such as PL/SQL's `SQL%rowcount`
- [ ] A way to access table types, such as PL/SQL's `TABLE.COL%TYPE` or Informix's `LIKE table.col`
- [ ] `PIPE`, `SUSPEND`, etc commands for pipelined functions
