### ISSUE TITLE
Let AbstractRecord extend Map<String, Object> for better out-of-the-box Jackson/Gson serialisation support

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11889]
A jOOQ `Record` is a kind of `Map<String, Object>`. It already exposes this behaviour when calling `Record.intoMap(): Map<String, Object>`.

The benefit of doing this would be improved interoperability with Jackson or Gson, which could then serialise a record in the most intuitive way, out of the box.

The caveat here is obviously that a `Record` can have duplicate column names because top level selects allow this, e.g.

```java
ctx.select(BOOK.ID, BOOK.author().ID)
   .from(BOOK)
   .fetch();
```

The `Record.intoMap()` method currently throws:

```
Exception in thread "main" org.jooq.exception.InvalidResultException: Field ID is not unique in Record : +----+----+
|  ID|  ID|
+----+----+
|   1|   1|
+----+----+

	at org.jooq.impl.AbstractRecord.intoMap(AbstractRecord.java:679)
	at org.jooq.impl.Tools.map(Tools.java:1941)
	at org.jooq.impl.ResultImpl.intoMaps(ResultImpl.java:259)
	at org.jooq.testscripts.JDBC.main(JDBC.java:44)
```

So, with this subtype suggestion, we have the choice between

- [x] Either we find a way to re-interpret the `Map` contract and offer both `ID` columns when iterating the `Map` (after all, JSON also allows duplicate keys). This seems to work!
- [x] ~Or, we produce only the first or the last `ID` column / value~
- [x] ~Or, we throw the same exception whenever an ambiguous column is being accessed~

In any case, users can work around this with aliasing.

A driving motivation for this is https://github.com/spring-projects/spring-boot/issues/26457, where jOOQ `Result` and `Record` types could be automatically serialised as JSON in Spring, quite the benefit from this change!

### Tasks

- [x] Let `Record <: Map<String, Object>`
- [x] Retrofit `Record.intoMap()` and `Result.intoMaps()` to return themselves
- [x] Add Javadoc to `Record` documenting the behaviour

----
See also:

- https://github.com/spring-projects/spring-boot/issues/26457
- https://github.com/jOOQ/jOOQ/issues/11203

**Comment by lukaseder** [comment]
A quick draft is very promising (just a draft. Some write operations can be improved, and some read operations should return views, not copies):

```java
    @Override
    public boolean isEmpty() {
        return false;
    }

    @Override
    public boolean containsKey(Object key) {
        return Tools.anyMatch(fields.fields.fields, f -> f.getName().equals(key));
    }

    @Override
    public boolean containsValue(Object value) {
        return Tools.anyMatch(values, v -> Objects.equals(v, value));
    }

    @Override
    public Object get(Object key) {
        return get("" + key);
    }

    @Override
    public Object put(String key, Object value) {
        throw new UnsupportedOperationException();
    }

    @Override
    public Object remove(Object key) {
        throw new UnsupportedOperationException();
    }

    @Override
    public void putAll(Map<? extends String, ? extends Object> m) {
        throw new UnsupportedOperationException();
    }

    @Override
    public void clear() {
        throw new UnsupportedOperationException();
    }

    @Override
    public Set<String> keySet() {
        return new HashSet<>(Tools.map(fields.fields.fields, f -> f.getName()));
    }

    @Override
    public Collection<Object> values() {
        return Arrays.asList(values);
    }

    @Override
    public Set<Entry<String, Object>> entrySet() {
        return new HashSet<>(Tools.map(fields.fields.fields, (f, i) -> new AbstractMap.SimpleImmutableEntry<>(f.getName(), get(i))));
    }
```

Then using it like this:

```java
var r1 = DSL.using(connection)
    .selectFrom(T_BOOK)
    .fetch();
System.out.println(new ObjectMapper().writeValueAsString(r1));
System.out.println(new Gson().toJson(r1));

var r2 = DSL.using(connection)
    .select(
        T_BOOK.ID,
        T_BOOK.fkTBookAuthorId().ID,
        row(T_BOOK.fkTBookAuthorId().FIRST_NAME, T_BOOK.fkTBookAuthorId().LAST_NAME).as("author"),
        array(select(row(T_BOOK_TO_BOOK_STORE.tBookStore().NAME, T_BOOK_TO_BOOK_STORE.STOCK))
            .from(T_BOOK_TO_BOOK_STORE)
            .where(T_BOOK_TO_BOOK_STORE.BOOK_ID.eq(T_BOOK.ID))).as("stock")
    )
    .from(T_BOOK)
    .fetch();
System.out.println(new ObjectMapper().writeValueAsString(r2));
System.out.println(new Gson().toJson(r2));
```

The results produced by jOOQ from the DEBUG logs look like:

```
+----+---------+------------+----------+------------+------------+-----------+------------+-----------+--------+-----------+---------------------+
|  id|author_id|co_author_id|details_id|title       |published_in|language_id|content_text|content_pdf|status  |rec_version|rec_timestamp        |
+----+---------+------------+----------+------------+------------+-----------+------------+-----------+--------+-----------+---------------------+
|   1|        1|      {null}|    {null}|1984        |        1948|          1|{null}      |{null}     |ORDERED |          1|2010-01-01 00:00:00.0|
|   2|        1|      {null}|    {null}|Animal Farm |        1945|          1|{null}      |{null}     |ON STOCK|     {null}|2010-01-01 00:00:00.0|
|   3|        2|      {null}|    {null}|O Alquimista|        1988|          4|{null}      |{null}     |ON STOCK|          1|{null}               |
|   4|        2|      {null}|    {null}|Brida       |        1990|          2|{null}      |{null}     |SOLD OUT|     {null}|{null}               |
+----+---------+------------+----------+------------+------------+-----------+------------+-----------+--------+-----------+---------------------+

+----+----+----------------+--------------------------------------------------+
|  id|  id|author          |stock                                             |
+----+----+----------------+--------------------------------------------------+
|   2|   1|(George, Orwell)|[(Orell Füssli, 10)]                              |
|   1|   1|(George, Orwell)|[(Orell Füssli, 10), (Ex Libris, 1)]              |
|   4|   2|(Paulo, Coelho) |[]                                                |
|   3|   2|(Paulo, Coelho) |[(Orell Füssli, 10), (Ex Libris, 2), (Buchhandl...|
+----+----+----------------+--------------------------------------------------+
```

And the JSON (unformatted, as printed from the above code):

```
[{"status":"ORDERED","rec_version":1,"content_text":null,"language_id":1,"co_author_id":null,"details_id":null,"published_in":1948,"id":1,"author_id":1,"title":"1984","content_pdf":null,"rec_timestamp":1262300400000},{"rec_version":null,"content_text":null,"language_id":1,"title":"Animal Farm","co_author_id":null,"status":"ON_STOCK","details_id":null,"published_in":1945,"id":2,"author_id":1,"content_pdf":null,"rec_timestamp":1262300400000},{"rec_version":1,"content_text":null,"published_in":1988,"co_author_id":null,"status":"ON_STOCK","rec_timestamp":null,"language_id":4,"details_id":null,"id":3,"author_id":2,"title":"O Alquimista","content_pdf":null},{"rec_version":null,"content_text":null,"published_in":1990,"language_id":2,"co_author_id":null,"title":"Brida","rec_timestamp":null,"status":"SOLD_OUT","details_id":null,"author_id":2,"id":4,"content_pdf":null}]
[{"status":"ORDERED","rec_version":1,"language_id":1,"published_in":1948,"id":1,"author_id":1,"title":"1984","rec_timestamp":"Jan 1, 2010, 12:00:00 AM"},{"language_id":1,"title":"Animal Farm","status":"ON_STOCK","published_in":1945,"id":2,"author_id":1,"rec_timestamp":"Jan 1, 2010, 12:00:00 AM"},{"rec_version":1,"published_in":1988,"status":"ON_STOCK","language_id":4,"id":3,"author_id":2,"title":"O Alquimista"},{"published_in":1990,"language_id":2,"title":"Brida","status":"SOLD_OUT","author_id":2,"id":4}]
[{"author":{"last_name":"Orwell","first_name":"George"},"id":2,"id":1,"stock":[{"v1":"10","v0":"Orell Füssli"}]},{"author":{"last_name":"Orwell","first_name":"George"},"stock":[{"v1":"10","v0":"Orell Füssli"},{"v0":"Ex Libris","v1":"1"}],"id":1},{"author":{"last_name":"Coelho","first_name":"Paulo"},"id":2,"stock":[],"id":4},{"stock":[{"v1":"10","v0":"Orell Füssli"},{"v0":"Ex Libris","v1":"2"},{"v0":"Buchhandlung im Volkshaus","v1":"1"}],"author":{"last_name":"Coelho","first_name":"Paulo"},"id":3,"id":2}]
[{"author":{"last_name":"Orwell","first_name":"George"},"id":2,"id":1,"stock":[{"v1":"10","v0":"Orell Füssli"}]},{"author":{"last_name":"Orwell","first_name":"George"},"stock":[{"v1":"10","v0":"Orell Füssli"},{"v0":"Ex Libris","v1":"1"}],"id":1},{"author":{"last_name":"Coelho","first_name":"Paulo"},"id":2,"stock":[],"id":4},{"stock":[{"v1":"10","v0":"Orell Füssli"},{"v0":"Ex Libris","v1":"2"},{"v0":"Buchhandlung im Volkshaus","v1":"1"}],"author":{"last_name":"Coelho","first_name":"Paulo"},"id":3,"id":2}]
```

One JSON example, formatted:

```json
[
   {
      "author":{
         "last_name":"Orwell",
         "first_name":"George"
      },
      "id":2,
      "id":1,
      "stock":[
         {
            "v1":"10",
            "v0":"Orell Füssli"
         }
      ]
   },
   {
      "author":{
         "last_name":"Orwell",
         "first_name":"George"
      },
      "stock":[
         {
            "v1":"10",
            "v0":"Orell Füssli"
         },
         {
            "v0":"Ex Libris",
            "v1":"1"
         }
      ],
      "id":1
   },
   {
      "author":{
         "last_name":"Coelho",
         "first_name":"Paulo"
      },
      "id":2,
      "stock":[
         
      ],
      "id":4
   },
   {
      "stock":[
         {
            "v1":"10",
            "v0":"Orell Füssli"
         },
         {
            "v0":"Ex Libris",
            "v1":"2"
         },
         {
            "v0":"Buchhandlung im Volkshaus",
            "v1":"1"
         }
      ],
      "author":{
         "last_name":"Coelho",
         "first_name":"Paulo"
      },
      "id":3,
      "id":2
   }
]
```

This confirms that we can "bend" the `Map` contract by having duplicate keys, and both Jackson and Gson seem to pick it up just fine!

**Comment by lukaseder** [comment]
The one big concern I have with this approach (but it might be a price worth paying) is that there will be that `Record` would now have:

- Some confusing new overloads, like `Map.get(Object)`, which does the same thing as `Map.get(String)` but removes type safety
- Some write operations that don't make sense on a `Record`, including:
  - `isEmpty()` (always `false`, because there is no `Record0` type in jOOQ (yet: https://github.com/jOOQ/jOOQ/issues/5982))
  - `put()` and `putAll()` will run into problems when trying to update an ambiguous column name, or when trying to add a new one, which is forbidden
  - `remove()` and `clear()` are not allowed, because a `Record`'s structure is immutable

I'll investigate this further. If I don't find any show stoppers, I'm willing to accept the above quirks given how powerful this new feature is for everyone using Gson or Jackson!

**Comment by lukaseder** [comment]
After careful thought, the above concerns are too significant to rush this. Too much `Map` API is added to `Record`, and the `Map` contract violation is a sore spot.

However, the `AbstractRecord` type could implement `Map<String, Object>` for experimental support of out-of-the-box Jackson/Gson serialisation.

I'll further investigate that alternative option.

**Comment by lukaseder** [comment]
Can't let `AbstractRecord` implement `Map<String, Object>`, as the type will leak through public subtypes, such as `TableRecordImpl`... So, it's either public API or nothing.

**Comment by lukaseder** [comment]
I'm delaying this task for now. I don't have a clear picture of the best solution here. Meanwhile, users can register their own Jackson serialisers

**Comment by mmm8955405** [comment]
You're a year late and haven't finished yet!

**Comment by lukaseder** [comment]
Closing this as won't fix. The reservations were justified, and the leaking of `Map` into public API of the `Record` type isn't acceptable.

**Comment by lukaseder** [comment]
I mean, we could generate record subclasses of type `GeneratedType & Map`, but that sounds even hairier!
