### ISSUE TITLE
Deprecate org.jooq.tools.Convert, the public API

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11898]
Since jOOQ 3.14, we have a `ConverterProvider` SPI that allows for overriding the usual calls to `Convert.convert()` by jOOQ's internals: https://github.com/jOOQ/jOOQ/issues/3896

An SPI is a much cleaner approach to this arbitrary PHP/JavaScript style type conversion functionality than a public static API that isn't even in the `org.jooq.impl` package. There have been numerous issues in the past, such as e.g. https://github.com/jOOQ/jOOQ/issues/11897, where the static API failed because it couldn't access a `Configuration`, which could offer some SPI access (such as e.g. Jackson/Gson configuration), as well as caching.

The conversion utility by itself isn't that useful to users, compared to using it in the API, implicitly (e.g. `record.get(0, int.class)`).

### Tasks

- [x] Deprecate the `Convert` class for removal
- [x] Create a package-private copy of the `Convert` class in `org.jooq.impl`
- [x] Look into a strategy of merging its functionality with the `ConverterProvider` SPI, allowing for more caching, etc. This will be done as part of  https://github.com/jOOQ/jOOQ/issues/11894
