### ISSUE TITLE
Improve Settings.parseWithMetaLookups

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11967]
Continuing https://github.com/jOOQ/jOOQ/issues/7163, #9061, and #10514, which have been implemented incompletely.

----

In some situations, it might be useful for the parser to be able to discover actual objects from the catalog through a `MetaProvider` (see #5296). For instance:

- Does a schema / table / column really exist?
- What's the data type of the object?

We need to add a setting with the following options:

- No lookups (current behaviour, default)
- Lookups, ignoring failures
- Lookups, throwing errors on failures

### Tasks:

- [ ] Support for case insensitive lookups (#9239)
- [ ] Support looking up domains and other user defined data types (#10489)
  - [ ] Ambiguities count only when the ambiguous columns are from the same scope
- [ ] Sequence and other identifiers are not looked up yet
- [ ] Scoping in `JOIN .. ON` predicates is incorrect. E.g. with `A join B on X = Y join C on Y = Z`, `X` needs to be looked up only in `A` and `B`, not in `C`
- [ ] Wrong ambiguity reported in correlated subqueries (#11143)
- [ ] Can we look up references outside the `SELECT` clause more eagerly?

The caveats exposed here make it clear that perhaps we cannot achieve all the parsing in a single go as we did until now, but will need to run two passes. The first one can already resolve all table references, whereas we will have to wait for the second pass to resolve the column references.
