### ISSUE TITLE
Various parser bugs / missing features

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11966]
This is a continuation of https://github.com/jOOQ/jOOQ/issues/10572

----

Some features were not yet supported in the jOOQ 3.9 parser. We'll fix them all in this single issue in order not to create too many issues. Here's the list of fixed things:

### SELECT features

- [x] `WITH` in parenthesised set operations or derived tables (see #11602):
  - [ ] `select 1 union (with t (c) as (select 1) select c from t)`
- [ ] Select columns called `SKIP`, `TOP`, `FIRST` etc. to be sure that works on databases where that is not reserved syntax.
- [ ] Hints
  - [ ] SQL Server style
    - [ ] JOIN hints (support in jOOQ first: #7213)
    - [ ] Query hints: https://docs.microsoft.com/en-us/sql/t-sql/queries/hints-transact-sql-query
  - [ ] MySQL style
- [ ] `SAMPLE` clause (support it in jOOQ, first: #2561)
- [ ] JOIN operation precedence is incorrect

### Other statements

- [ ] `exec sp_rename` calls
- [ ] `OUTPUT` clause from SQL Server
- [ ] `COMMIT`, `ROLLBACK`, `ROLLBACK TO SAVEPOINT`, `SAVEPOINT` statements (support in jOOQ first: #7106)
- [ ] `CREATE TABLE`: Vendor-specific storage clauses (support in jOOQ first: #6131)
  - [ ] DB2 storage options:
  - [ ] Oracle storage options:
  - [ ] PostgreSQL storage options
  - [ ] SQL Server storage options: https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql
- [ ] `CREATE TABLE`: Vendor-specific partition clauses (does this need support in jOOQ?)
- [ ] `CREATE TABLE`: Various `IDENTITY` syntaxes
used. See: #7347, #7348
- [ ] `CREATE TABLE .. ON [PRIMARY]` syntax (see https://stackoverflow.com/q/2798213/521799, ignore this syntax)
- [ ] `CREATE TABLE`: Data type specification `ON UPDATE <expr>` action (support in jOOQ first: #6132) 
- [ ] `ALTER TABLE .. MODIFY .. IF EXISTS`
- [ ] `ALTER TABLE .. MODIFY ( c1 type1, c2 type2, ..., cN typeN )` (support in jOOQ first: #7898)
- [ ] PL/SQL spool character `/`
- [ ] Local variable `DECLARE` statements (MySQL, SQL Server)
- [ ] Local variable `SET` statements / assignments
- [ ] JDBC escape syntax for the limit clause: `{limit <limit clause>}` with `rows [offset row_offset]`
- [ ] Add support for `ALTER TYPE` (support in jOOQ first: #7775)
- [ ] Parse and ignore these statements:
  - [ ] `CREATE EXTENSION ...` (PostgreSQL)
  - [ ] `CREATE TYPE ...` (PostgreSQL, Oracle)
  - [ ] Unknown `GRANT` and `REVOKE` privileges, roles, etc.
- [ ] `CREATE CLUSTERED INDEX` and other `CLUSTERED` features. Could be emulated as IOT in Oracle (see #9561)
- [ ] `PRIMARY KEY | UNIQUE (b DESC)` (SQL Server: Support in jOOQ first: #7899)

### Table expressions

- [ ] `PARTITION BY .. OUTER JOIN`
- [ ] DB2 data change table (`{ FINAL | NEW | OLD } TABLE ( { INSERT | UPDATE | DELETE } )`) (support in jOOQ first: https://github.com/jOOQ/jOOQ/issues/5306)
- [ ] `VALUES` constructor (as top-level query) must generate correct query e.g. for Oracle
- [ ] `VALUES` constructor (in CTE)
- [ ] Derived column lists with less than required columns (supported by PostgreSQL)
- [ ] Throw an error if a derived column list has too many columns
- [ ] `PIVOT` with `ROW` expressions in `FOR` and `IN` clauses (support this in jOOQ first https://github.com/jOOQ/jOOQ/issues/6100)
- [ ] `PIVOT` on aliased derived tables, e.g. `SELECT .. FROM (...) t PIVOT (...) u`
- [ ] `UNPIVOT` (support this in jOOQ first https://github.com/jOOQ/jOOQ/issues/1043)
- [ ] `CHECK OPTION` (subquery restriction clause) (Support this in jOOQ first https://github.com/jOOQ/jOOQ/issues/6098)
- [ ] `PARTITION` selection clause (Support this in jOOQ first #2774)
- [ ] Table valued function calls

### Column expressions (and predicates)

- [ ] PostgreSQL JSON functions
  - [ ] `JSON_STRIP_NULLS` (inside of `JSON_AGG`: translate to `ABSENT ON NULL` clause)
  - [ ] `JSON_STRIP_NULLS` (as a standalone function)
- [ ] Various function aliases (see #11232)
- [ ] `ROW` constructor (in projection)
- [ ] `CASE` expression: Simple form with extension, e.g. `CASE v WHEN = 1 THEN .. WHEN NOT NULL THEN ..` (currently not supported through the jOOQ API)
- [ ] Support the SQL Server overloaded `+` operator (arithmetic and string concat)
- [ ] `CONCAT()` generates unnecessary casts (because column type is unknown to parser)
- [ ] `COLLECT` aggregate function
- [ ] `STRING_AGG` aggregate function
- [ ] JDBC escape syntax for LIKE escape characters `{escape '<escape-character>'}`
- [ ] `group_concat` without order by generates wrong `listagg` in Oracle (without `WITHIN GROUP`)
- [ ] All sorts of vendor-specific functions
  - [ ] SQLite `DATE[TIME](x, modifier, modifier, ...)` function (see #8367)
  - [ ] PostgreSQL's array functions (e.g. `array_to_string`)
  - [ ] Oracle's `SYSDATE` and `SYSTIMESTAMP` (and others?) expressions (see #9716)
  - [ ] Oracle's hierarchical functions, such as `SYS_CONNECT_BY_PATH`
sql/functions/logical-functions-iif-transact-sql
  - [ ] `DATEDIFF` (SQL Server version) https://docs.microsoft.com/en-us/sql/t-sql/functions/datediff-transact-sql (support in jOOQ first: #7900)
- [ ] `x = ANY(array_expression)`
- [ ] Support Firebird's `MINVALUE()` and `MAXVALUE()` functions (https://firebirdsql.org/refdocs/langrefupd25-intfunc-minvalue.html)
- [ ] MySQL's `INSERT` function (corresponds to `OVERLAY`: https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_insert)

### Operators

- [ ] MySQL `DIV` operator (see https://dev.mysql.com/doc/refman/5.7/en/non-typed-operators.html)
- [ ] MySQL `MOD` operator
- [ ] Bitwise operators (e.g. PostgreSQL's `a & b`, `a | b`, `~a` etc.)
- [ ] Bitwise and logical `XOR` operator

### Literals and data types

- [ ] Various interval literals
  - [ ] Oracle interval literals
  - [ ] Others?
- [ ] Interval cast expressions should translate the interval syntax, if vendor specific
- [ ] MySQL escaped string literals (e.g. `\\` and `\'` in strings)
- [ ] PostgreSQL escape syntax for unicode string literals (see #6777)
- [ ] Unicode escapes in string literals
- [ ] Floating point numbers
- [ ] MySQL `_utf8'...'` string literal (and similar?)
- [ ] MySQL `[ VAR ] CHAR BINARY` type
- [ ] All JDBC escape functions (their syntaxes may vary from our existing syntax support: http://download.oracle.com/otn-pub/jcp/jdbc-4_2-mrel2-eval-spec/jdbc4.2-fr-spec.pdf)
- [ ] Nonstandard binary literals (other than `X'1234ABCD'`)
- [ ] SQL Server `datetimeoffset`
- [ ] Firebird `CHARACTER SET` specification, e.g. `KIT_NAME varchar(50) CHARACTER SET NONE`
- [ ] SQL Server `DATETIME2` data type

### Language features

- [ ] Spring (and others?) indexed bind variable syntax `?1 .. ?2`
- [ ] Qualified vs unqualified identifiers at various locations
- [ ] Quoted identifiers with escaped quote character, e.g. `1 AS "a "" b"`
- [ ] Support trigraphs (e.g. `[` = `??(` etc.)
- [ ] Support PostgreSQL's scalar-function-in-from-clause feature
- [ ] New PostgreSQL specific `DateParts`: #2132
- [ ] `@` and `#` characters in identifiers (for SQL Server)
- [ ] SQL Server default schema qualifiers: `CatalogName..TableName` (see also #10604)
- [ ] String literals in comments: `select 1 -- ''`
- [ ] MySQL string literals using double quotes `select concat("abc", "def")` meaning the same thing as `select 'abc' || 'def'` (needs an input dialect to be configured: #7337)
- [ ] MySQL executable comments (#8112)
- [ ] T-SQL statement batches containing procedural code

### Other improvements

- [ ] Work more with arrays to prevent conversion from/to collections
- [ ] Performance
  - [ ] Too much time is being spent in `parseWhitespaceIf()` (see also: #10671)
- [ ] Support Firebird `SET TERM` similar to MySQL's `DELIMITER` feature

### New features

- [ ] Support parsing literals as bind values
- [ ] Recognise `DUAL` synonyms like `sys.dual`, `sysibm.dual`, `sysibm.sysdummy1`, `sys.dummy` (perhaps, make that configurable) (see #6023 and #9182)

**Comment by lukaseder** [comment]
To be continued: https://github.com/jOOQ/jOOQ/issues/14682
