### ISSUE TITLE
Let Condition extend Field<Boolean>

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11969]
A `Condition` is really a `Field<Boolean>`. Throughout the jOOQ API, we tend to overload the API and accept both, e.g.

```java
interface Condition {
  Condition and(Condition c);
  Condition and(Field<Boolean> f);
}
```

### Experiments (see comments below)

Some experiments show that it might be possible to let `Condition <: Field<Boolean>` directly, rather than the workaround of letting `Condition <: SelectField<Boolean> & GroupField & SortField<Boolean>`. The first option would make using `Condition` as field really versatile, including supporting it in `nvl()`, `coalesce()`, etc.

### Ambiguities

The experiments did not hint at any ambiguities arising from API usage, because `Condition` is always more specific than `Field<Boolean>` or `Field<?>`, so the compiler should be able to continue dispatching to the right method.

In case ambiguities do arise, we might consider removing the `Field<Boolean>` overloads again (see various past issues, including https://github.com/jOOQ/jOOQ/issues/10402, https://github.com/jOOQ/jOOQ/issues/3203, etc.).

### Tasks

- [x] Add the subtype hierarchy
- [x] Add `Context.visit(Field<?>)` and `Context.visit(Condition)` to auto-wrap all `Field<Boolean>` in `ConditionAsField`, if they are also `Condition`
- [x] Implement the disambiguation logic to all relevant `QueryPartList` types
  - [x] ~`GroupFieldList`~ (unnecessary, see below)
  - [x] ~`SelectFieldList`~ (unnecessary, see below)
  - [x] ~`SortFieldList`~ (unnecessary, see below)
  - [x] Other types of `QueryPartCollectionView<Field<?>>`, which could be recognised automatically via a reification trick? https://twitter.com/lukaseder/status/1526227345711026183
    - [x] Currently, the reification trick isn't required as no `QueryPartCollectionView<Condition>` is being declared, ever.

**Comment by lukaseder** [comment]
Reconsidering this because it would play nicely with a new feature of jOOQ 3.17, the generated "exists convenience" methods:
https://github.com/jOOQ/jOOQ/issues/13069

With #13069, I can write:

```java
Result<Record3<Integer, String, Boolean>> r =
ctx.select(
        T_LANGUAGE.ID,
        T_LANGUAGE.CD,
        field(T_LANGUAGE.tBookExists(b -> b.where(b.ID.in(2, 4)))))
   .from(T_LANGUAGE)
   .orderBy(T_LANGUAGE.ID)
   .fetch();
```

But it would also be nice to be able to write this, without having to wrap the `EXISTS` expression in `field(Condition)`:

```java
Result<Record3<Integer, String, Boolean>> r =
ctx.select(
        T_LANGUAGE.ID,
        T_LANGUAGE.CD,
        T_LANGUAGE.tBookExists(b -> b.where(b.ID.in(2, 4))))
   .from(T_LANGUAGE)
   .orderBy(T_LANGUAGE.ID)
   .fetch();
```

This would be possible if `Condition <: SelectField<Boolean>`.

Even better if `Condition <: Field<Boolean>`. I'll review that option again right now.

**Comment by lukaseder** [comment]
The biggest problem in a refactoring where `Condition <: Field<Boolean>` is to find all the "accidents" where a static import `DSL.count()` now gets changed into `Field.count()`. Integration tests only discovered one such case so far, but there may be more hidden cases.

**Comment by lukaseder** [comment]
It really seems to be the only case. I just verified this by removing all that deprecated `Field.xyz()` API...

**Comment by lukaseder** [comment]
Given how well this works in PostgreSQL, I would really love to go forward with this, but it's hard to get right for all dialects. Whenever a `Condition` is passed somewhere a `Field<Boolean>` is expected (e.g. to `select()`, `groupBy()`, `orderBy()`, or any function, like `nvl()`), we have to ensure the `Condition` is wrapped as `field(Condition)`, either:

- When the expression tree is created
  - Every `QueryPart` could handle the case of a `Field<?>` being declared, but a `Condition` being passed
  - We could implement this logic in the ubiquitous `Tools::nullSafe`
- When the SQL is traversed
  - Every `QueryPart` could handle the case of a `Field<?>` being declared, but a `Condition` being rendered
  - There could be a `Context.visit(Field<?>)` overload, which handles the case where the `Field<?>` also implements `Condition`

Some options feels a bit "clever," almost hackish, but would ensure we do the right thing (almost) *everywhere*, with only a single method. At least, all the non-collection cases would be covered.

**Comment by lukaseder** [comment]
I wonder if we can recognise arbitrary `QueryPartCollectionView<Field<?>>` types via a cunning reification trick?

```
jshell> @SafeVarargs <T> void m(Iterable<T> iterable, T... reify) {
   ...>     System.out.println(reify.getClass().getComponentType());
   ...> }
|  created method m(Iterable<T>,T...)

jshell> m(List.of())
class java.lang.Object

jshell> m(List.of(1))
class java.lang.Integer

jshell> m(List.<String>of())
class java.lang.String
```

See also: https://twitter.com/lukaseder/status/1526227345711026183

**Comment by lukaseder** [comment]
The reification trick would work, but maybe, it isn't really necessary. While there are plenty of `QueryPartCollectionView<Field<?>>`, there's not a single `QueryPartCollectionView<Condition>`, so we can (currently) safely say that for every `QueryPartCollectionView<Field<?>>`, if an element is a `Condition`, we must wrap it as a `ConditionAsField`

**Comment by lukaseder** [comment]
Continuing this. I just realised, this would open up `Condition` also to ad-hoc conversion, which is very cool, e.g.

```java
exists(selectOne()).convertFrom(b -> b ? x : y);
```

**Comment by lukaseder** [comment]
This obsoletes https://github.com/jOOQ/jOOQ/issues/4771

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.17.0
