### ISSUE TITLE
Fix known limitations of embeddable types

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11975]
This is a continuation of #8353, #10527, which fixed a lot of issues already in jOOQ 3.14 / 3.15

### Runtime library (known issues)

- [ ] Support for `UPDATE .. SET emb1 = (SELECT emb2 ..)`. 
  - [ ] Emulation using `SET (a, b) = (SELECT x, y)`, see #10522 and #10523
- [ ] `INSERT .. VALUES ((SELECT emb))` doesn't work, if embeddable has more than one column. 
- [ ] `ORDER BY` issues
  - [ ] `ORDER BY .. NULLS FIRST / LAST` emulations
  - [ ] `SEEK`
- [ ] There needs to be a way to create `Field<? extends EmbeddableRecord>` that is not a `Val`, but a `RowField` (let's wait for use-cases)
- [ ] `Record::fromArray` flattens embeddables, even if there are embeddable fields in the record. There are probably other unmappers that also don't work.
- [ ] Aliasing produces numerous edge cases where a single column is aliased, but in generated SQL there are multiple columns.
  - [ ] Aliasing embeddables in `SELECT embeddable AS e`
  - [ ] Aliasing embeddables through derived column lists `FROM (SELECT embeddable FROM t) AS t (a, b, c)`
  - [ ] Apply this optimisation once aliasing has been settled: #10540
  - [x] Auto-aliasing when putting embeddables in `MULTISET`: https://github.com/jOOQ/jOOQ/issues/12237
- [ ] `Record.from()` and `Record.into()` don't work when fields are renamed, see https://github.com/jOOQ/jOOQ/issues/11178
- [x] https://github.com/jOOQ/jOOQ/issues/15873

### Runtime library (not integration tested yet)

- [ ] Overlapping embeddables
  - [ ] In `INSERT .. SELECT`
  - [ ] In `MERGE`
  - [ ] In `ALTER TABLE`
- [ ] `<replaceFields/>` feature:
  - [ ] Mixing embeddables that replace fields with embeddables that don't replace fields
    - [ ] Let them overlap in addition to them co-existing
  - [ ] `UpdatableRecord.key()` calls (see also code generation issue, below)
  - [ ] `Table.getPrimaryKey()` and similar methods
- [ ] Use embeddable types in expressions
  - [ ] Functions like `COALESCE()`, `NVL()`, etc.
  - [ ] JSON functions
  - [ ] XML functions
- [ ] Working with readonly types contained in embeddables: https://github.com/jOOQ/jOOQ/issues/9864
- [ ] Table projections containing embeddables (see https://github.com/jOOQ/jOOQ/issues/4727)

### Code generator (known issues)

- [x] Support referencing the same embeddable multiple times per table: https://github.com/jOOQ/jOOQ/issues/12608
- [ ] DAOs
  - [ ] Generate `fetchOneByXYZ()` methods in DAOs for `<embeddablePrimaryKeys/>` (is it possible?): https://github.com/jOOQ/jOOQ/issues/11188
  - [ ] Reference the `<embeddablePrimaryKeys/>` generated key record from generated DAOs as well
  - [x] Use the `referencingName` instead of the `name` for generated `fetch` methods: https://github.com/jOOQ/jOOQ/issues/13028
- [ ] Generate interfaces if requested (currently, the `IXYZ` interface is declared on the `EmbeddableRecord`, but not generated)
  - [ ] Immutable interfaces
  - [x] https://github.com/jOOQ/jOOQ/issues/14003
- [ ] Generate POJOs if requested
  - [ ] Immutable POJOs
- [ ] Overlapping embeddables should be able to nest, optionally. E.g. a UK on `(A, B, C)` and an FK on `(A, B)` should produce an embeddable type of the structural form `((A, B), C)`
  - [x] Related: https://github.com/jOOQ/jOOQ/issues/15828
- [ ] Generated overriden `UpdatableRecord.key()` method does not produce correct type
- [ ] Embeddable domains with POJOs: https://github.com/jOOQ/jOOQ/issues/11716
- [ ] Embeddable types with converters: https://github.com/jOOQ/jOOQ/issues/11833
- [ ] https://github.com/jOOQ/jOOQ/issues/13059
- [x] https://github.com/jOOQ/jOOQ/issues/15883

### Code generator (not integration tested yet)

- [ ] Embeddables containing actual `UDTRecord` types
- [ ] `UDTRecord` types containing embeddables (probably won't be supported)
- [ ] Embeddables containing array types
- [ ] Embeddable domains overlapping with embeddable PKs / UKs / FKs
- [ ] Embeddable domains overlapping with custom embeddables

**Comment by lukaseder** [comment]
To be continued: https://github.com/jOOQ/jOOQ/issues/15892
