### ISSUE TITLE
Add more Settings to enable / disable DefaultRecordMapper mapping algorithms

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11974]
Continuing with #10349 (jOOQ 3.15.0)

1. [ ] The target type `E` is an array, then we use  `ArrayMapper`
2. [ ] `E` is a `Stream`, then we map into an `Object[]` and stream that (#5508)
3. [ ] `E` is a type for which we have a `Converter` in `ConverterProvider`, and the source contains a single field, then we use `ValueTypeMapper` (#3212, #10071)
4. [ ] `E` is abstract, then we use `ProxyMapper` (#1470)
5. [ ] `E` is an `AbstractRecord`, then we use `RecordToRecordMapper`
6. [ ] `E` has a no-arg constructor, then we use `MutablePOJOMapper` (#1340, #10194)

**Comment by davidsonnabend** [comment]
It would be great to have a setting to disable the use of non-public default constructors for Kotlin data classes.

Using the following simple Kotlin data class:

```
data class Address(
    val street: String? = null,
    val city: String? = null,
    ...
)
```

the `DefaultRecordMapper` works as expected.
A `MutablePOJOMapper` will be created using `Constructor.setAccessible()` (#1340) but the addition check for mutability fails (#10194) and the mapping will be done using kotlin-reflect (#7324).

As soon as at least one property will be mutable, the class will be treated as mutable and only the mutable property will be mapped.

```
data class Address(
    var street: String? = null, // will be mapped correctly
    val city: String? = null,   // will always be null
    ...
)
```

Would be great to be able to configure the `DefaultRecordMapper` instead of implementing an own one. 

Or is there already an intended way to overcome the "issue" from above?

**Comment by lukaseder** [comment]
Thanks for your message @davidsonnabend. I'm not sure if this is worth addressing with settings (or at all). In any case, if you want this to be tracked, can you please create a new issue for it? You can just copy paste your comment's content.

**Comment by davidsonnabend** [comment]
Thank you for you instant reply @lukaseder . I was not sure if this issue was worth an issue, so I added a comment. :-) 

I created an issue (#15911) now.
