### ISSUE TITLE
Fix known issues of Settings.transformRownum

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11997]
jOOQ 3.14 introduced `Settings.transformRownum` with #9017. It works decently for simple cases, offering already quite some value, but still suffers from quite a few caveats as the transformation is far more complex than one would wish.

These are known issues that need to be addressed (some issues already fixed in 3.15: #10716):

**Bugs and limitations:**

- [ ] `ROWNUM` filtering in DML

**Tasks:**

We're not sure yet if we have bugs, as these scenarios are not covered by tests yet

- [ ] Test using `ROWNUM` with `OR` predicates
- [ ] Test using `ROWNUM` with `NOT` predicates
- [ ] Test using `ROWNUM <= [ expression ]` in predicates. Currently, only `Param` expressions are tested

**Improvements:**

- [ ] When filtering on projected `ROWNUM` values (e.g. to emulate `OFFSET`), jOOQ could apply an additional transformation step to recognise `ROW_NUMBER()` filtering as `OFFSET .. LIMIT`. This might be a useful transformation in general (e.g. to upgrade old SQL Server queries where `OFFSET` was not yet available).

**Comment by victornoel** [comment]
Hi @lukaseder, I'm using jOOQ with Postgres to parse SQL queries and when using a query such as:
```sql
SELECT * FROM (SELECT field, row_number() OVER (ORDER BY field) as rownum FROM T1) WHERE rownum = 1
```

With 3.15.4, I'm getting the following error when trying to parse it with `Parser.parseSelect`: `Feature only supported in pro edition: [274:76] ... rownum [*]= 1` (the line/row number are incorrect because I simplified the query :).

With 3.13.6 it's just working as expected.

I wanted to know if this issue will fix this or if I should open another one?

**Comment by lukaseder** [comment]
Oh interesting case, thanks @victornoel.

Please create a new one. That's clearly a bug. The workaround is to use any other alias than `ROWNUM` (e.g. `RN`)

**Comment by victornoel** [comment]
@lukaseder thank you, here it is https://github.com/jOOQ/jOOQ/issues/12950
