### ISSUE TITLE
Address known issues of Settings.transformTableListsToAnsiJoin

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11996]
jOOQ 3.14 introduced the `Settings.transformTableListsToAnsiJoin` flag (https://github.com/jOOQ/jOOQ/issues/7312). There are numerous known issues and limitations which need to be addressed, still. Some have been fixed in 3.15 (#10697):

### TODO

**Bugs / missing features**

- [ ] Tables aren't resolved when they're not consistently qualified (e.g. fully qualified in `FROM` clause, but unqualified in references)
  - [ ] This should work with heuristics if we're not looking up identifiers
  - [ ] And it should work precisely if we're looking up identifiers (in case of which this may not be a transformation bug)
- [ ] Join "cycles" are not maintained, e.g. `FROM t1, t2, t3 WHERE t1.a = t2.a AND t2.b = t3.b AND t3.c = t1.c`
- [ ] Try to look up unqualified `TableField` from `MetaProvider` (may need a new `Settings` flag to opt out for performance)
- [ ] Write some more advanced integration tests to find out if we get join precedence wrong somewhere
- [ ] Row value expression predicates, such as `(A, B) = ((X(+), Y(+)))`
- [ ] Other predicates `A IS DISTINCT FROM B`, etc. We'll list them here.
- [ ] `WHERE .. OR ..`: Check if we can apply some De Morgan's law transformations first
- [ ] `WHERE .. NOT ..`
- [ ] A mix of table lists and ANSI JOIN syntax
- [ ] `LATERAL` joins with table list syntax
- [ ] Any impact of using derived tables or table valued functions?
- [ ] `COL(+) IN (1, 2)`
- [ ] `LHS(+) = RHS(+)` (theoretical full outer join, which isn't supported by Oracle)

### Oracle's own limitations:

- https://www.salvis.com/blog/2015/12/07/outer-join-operator-restrictions-in-12-1-0-2/
