### ISSUE TITLE
Implicit JOIN improvements

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12037]
jOOQ 3.11 introduced implicit joins (#1502). jOOQ 3.15 improved on them (#7536). This issue tracks further improvements on the feature:

### Improvements

- [x] ~Flag to activate the feature (not a configuration flag. On the first call to the path API, we'll activate a static variable)~ (benchmarks haven't shown the overhead to be significant enough)
- [x] Usage in DML: #7508
- [x] Explicit path aliasing (https://github.com/jOOQ/jOOQ/issues/12210)
- [x] ~Inverse To-one joining~ (#8667, merged into #13639)
- [x] ~To-many joining~ (moved to https://github.com/jOOQ/jOOQ/issues/13639)

**Comment by lukaseder** [comment]
To be continued in future releases: https://github.com/jOOQ/jOOQ/issues/14614
