### ISSUE TITLE
Validate the soundness of our alias generation algorithm

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12068]
When users don't provide explicit aliases where an alias is needed (e.g. derived tables), or where they can't provide one (e.g. implicit join paths), we generate table aliases based on the hash code of the generated SQL string of a `QueryPart`. Pros and cons of this approach:

**Pros**

- Our generated SQL is stable, which benefits execution plan caching. 
- The alias is calculated eagerly and readily available when users dereference columns again from such tables, e.g. `table(select).field("field")` (an alternative would assign aliases from context within the query they're used in, e.g. by enumerating all generated aliases, but that would prevent dereferencing fields)

**Cons**

- The calculation is relatively slow (see https://github.com/jOOQ/jOOQ/issues/6175).
- There may be collisions

About that last bullet, there may be collisions for two distinct table expressions, that produce the same hash code. In the case of derived tables, this can be worked around easily by users, by providing explicit aliases. With implicit joins, this is harder.

### Task

This issue attempts to:

- [ ] Calculate some statistics of how probable such collisions really are (2B possible hash values compared to relatively few tables declared in a query)
- [ ] Discuss possible solutions, including
  - [ ] Better (?) hash algorithms, e.g. MD5 (not necessarily less collision prone, but producing longer values)
  - [ ] Other strategies of auto-aliasing objects

Since we'll generate a lot of new SQL this way, and thus effectively flush execution plan caches when users upgrade, this must not be implemented in a patch release.

**Comment by lukaseder** [comment]
This hasn't come up in client code in all these years. Seems like collisions are still very unlikely.
