### ISSUE TITLE
Built in SQL transformations

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12062]
This issue continues work of #9767

This issue lists all built-in SQL transformations that will be made available out of the box via the new query object model:

### jOOQ Professional and Enterprise Editions

- [ ] #668 Oracle `CONNECT BY` support (general case)
- [ ] #3173 Inline non-recursive CTEs to derived tables
- [ ] #3175 Transform nested CTE to top level CTE (existing transformation)
- [ ] #10166 Transform `LENGTH(literal)` to constant
- [ ] #10306 Transform implicit type conversions to explicit ones
- [ ] #10307 Transform asterisks (qualified or unqualified) to their respective explicit select lists
- [ ] #10308 Transform unqualified column, table, etc. references to qualified ones
- [ ] #11669 `GROUPING SETS` support
- [ ] #11825 Transform `ROW` projections
- [ ] Transform between different semi or anti join syntaxes
- [ ] Inline derived tables to outer queries (see special implementation #10353)

### All editions

- [ ] #8800 Transformation of ANSI join syntax to pre-ANSI join syntax (preliminary implementation shipped in 3.13, needs retrofitting)

### Flags managing transformations

- [ ] ...

If a flag is available only in the commercial distributions, its activation (including auto-activation by default, `WHEN_NEEDED`) should

- [ ] throw an exception pointing to a section in the manual discussing the transformation

Some flags have been published already in 3.14 as `Boolean`, when they should in fact be a 3-valued enum: `ALWAYS`, `WHEN_NEEDED`, `NEVER`, see https://github.com/jOOQ/jOOQ/issues/11802

This list will be enhanced as we identify more use cases
