### ISSUE TITLE
Add support for <JSON array constructor by query>

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12066]
Similar to the `MULTISET` value constructor by query (or just `MULTISET`: https://github.com/jOOQ/jOOQ/issues/3884), the standard SQL `<JSON array constructor by query>` would be very useful to support, to collect the contents of a subquery into a `JSON` document

### Tasks:

- [ ] Find out what native support is available
- [ ] There are 2 ways how to design this API:
  - [ ] We auto-collect subquery content into a `jsonObject()`
  - [ ] We require users to use `Select<Record1<JSON>>` subqueries explicitly

**Comment by lukaseder** [comment]
Oracle 23c now supports this:

```sql
select json_array(select 1)
```

Producing:

```
|JSON_ARRAY(SELECT1FROMDUAL)|
|---------------------------|
|[1]                        |
```

Or also:

```sql
select json [ select 1 from dual ] 
```

**Comment by lukaseder** [comment]
Some bugs in this area:

- https://forums.oracle.com/ords/apexds/post/json-convenience-syntax-requires-from-clause-in-subquery-6359
- https://forums.oracle.com/ords/apexds/post/cannot-project-boolean-expressions-in-json-functions-2200

**Comment by lukaseder** [comment]
Curiously, this returns `NULL` in PostgreSQL:

```sql
select json_array(select 1 where false);
```

When the SQL standard (and intuition) expects an empty array

**Comment by lukaseder** [comment]
In some dialects, the emulation won't produce stable ordering. We'll have to pull up the subquery `ORDER BY` to the `JSON_ARRAYAGG()` function, which is a commonly re-occurring theme. Perhaps there's a thorough fix.

**Comment by lukaseder** [comment]
Implemented in jOOQ 3.21.0
