### ISSUE TITLE
Support using generated PostgreSQL functions with row type parameters in SQL

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12069]
jOOQ 3.11 introduced support for PostgreSQL row type parameters to stored functions:
https://github.com/jOOQ/jOOQ/issues/7174

Currently, users can only use such functions in standalone routine calls. It would be nice if we offered an overload that allows for passing a table reference and produce a `Field<?>` expression for the function call to embed in SQL

### Tasks

- [ ] Add necessary runtime API support for such `Field<? extends TableRecord<?>>` usage (see also #4727)
- [ ] Support functions that accept row type parameters
- [ ] Support functions that return row type parameters

----
See also:
- https://stackoverflow.com/a/68149343/521799
- https://github.com/jOOQ/jOOQ/issues/4727
