### ISSUE TITLE
Add code generation flags to turn on/off the generation of record or POJO constructors that list all the fields

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12610]
Generated records and POJOs have a few constructors, including:

- An empty constructor
- A copy constructor
- A constructor listing all the values
- A constructor listing all the values but replacing embeddables
- A constructor listing all the writable values (since jOOQ 3.16, see https://github.com/jOOQ/jOOQ/issues/9864)

This can be excessive, and possibly even lead to conflicts in generated code. A new code generation flag that allows for turning on/off the generation of record an POJO constructors listing all the fields could be useful. The default is to keep them all on.

### Tasks:

Flags in `configuration/generator/generate`

- [ ] `<pojoConstructorAllFields/>` (default: `true`)
- [ ] `<pojoConstructorWritableFields/>` (default: `true`)
- [ ] `<recordConstructorAllFields/>` (default: `true`)
- [ ] `<recordConstructorWritableFields/>` (default: `true`)

### Caveats:

- Immutable POJOs require a constructor that lists all the fields, otherwise, it won't be possible to initialise the POJO. It's up to the user to avoid a code generation configuration that produces silly output.

**Comment by lukaseder** [comment]
This issue might not be solving any real problem. Won't fix
