### ISSUE TITLE
Add more startup tips to be logged with the jOOQ logo

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12721]
Continuing #11864

**jOOQ runtime features**

Backport to 3.16:

New in 3.17:

- [x] Using `Table` as `SelectField`: https://blog.jooq.org/projecting-type-safe-nested-tablerecords-with-jooq-3-17/
- [x] Using `Condition` as `Field<Boolean>`: https://github.com/jOOQ/jOOQ/issues/11969
  - [ ] Link to a blog post
- [x] `DSL.noField()`: https://github.com/jOOQ/jOOQ/issues/2333
- [x] Auto inlining bind values: https://github.com/jOOQ/jOOQ/issues/5970, https://www.jooq.org/doc/dev/manual/sql-building/dsl-context/custom-settings/settings-auto-inline-bind-values/
- [x] kotlin extension functions in `jooq-kotlin`: https://github.com/jOOQ/jOOQ/issues/13538
- [x] Audit columns: https://www.jooq.org/doc/dev/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-forced-types/codegen-database-forced-types-audit/
- [x] Client side computed columns: https://www.jooq.org/doc/dev/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-forced-types/codegen-database-forced-types-computed/
- [x] Don't do this: https://www.jooq.org/doc/latest/manual/reference/dont-do-this/

**jOOQ code generation features**

Backport to 3.16:

New in 3.17:

**Understanding SQL**

**SQL Performance tips** (see also: https://blog.jooq.org/sql)

**Implementation**

**General improvements**

Backport to 3.16:

New in 3.16:
