### ISSUE TITLE
Offer out of the box data type bindings that bind org.jooq.Geometry to JTS Geometry

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12738]
Continuing on https://github.com/jOOQ/jOOQ/issues/982 from jOOQ 3.16, it would be useful if we had out of the box data type bindings that bind `org.jooq.Geometry` to the JTS `Geometry` type, so users don't have to worry about the WKT or WKB serialisation formats.

### Tasks

- [ ] Create a `jooq-spatial-extensions` module that manages this extension and the dependency
- [ ] Add the converters
- [ ] Possibly add a mechanism to auto-discover such bindings in the code generator as a separate task. Would also be useful for the `HSTORE` binding from the `jooq-postgres-extensions` extension module

**Comment by lukaseder** [comment]
With dialects producing quite different serialisations when reading the data, this seems inevitable.
