### ISSUE TITLE
Add Settings.renderOptionalAssociativityParentheses

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12896]
jOOQ currently doesn't render parentheses to maintain the associativity of some operators, including:

- [x] `+`
- [x] `*`
- [x] `AND`
- [x] `OR`
- [x] ~`||`~ (already has an issue https://github.com/jOOQ/jOOQ/issues/11886)
- [x] ~`UNION`~ (extracted to https://github.com/jOOQ/jOOQ/issues/12899)
- [x] ~`INTERSECT`~ (extracted to https://github.com/jOOQ/jOOQ/issues/12899)
- [x] ~`JOIN`~ (extracted to https://github.com/jOOQ/jOOQ/issues/12900)

In rare cases, it could be useful to govern this behaviour using a new `Settings` flag, e.g. when we want to test the correct transformation of an expression tree `(a + b) + (c + d)` to `((a + b) + c) + d`. We can access the internal representation of the expression tree now, and extract the tree structure, but it would be nice if this was also possible in generated SQL.

**Comment by lukaseder** [comment]
`Concat` is not yet a binary expression, but contains an array of arguments, see https://github.com/jOOQ/jOOQ/issues/11886.
