### ISSUE TITLE
Add various additional DSL.noXXX() constructors for better dynamic SQL construction

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12969]
We have the `DSL.noCondition()` constructor, which produces a special type of `Condition` that generates no SQL string, unless strictly required syntactically. It can be used for dynamic SQL:

```java
ctx.select(T.VALUE)
   .from(T)
   .where(check ? noCondition() : T.ID.eq(1))
```

We don't have any other such query parts yet, though it would be very useful for at least:

- [ ] `noTable()` for optional joins: https://github.com/jOOQ/jOOQ/issues/9635
  - If it's the only table present, we wouldn't generate the `FROM` clause, defaulting to the `DUAL` behaviour
  - In a table list, we just skip all `noTable()` values
  - In a join expression, we just skip the join (and ignore the `ON`, `USING`, `PARTITION BY` clauses)
  - In DML, where tables are mandatory, we'll generate `/* no table */`, which should result in a syntax error on the server
- [ ] `noSelect()` for optional union subqueries: https://github.com/jOOQ/jOOQ/issues/12346
  - If it's the only select, it will result in an empty `Result` of the same rowtype as the `noSelect()` expression
  - If it's a union (or except / intersect) subquery, then the set operation is skipped
  - If it's an `IN`, `EXISTS`, `UNIQUE` or other kind of predicate, then there are two options:
    - Produce an empty query (probably better, and more consistent with `noCondition()`
    - Skip the predicate itself
- [x] `noField()` for optional column expressions: https://github.com/jOOQ/jOOQ/issues/2333
  - If it's in the `SELECT` clause or anywhere where we need a value (e.g. a function argument), we produce `NULL` of that column type
  - If it's in the `GROUP BY` clause, we skip the field. If it's the only field, we don't group
  - If it's in the `ORDER BY` clause, we skip the field. If it's the only field, we don't order
  - If it's in the `LIMIT` or `OFFSET` clause, we skip the clause.

**Comment by lukaseder** [comment]
`noField()` support has been added: https://github.com/jOOQ/jOOQ/issues/2333
