### ISSUE TITLE
java.lang.NoClassDefFoundError: org/postgresql/util/PGInterval when rendering SQL without the pgjdbc dependency

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13053]
In order to profit from vendor specific data type bindings, we've added some JDBC driver dependencies in a recent jOOQ release.

However, this shouldn't be necessary when merely generating SQL. It currently happens when generating the SQL for PostgreSQL intervals:

```
java.lang.NoClassDefFoundError: org/postgresql/util/PGInterval
	at org.jooq.util.postgres.PostgresUtils.toPGInterval(PostgresUtils.java:242)
	at org.jooq.impl.DefaultBinding$DefaultYearToMonthBinding.sqlInline0(DefaultBinding.java:5549)
	at org.jooq.impl.DefaultBinding$DefaultYearToMonthBinding.sqlInline0(DefaultBinding.java:1)
	at org.jooq.impl.DefaultBinding$AbstractBinding.sql(DefaultBinding.java:937)
	at org.jooq.impl.DefaultBinding$AbstractBinding.sqlCast(DefaultBinding.java:902)
	at org.jooq.impl.DefaultBinding$AbstractBinding.sqlCast(DefaultBinding.java:872)
	at org.jooq.impl.DefaultBinding$AbstractBinding.sql(DefaultBinding.java:925)
	at org.jooq.impl.Val.accept(Val.java:186)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:726)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:295)
	at org.jooq.impl.Expression$DateExpression.acceptIntervalExpression(Expression.java:657)
	at org.jooq.impl.Expression$DateExpression.accept(Expression.java:357)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:726)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:295)
	at org.jooq.impl.Expression.accept0(Expression.java:177)
	at org.jooq.impl.AbstractTransformable.accept(AbstractTransformable.java:70)
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:726)
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:295)
	at org.jooq.impl.DefaultDSLContext.render(DefaultDSLContext.java:709)
	at org.jooq.test.util.BaseTest.schemaMappingAssertions(BaseTest.java:659)
	at org.jooq.impl.AbstractParserTest.additionalAssertions(AbstractParserTest.java:512)
	at org.jooq.impl.AbstractParserTest.assertFieldEquals(AbstractParserTest.java:343)
	at org.jooq.impl.AbstractParserTest.assertFieldEqualsAll(AbstractParserTest.java:351)
	at org.jooq.impl.ParserDateFunctionTest.testDateSubMySQL(ParserDateFunctionTest.java:631)
```

Removing this dependency requirement also improves jOOQ usage for all customers using jOOQ only as a SQL translator.

### Tasks

- [x] Implement the above logic in jOOQ, itself
  - [x] By shading the pgjdbc `PGInterval` and `PGobject` classes
  - [ ] Document this dependency on https://www.jooq.org/legal/licensing
- [x] Check if we still need the pgjdbc / redshift / other JDBC driver dependencies, afterwards
- [ ] Check if our unit tests still need those dependencies, afterwards

**Comment by lukaseder** [comment]
The above stack trace is caused by a new test introduced for https://github.com/jOOQ/jOOQ/issues/13051

**Comment by lukaseder** [comment]
The simplest approach here would be to shade the `PGInterval` class from pgjdbc. Also, we can no longer pass the `PGInterval` type to `PreparedStatement.setObject()`, but that's unnecessary anyway, because the driver effectively binds the string representation.

**Comment by lukaseder** [comment]
This requires some incompatible changes in the internal `PostgresUtils` class, namely the `toDayToSecond()` and similar methods no longer return the original `PGInterval` type.

**Comment by lukaseder** [comment]
So, we can effectively remove the pgjdbc and redshift jdbc driver dependency again, which had been added in #11960 / jOOQ 3.15.0 and related changes.

The stance on JDBC driver dependencies going forward is this:

- A dependency is acceptable when it is needed to implement bind variable support and other query execution support
- It is not acceptable as a means to generate SQL (which can be done also outside of execution, e.g. when parsing / translating)
