### ISSUE TITLE
Add Configuration.unmodifiable() to wrap a Configuration instance in a new UnmodifiableConfiguration

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13079]
The ubiquitous `Configuration` type is mutable by default (via its various `set()` methods, as well as its component types such as `Settings` are mutable).

It would be occasionally useful to be able to wrap a specific instance in a new `UnmodifiableConfiguration` type, which would throw exceptions on all mutating method calls. This would be useful for our internal `Tools.CONFIG` and `Tools.CTX` default instances, which are shared for performance reasons, but probably leak into user code occasionally, risking accidental (or hackish) concurrent modification by the user, including our own internals.

### Tasks

- [ ] Create an internal wrapper `UnmodifiableConfiguration` type
- [ ] Let all the mutating methods throw

Dependencies:

- [ ] Turn `Settings` into something that is immutable capable
- [ ] Stop exposing array types from `Configuration`. Alternatively, we could wait for frozen arrays https://openjdk.java.net/jeps/8261007

There's probably no backwards compatible way to do this task.

**Comment by lukaseder** [comment]
Much like an unmodifiable `Settings` (see https://github.com/jOOQ/jOOQ/issues/14959), it will not be possible to make the default `Configuration` unmodifiable without breaking all sorts of client code, e.g.:

```java
DSLContext ctx = DSL.using(...);
ctx.configuration().set(...);
```
