### ISSUE TITLE
Add a SQLDialect.SQLITE_3_38 dialect

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13195]
There are a few noteworthy improvements since our last SQLite dialect version 3.30:
https://www.sqlite.org/news.html

These include:

- [x] 3.33 introduces an `UPDATE FROM` syntax, like PostgreSQL: https://www.sqlite.org/lang_update.html. https://github.com/jOOQ/jOOQ/issues/13271
- [x] 3.35 introduces
  - [x] `ALTER TABLE DROP COLUMN` (and other DDL?)
  - [x] built-in math functions https://github.com/jOOQ/jOOQ/issues/13277
  - [x] `MATERIALIZED` hint on CTEs. https://github.com/jOOQ/jOOQ/issues/13275
  - [x] Support for optional `ON CONFLICT` targets: https://github.com/jOOQ/jOOQ/issues/13273

Out of scope for now (3.37 isn't yet available as a JDBC driver):

- 3.35 "generalised UPSERT" (i.e. multiple `ON CONFLICT` clauses): https://www.sqlite.org/lang_upsert.html. https://github.com/jOOQ/jOOQ/issues/13274
- 3.37 introduces `STRICT TABLE`: https://www.sqlite.org/stricttables.html

**Comment by lukaseder** [comment]
The xerial driver only supports 3.36 so far: https://github.com/xerial/sqlite-jdbc/issues/694. That should suffice for most features I've discovered in the above list. The dialect version is still 3.38, and we might support the `STRICT TABLE` feature later, in a separate issue.
