### ISSUE TITLE
Add Table::as and TableLike::asTable overloads accepting Collection<? extends X> for derived column lists

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13335]
The usual `T...|Collection<? extends T>` overloads aren't being put in place for `Table::as` and `TableLike::asTable` where derived column lists can be supplied. Only overloads accepting varargs are available, e.g.:

```java
// Possible
select(val(1), val(2)).asTable("t", "a", "b)

// Not possible
select(val(1), val(2)).asTable("t", List.of("a", "b))
```

The various overloads do not conflict with one another after erasure, because the collection contents must always match the table type, e.g.:

- `as(String, Collection<? extends String>)`
- `as(Name, Collection<? extends Name>)`
- `as(Table<?>, Collection<? extends Field<?>>)`

### Tasks

- [x] Add API methods
- [x] ~Adapt code generation for covariant overriding~. Not applicable for derived column lists.
- [x] Adapt internals to use the new method, where appropriate
