### ISSUE TITLE
Support multiple ROW assignment in UPDATE .. SET

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13330]
The current DSL API allows for a single `ROW` assignment in `UPDATE .. SET ROW = ..`, but there's no reason to limit ourselves to that. The `UpdateQuery` API already allows multiple such rows, even if the implementation didn't store them all.

Now that this refactoring has been implemented: https://github.com/jOOQ/jOOQ/issues/13325, we can offer multiple `ROW` assignment expressions in `UPDATE .. SET`

### Tasks

- [ ] Update DSL API
- [ ] Update parser
- [ ] Fix implementation where appropriate
  - [ ] Native support
  - [ ] Emulation using flattening of `ROW = ROW`
  - [ ] Emulation using `UPDATE .. FROM` in case of `ROW = (SELECT ..)`
- [ ] Add tests

Additional tasks:

- [ ] Support this also in `INSERT .. ON CONFLICT DO UPDATE`, see https://github.com/jOOQ/jOOQ/issues/6769
- [ ] Support this also in `MERGE .. WHEN MATCHED THEN UPDATE`

**Comment by lukaseder** [comment]
There might already be an issue for this change, but I couldn't find it.
