### ISSUE TITLE
Support aliasing PASSING expressions in XMLQUERY

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13394]
At least in Db2, perhaps in other dialects, too, it's possible to write this:

```sql
-- Db2
select xmlquery('$x' passing 1 as "x")
from sysibm.dual;

-- Oracle:
select xmlquery('$x' passing 1 as "x" returning content)
from dual;
```

We should support this idiom too in jOOQ

### Tasks

- [ ] Add tests
- [ ] Add implementations
  - [ ] Native support as above
  - [ ] PostgreSQL emulation (using `XPATH()`)
- [ ] Parser support
- [ ] Adapt Db2's `JSONEntryImpl::jsonCast` implementation (from https://github.com/jOOQ/jOOQ/issues/12134)
