### ISSUE TITLE
Add <hidden/>, a <forcedType/> flag that removes columns from projections by default

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13411]
Under some circumstances, it could be useful to be able to hide columns from the user of a table, but not from the table itself. For example, when using client side computed columns (https://github.com/jOOQ/jOOQ/issues/9879), the computation could be based on a column that is otherwise hidden.

The effects are:

- [x] The column definition is `private` (or package private, or `protected`, could be configurable). This should be a separate configuration, though! https://github.com/jOOQ/jOOQ/issues/13432
- [x] Runtime effects
  - [x] The column is not included in `Table.fieldsRow()` and related methods
  - [x] The column is not included in `*` expansions
    - [x] In `SELECT`
    - [x] In `RETURNING`
  - [x] The column is not included in `INSERT INTO t VALUES (..)` (insert without explicit column list)
  - [x] The column is not included in `TableAsField` projections
  - [x] The column is not included in `MULTISET` projections
- [x] The column is not included in generated `TableRecord`, POJO, interface types. We currently cannot make this configurable, because all the record field access on generated getters is index based, and that would just shift all the indexes, producing wrong results.

But:

- The column is still generated, so it can be used
  - In client side computed column expressions: https://github.com/jOOQ/jOOQ/issues/9879
  - Using reflection, or whatever other tools that circumvent visibility, to project and write to the column

That way, it works similar to server side hidden columns.

### Tasks

- [x] Add code generation configuration
  - [x] Configure it via `forcedTypes`
    - [x] Do this also for `readonly` columns, perhaps? See: https://github.com/jOOQ/jOOQ/issues/16118
  - [x] Generate the `DataType::hidden` flag
  - [x] Remove it from generated `Record`, POJO, and interfaces ~(make this configurable)~ (it would be too complicated if we enabled this)
  - [x] Add a flag that allows for treating "DB hidden" fields as "jOOQ hidden" with these states: See https://github.com/jOOQ/jOOQ/issues/16135
  - [x] Support the flag in `XMLGenerator` and `XMLDatabase` as well as `InformationSchema`
    - [x] Add it to the `InformationSchema`
    - [x] Generate it in `XMLGenerator`
    - [x] Read it in `XMLDatabase`
  - [x] There might be other, automatically hidden columns, perhaps?
- [x] Add `DataType::hidden` API
- [x] Enforce `*` expansion for explicit asterisks, if columns are known
  - [x] To know if a table has hidden fields, we need an additional method, such as `Fields.includingHidden()` or something like that.
  - [x] In `SELECT`
  - [x] In `RETURNING`
- [x] Parser support
- [x] `Meta::ddl` support
  - [x] While `Table::fieldsRow` doesn't contain the `Field`, we must still export it in generated DDL! See: https://github.com/jOOQ/jOOQ/issues/16136
- [x] Add some `Settings` to govern runtime behaviour
  - [x] ~`Settings.projectHiddenFields`~ (this seems very complicated)

### Feature interactions and edge cases

- [x] What if a hidden column is part of an embeddable type?
- [x] What if a hidden column is part of a constraint?
  - [x] Can the primary key be hidden? - Yes, the constraint disappears
  - [x] Can a foreign key be hidden? - Yes, the constraint disappears
- [x] Some meta lookups must continue to work, including
  - [x] Parser meta lookups
- [x] Inline derived tables

### Related features

- Comments / deprecation:
  - https://github.com/jOOQ/jOOQ/issues/9728
  - https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-comments/
- Multi schema version support:
  - https://github.com/jOOQ/jOOQ/issues/9626

**Comment by lukaseder** [comment]
This feature here is less immediately useful for client side computed columns (#9879) compared to the one where we simply change the Java visibility of generated columns (https://github.com/jOOQ/jOOQ/issues/13432).

So, I'm postponing this for now, to prevent too many open projects in jOOQ 3.17, adding delays.

**Comment by lukaseder** [comment]
Duplicate of this feature:

- https://github.com/jOOQ/jOOQ/issues/14070

**Comment by lukaseder** [comment]
I have second thoughts about the term `hidden` given that some RDBMS that support this natively call the flag `invisible`:

- H2
- MySQL
- Oracle

**Comment by lukaseder** [comment]
On the other hand, these have a concept of `HIDDEN` columns:

- CockroachDB
- Db2
- HANA
- Oracle (both terms exist)
- SQLite

Perhaps, I'll just leave it the way it is.
- SQL Server
-
