### ISSUE TITLE
Add a Settings.emulateComputedColumns

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13418]
jOOQ 3.17 will ship with implementations for client side computed columns, see https://github.com/jOOQ/jOOQ/issues/9879, meaning jOOQ generates SQL expressions on the client, which are substituted for columns whenever data is:

- read (for `VIRTUAL` columns)
- written (for `STORED` columns)

Many RDBMS already support this feature natively, and starting with jOOQ 3.16, we generate the necessary meta data in our code generator: https://github.com/jOOQ/jOOQ/issues/6492.

It would now be interesting if we could emulate the generated computed column expression in the form of a client side computed column. Use-cases:

- The code is generated from a schema that has actual server side computed columns, but the production schema doesn't compute those columns
- Multiple RDBMS have to be supported. While the source dialect for generated code supports server side computed columns, not all other dialects do, so jOOQ can emulate the behaviour
- When migrating off a dialect that supports computed columns to a dialect that doesn't, users may want to maintain the functionality, and move it into jOOQ

### Tasks

- [x] Add a `Settings`
- [x] Apply the setting
  - [x] in DDL (the expression must not be generated, both `VIRTUAL` and `STORED` translate to `STORED`)
  - [x] in DML (just switch `DataType::generationLocation` from `SERVER` to `CLIENT`)

**Comment by lukaseder** [comment]
This feature would greatly profit from generated computed column expressions to be parsed either at runtime or at code generation time: https://github.com/jOOQ/jOOQ/issues/7850

For simple expressions, we can still work with the currently generated string version.
