### ISSUE TITLE
Add <columns/> to <syntheticObjects/> to generate synthetic columns

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13434]
In order to be able to generate `VIRTUAL` client side computed columns (https://github.com/jOOQ/jOOQ/issues/9879), we must be able to add synthetic columns to the code generation output, i.e. column definitions that are not available otherwise in generated code.

The specification will be:

```xml
<configuration xmlns="http://www.jooq.org/xsd/jooq-codegen-3.16.5.xsd">
  <generator>
    <database>
      <syntheticObjects>
        <columns>
          <column>

            <!-- Optional regular expression matching all tables that have this column. -->
            <tables>SCHEMA\.TABLE</tables>

            <!-- The column specification -->
            <name>COLUMN</name>
            <type>VARCHAR(10)</type>

            <!-- Possibly also some configuration options from forcedType, for convenience -->
          </column>
        </columns>
      </syntheticObjects>
    </database>
  </generator>
</configuration>
```

When the synthetic column is not also matched as a client side computed column, then jOOQ will just use it like any ordinary column. The use-case would then be that a column isn't being reported by the schema / dictionary views (e.g. it's hidden), but the user *knows* it's there.

### Tasks

- [x] Add code generation configuration for `<tables>`, `<name>`, `<type>` (mandatory config)
- [x] Add code generation configuration for extended attributes
  - [x] Comment
- [x] Implement code generation

Other, more sophisticated flags may be added in the future: https://github.com/jOOQ/jOOQ/issues/13436
