### ISSUE TITLE
Add <visibilityModifier/> code generation option to <forcedType/>

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13432]
jOOQ 3.15 has introduced the `<visibilityModifier/>` to define what visibility most classes are generated with, as well as a few methods that are not inherited:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-generate/codegen-generate-visibility-modifier/

There exist use-cases where a more specific visibility could be useful for columns, in order to hide them from client code, and make them accessible only to generated code, including:

- Custom code sections
- Client side computed columns: https://github.com/jOOQ/jOOQ/issues/9879
- Client side hidden columns: https://github.com/jOOQ/jOOQ/issues/13411

A new `<visibilityModifier/>` flag inside of `<forcedType/>` with the same values as the `<visibilityModifier/>` will be added, and a new `PRIVATE` visibility will be added, too.

In case both modifiers are provided, the local one on the column wins.

An example:

```xml
<forcedType>
  <visibilityModifier>PRIVATE</visibilityModifier>
  <includeExpression>AUTHOR.CREATED_AT</includeExpression>
</forcedType>
```

### Tasks

- [x] Add code generation configuration
- [x] Apply visibility to `TableField` declaration
- [x] ~Apply visibility to `Record` and POJO getters, setters, and constructors (?)~
  - The fields aren't removed by this visibility. Perhaps, #13411's hidden column feature has an influence on removing the fields?
  - Might be done separately: https://github.com/jOOQ/jOOQ/issues/13433
