### ISSUE TITLE
Address known limitations of MULTISET support

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13589]
jOOQ 3.15 introduced support for nested collection emulations via JSON/XML: #3884

Many issues were addressed in 3.16 and 3.17:

- 3.16: #12021
- 3.17: #12734

This issue addresses remaining known limitations of the 3.16 implementation, including:

### Limitations, missing features

- [ ] `ORDER BY` clauses in `MULTISET` may not work as expected when columns are aliased, see https://github.com/jOOQ/jOOQ/issues/11473
- [ ] `ORDER BY` clause emulation is unstable in some dialects, e.g. Oracle, see #13155
- [ ] Emulate nested collections using native `ARRAY` support, where available. These should work:
  - [ ] BigQuery
  - [ ] CockroachDB
  - [ ] H2
  - [ ] PostgreSQL
  - [ ] Redshift
  - [ ] Possibly others? A good opportunity to improve general array support for other dialects
- [ ] Emulate nested collections using `NATIVE` support, where available
  - [ ] Oracle would require generating auxiliary `TABLE` and `OBJECT` types
- [ ] Offer an explicit `JSONFormat.RecordFormat` choice:
  - [ ] `ARRAY` (default because it uses less bandwidth and better handles ambiguous column names)
    - [ ] However, this mode doesn't work on Db2: https://stackoverflow.com/q/68228063/521799
  - [ ] `OBJECT` (our parser should be adapted to support multiple identical keys!)
- [ ] Offer an explicit `XMLFormat.RecordFormat` choice:
  - [ ] `VALUE_ELEMENTS` (default because it uses less bandwidth)
  - [ ] `VALUE_ELEMENTS_WITH_FIELD_ATTRIBUTE`
  - [ ] `COLUMN_NAME_ELEMENTS`
- [ ] Add support for `SET` (removing duplicates)
- [ ] Support for correlated `MULTISET` subqueries where derived tables can't be correlated: https://github.com/jOOQ/jOOQ/issues/12045
- [ ] The behaviour of a `MULTISET` with duplicate column names is currently undefined
  - [ ] We also don't have any unit / integration tests that validate duplicate column names in `fetchFromJSON()`, and `fetchFromXML()`. It should be possible in both, but the former probably "swallows" one of the duplicates because our parser is using `java.util.Map`
- [ ] We currently don't test what happens when XML/JSON content is nested in MULTISET, i.e.
  - [ ] XML content in a MULTISET/XML emulation
  - [ ] XML content in a MULTISET/JSON emulation
  - [ ] JSON content in a MULTISET/XML emulation
- [ ] `MULTISET` comparisons currently cast to `VARCHAR`, which can run into the 4000 byte limitation e.g. in Oracle, in case of which we should compare with these instead:
  - [ ] `XMLDIFF`
  - [ ] `DBMS_LOB.COMPARE`
- [ ] Mocking doesn't work yet: https://github.com/jOOQ/jOOQ/issues/12308 (also nested records?)

### Internal improvements

- [ ] The JSON conversion is currently done in `MultisetDataType`. It should be moved to a different level, e.g. `ConverterProvider`
- [ ] `DSLContext.fetchFromJSON()` et al. should be able to parse nested collections also without explicit `MultsetDataType` availability (see also #12012)
- [ ] Can `ConverterProvider` convert between JSON/XML and `Result`?
