### ISSUE TITLE
Add a SQLDialect.SQLSERVER2022

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13656]
SQL Server 2022 has a few improvements on the roadmap:
https://docs.microsoft.com/en-us/sql/sql-server/what-s-new-in-sql-server-2022?view=sql-server-ver16#language

These include:

- [x] `GENERATE_SERIES`: https://github.com/jOOQ/jOOQ/issues/14268
- [x] `IGNORE NULLS` and `RESPECT NULLS` on `FIRST_VALUE` and `LAST_VALUE`:  https://github.com/jOOQ/jOOQ/issues/14272
- [x] `WINDOW` clause: https://github.com/jOOQ/jOOQ/issues/14270
- [x] `GREATEST`: https://github.com/jOOQ/jOOQ/issues/14269
- [x] `LEAST`: https://github.com/jOOQ/jOOQ/issues/14269
- [x] `STRING_SPLIT` (with ordinals): https://github.com/jOOQ/jOOQ/issues/14271
- [x] `DISTINCT` predicate: https://github.com/jOOQ/jOOQ/issues/14578
- [x] `LEFT_SHIFT` and `RIGHT_SHIFT`: https://github.com/jOOQ/jOOQ/issues/14579
- [x] `BIT_COUNT`: https://github.com/jOOQ/jOOQ/issues/14580
- [x] `GET_BIT` and `SET_BIT`: https://github.com/jOOQ/jOOQ/issues/14581

JSON support has been published, but I'm not convinced it's ready yet

- `ISJSON`: https://docs.microsoft.com/en-us/sql/t-sql/functions/isjson-transact-sql?view=sql-server-ver16
- `JSON_PATH_EXISTS`: https://docs.microsoft.com/en-us/sql/t-sql/functions/json-path-exists-transact-sql?view=sql-server-ver16
- `JSON_ARRAY`: https://github.com/jOOQ/jOOQ/issues/13729
- `JSON_OBJECT`: https://github.com/jOOQ/jOOQ/issues/13729

All of the above have been tracked under https://github.com/jOOQ/jOOQ/issues/13729, separately.

Other stuff that is of interest:

- `DATE_BUCKET`: https://github.com/jOOQ/jOOQ/issues/14273

**Comment by lukaseder** [comment]
The release has been announced:
https://www.microsoft.com/en-us/sql-server/sql-server-2022

I'll try this again, now that the bugs observed should have been fixed?

**Comment by lukaseder** [comment]
It seems some additional things have been added in SQL Server 2022 since I last checked. Will update the issue and implement things right away:
https://learn.microsoft.com/en-us/sql/sql-server/what-s-new-in-sql-server-2022?view=sql-server-ver16#language
