### ISSUE TITLE
Continue work on Meta.migrateTo(Meta):Queries

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13654]
jOOQ 3.13 added support for a schema diff tool: https://github.com/jOOQ/jOOQ/issues/9425

There are still more things that could be diffed, including:

### Things that can be detected automatically:

- [ ] Catalogs
  - [ ] Catalog additions
  - [ ] Catalog removals
- [ ] Tables
  - [ ] Column data type changes
    - [ ] Identities
    - [ ] Collations
    - [ ] Character sets
  - [ ] Column reorderings (only if `respectColumnOrder` is set)
- [ ] Types
  - [ ] Enum types (`Meta` needs additional API to find these types: https://github.com/jOOQ/jOOQ/issues/9509)
    - [ ] Enum value additions: https://www.postgresql.org/docs/current/sql-altertype.html
    - [ ] Enum value renaming: https://www.postgresql.org/docs/current/sql-altertype.html
  - [ ] UDTs (?)

### Things that can be detected using some heuristics (based on likeliness):

- [ ] Renaming
  - [ ] Catalog renames
  - [ ] Schema renames
  - [ ] Table renames
  - [ ] Column renames
  - [ ] View renames
  - [ ] Sequence renames
- [ ] Moving
  - [ ] Moving an entire schema between catalogs
  - [ ] Moving an entire table between schemas

### `MigrationConfiguration`

Just like the `DDLExportConfiguration`, we should have a `MigrationConfiguration` that governs the style of produced queries. Some examples:

- [ ] `alterTableDropCascade`: To use the `CASCADE` syntax when dropping columns or constraints (default: `false`)
- [ ] `dropTypeCascade`: To use the `CASCADE` syntax when dropping types (default: `false`)
- [ ] `respectColumnOrder`: Whether column order is relevant (default: `false`)
