### ISSUE TITLE
Apply an auto-converter to <forcedType> in the absence of an explicit converter, if possible

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13791]
Currently, users cannot omit `<converter/>` or `<binding/>` in a `<forcedType/>`, when they provide a `<userType/>`. But in many cases, we do support auto-conversion between the `T` type and some user types, e.g. between:

- `String` and `Integer`
- `Boolean` and `Integer`
- etc.

In case the `<userType/>` is supported by the `DefaultConverterProvider`, we could add an auto-conversion capability to a forced type like this:

```xml
<forcedType>
    <userType>java.lang.Boolean</userType>
    <inputExpression>TABLE\.COLUMN</inputExpression>
</forcedType>
```

### Tasks

- [x] Implement this auto converter
  - [x] Allow for explicitly specifying `<autoConverter/>`, similar to `<enumConverter/>` and others
  - [x] Allow for omitting `<autoConverter/>`
  - [x] Map the converter to an actual `org.jooq.impl.AutoConverter` class, which can also be specified explicitly
- [x] Update code generation
- [x] ~Continue rejecting `<forcedType/>` configurations in case the `<userType/>` isn't supported~ (in fact, no. Since the `ConverterProvider` SPI is invoked, we can convert arbitrary types between each other, this way!)

### Feature interactions

- [x] ~This feature may or may not interact with the data type rewrite feature, where the type is changed transparently for jOOQ~ (we'll investigate this later)

**Comment by lukaseder** [comment]
I mean, thanks to `ContextConverter` (https://github.com/jOOQ/jOOQ/issues/13961), this also works for user implemented `ConverterProvider` implementations!
