### ISSUE TITLE
Add support for common RANGE functions in jooq-postgres-extensions

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13828]
We should probably add support for all the `RANGE` functions available here:
https://www.postgresql.org/docs/current/functions-range.html

E.g. `UPPER(anyrange)` would be quite useful. Since all of these types are part of this extensions module, we'll need a new `DSL` class for the function specifications.

### Tasks:

- [ ] Add a new `DSL` class
- [ ] Think about how this maps to the `QOM` type (new `QOM` type, too?)
- [ ] Implement the various range functions, which will be listed here
