### ISSUE TITLE
Simplify SQL Server's RETURNING emulation in the absence of triggers

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13912]
Our current `RETURNING` emulation for SQL Server is quite laborious, e.g.:

```sql
-- Declare an in-memory table for the results
DECLARE @result TABLE (
  id INT,
  last_update DATETIME2
);

-- Insert the data and return the results into the in-memory table
INSERT INTO actor (first_name, last_name)
OUTPUT inserted.id, inserted.last_update
INTO @result
VALUES ('John', 'Doe');

-- Merge trigger generated values into the previous results
MERGE INTO @result r
USING (
  SELECT actor.id, actor.last_update AS x
  FROM actor
) s
ON r.id = s.id
WHEN MATCHED THEN UPDATE SET last_update = s.x;

-- Return the results to the client
SELECT id, last_update
FROM @result;
```

Most of this is necessary only, because SQL Server can't return trigger generated values from `OUTPUT` (which is really weird!). If we *know* a table doesn't have any triggers, then we could avoid most of this, and just generate this instead:

```sql
INSERT INTO actor (first_name, last_name)
OUTPUT inserted.id, inserted.last_update
VALUES ('John', 'Doe');
```

### Tasks

- [x] Generate code for triggers: https://github.com/jOOQ/jOOQ/issues/11248
- [x] Implement the optimisation that avoids the extra statements 
  - [x] if we *know* there are no triggers on the table
  - [x] if we *know* there are no triggers that fire for any columns used in the statement
  - [x] if we *know* there are no triggers that fire for the statement type (`ON DELETE`, `ON UPDATE`, `ON INSERT`)
  - [x] Including the usual runtime settings that turn off the feature

**Comment by lukaseder** [comment]
This simplification would prevent a few edge case bugs like parts of the problems described here: https://github.com/jOOQ/jOOQ/issues/14477

**Comment by lukaseder** [comment]
As discovered here: https://github.com/jOOQ/jOOQ/issues/14479#issuecomment-1378540740, this optimisation can *only* be implemented in the absence of triggers. Otherwise, an error is raised:

> The target table 'test.dbo.t_triggers' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.

**Comment by lukaseder** [comment]
This also applies to SQLite: https://github.com/jOOQ/jOOQ/issues/15316
