### ISSUE TITLE
Add a ConnectionPoolDataSourceConnectionProvider

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13920]
We're going to get Springified. There's a `javax.sql.ConnectionPoolDataSource`, which is a bit less popular than the `DataSource` API. A lot of connection pools seem to implement the latter, but obviously, there are also some that implement the former (and only the former).

Those connection pools can't be used with jOOQ API directly. A custom `ConnectionProvider` has to be implemented and supplied to the jOOQ `Configuration`. But as the `ConnectionPoolDataSource` type is in JDK's `java.sql` module, why not support it out of the box as well.

### Tasks

- [ ] Add an `org.jooq.impl.ConnectionPoolDataSourceConnectionProvider`
- [ ] Add convenience API overloads to `Configuration` and `DefaultConfiguration`
- [ ] Add convenience API overloads on `DSL.using()`

**Comment by lukaseder** [comment]
Reviewing this a bit further, I am not convinced we should rush this implementation:

1. In many years of doing jOOQ, this is the first time this came up. Hence, it's not a popular thing at all
2. Third party connection pools that are `javax.sql.DataSource` based are much more popular and better established. It's unlikely users really want to rely on JDBC drivers to pool their connections
3. Looking at implementations, I'm not convinced that they're sound. The OSS drivers I've checked simply wrap `java.sql.Connection` in a `PooledConnection` without implementing any logic. Hence, implementations tend to just offer adapters.
4. I'm not even sure how jOOQ can correctly implement any connection pool lifecycle. The `PooledConnection::close` method is supposed to close the underlying *physical* connection. But how can I tell the pool that I'm simply returning it? It doesn't seem clear to me.

As such, I want to postpone offering this. If users know what lifecycle management they can expect, then it should be easy to implement a custom `ConnectionProvider`.

I'll leave this issue open to gather feedback from other users. But it's definitely a low priority.
