### ISSUE TITLE
Add support for JSON / JSONB concatenation

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13950]
In PostgreSQL and possibly in other dialects, this is possible:

```sql
select '[1]'::jsonb || '[2,3]'::jsonb
```

jOOQ should be able to produce this syntax from a new `DSL.jsonConcat()` or `DSL.jsonbConcat()` function. `DSL.concat()` currently casts everything to `varchar`, which isn't what users want:

```sql
select (cast(cast('[1]' as jsonb) as varchar) || cast(cast('[2,3]' as jsonb) as varchar))
```

While it would be possible to change `DSL.concat()` itself, the change would be backwards incompatible for some usages, so perhaps, it's better to introduce a new function that clearly distinguishes itself.

### Tasks

- [ ] Add the new function
- [ ] Add emulations where possible (to be listed, e.g. Oracle has `JSON_TRANSFORM`: https://oracle-base.com/articles/21c/json_transform-21c)
- [ ] Add parser support

**Comment by dhoepelman** [comment]
Workaround provided by lukaseder [in this SA post](https://stackoverflow.com/a/76445346/572635)

```java
Field<JSONB> jsonbConcat(Field<JSONB> f1, Field<JSONB> f2) {
    DSL.field("({0} || {1})", f1.getDataType(), f1, f2);
}
```
