### ISSUE TITLE
Add support for standard SQL array maximum cardinality

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13972]
The SQL standard and possibly a few dialects (e.g. H2, see https://github.com/jOOQ/jOOQ/issues/252#issuecomment-1241663163) support a maximum cardinality on arrays. We're already parsing this in the parser, but ignore the value for now as `DataType` cannot represent this.

### Tasks

- [ ] Support the cardinality in the runtime model (`DataType`)
- [ ] Support the feature in casts and DDL
- [ ] Support the feature in the code generator
