### ISSUE TITLE
Add support for MySQL's JSON_KEYS()

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14046]
MySQL has a `JSON_KEYS()` function with 2 overloads: `JSON_KEYS(json_doc[, path])`.

While the one taking a `path` argument is a bit esoteric (allowing to access nested keys, see [documentation](https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#function_json-keys)), the first one is certainly useful and can probably be emulated in a variety of dialects.

The function was used internally already, in the emulation of MySQL `JSON_OBJECT()`'s `ABSENT ON NULL` clause: https://github.com/jOOQ/jOOQ/issues/13249

### Emulations:

- [x] MariaDB: Native support https://mariadb.com/kb/en/json_keys/
- [x] MySQL: Native support https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#function_json-keys
- [x] PostgreSQL: Use `json_object_keys`, see below
- [x] Oracle: Using PL/SQL `json_object_t`, see below
- [x] SQLite: Using `JSON_EACH`, see below

Details:

**PostgreSQL**

```sql
select 
  o,
  (select coalesce(json_agg(j), json_build_array()) from json_object_keys(o) as j(j))
from (values ('{}'::json), ('{"a":1}'::json), ('{"a":1,"b":2}'::json)) as t(o)
```

**Oracle**

```sql
with
  function json_keys(j varchar2) return varchar2 as
    jo json_object_t;
    k json_key_list;
    r clob;
  begin
    jo := json_object_t(j);
    k := jo.get_keys();
    select coalesce(json_arrayagg(column_value), json_array())
    into r
    from table (k);
    return r;
  end;
select o, json_keys(o)
from (
  select '{}' as o from dual union all
  select '{"a":1}' from dual union all
  select '{"a":1,"b":2}' from dual
) t;
```

**SQLite**

```sql
select 
  o, 
  (
    select json_group_array(key)
    from json_each(o) as t
  )
from (
  select '{}' as o union all
  select '{"a":1}' union all
  select '{"a":1,"b":2}'
) t;
```

**SQLServer**

```sql
-- This is assuming an existing JSON_ARRAYAGG() emulation. Quoting of [key] is still a TODO
select json_query('[' + string_agg('"' + [key] + '"', ',') + ']', '$')
from openjson((
  select *
  from (values ('a', 1)) as t (k, v)
  for json auto, without_array_wrapper
));
```

### Tasks

- [x] Add API
- [x] Add `QOM` type
- [x] Add parser support

----
See also:
- https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#function_json-keys

**Comment by lukaseder** [comment]
Starting from PostgreSQL 12+ and YugabyteDB (not CockroachDB, yet), a better emulation would be:

```sql
select jsonb_path_query_array('{"a":1,"b":2}', '$.keyvalue().key')
```

Producing:

```
|jsonb_path_query_array|
|----------------------|
|["a", "b"]            |
```

**Comment by lukaseder** [comment]
The Oracle implementation of `JSONB_KEYS` doesn't work correctly yet:

```
org.jooq.exception.DataAccessException: SQL [with function json_keys(j clob) return clob as o json_object_t; k json_key_list; r clob; begin o := json_object_t(j); k := o.get_keys; select coalesce(json_arrayagg(column_value), json_array()) into r from table (k); return r; end;  select json_keys(json_object()) from DUAL -- SQL rendered with a free trial version of jOOQ 3.18.0-SNAPSHOT]; Error while reading field: json_keys(json_object()), at JDBC index: 1
	at org.jooq_3.18.0-SNAPSHOT.ORACLE21C.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3460)
	at org.jooq.impl.Tools.translate(Tools.java:3448)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:765)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1404)
	at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1365)
	at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:173)
	at org.jooq.impl.Tools.fetchOne(Tools.java:2720)
	at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:509)
	at org.jooq.test.all.testcases.JSONTests.testJSONBKeys(JSONTests.java:940)
	at org.jooq.test.jOOQAbstractTest.testJSONBKeys(jOOQAbstractTest.java:10825)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.sql.SQLException: Error while reading field: json_keys(json_object()), at JDBC index: 1
	at org.jooq.impl.CursorImpl$CursorRecordInitialiser.setValue(CursorImpl.java:1591)
	at org.jooq.impl.CursorImpl$CursorRecordInitialiser.apply(CursorImpl.java:1511)
	at org.jooq.impl.CursorImpl$CursorRecordInitialiser.apply(CursorImpl.java:1432)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1389)
	... 38 more
Caused by: java.sql.SQLFeatureNotSupportedException: Nicht unterstützte Funktion: getBytes
	at oracle.jdbc.driver.ClobAccessor.getBytes(ClobAccessor.java:573)
	at oracle.jdbc.driver.GeneratedStatement.getBytes(GeneratedStatement.java:135)
	at oracle.jdbc.driver.GeneratedScrollableResultSet.getBytes(GeneratedScrollableResultSet.java:183)
	at org.jooq.tools.jdbc.DefaultResultSet.getBytes(DefaultResultSet.java:170)
	at org.jooq.tools.jdbc.DefaultResultSet.getBytes(DefaultResultSet.java:170)
	at org.jooq.tools.jdbc.DefaultResultSet.getBytes(DefaultResultSet.java:170)
	at org.jooq.impl.CursorImpl$CursorResultSet.getBytes(CursorImpl.java:482)
```

The problem is that our function returns a `CLOB` instead of a `BLOB`, irrespective of whether the user calls `JSON_KEYS` or `JSONB_KEYS`
