### ISSUE TITLE
Add a LoggingDiagnosticsListener, a default DiagnosticsListener implementation that logs events

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14146]
Currently, users have to implement their own `DiagnosticsListener` handling, which is a bit of work:

- They have to first understand each event *before* it happens
- They have to implement logic

It would be much better if they could just turn on the feature with a simple flag, and then get all the information in a log file. The logs can be ignored at first, or handled when the user is ready or when they notice it at all.

### Tasks

- [x] Add a `LoggingDiagnosticsListener` implementation
- [x] Add a `Settings.diagnosticsLogging` flag, that allows for auto-adding it to the `Configuration` (similar to the `ExecuteLogger`). The default is `true`, so this is just used to turn the feature off.
- [x] ~Think about adding a debug mode to `Configuration` that turns on all of these dev features~: Moved to a separate issue: https://github.com/jOOQ/jOOQ/issues/14190
