### ISSUE TITLE
Plain SQL templates whose template is an identifier should behave like TableFieldImpl, or TableImpl

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14218]
These two API usages are similar, but subtly different:

```java
field("f", type);
field(unquotedName("f"), type);
```

The documentation that describes these two APIs is:

- https://www.jooq.org/doc/latest/manual/sql-building/plain-sql/
- https://www.jooq.org/doc/latest/manual/sql-building/names/

The plain SQL templating API produces a `SQLField<T>`, which doesn't know that its template is an identifiers, whereas the API accepting an `org.jooq.Name` produces a `TableField<?, ?>`.

There's a bit of `TableField` specific logic in jOOQ as can be seen here (probably not exhaustive):

<img width="531" alt="image" src="https://user-images.githubusercontent.com/734593/201877307-42693dc6-b978-45dd-b63b-c5472b310479.png">

Some of that logic would apply to identifier-only plain SQL templates as well. I bet users wouldn't mind if the identifier-only plain SQL template usage wouldn't differ from the `Name` plain SQL usage, because wrapping things by name is a chore. Besides, the API isn't consistent. A `String` isn't always a template. When using DDL, for example, it isn't. #10030 introduced the `@Stringly.Name` and `@Stringly.SQL` annotations to help documente the distinction.

### Affected SQL generation:

- [x] SQL Server `OUTPUT` clause (see https://github.com/jOOQ/jOOQ/issues/14215)
- [x] Some pattern transformations (see https://github.com/jOOQ/jOOQ/issues/13593)
- [ ] List be completed ...

### Related tasks:

- [ ] Check if this mapping would work: https://github.com/jOOQ/jOOQ/issues/7995

### Caveats

- [ ] We'd have to implement some rule regarding what constitutes an unquoted identifier
- [ ] Quoted identifiers would also have to be supported

### Benefits

- We could omit the plain SQL templating logic at runtime, speeding up a lot of existing SQL queries in user code (though that could be done independently, see https://github.com/jOOQ/jOOQ/issues/9298)
