### ISSUE TITLE
Implicit JOIN improvements

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14614]
jOOQ 3.11 introduced implicit joins (#1502). jOOQ 3.15 improved on them (#7536), and so did 3.18 (https://github.com/jOOQ/jOOQ/issues/12037). This issue tracks further improvements on the feature:

### Improvements

- [x] ~Public API in Table (for use with plain SQL)~ (This is unrealistic. Too much meta data is needed, which is not available unless using generated code)
- [x] ~Parser support (once the metadata is known to the configuration: #5296):~ Moved to external issue #7506

### Bugs

- [x] ~Correct semantics of `DSL.asterisk()`:~ Moved to new issue #7156

### To be verified

Does implicit join work

- [x] In `LATERAL` derived tables? E.g. `FROM a, LATERAL (SELECT a.b.c)`
  - [x] It works: https://github.com/jOOQ/jOOQ/issues/14983
- [x] Using a join path with the `JOIN` operator
  - [x] This isn't supported yet, will be done in a new issue: https://github.com/jOOQ/jOOQ/issues/14985
