### ISSUE TITLE
Get SNOWFLAKE dialect up to date

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14648]
Various recent jOOQ features should be supported in `SNOWFLAKE` as well, in addition to other minor improvements, including:

- [x] SQL/JSON support: https://github.com/jOOQ/jOOQ/issues/14653
- [x] `MULTISET` support: https://github.com/jOOQ/jOOQ/issues/14196
- [x] `BLOB` support via `VARBINARY`:
  - https://docs.snowflake.com/en/sql-reference/data-types-unsupported
  - https://docs.snowflake.com/en/sql-reference/data-types-text#data-types-for-binary-strings
- [x] `LIMIT .. OFFSET` with expressions: https://github.com/jOOQ/jOOQ/issues/14365
- [x] Oracle `(+)` JOIN support:
  - https://github.com/jOOQ/jOOQ/issues/7312
  - https://docs.snowflake.com/en/sql-reference/constructs/where#joins-in-the-where-clause
- [x] `Table` as `GroupField`: #11834
- [x] Turn on `Settings.backslashEscaping` by default
  - https://docs.snowflake.com/en/sql-reference/data-types-text#label-single-quoted-string-constants
- [x] `Asterisk::except`: https://github.com/jOOQ/jOOQ/issues/14230
- [x] Aliased join tables: https://github.com/jOOQ/jOOQ/issues/14310
- [x] Procedural language support:
  - [x] https://github.com/jOOQ/jOOQ/issues/14655
  - [x] Code generation
    - [x] Procedures
    - [x] Scalar functions
    - [x] Table valued functions
    - [x] Overloads
  - [x] Runtime support
- [x] Spatial support:
  - https://docs.snowflake.com/en/sql-reference/data-types-geospatial
  - https://docs.snowflake.com/en/sql-reference/functions-geospatial

Possibly:

  - https://github.com/jOOQ/jOOQ/issues/13530

Rejected improvements:

- ~Code generation support for constraints via `TABLE_CONSTRAINTS` (to be verified, we're currently using `SHOW` commands)~ (We'll do this once there's a good reason for it)
  - https://docs.snowflake.com/en/sql-reference/info-schema/table_constraints

Bugs:

- [x] https://github.com/jOOQ/jOOQ/issues/14650
- [x] https://github.com/jOOQ/jOOQ/issues/14660

Bugs in Snowflake: 

- https://community.snowflake.com/s/question/0D5Do00000HcqwaKAB/a-recursive-cte-is-not-allowed-to-have-quoted-lower-case-identifiers

This list will be amended

**Comment by lukaseder** [comment]
Welp, the spatial parts don't work too well yet. But that's what they say on Snowflake, it's experimental functionality (preview feature): https://docs.snowflake.com/en/sql-reference/data-types-geospatial#label-data-types-geometry

**Comment by lukaseder** [comment]
The remaining task of supporting the procedural language extensions (https://github.com/jOOQ/jOOQ/issues/13530) might be implemented still, in case customers would like to see that. The important bit is code generation for procedures and functions. Generating procedural code from jOOQ is quite advanced, and not necessarily needed (yet).
