### ISSUE TITLE
Continue work on public query object model API

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14756]
jOOQ 3.16 introduced a new draft query object model API with https://github.com/jOOQ/jOOQ/issues/12425, and 3.17, 3.18 implemented a few improvements on it: https://github.com/jOOQ/jOOQ/issues/12772, https://github.com/jOOQ/jOOQ/issues/13640.

This task continues the work of 3.16. New tasks include:

### Bugs

- [ ] Check if `QOM.$replace()` works correctly for optional child parts (e.g. `Declaration::$value` and such)
- [ ] Generated operators should use `Val.getJavaValue(field2)` on the rhs of an operator (if available)
- [ ] Generated setters
  - [ ] Mutually exclusive clauses must make sure to leave the resulting statement in a meaningful state, e.g. `Revoke::from` and `Revoke::fromPublic`, when calling mutators
  - [ ] This doesn't work correctly for aggregate / window functions yet. The `FILTER` / `OVER` and other clauses aren't being copied.
- [ ] Collections, such as `SelectFieldList` produce a generic collection instead of a compatible one on `QueryPart::$replace`

### Possible deprecations

- [ ] `SelectIsNull` and `SelectIsNotNull`, once `RowSubquery` is available: https://github.com/jOOQ/jOOQ/issues/14557 (replace by `RowIsNull` and `RowIsNotNull`)

### Leftovers `QueryPart` types

- [ ] More documentation
- [ ] `UNotYetImplemented` subtypes
  - [ ] `AbstractRoutine`
  - [ ] `AlterTable`
  - [ ] `ArrayConstant`
  - [ ] `ArrayOfValues` (new type in jOOQ 3.18)
  - [ ] `ArrayTable`
  - [ ] `AssociativeArrayConstant`
  - [ ] `CharacterSetImpl`
  - [ ] `CheckImpl`
  - [ ] `CollationImpl`
  - [ ] `ConstraintImpl`
  - [ ] `ConvertedVal`
  - [ ] `DateDiff`
  - [ ] `DateOrTime`
  - [ ] `DomainImpl`
  - [ ] `EmbeddableTableField`
  - [ ] `FlashbackTable`
  - [ ] `ForJSON`
  - [ ] `ForLock`
  - [ ] `ForXML`
  - [ ] `FunctionTable`
  - [ ] `GroupConcat`
  - [ ] `IfImpl`
  - [ ] `IndexImpl`
  - [x] `InsertQueryImpl` (in 3.18)
    - [ ] `ON CONFLICT` clause needs some additional thought
  - [ ] `JSONExists`
  - [ ] `JSONTable`
  - [ ] `JSONValue`
  - [ ] `ListAgg`
  - [ ] `LoopImpl`
  - [ ] `MergeImpl`
  - [ ] `PeriodImpl`
  - [ ] `PeriodSpecificationImpl`
  - [ ] `PeriodTable`
  - [ ] `Pivot`
  - [ ] `QualifiedRecordConstant`
  - [ ] `RegexpReplace`
  - [ ] `RowAssignment`
  - [ ] `RowBetweenCondition`
  - [ ] `RowInCondition`
  - [ ] `RowIsDistinctFrom`
  - [ ] `RowSubqueryCondition`
    - [ ] This type should be merged with the existing `RowEq` etc. types. The subquery being not a special type of predicate, but wrapped in a similar way to `ScalarSubquery` in `Eq`. See also https://github.com/jOOQ/jOOQ/issues/14556
  - [ ] `SequenceImpl`
  - [ ] `TableFieldImpl`
  - [ ] `TableImpl`
  - [ ] `TruncDate`
  - [ ] `UDTFieldImpl`
  - [ ] `UDTImpl`
  - [ ] `XMLExists`
  - [ ] `XMLTable`
- [ ] Incompletely supported `QOM` types (only accessors no mutators)
  - [ ] Add a test that validates that every accessor has a corresponding mutator
  - [ ]  `With`
    - [ ] `$with()` in `Insert`
    - [ ] `$with()` in `Update`
    - [ ] `$with()` in `Delete`
- [ ] `Select` QOM API
  - [ ] Missing accessors / mutators https://github.com/jOOQ/jOOQ/issues/13310
  - [ ] Think about hiding those again in a `QOM.Select` type
- [ ] `UOperatorN` API leaks into public types, despite the interfaces being package private. Review this.
- [ ] Avoid storing arrays in QOM implementations where we really work with lists
  - [ ] https://github.com/jOOQ/jOOQ/issues/12462
- [ ] Check if common "duck types" can be extracted into formal types, e.g.
  - [ ] All types that have `$schema()`
  - [ ] Similar functions, such as `LTRIM`, `RTRIM`, `TRIM`
- [ ] Think about possible conflicts between e.g. `ArrayEnumeration` and `ArrayQuery`, etc.
  - [ ] `Array`, `Multiset`, etc.
  - [ ] `Eq` (field or row)
  - [ ] `In` (field list or select)
- [ ] Review the child `QueryPart` that are traversed or replaced. E.g. should we really traverse / replace the comment of a catalog?
- [ ] The `replace()` function should be able to handle arrays and collections, (and debug log whenever it ignores an argument?)
- [ ] During this refactoring, it became clear once more that we have 3 types of API all blended together: DSL, model, meta. What's currently unclear is how the meta API interacts with this new model API and its transformations, e.g. what happens in `TableImpl.replace()`?
- [ ] Some `AbstractTable` types have a `name` for aliasing purposes. What to do about this?
- [ ] Forward compatibility of the API is important. We should decide already now if we return a `String`, `Name` or a new `QueryPart` type (even if a meta query part doesn't yet exist, e.g. when running a `CREATE TYPE` statement).
- [ ] `traverse()`
  - [ ] Depth first vs breadth first options?
  - [ ] Child order options? E.g. is it interesting to traverse a `SELECT` in its lexical or logical order?
  - [ ] Implement some primitive detection for infinite loops in traverse and recurse (e.g. replace at most 65k times)
- [ ] The current generated `QueryPart` API translates a "choice" to several nullable fields. Also, some paths depend on previous steps, e.g. the `AlterTableImpl::$renameColumnTo` property is not nullable, if the `AlterTableImpl::$renameColumn` property is set. This can only be fixed if all generated expression trees follow the step model, just like the DSL, with nested objects for each type of substatement
  - [ ] This possibly includes a few functions, too, such as `Log` with an optional `$base()`
  - [ ] If this can't be fixed, then at least:
    - [ ] The nullability must be the same for all steps that belong together
    - [ ] The properties that belong together should be listed together, lexically. This isn't important, but it would still be nicer.
- [ ] Make more use of `DerivedColumnList` wherever we have a `table (column1, column2, ...)` style syntax
- [ ] Statements should group attributes (of substatements) that belong together in new types. Example given here: https://twitter.com/lukaseder/status/1445675264948592640
- [ ] The `org.jooq.parser.param-collector` internal flag might be a candidate for replacement by `QOM::traverse`?
- [ ] Some `QOM` types don't have correct subtypes for all cases, e.g.
  - [ ] `QOM.QualifiedRowid` (see https://github.com/jOOQ/jOOQ/issues/8388)
- [ ] Split existing implementations into several types
  - [ ] New `QuantifiedSelect` implementations
  - [ ] `Asterisk` and `AsteriskExcept`
  - [ ] Various `RowCondition` and similar predicates
  - [ ] Many more, which aren't listed here, explicitly
- [ ] Make sure the API is as regular as possible
  - [ ] Don't use `T, T...` style arguments when a list has a length of at least 1, always use `MList<T>` instead
  - [ ] Unify naming of function arguments for similar concepts
  - [ ] Move the `QOM` class to `org.jooq`. Caveats:
    - [ ] The `U` types are currently internal. They would have to be made public (so implementations can reference them)
    - [ ] So are the `QOM.replace()` utilities. These could probably be moved to `Tools`
    - [ ] Sealed API types from `org.jooq` couldn't reference any package private implementation types from `org.jooq.impl`. This is almost a show stopper for moving this API to `org.jooq`
  - [ ] Unify nullability, flags, etc. The status quo is not good:
    - [ ] Some flags are boolean (`true` / `false`)
    - [ ] ~Some flags are non-nullable enums (`A` / `B` / `DEFAULT`)~ This will be changed to nullable enums
    - [ ] Some list containers are nullable or not (e.g. `WITH` could be non-nullable. Every `SELECT` has a `WITH` instance, but the list of CTE might still be empty)
    - [ ] Some trees are nullable or not (e.g. `WHERE` could be non-nullable, given that a `noCondition()` could be the default)
- [ ] https://github.com/jOOQ/jOOQ/issues/11563

### Tests

- [ ] API
  - [ ] All mutator methods should be annotated:
    - [ ] `@NotNull`
    - [ ] `@CheckReturnValue`
  - [ ] Test if all `UOperatorN` subtypes expose *all* of their relevant properties also as `$argN()` (e.g. `JSONObjectAgg` with `$onNull()` and `$returning()`)
- [ ] Behaviour
  - [ ] Mutability tests. It shouldn't be possible to mutate any QOM types (via QOM API)
    - [ ] Make sure all `MList` access via the QOM API produces immutable lists
  - [ ] Make sure `replace()` doesn't touch subtrees that it doesn't modify. Only the ancestor path needs to be replaced
  - [ ] More complex type hierarchies probably don't implement `traverse()` and `replace()` correctly, including:
    - [ ] Window functions
    - [ ] Aggregate functions
- [ ] Make sure we don't wrap `QueryPartList` into `QueryPartList` in our generated API

### Improvements, new features

- [ ] Javadoc: There's currently no `Javadoc` on `QOM` types
- [ ] Special types: Some types act both as DSL base types and QOM types, e.g. `Select`, `Field`, etc. They have (some) accessor and mutator methods. This decision has been controversial and needs to be finalised before we make this API non-experimental. Pros and cons:
  - Pro: It's very convenient, e.g. for `Select`
  - Con: It's confusing, especially with IDE auto completion
  - Con: It can be a cause of inconsistent type hierarchies, including some that we don't see yet
- [ ] Seal the type hierarchy with Java 17 sealed types.
  - [x] Some types were sealed, but there still seem to be some hard to reproduce issues in both javac and ejc
- [ ] Think about visibility of internal logic. Either:
  - [ ] Move stuff from `org.jooq.impl` to `org.jooq` and keep using package private visibility for internal stuff
  - [ ] Embrace modularity and create a `org.jooq.internal` package, which isn't exported, but all public, so effectively an "internal" visibility
- [ ] Improve the generated `equals()` implementation (SQL generation is only required if we have plain SQL involved) and add a `hashCode()` one
- [ ] Import / export of expression tree
  - [ ] As JSON
    - [ ] Export
    - [ ] Import
  - [ ] As XML
    - [ ] Export (https://github.com/jOOQ/jOOQ/issues/855)
    - [ ] Import (https://github.com/jOOQ/jOOQ/issues/642)
    - [ ] Generate an XSD
    - [ ] Can we generate JAXB annotations on the QOM API, perhaps?
  - [ ] We need a way for a `QueryPart` to identify its `QOM` type name
  - [ ] Add the feature to the online translation service
- [ ] Experiment with language extensions
  - [ ] Kotlin `componentN()` methods could be useful on all `UOperatorN` types (where `N` could go to the usual 22)
    - [ ] Think about making *all* `QOM` types a `UOperator` subtype
  - [ ] Scala could convert `UOperatorN` types to `TupleN` types

### Retrofitting

Existing functionality could be re-written to use the new `$traverse()` and `$replace()` methods. This might mean that some previously open sourced features will now be turned commercial. This isn't decided yet, might depend on the feature. Big feature removals (from OSS edition) aren't desirable, though small ones are acceptable:

- [ ] The schema mapping feature should be re-implemented using query object model transformation
- [ ] Deprecate redundant getters
  - [ ] `SortField::getOrder`
  - [ ] `Comment::getComment` -> `Comment::$comment`
- [ ] Refactor existing methods to use the new transformation APIs instead
  - [ ] `transform` (various occasions)
    - [ ] Unneeded arithmetic in `Expression` and `Neg`
    - [ ] `JoinTable`
  - [ ] Various `copy()` methods
  - [ ] Optimistic locking
  - [ ] Embeddable flattening (?)
  - [ ] `WriteIfReadonly.IGNORE` emulation
