### ISSUE TITLE
Add Settings to turn off client side computed column including audit columns

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14775]
There are use-cases where users may want to turn off client side computed columns (including audit columns) for some queries, overriding the computation logic on a per-query basis. See, for example:

- https://github.com/jOOQ/jOOQ/issues/14768

There is a simple workaround: To avoid using generated code. Instead of:

```java
dslContext
    .update(FOO)
    .set(FOO.CREATED, hardcodedDate) // This is overridden
    .where(FOO.ID.eq(fooId))
    .execute()
```

Users can write:

```java
dslContext
    .update(table(FOO.getQualifiedName())) // Now, jOOQ doesn't know it's computed
    .set(field(FOO.CREATED.getUnqualifiedName(), INSTANT), hardcodedDate)
    .where(FOO.ID.eq(fooId))
    .execute()
```

But this is cumbersome as it involves changing queries. It would be more convenient for some use cases to just change the session into a mode where the computed columns are ignored automatically.

## Tasks

- [x] Flags
  - [x] `Settings.computedOnClientVirtual` (this is probably not very useful as these columns are synthetic and don't exist, so if this flag is turned off, the resulting SQL is just wrong. But for consistency reasons, we'll add it anyway)
  - [x] `Settings.computedOnClientStored` (this includes audit columns)
- [x] ~Offer some way to specify that a column's computation should be overridden on a per-query basis, but not with this hacky approach shown above. E.g. `DSL.overrideCompute(Field)` or something like that.~ (Maybe another day)
- [x] Documentation
  - [x] Check if readonly related `Settings` are documented also. They have to be changed as well in order to insert into stored computed columns. There are 4 flags that need to be taken into consideration!

The flags:

```java
settings
    .withComputedOnClientStored(false)
    .withReadonlyInsert(WRITE)
    .withReadonlyUpdate(WRITE)
    .withReadonlyTableRecordInsert(WRITE)
    .withReadonlyUpdatableRecordUpdate(WRITE)
```

**Comment by lukaseder** [comment]
Doing this now for jOOQ 3.20, given there are already 2 requests about the feature:

- #14768 
- #16781
