### ISSUE TITLE
Implement alternative batch execution mode to emulate batch

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14784]
The new `TRINO` dialect (https://github.com/jOOQ/jOOQ/issues/11485) doesn't support batching natively with their JDBC driver:

```
java.sql.SQLFeatureNotSupportedException: Batches not supported
	at io.trino.jdbc.TrinoStatement.addBatch(TrinoStatement.java:399)
	at org.jooq.impl.ParsingStatement.addBatch(ParsingStatement.java:335)
	at org.jooq.test.all.testcases.ParserTests.testTranslateSQLExecuteJDBCDirectlyBatchMultiple(ParserTests.java:840)
	at org.jooq.test.jOOQAbstractTest.testTranslateSQLExecuteJDBCDirectlyBatchMultiple(jOOQAbstractTest.java:11137)
```

It would be very simple to emulate batching in jOOQ, not just for `TRINO`, but for any dialect, in case that is useful for a certain transaction e.g. in MySQL. Use-case: Users implement a transaction containing batches, but for some cases, it would be better to throttle things, or whatever.

## Tasks:

- [ ] Add `Settings.batchExecutionAsSingleStatements` with the usual 3 states:
  - [ ] `NEVER`
  - [ ] `WHEN_NEEDED` (default)
  - [ ] `ALWAYS`
- [ ] Implement the flag

**Comment by lukaseder** [comment]
The emulation has been implemented, though it is not yet configurable.
