### ISSUE TITLE
Add support for TRY_CAST()

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14799]
Numerous SQL dialects have some way of expressing `TRY_CAST()`

- [x] BigQuery: `SAFE_CAST`: https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#safe_casting
- [x] DuckDB: https://duckdb.org/docs/sql/expressions/cast.html
- [x] Oracle: https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/VALIDATE_CONVERSION.html#GUID-DC485EEB-CB6D-42EF-97AA-4487884CB2CD
  - [x] But there's also 12c's `CAST(x AS y DEFAULT NULL ON CONVERSION ERROR)`
- [x] SQL Server: https://learn.microsoft.com/en-us/sql/t-sql/functions/try-cast-transact-sql?view=sql-server-ver16
- [x] Snowflake: https://docs.snowflake.com/en/sql-reference/functions/try_cast
- [x] Trino: https://trino.io/docs/current/functions/conversion.html

### Tasks

- [x] Support the above dialects
- [x] Parser support

**Comment by lukaseder** [comment]
In some RDBMS it might be possible to emulate some pairs of data type conversions like this, e.g. from `VARCHAR` to `INT`:

```sql
CASE WHEN vc LIKE_REGEXP '-?[0-9]+' THEN CAST(vc AS INT) END
```

I might do this in a future release:

- https://github.com/jOOQ/jOOQ/issues/15545
