### ISSUE TITLE
jOOQ-meta should avoid redundancies between getTables0() and sources() methods to fetch view sources

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14930]
There is some historic redundancy in various jOOQ-meta `Database` implementations, between the `getTables0()` and `sources()` methods to fetch view sources.

The latter was added with #9818 in jOOQ 3.18 to allow for fetching view sources also in the runtime `Meta` API. Dialects that have this redundancy include:

- [x] Db2
- [x] Derby
- [x] Firebird
- [x] H2
- [x] ~HSQLDB~ (we're currently also fetching TVF sources, this way, and use it for other reasons)
- [x] MySQL (and related)
- [x] Oracle
- [x] PostgreSQL (and related)
- [x] SQL Server
- [x] Trino

Nothing is gained from this refactoring for:

- HANA (We need to create a `UNION` between `TABLES` and `VIEWS` tables, because the former doesn't contain views)
- SQLite (We're querying `SQLITE_MASTER` to fetch tables, and it already has a `SQL` column)
- Teradata (We're querying `TABLES` which contains view text in its `REQUESTTEXT` column)

**Comment by lukaseder** [comment]
Specifically, since the `sources()` query is run in any case no matter if it is needed or not, we don't gain anything from eagerly fetching the sources with the views.
