### ISSUE TITLE
Get BigQuery dialect up to date

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#15012]
Judging from the release notes (https://cloud.google.com/bigquery/docs/release-notes), there are a few noteworthy features to support in BigQuery:

- [ ] Comments on views: https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_view_statement
- [x] Comments on (view) columns: 
  - https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#alter_column_set_options_statement
  - https://github.com/jOOQ/jOOQ/issues/16615
- [x] Comment meta data at runtime: https://github.com/jOOQ/jOOQ/issues/16761
- [x] Materialized views: https://cloud.google.com/bigquery/docs/materialized-views-intro
- [ ] `MIN`, `MAX`, `COUNT` with `DISTINCT` window functions: https://cloud.google.com/bigquery/docs/reference/standard-sql/aggregate_functions#min
- [ ] `ORDER BY` and `PARTITION BY` in the `WINDOW` clause: https://cloud.google.com/bigquery/docs/reference/standard-sql/window-function-calls
- [ ] `LIKE` operator with limitations: https://cloud.google.com/bigquery/docs/reference/standard-sql/operatorr#like_operator
- [ ] Table valued functions: https://cloud.google.com/bigquery/docs/reference/standard-sql/table-functions
- [x] `WITH RECURSIVE`: https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#with_clause
- [x] `DEFAULT` values: 
  - https://cloud.google.com/bigquery/docs/default-values
  - https://github.com/jOOQ/jOOQ/issues/16616
- [x] `DEFAULT` expression in `INSERT` and `UPDATE`: https://github.com/jOOQ/jOOQ/issues/16760
- [x] `PRIMARY KEY` and `FOREIGN KEY` constraints: https://github.com/jOOQ/jOOQ/issues/17225
- [x] `ALTER TABLE .. RENAME COLUMN`: https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#alter_table_rename_column_statement
- [x] `ALTER TABLE .. DROP COLUMN`: https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#alter_table_drop_column_statement
- [x] `ALTER TABLE .. ADD` with multiple columns
- [x] `ALTER TABLE .. DROP` with multiple columns
- Maybe more? Check older than August 29, 2022 https://cloud.google.com/bigquery/docs/release-notes#August_29_2022
- [x] `JSON` support: https://github.com/jOOQ/jOOQ/issues/16754
  - [ ] `MULTISET` support: https://github.com/jOOQ/jOOQ/issues/16766
- [x] Inverse distribution function support: https://github.com/jOOQ/jOOQ/issues/16759
- [x] Remove `GROUP BY <index>` emulation. It's supported natively
- [x] Emulate `GROUP BY <table>`
- [ ] Subquery in limit support, currently runs into this bug: https://issuetracker.google.com/issues/345151270
- [x] https://github.com/jOOQ/jOOQ/issues/16777
- [x] https://github.com/jOOQ/jOOQ/issues/16786
- [x] https://github.com/jOOQ/jOOQ/issues/16877

Other features:

- [x] `ALTER TABLE .. RENAME TO`: https://cloud.google.com/bigquery/docs/managing-tables#renaming-table
- [x] `ALTER TABLE IF EXISTS`

Bugs:

- [x] `CROSS APPLY` and `OUTER APPLY` isn't really supported
- [x] https://github.com/jOOQ/jOOQ/issues/16773

Interesting features to investigate:

- `HAVING MAX` and `HAVING MIN`: https://cloud.google.com/bigquery/docs/reference/standard-sql/aggregate-function-calls#having_max seems to be similar to `DISTINCT ON`

----
See also:
- https://cloud.google.com/bigquery/docs/release-notes

**Comment by lukaseder** [comment]
As always, when I integration test BigQuery DDL, I'm running into their rate limiting:

```
org.jooq.exception.DataAccessException: SQL [create table `t` (`dummy` int64, `a` string)]; [Simba][BigQueryJDBCDriver](100032) Error executing query job. Message: Exceeded rate limits: too many table update operations for this table. For more information, see https://cloud.google.com/bigquery/docs/troubleshoot-quotas
	at org.jooq_3.19.0-SNAPSHOT.BIGQUERY.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3522)
	at org.jooq.impl.Tools.translate(Tools.java:3510)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:772)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:373)
	at org.jooq.test.all.testcases.DDLTests.testAlterTableAddMultiple(DDLTests.java:1856)
	at org.jooq.test.jOOQAbstractTest.testAlterTableAddMultiple(jOOQAbstractTest.java:3729)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.sql.SQLException: [Simba][BigQueryJDBCDriver](100032) Error executing query job. Message: Exceeded rate limits: too many table update operations for this table. For more information, see https://cloud.google.com/bigquery/docs/troubleshoot-quotas
	at com.simba.googlebigquery.googlebigquery.client.requests.jobs.JobsQueryRequest.throwException(Unknown Source)
	at com.simba.googlebigquery.googlebigquery.client.requests.AbstractRequestWithRetry.executeWithRetry(Unknown Source)
	at com.simba.googlebigquery.googlebigquery.client.queryclient.JobsQueryClient.executeQuery(Unknown Source)
	at com.simba.googlebigquery.googlebigquery.client.BQClient.executeQuery(Unknown Source)
	at com.simba.googlebigquery.googlebigquery.dataengine.BQAbstractExecutor.execute(Unknown Source)
	at com.simba.googlebigquery.googlebigquery.dataengine.BQSQLExecutor.execute(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SStatement.executeNoParams(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.BaseStatement.execute(Unknown Source)
	at org.jooq.tools.jdbc.DefaultStatement.execute(DefaultStatement.java:102)
	at org.jooq.impl.SettingsEnabledPreparedStatement.execute(SettingsEnabledPreparedStatement.java:227)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:449)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:359)
	... 34 more
Caused by: com.simba.googlebigquery.googlebigquery.client.exceptions.JobExecutionErrorException: [Simba][BigQueryJDBCDriver](100032) Error executing query job. Message: Exceeded rate limits: too many table update operations for this table. For more information, see https://cloud.google.com/bigquery/docs/troubleshoot-quotas
	... 46 more
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
POST https://bigquery.googleapis.com/bigquery/v2/projects/curious-domain-305108/queries
{
  "code": 400,
  "errors": [
    {
      "domain": "global",
      "message": "Exceeded rate limits: too many table update operations for this table. For more information, see https://cloud.google.com/bigquery/docs/troubleshoot-quotas",
      "reason": "jobRateLimitExceeded"
    }
  ],
  "message": "Exceeded rate limits: too many table update operations for this table. For more information, see https://cloud.google.com/bigquery/docs/troubleshoot-quotas",
  "status": "INVALID_ARGUMENT"
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:439)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1111)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:525)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:466)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:576)
	at com.simba.googlebigquery.googlebigquery.client.requests.jobs.JobsQueryRequest.execute(Unknown Source)
	at com.simba.googlebigquery.googlebigquery.client.requests.jobs.JobsQueryRequest.execute(Unknown Source)
	... 45 more
```

I really wonder who is using such a thing in production, if it is so drastically limited...

**Comment by jacques-charnay** [comment]
Do you know when Jooq will fully support `PRIMARY KEY` and `FOREIGN KEY` on BigQuery ?

Currently, as stated in the doc, Jooq seems to simply "ignore" the key statement:
https://www.jooq.org/doc/latest/manual/sql-building/ddl-statements/create-statement/create-table-statement/create-table-primary-key/
![image](https://github.com/user-attachments/assets/565ccaad-9d60-46b7-84f3-be139f1a745f)

Even though BigQuery still doesn't support keys as real constraints like a classic db, it would be better to use constraints in `NOT ENFORCED` mode (the only mode currently available):
```sql
CREATE TABLE table (
  column1 int64,
  PRIMARY KEY (column1) NOT ENFORCED
)
```
It helps the BigQuery optimizer to run queries faster.

**Comment by lukaseder** [comment]
Thanks for your suggestion, @jacques-charnay. I'll look into it right away, via:

- https://github.com/jOOQ/jOOQ/issues/17225

**Comment by lukaseder** [comment]
To be continued:

- https://github.com/jOOQ/jOOQ/issues/17764
