### ISSUE TITLE
Add support for implicit join over to-one relationships

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#1502]
It would be nice if jOOQ could detect necesary JOINs automatically using a syntax such as:

``` java
// Query 1
create.select(FIRST_NAME, LAST_NAME)
      .from(AUTHORS)
      .where(AUTHORS.BOOKS().TITLE.equal("1984"))

// Query 2
create.select(TITLE)
      .from(BOOKS)
      .where(BOOKS.AUTHORS().LAST_NAME.equal("Orwell"))
```

This is the SQL that would be generated:

``` sql
-- Query 1
SELECT first_name, last_name
FROM   authors
WHERE  EXISTS (
  SELECT 1 FROM books
  WHERE books.author_id = author.id
  AND books.title = '1984'
)

-- Query 2
SELECT title
FROM   books
JOIN   authors ON authors.id = books.author_id
WHERE  authors.last_name = 'Orwell'
```

----

This issue will cover the "to-one" part of implicit joins, whose implementation is straightforward. Work in progress:

- [x] ~Flag to activate the feature (not a configuration flag. On the first call to the path API, we'll activate a static variable)~: Won't fix
- [x] Code generation (see #7148)
- [x] ~Public API in Table (for use with plain SQL)~: Won't fix for now
- [x] Introduce a select scope map where objects can be registered for the scope of a SELECT
- [x] Documentation
- [x] Formatting
- [x] ~Parser support (once the metadata is known to the configuration: #5296)~: Moved to external issue #7506
- [x] Scala generation
- [x] Implicit join on aliased root table
- [x] Path alias generation
- [x] ~Left join / inner join semantics!~: Moved to external issue: #7507
- [x] Nested queries
- [x] ~Usage in DML~: Moved to external issue: #7508
- [x] Self joins
- [x] Join same table several times
- [x] Join "diamond" A -> B1 -> C and A -> B2 -> C
- [x] Join "circuit" A -> B -> C -> A
- [x] ~Aliased join trees~: Moved to follow-up issue: #7536
- [x] Cross-schema implicit joins
- [x] ~Accessing projected fields from result (including ambiguities!)~: Moved to follow-up issue: #7536
- [x] ~Table name redefinition in nested scope~: Moved to follow-up issue: #7536
- [x] ~Possible column ambiguities in the join graph~: Moved to follow-up issue: #7536
- [x] ~Using a join path with the `JOIN` operator~: Moved to follow-up issue: #7536
- [x] ~Explicit path aliasing~: Moved to follow-up issue: #7536
- [x] ~Correct semantics of `DSL.asterisk()`~ will be fixed separately: #7156
- [x] ~Generate inner join on non-nullable foreign keys~: Moved to follow-up issue: #7536

**Comment by lukaseder** [comment]
Findings from an initial implementation:

1. There is a very simple solution that puts markers to the positions of all tables in the `RenderContext`'s `StringBuilder`, collects all implicit joins while traversing the AST, and patches additional `OUTER JOIN` expressions into those positions when required, at the end of the rendering phase.

    - **Advantage**: This solution has no performance impact on the existing API and is rather easy to implement and understand
    - **Disadvantage**: This solution bypasses the `VisitListener` SPI. It is not possible, for instance, to implement row-level security on tables that are joined implicitly. That's a show-stopper for this solution

2. There is a more complex solution that uses an intermediary `Context` to collect all implicit joins in the scope of the current `SELECT` statement prior to rendering the `FROM` clause, where `OUTER JOIN` expressions are amended to the relevant tables

    - **Advantage**: This solution is correct as the `VisitListener` contract is formally applied
    - **Disadvantage**: This solution traverses the `SELECT` AST twice during rendering, which is something we want to avoid for performance reasons (see also #4650). The additional overhead is significant. What's worse, the overhead appears also in queries that do not make use of implicit joins, just to check for the presence of such a join.

As it looks right now, we might not implement this feature in jOOQ, unless we find a way to significantly speed up solution 2), or we find another solution 3) that is not yet exposed here.
