### ISSUE TITLE
Offer JEP 430 JDK 21 string templates implemented by jOOQ

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#15179]
[JEP 430](https://openjdk.org/jeps/430) offers string templates to the Java language, which can be used by jOOQ to improve the API experience when running:

- Plain SQL
- Parsed and translated SQL

The idea is similar to the JDBC example from the [JEP document](https://openjdk.org/jeps/430)

```java
record ResultQueryProcessor(Configuration c)
implements 
    StringTemplate.Processor<Result<?>, DataAccessException>
{
    public Result<?> process(StringTemplate st) {
        return c.dsl().fetch(
            String.join("?", st.fragments()), 
            st.values().stream().map(v -> DSL.val(v))
        );
    }
}

record QueryProcessor(Configuration c)
implements 
    StringTemplate.Processor<Integer, DataAccessException>
{
    public Integer process(StringTemplate st) {
        return c.dsl().execute(
            String.join("?", st.fragments()), 
            st.values().stream().map(v -> DSL.val(v))
        );
    }
}
```

### Tasks

- [ ] Add new `DSLContext.queryProcessor(): StringTemplate.Processor` methods, that returns the processor (JDK 21 distribution only: https://github.com/jOOQ/jOOQ/issues/15177)
- [ ] Add new `QueryProcessor` types that can be used directly (?). This would allow for publishing them also in a new multi-release JDK 17 baseline build in the jOOQ Open Source Edition
- [ ] Offer reactive versions of the processors, returning a `Publisher<Result<?>>` or a `Publisher<Integer>` instead (can also be done later)
- [ ] Add a new `Settings.parseAndRenderPlainSQL` flag to allow for creating vendor agnostic templates: https://github.com/jOOQ/jOOQ/issues/15178

Note that in the JDK 21 build, string templates remain a preview feature, so for users to use this, they'd have to `--enable-preview`, and risk using a moving target.

### Objections

While the JEP document offers such a suggestion, the idea is by no means lacking controversy. Some may argue that string templates are not supposed to have side effects, so query execution may be "weird" (although parsing is not).

Unlike the JDBC example, where a statement has to be prepared, jOOQ can wrap bind values with the query for later preparing, so jOOQ can implement side effect free templating. Given that a `ResultQuery<R>` extends `Iterable<R>`, there can still be the usual execution convenience:

```java
for (Record record : SQL."SELECT 1") {
}
```

**Comment by lukaseder** [comment]
The string template drafts have been withdrawn in JDK 23:
https://mail.openjdk.org/pipermail/amber-spec-experts/2024-April/004106.html

There might be something in the future in this area. I'll create a new ticket for that, then.
