### ISSUE TITLE
SelectQueryImpl::toSQLReferenceLimitWithWindowFunctions should use QUALIFY to emulate WITH TIES where possible

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#15188]
By now, there are a few SQL dialects that:

- Support `QUALIFY` natively
- Do not support advanced `LIMIT` clauses (such as `PERCENT`, `WITH TIES`, etc.)

This means we can simplify the `SelectQueryImpl::toSQLReferenceLimitWithWindowFunctions` for those dialects by using `QUALIFY` rather than by nesting the query in a derived table and projecting an additional column and aliasing / unaliasing all the other columns.

Affected dialects include at least:

- DuckDB
- Exasol
- Snowflake
- Teradata

In principle, we could remove the existing emulation entirely, and let the `QUALIFY` emulation do its work, but that is a commercial only feature, so we'd be effectively removing `WITH TIES` support from the jOOQ Open Source Edition - so I won't do this for now.

### Tasks

- [x] Implement the refactoring
- [x] Add tests ensuring existing `QUALIFY` semantics isn't affected
  - [x] Combine `QUALIFY` with `DISTINCT`, `WITH TIES` to make sure all edge cases are covered
  - [x] If there's an existing `QUALIFY` clause, then we must continue using the existing emulation. The clauses can't be merged, because `LIMIT` must happen *after* `QUALIFY`
    - [x] The tests for this case have unveiled another bug: https://github.com/jOOQ/jOOQ/issues/15189

**Comment by lukaseder** [comment]
This improvement shouldn't apply to `UNION` queries:

- https://github.com/jOOQ/jOOQ/issues/19316
