### ISSUE TITLE
Add a configuration flag to avoid generating DefaultCatalog and DefaultSchema

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#15207]
These objects aren't really needed, I think? If users want to omit them, they should be able to.

### Tasks

- [x] Add configuration options to omit these (default is to generate them, to stay compatible)
- [ ] Apply the configuration to `jOOQ-meta`, where we don't really need the `DefaultCatalog` either (though we need the schema, which isn't the `DefaultSchema`, it's usually `InformationSchema` or `Sys`, etc.)
  - [x] Firebird: No catalog, no schema
- [x] Make sure omitted catalogs or schemas are no longer referenced

### Tests

- [x] Test that queries work both with or without such a reference
- [ ] Test that if there are multiple schemas and one of them is the default, this flag has no effect
- [x] Test that in the absence of a default schema, this flag has no effect
- [x] Make sure all sorts of object types are covered, including enums, sequences, routines, etc.
- [x] Test Java/Kotlin/Scala codegen

**Comment by lukaseder** [comment]
Reopening to make sure this important test is implemented:

> Test that if there are multiple schemas and one of them is the default, this flag has no effect

**Comment by lukaseder** [comment]
> Reopening to make sure this important test is implemented:
> 
> > Test that if there are multiple schemas and one of them is the default, this flag has no effect

Thinking about this again, it looks as though we don't have to make any special rules about this case. Users don't want the `DefaultSchema` class and instance, for whatever reason? Well, they don't get the instance, even in this case.

To be clear, the case is when we configure `<outputSchemaToDefault>true</outputSchemaToDefault>`

**Comment by lukaseder** [comment]
Another caveat when combining the omission of the generated `DefaultSchema` with the `<outputSchemaToDefault>true</outputSchemaToDefault>` is that generated `EnumType` values will not have any schema to reference, and thus, will work like MySQL's untyped `EnumType` even in PostgreSQL.

Specifically, this produces a regression in this integration test for #13723

```
org.jooq.exception.DataAccessException: 
SQL [insert into "t_13723" ("id", "e") values (?, ?)]; ERROR: column "e" is of type u_13723 but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 47
	at org.jooq_3.19.0-SNAPSHOT.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3523)
	at org.jooq.impl.Tools.translate(Tools.java:3511)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:811)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:373)
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:115)
	at org.jooq.test.PostgresTest.lambda$testPostgresOutputSchemaToDefaultEnums$112(PostgresTest.java:4662)
	at org.jooq.test.jOOQAbstractTest.withDSLContext(jOOQAbstractTest.java:2347)
	at org.jooq.test.jOOQAbstractTest.bindAndInline(jOOQAbstractTest.java:2330)
	at org.jooq.test.PostgresTest.testPostgresOutputSchemaToDefaultEnums(PostgresTest.java:4654)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

Without the schema, we ignore the enum type name, and by consequence don't cast the enum type bind value.

There are 2 ways to fix this:

1. Return a non-null empty schema: `DSL.schema("")`, effectively circumventing the `null` check (I don't like this very subtle difference in semantics. So far, a `(Schema) null` behaved exactly like `schema("")`, almost everywhere)
2. Add new API to clearly declare whether an `EnumType` is from a schema or not (we can do this if we're adding the API only to 3.19. Before 3.19, and before this feature here, this wasn't a real problem, only a hypothetical one)

**Comment by lukaseder** [comment]
I'm going for option 2, the new type is `QualifiedEnumType`:

- https://github.com/jOOQ/jOOQ/issues/15252

**Comment by lukaseder** [comment]
Welp. The marker interface approach will produce a regression in case someone hand-writes their `EnumType` values:

- https://github.com/jOOQ/jOOQ/issues/15252#issuecomment-1598361773
- https://stackoverflow.com/q/52814083/521799

So, maybe, option 1 is the way forward after all... Perhaps we can again re-visit the nullability of the `Schema`, though. Someone not wanting to generate a `DefaultSchema` doesn't mean we can't return one from jOOQ's internals.

**Comment by lukaseder** [comment]
Reopening this to review this additional option:

- If no `DefaultSchema`  (and catalog) is generated, then we'll return our own internal one.

**Comment by lukaseder** [comment]
What a rabbit hole. When returning `DSL.schema("")`, then the catalog is still `null`, but the `Schema` no longer is, leading to inconsistencies.

Also, this option would be inconsistent with what might be done for tables, domains, etc. Another thing I'll try is check `EnumType::getName`

**Comment by lukaseder** [comment]
Of course, this can again produce regressions in case someone hand writes their `EnumType` types. But at least, this time, the regression is caused by the user not adhereing to the Javadoc:

> The type name as registered in the database, if applicable (Postgresschema-scope enum type only). Otherwise, this returns null
