### ISSUE TITLE
Add Javadoc to discourage using any m(Class<T>) method if there's an m(DataType<T>) overload

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#15286]
The internal static type registry always causes trouble because the order of loading user defined types `U` isn't specified, so it's perfectly possible:

- For a `U` type not to register in time before it is referenced as a `Class<U>` reference
- For a `U` type to register twice, with entirely different semantics.

For example:

```java
TABLE.FIELD.cast(MyCustomType.class)
```

This will look up the `MyCustomType.class` from an internal type registry, which has been "enriched" by custom data types (via converters / bindings from generated code or manual data type declarations). This static type registry will eventually be replaced by:

- https://github.com/jOOQ/jOOQ/issues/5713

The *only* reason why this API can be used safely is for convenience for built in data types, such as e.g. `Integer.class` or `String.class`, which is why we won't deprecate the API yet.

### Tasks:

- [x] Add Javadoc to discourage usage of this API, unless for usage with internal data types (types from `SQLDataType`)
- [x] Add a warning that logs ~5 times whenever such a lookup is made, to discourage using this API this way.
- [x] More tasks moved to https://github.com/jOOQ/jOOQ/issues/5713, including:
  - Making the warning configurable through a `Settings`

----
See also:
- https://github.com/jOOQ/jOOQ/issues/15284
- https://github.com/jOOQ/jOOQ/issues/7483

**Comment by lukaseder** [comment]
The Javadoc part is implemented and backported to:

- 3.19.0
- 3.18.6 (https://github.com/jOOQ/jOOQ/issues/15287)
- 3.17.15 (https://github.com/jOOQ/jOOQ/issues/15288)
- 3.16.21 (https://github.com/jOOQ/jOOQ/issues/15289)

**Comment by lukaseder** [comment]
This issue is just about documentation and the warning. Additional work will be done via #5713

**Comment by lukaseder** [comment]
Other cases that have been overlooked will be implemented via:

- https://github.com/jOOQ/jOOQ/issues/16012

**Comment by hylkevds** [comment]
Is this warning supposed to trigger when using `DSL.inline(T value)` ?
Since that call does not have the JavaDoc warning, nor is it deprecated, but it indirectly leads to a call to `getDataType0(Class<T> type)`.

**Comment by lukaseder** [comment]
Yes, you're right. Also `val(T)`

**Comment by lukaseder** [comment]
I've updated the Javadoc of these methods via the new issue https://github.com/jOOQ/jOOQ/issues/16012

**Comment by runeflobakk** [comment]
I got the warning "The deprecated static type registry was being accessed for a non-built-in data type: clob /* java.net.URI */", referring to this issue.

I used 
```java
dslContext.transaction(config -> using(config)
    .update(TABLE)
    .set(DSL.row(TABLE.TIMESTAMP, TABLE.URL), DSL.row(OffsetDateTime.now(), URI.create("url")))
    .where(..)
    .execute());
```
Changing to two `.set(Field<T>, T)` invocations instead made the warning go away.

Is this to be expected? I use `Dsl.row()` other places including, e.g. inserting rows including `URIs` using `.valuesOfRows(..)`, but I don't get any warning. The type of `TABLE.URL` is `TableField<TableRecord, URI>`.

I can provide more details if needed, just wanted to ask first.

**Comment by runeflobakk** [comment]
@lukaseder I noticed the warning after upgrading from 3.19.3 to 3.19.7, but on further investigation it seems that the warn was emitted already from v3.19.0, so it was just that I hadn't noticed it.

I tried downgrading to 3.18.14 just to check, and the warning disappears.

I will register a new issue! 👍

**Comment by runeflobakk** [comment]
@lukaseder Not sure if this is an issue or expected, so I thought I'd ask here first.

I got a new instance of this warning for a select with a `CASE .. WHEN .. ELSE`.

I have a table `A` being joined with `B`, and if column `B.X` is a certain (custom type) value, I want to get a certain other value of the same custom type as `A.Y`, or else just get `A.Y`.
`B.X` is `TableField<BRecord, BCustomEnum>`, and `A.Y` is a `TableField<ARecord, ACustomEnum>`.

The query looks like this:
```java
dslContext
  .select(case_(B.X).when(BCustomEnum.P, ACustomEnum.Q).else_(A.Y))
  .from(A)
  .leftOuterJoin(B).on(...)
  .fetch(....
```

This results in the Static type registry warning.

I am able to make the warning go away by using `DSL.value(..)` like this:
```diff
< case_(B.X).when(BCustomEnum.P, ACustomEnum.Q).else_(A.Y)
> case_(B.X).when(BCustomEnum.P, value(ACustomEnum.Q, A.Y)).else_(A.Y)
```

Is this to be expected? Please let me know if you want this registered as a separate issue, and I will do that!
jOOQ version is 3.19.10.

**Comment by lukaseder** [comment]
This looks like another *case* of this issue here:

- https://github.com/jOOQ/jOOQ/issues/16750

I'll look into that soon.

**Comment by stellingsimon** [comment]
Documentation for `DSL.field(*, Class<T>)` was added in 

- #16012 
 
but they do not trigger the warning associated with `DiscouragedStaticTypeRegistryUsage`. Since they too rely on the static type registry, I would expect them to.

In our case, the fact that `DSL.field()` currently do not trigger the `DiscouragedStaticTypeRegistryUsage` led to the following situation:

1. Unit tests for feature A are green, everything works as expected.
2. Feature A in the real deployment fails with an error:
```
org.jooq.exception.SQLDialectNotSupportedException: Type class XYZ is not supported in dialect DEFAULT
```
3. Using an unrelated feature B in the real deployment causes the type XYZ to be registered in the static type registry.
4. Feature A in the real deployment now works as expected. 

I've created [an MVCE for the above situation](https://github.com/stellingsimon/jOOQ-mvce-field-using-static-type-registry/blob/main/jOOQ-mcve-java-postgres/src/test/java/org/jooq/mcve/test/java/postgres/JavaTest.java) with all the nitty gritty and our expectation in the form of assertions.

We've set `-Dorg.jooq.throw-on-discouraged-static-type-registry-access=true` in our tests and were relying on it to  find all problematic usages of the static type registry.

I already considered forbidding all relevant JOOQ method overloads like `m(Class<T>)` in governance tests, but sadly I'm not able reliably to distinguish the legitimate `DSL.val(..., LocalDate::class.java)` from the problematic `DSL.val(..., MyType::class.java)`, so I've come to rely on JOOQ's internals. 

**Questions for Lukas:** 
 - Can I (in theory) rely on JOOQ to throw an `DiscouragedStaticTypeRegistryUsage` in all problematic cases, or do I need to find another way to prevent them?
 - Do you advise against the use of the `m(Class<T>)` overload for built-in types, like e.g. `DSL.val(..., LocalDate::class.java)` or is that still considered "proper use" of the JOOQ API?

**Comment by lukaseder** [comment]
> * Can I (in theory) rely on JOOQ to throw an `DiscouragedStaticTypeRegistryUsage` in all problematic cases, or do I need to find another way to prevent them?

Well, as you've illustrated in your MCVE, the `DiscouragedStaticTypeRegistryUsage` exception can only be thrown when a user type is registered in the static type registry. The `SQLDialectNotSupportedException` is different, because when that is thrown, then it hints at things not having been initialised yet (or the type being completely unknown to jOOQ). For your purposes, I'd say the two exceptions are equivalent.

Regarding your actual question, the intention is indeed for the `DiscouragedStaticTypeRegistryUsage` exception to be thrown (or by default: logged) in *all* cases where user defined types are accessed via this internal static type registry instead of an explicit reference. If the exception isn't thrown (or logged) in case of a static type registry access, then that would be a bug. I want to deprecate the static type registry feature in the long run: probably in 5 years or so, when we can be sure that almost all bugs are fixed, i.e. all cases where we're accessing the static type registry but actually shouldn't, such as e.g. `TABLE.CONVERTED_COLUMN.eq(convertedValue)`. And the point of the exception is to get user feedback about such bugs, see e.g.:

- https://github.com/jOOQ/jOOQ/issues/16090
- https://github.com/jOOQ/jOOQ/issues/16425
- https://github.com/jOOQ/jOOQ/issues/16627

> * Do you advise against the use of the `m(Class<T>)` overload for built-in types, like e.g. `DSL.val(..., LocalDate::class.java)` or is that still considered "proper use" of the JOOQ API?

Well, it's probably a bit better to use the `SQLDataType.LOCALDATE` instance, because that's what jOOQ internally has to look up anyway. But since this has been so ubiquitous in jOOQ's history, and thus in all applications based on jOOQ, this will very unlikely ever be formally discouraged, let alone deprecated or removed.

Think about not just `DSL.val(.., Class<T>)`, but also `Record.get(int, Class<E>)` where the `ConverterProvider` is used to auto-convert e.g. between `String` and `Integer`, or whatever.

The historic context here is that JDBC and later also R2DBC use `Class` literals for generic type access, e.g. in `ResultSet.getObject(int, Class<T>)` or `CallableStatement.getObject(int, Class<T>)`, so jOOQ just mimicked what already worked well for tons of JDBC clients.

The big mistake in jOOQ was really just that all user defined types end up in this static type registry.
