### ISSUE TITLE
Add a code generation flag that auto-applies data type specifics of a PRIMARY KEY or UNIQUE key to referencing FOREIGN KEYS

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#15299]
In most RDBMS, it's not necessary for `PRIMARY KEY` or `UNIQUE` keys to use the same data type as their referencing `FOREIGN KEYS`. E.g. this is possible:

```sql
CREATE TABLE a (id int PRIMARY KEY);
CREATE TABLE b (id bigint REFERENCES a);
```

This produces annoying code generation output in jOOQ's code generator, as the resulting `Field<Integer>` and `Field<Long>` types aren't comparable anymore, e.g. `A.ID.eq(B.ID)` doesn't compile.

Worse:

```sql
CREATE TABLE a (e enum('a', 'b') PRIMARY KEY);
CREATE TABLE b (e varchar(10) REFERENCES a);
```

Here, the generated `enum` type is definitely desirable also on the referencing column! I've noticed this flaw while implementing the synthetic enums feature:

- https://github.com/jOOQ/jOOQ/issues/15276#issuecomment-1611579194

But it isn't `enum` type specific. In fact, we already do this when generating embedded keys, in case of which `FOREIGN KEY` references already use the same embedded type as the referenced `PRIMARY KEY` or `UNIQUE` key:

- https://www.jooq.org/doc/latest/manual/code-generation/codegen-embeddable-types/codegen-embedded-keys/

### Tasks:

- [ ] Add a code generation flag to configure this (default TBD. A better default seems to enable the feature, but that will cause compilation errors in user code upgrading jOOQ)
  - [ ] This could be a flag or a regex matching fields
  - [ ] Irrespective of the default, some logging might be useful, whenever we auto-apply some type
  - [ ] Possibly, we could implement this as low priority forced types on the foreign key columns, allowing for column-based, user-defined overrides even when the feature is turned on
- [ ] Add the implementation
  - [ ] Data type properties to be inherited:
    - [ ] Type name
    - [ ] Length, precision, scale
    - [ ] Converter
    - [ ] Binding
  - [ ] Data type properties not to be inherited:
    - [ ] Identity
    - [ ] Computed
    - [ ] Default
    - [ ] Nullability
    - [ ] Readonly

### Caveats

- [ ] Columns can be part of multiple foreign keys, referencing differently typed primary keys. Here, we simply don't apply any PK types at all
