### ISSUE TITLE
Maintain view and routine object dependency tree in meta data

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#15327]
Our various `Meta` representations should maintain an object dependency tree for view and routine objects, in order to be able to order generated DDL statements accordingly.

### Tasks

- [ ] Add a dependency meta model and implement it in:
  - [ ] Generated code
  - [ ] JDBC `DatabaseMetaData` backed `Meta`
  - [ ] XML backed `Meta`
- [ ] Add a `Settings` to specify whether the meta model should be derived from source code, if available
- [ ] Offer reordering `Meta` objects in `Meta::ddl`, accordingly

**Comment by lukaseder** [comment]
Regarding the search path, unfortunately, RDBMS behave differently here. E.g. PostgreSQL or H2:

```sql
create schema s;
create table s.t (i int);
insert into s.t values (1);
create view s.v as select i from t; -- ERROR: relation "t" does not exist
```

After setting the current schema / search path to `s`, the identifier can be resolved correctly:

```sql
set search_path = s;
create view s.v as select i from t;
select view_definition, (select * from s.v) from information_schema.views where table_schema = 's';
set search_path = public;
select view_definition, (select * from s.v) from information_schema.views where table_schema = 's';
```

Resulting in:

```
|view_definition     |i  |
|--------------------|---|
| SELECT i¶   FROM t;|1  |


|view_definition       |i  |
|----------------------|---|
| SELECT i¶   FROM s.t;|1  |
```

So, it seems that PostgreSQL resolves unqualified identifiers at `CREATE VIEW` time, and renders the view definition according to the search path (!).

This isn't the case in H2:

```sql
set schema = s;
create view s.v as select i from t;
select view_definition, (select * from s.v) from information_schema.views where table_schema = 'S';
set schema = public;
select view_definition, (select * from s.v) from information_schema.views where table_schema = 'S';
```

producing:

```
|VIEW_DEFINITION            |(SELECT    S.V.I  FROM S.V)|
|---------------------------|---------------------------|
|SELECT¶    "I"¶FROM "S"."T"|1                          |

|VIEW_DEFINITION            |(SELECT    S.V.I  FROM S.V)|
|---------------------------|---------------------------|
|SELECT¶    "I"¶FROM "S"."T"|1                          |
```

Whereas in Oracle:

```sql
create user s identified by s;
create table s.t (i int);
insert into s.t values (1);
create view s.v as select i from t;
select text, (select * from s.v) from all_views where owner = 'S';
```

The result is:

```
|TEXT             |(SELECT*FROMS.V)|
|-----------------|----------------|
|"select i from t"|                |
```

So, the unqualified identifier is not resolved at create time. It just corresponds to the owner of the view itself (which I personally find much more reasonable!). E.g. this doesn't work:

```sql
create user s identified by s;
create table t (i int);
insert into t values (1);
create view s.v as select i from t;
```

Result:

> ORA-00942: table or view "S"."T" does not exist

So, in addition to the `Settings.interpreterSearchPath`, we'll need `Settings.interpreterSearchScope` with possible values:

- `DEFAULT` (`Settings.interpreterSearchPath` specific)
- `DEFINER` (Like Oracle, the view's owner schema will be used to look up identifiers)
- `SEARCH_PATH` (Like H2, PostgreSQL, the configured search path will be used to look up identifiers)

Potentially, there's room for storing the resolved identifier back into the view and forgetting about it ever having been unqualified (see also resolving synonyms: https://github.com/jOOQ/jOOQ/issues/18504).

**Comment by lukaseder** [comment]
Things get far worse. On PostgreSQL:

```sql
set search_path = s;
create function s.f () returns int language sql as $$ select count(*) from t $$ ;
select s.f(); -- Returns 1
set search_path = public;
select s.f(); -- Raises ERROR: relation "t" does not exist
```

So, when defining a view, the identifiers are resolved according to the search path *at creation time*. When defining a function, the identifiers are still verified according to the search path (e.g. the table `t` has to exist on the search_path `s`), but the resolution is done at runtime.

This could even be seen as a security issue in PostgreSQL! If a function of any product uses unqualified identifiers, I can inject behaviour by using my own schema and re-creating tables in my schema...

**Comment by lukaseder** [comment]
Implemented in jOOQ 3.21.0. More work to be done via separate issues as linked by the description.
