### ISSUE TITLE
Add a Settings.fetchTrimmedStrings flag to auto-trim results from certain RDBMS

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#15346]
Some RDBMS have a weird (but probably acceptable by the standard?) understanding of sized strings. They tend to right-pad strings every time to match the string size, which is hardly ever useful. `jOOQ-meta` is full of `trim(somefield)` calls in projections, and I keep forgetting this when writing new queries for:

- [x] Db2
- [x] Firebird
- [x] Informix
- [x] Teradata

We could help users avoid this useless RDBMS feature when fetching data by always trimming String data by default right after fetching it from the JDBC `ResultSet` in the `DefaultStringBinding`.

### Tasks

- [x] Add a boolean flag with the following values
  - [x] `false` (default, for backwards compatibility)
  - [x] `true` (implemented in Java, when fetching from `ResultSet` columns)
- [x] Implement flag
- [x] Enable flag in all of the above dialects for `jOOQ-meta` queries as well as when running `MetaSQL` queries, the implementation of queries in `org.jooq.Meta`
- [ ] Add documentation

### Note

There used to be a historic version of this flag where there was an option to render `TRIM(x)` expressions automatically. This risks breaking SQL queries, e.g. when there's an expectation of a column name to be qualified (e.g. for usage in `ORDER BY`). I'd rather not implement things this way. This can be implemented usefully purely as a JDBC client feature.

**Comment by lukaseder** [comment]
This affects only the `CHAR` type, which is used extensively for historic reasons in some RDBMS dictionary views, not `VARCHAR`.

**Comment by lukaseder** [comment]
I'll revert adapting the `jOOQ-meta` queries again. While the flag is useful, no doubt, the `jOOQ-meta` queries are exported in `String` form to `MetaSQL`, where they are executed as plain SQL templates. Thus the information about the columns being `CHAR` typed columns is lost, and the trimming no longer works at runtime.

Better keep the queries as they are.
