### ISSUE TITLE
Add Replacers.mappingTable(Function<? super Table<?>, ? extends Table<?>)

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#15356]
In jOOQ's internals, I've occasionally had use-cases for ad-hoc schema / table mappings, based on the `Replacer` API, for example:

```java
// This doesn't actually return TableList, yet, see:
// https://github.com/jOOQ/jOOQ/issues/15019
tablelist = (TableList) tablelist.$replace(Replacers.mappingTable(
    t -> t.getName().equals(something) ? u : t
));
```

This would effectively map all `t` tables to `u`, e.g.:

```sql
-- Input
SELECT t.x, x.y FROM t, x

-- Output
SELECT u.x, x.y FROM u, x
```

While it would be possible to tweak the `SchemaMapping` for this, it's much more convenient to just transform the expression tree on an ad-hoc basis.

### Tasks

- [x] Add `Replacers.mappingTable(Function<? super Table<?>, ? extends Table<?>)`
- [x] Add `Replacers.mappingTable(Table<?>, Table<?>)` (single mapping convenience method)

### Caveats:

- [x] Proper handling of table aliases

Possible future tasks:

- Add `Replacers.mappingSchema(Function<? super Schema, ? extends Schema)`
- Add `Replacers.mappingCatalog(Function<? super Catalog, ? extends Catalog)`
