### ISSUE TITLE
Add SQLDialect.H2_2_2_220

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#15350]
A new H2 version has been released:

- https://github.com/h2database/h2database/issues/3683#issuecomment-1620572101
- http://h2database.com/html/changelog.html

### Tasks

- [x] Add `SQLDialect.H2_2_2_220`

**Features relevant for jOOQ in general:**

- [x] ANY_VALUE aggregate function
- [x] Array elements as UPDATE targets
- [x] NOWAIT, WAIT n, and SKIP LOCKED in FOR UPDATE clause

**Features relevant for the parser:**

- Octal and binary numeric literals (see https://github.com/jOOQ/jOOQ/issues/15352)
- Underscores in numeric literals (see https://github.com/jOOQ/jOOQ/issues/15352)

**Other improvements:**

- [x] https://github.com/jOOQ/jOOQ/issues/13680

**Comment by katzyn** [comment]
You can also remove workaround for `MERGE`, that issue was fixed in 2.1.212: #13680

**Comment by lukaseder** [comment]
Thanks a lot for the reminder, @katzyn !

**Comment by lukaseder** [comment]
> Non-standard ANY | SOME with an array may conflict with standard ANY | SOME

Yeah, I think that's similar as in PostgreSQL? I don't think jOOQ has run into this yet with PostgreSQL.

**Comment by katzyn** [comment]
Yes, it is possible to use ANY | SOME with array returned from a subquery in PostgreSQL too, but PostgreSQL also cannot distinguish this subquery from a normal query for standard version of this predicate by itself. Extra parentheses can't help here, but cast to array data type works as well as in H2.

> new RequiredVersion(2, 2, 202)

220

**Comment by lukaseder** [comment]
> > new RequiredVersion(2, 2, 202)
> 
> 220

Thanks

**Comment by lukaseder** [comment]
Implemented in  jOOQ 3.19
