### ISSUE TITLE
UDTImpl should use Name instead of String in constructor

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#15583]
Like most other internal `QueryPart` base types for the code generator, the `UDTImpl` type should accept `Name` instead of `String` in its constructors.

### Tasks

- [x] Add new constructors
- [x] Deprecate old ones
- [x] Update code generator
