### ISSUE TITLE
Add API to construct a org.jooq.Path from meta data manually

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#15645]
jOOQ 3.19 has introduced the `org.jooq.Path` marker interface for all implicit join paths:

- #15005

The above issue mainly cared about enabling the explicit path based join syntax, such as:

```java
ctx.select()
   .from(BOOK)
   .join(BOOK.author())
   .join(BOOK.author().country())
```

With this syntax (and with this syntax alone!) it is now possible to omit the now optional `on` clause, which isn't necessary unless additional join predicates are to be added.

But a `org.jooq.Path` can also serve as a meta data API for any path. It has been used to configure `Policy` inheritance to child tables with:

- https://github.com/jOOQ/jOOQ/issues/15644

Since this policy inheritance should work also in the absence of generated code (e.g. when working with a dynamic schema based on `org.jooq.Meta`) we must:

- [ ] Offer an API to construct `org.jooq.Path` instances from `Table` and `ForeignKey` types
  - [ ] Allow for concatenating `Path` instances
  - [ ] Allow for reversing a `Path` (child-to-parent to parent-to-child)
- [ ] Expose "known" paths via the `Table` type

This isn't necessary for jOOQ 3.19. The driver for this improvement is #15644 and it can work with generated code only for now, but it would be great to have this soon, nonetheless.
