### ISSUE TITLE
Add support for Oracle 23ai's new NEW and OLD pseudo tables in RETURNING clauses

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#15839]
Oracle 23ai added two new pseudo tables for use in `RETURNING` clauses: `NEW` and `OLD`:
https://oracle-base.com/articles/23c/dml-returning-clause-enhancements-23c

This has already been offered by SQL Server via the `INSERTED` and `DELETED` pseudo tables in `OUTPUT` and is quite equivalent. In Db2 and H2 (and the SQL standard), we have the `OLD TABLE`, `NEW TABLE`, and `FINAL TABLE` distinction of the `<data change delta table>` syntax.

Since we've always offered the Oracle/PostgreSQL `RETURNING` syntax in our API, which is the most intuitive, it will make sense to offer also a way to construct these pseudo tables (useful also in triggers!)

### Tasks

- [ ] Add the `DSL` and `QOM` API
- [ ] Add the implementation. Make this work in
  - [ ] `RETURNING`
  - [ ] Triggers
    - [ ] Make sure that any implicit `REFERENCING` clause is generated even if `NEW` or `OLD` aren't declared explicitly.
- [ ] Support this in the parser

**Comment by lukaseder** [comment]
Duplicate of https://github.com/jOOQ/jOOQ/issues/15174
