### ISSUE TITLE
Fix known limitations of embeddable types

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#15892]
This is a continuation of #8353, #10527, and #11975, which fixed a lot of issues already in jOOQ 3.14 / 3.15 / 3.19

### Runtime library (known issues)

- [x] Projecting `TableAsField` or `RowAsField` containing embeddeables: https://github.com/jOOQ/jOOQ/issues/15991
- [x] Projecting an embeddable domain from a path: https://github.com/jOOQ/jOOQ/issues/16036
- [x] Returning embeddables containing computed/defaulted values from `UpdatableRecord`: https://github.com/jOOQ/jOOQ/issues/16114
- [x] Using embeddables in predicates within `MULTISET` projections: https://github.com/jOOQ/jOOQ/issues/16310
- [x] Using embeddables with `SelectIsNull`: https://github.com/jOOQ/jOOQ/issues/16319
- [x] Projecting them in `DSLContext::fetchCount`: https://github.com/jOOQ/jOOQ/issues/16326

### Code generator (known issues)

- [x] Generate interfaces if requested (currently, the `IXYZ` interface is declared on the `EmbeddableRecord`, but not generated)
  - [x] Immutable interfaces: https://github.com/jOOQ/jOOQ/issues/17178
  - [x] https://github.com/jOOQ/jOOQ/issues/14003
  - [x] https://github.com/jOOQ/jOOQ/issues/17179
  - [x] https://github.com/jOOQ/jOOQ/issues/17180
- [x] Generate POJOs if requested
  - [x] Immutable POJOs
- [x] Embeddable domains with POJOs: https://github.com/jOOQ/jOOQ/issues/11716

**Comment by alf** [comment]
Is it possible to find the parent table of an embedded primary key given just the embedded record?

**Comment by lukaseder** [comment]
@alf Embedded keys are just a code generation convenience feature, where the code generator makes sure that primary/unique constraints will generate the same embeddable type as the referencing foreign keys. There's no runtime information generated about the types being derived from keys.

You can, of course, query the generated code using Java reflection to find out who references an embedded type, and then implement heuristics, knowing your own code generation configuration.

I guess it could make sense, in some cases, to maintain meta information about this relationship. If you're interested in that, could you please create a new feature request with details about your use-case?

**Comment by alf** [comment]
https://github.com/jOOQ/jOOQ/issues/16803

**Comment by lukaseder** [comment]
To be continued:

- https://github.com/jOOQ/jOOQ/issues/17783
