### ISSUE TITLE
Add formal support for "audit" fields, such as CREATED_AT, CREATED_BY, MODIFIED_AT, MODIFIED_BY

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#1592]
A lot of databases contain audit fields such as:

- `CREATED_AT`: Time of the `INSERT`
- `CREATED_BY`: A credential who executed the `INSERT`
- `MODIFIED_AT`: Time of the last `UPDATE`
- `MODIFIED_BY`: A credential who executed the last `UPDATE`

In case further normalisation isn't given, then these might be useful, too:

- `XYZ_MODIFIED_AT`: Time of the last `UPDATE` of a column group `XYZ`
- `XYZ_MODIFIED_BY`: Credentials who executed the last `UPDATE` of a column group `XYZ`

Other interesting auditing use-cases here

- https://twitter.com/lukaseder/status/1514235182177570822

...showing that the above is too simple and opinionated. E.g. `_BY` designates a user, but it could also be interesting to log various other identifying tokens, including:

- User
- Role
- Application
- IP address, etc.

### Tasks

jOOQ could offer this functionality out of the box for convenience, in the following form:

- [x] Code generation
  - [x] A configuration that flags fields as audit fields, including their specific audit role
- [x] Runtime
  - [x] A set of `org.jooq.Generator` implementations to use for the computation of these values
  - [x] A new `AuditProvider` SPI in `Configuration` to override the defaults
    - [x] `*_AT` columns default to `currentDate()`, `currentTimestamp()`, etc. depending on their type
    - [x] `*_BY` columns default to `currentUser()`
  - [x] A mechanism to distinguish between `INSERT` computed columns and `UPDATE` computed columns (will be implemented as part of https://github.com/jOOQ/jOOQ/issues/9879, for all `GeneratorContext` usages)

Feature interactions and tests:

- [x] Modified columns can be nullable or non-nullable. The distinction is done by specifying both `auditInsertTimestamp` and `auditUpdateTimestamp` on the same column
  - [x] Nullable modified columns (value computed only on first `UPDATE`)
  - [x] Non-nullable modified columns (value computed also on first `INSERT`) 
- [x] Embeddable types. This is a prime use-case, and the feature must work with all sorts of embeddable designs, including:
  - [x] An embeddable containing all 4 values
    - [x] `replacesFields = false`
    - [x] `replacesFields = true`
  - [x] 2 embeddables with pairs of `AT|BY` columns, the embeddables being of the same type
    - [x] `replacesFields = false`
    - [x] `replacesFields = true`
  - [x] ~A nested embeddable containing the above 2 embeddables~: Not yet possible: https://github.com/jOOQ/jOOQ/issues/13059

### Code generation configuration example

The configuration will be done via a `<forcedType>`, e.g.

```xml
<forcedType>
  <auditInsertTimestamp>true</auditInsertTimestamp>
  <auditUpdateTimestamp>true</auditUpdateTimestamp>
  <includeExpression>MODIFIED_AT</includeExpression>
</forcedType>
```

### Historic feature description

This idea was seen on the user group several times:

- https://groups.google.com/d/topic/jooq-user/iS3UBATSorA/discussion
- https://groups.google.com/d/topic/jooq-user/bGUYxeNd5X0/discussion
- https://groups.google.com/d/topic/jooq-user/OO8TMx07ZCU/discussion
- https://groups.google.com/d/msg/jooq-user/yU5iIXcxkQI/bciPaqXLDgAJ
- http://stackoverflow.com/q/33534872/521799

It would align well with the recently implemented support for "optimistic locking" (#1547, #1591).

----

In the mean time #2010 has been implemented to allow for a `RecordListener` SPI, which is triggered prior to storing records. This feature here could be implemented using a `RecordListener`

**Comment by davidkarlsen** [comment]
Any progress on this one? It's one of the last things to cover in order to be able to ditch JPA and it's entitylisteners.

**Comment by lukaseder** [comment]
You can probably already cover quite a bit of functionality using `RecordListener`:
http://www.jooq.org/doc/latest/manual/sql-execution/crud-with-updatablerecords/crud-record-listener

But we're always open to review requirements. What particular use-cases do you have? Are the ones mentioned in this issue sufficient?

**Comment by lukaseder** [comment]
I just double-checked. One additional reason that might keep us from going ahead is #3943. In the past, we've made assumptions about the user data type of the optimistic locking timestamp column. This might not work well for users that use JodaTime, or Java 8's time API.

**Comment by lukaseder** [comment]
Picking this back up again in a greater context: The context of temporal validity (#4704).

**Comment by Sytten** [comment]
Do we have any progress on that?
I use the DSLContext when I insert stuff in my database and it seems that it bypass the RecordListener, but I still need this feature badly.
If you have another solution @lukaseder 
Thanks

**Comment by lukaseder** [comment]
@Sytten: Can you please create a new issue (ideally with details for reproduction). I think the issue you're encountering and this feature request are independent of one another.

**Comment by Sytten** [comment]
I will do that

**Comment by stellingsimon** [comment]
I'd be very interested in such a feature too. Every single application I've worked on used these kinds of audit columns.

Until JOOQ supports this natively, we're using a wrapper around the JDBC `Connection` that injects context information and leverage this in our Postgres triggers. All code necessary to implement this feature application/DB-side can be found in this gist.

I hope the gist will serve @lukaseder as a concrete example of the feature scope we'd require and other JOOQ users as a baseline implementation which they can adapt to their own RDBMS.

**Comment by lukaseder** [comment]
@stellingsimon : I really like your example implementation for PostgreSQL, as I've worked with similar applications in the past that did exactly that on e.g. Oracle. I personally think triggers are the way to go here, because they *always* apply, regardless of the specific database client being used, and of the specific API usage.

I'm aware that the same rules apply to the existing optimistic locking feature, which breaks as soon as we run explicit `UPDATE` statements, rather than going through `UpdatableRecord.store()`. But maybe, we could improve jOOQ to actually modify such `UPDATE` statements automatically. It won't be trivial, but perhaps it's possible.

**Comment by nekperu15739** [comment]
Hi, any update?

**Comment by lukaseder** [comment]
@nekperu15739 No update :)

**Comment by lukaseder** [comment]
No need to use the query object model for this, it can be implemented purely as code generation sugar on top of stored client side computed columns (#9879), along with an SPI to override the defaults. I'll implement this now. Will update the issue description with a more up-to-date specification

**Comment by lukaseder** [comment]
This has been implemented for jOOQ 3.17. There's still quite a bit of yak shaving to do, e.g. feature combinations with embeddables, but most of that is more related to the underlying client side stored computed column feature (#9879) than with auditing.

**Comment by sansnom** [comment]
@lukaseder I'm curious what's the best approach currently ? We have object with both created_at and updated_at but we use the pattern below to save or update. Is there a way to use the same pattern but leaving out the created_at for the onDuplicateKeyUpdate ?

I know one workaround would be to explicitly add all set() after the onDuplicateKeyUpdate but that's a bit sad (and we would like to avoid duplicating).

```kotlin
fun save(object: ObjectDomain) {
	dslContext.insertInto(TABLE)
		.set(object.toRecord())
		.onDuplicateKeyUpdate()
		.set(object.toRecord())
		.execute()
}
```

**Comment by lukaseder** [comment]
@sansnom use the out-of-the-box feature: https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-forced-types/codegen-database-forced-types-audit/
