### ISSUE TITLE
Add support for lambda accepting array functions

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#16499]
Multiple dialects support some form of lambda expressions, mainly for array / list functions, including:

- Clickhouse: https://clickhouse.com/docs/en/sql-reference/functions#higher-order-functions---operator-and-lambdaparams-expr-function
- DuckDB: https://duckdb.org/docs/sql/functions/lambda
- Trino: https://trino.io/docs/current/functions/lambda.html

There might be others. It's not an unrealistic concept for SQL functions to be higher order functions as well, even if the specific syntax variants may appear a bit unidiomatic for standard SQL.

Also, I imagine that some array functions accepting lambdas can be emulated using `UNNEST()` and `ARRAY_AGG()`, e.g.:

```sql
-- DuckDB:
select array_filter(array[1, 2, 3, 4], e -> e > 2)

-- PostgreSQL:
select (select array_agg(e) from unnest(array[1, 2, 3, 4]) as t (e) where e > 2)

-- Alternative, with guaranteed ordering, or when ordinals are requested
select (
  select array_agg(e order by o) 
  from unnest(array[1, 2, 3, 4]) with ordinality as t (e, o)
  where e > 2
)
```

### Tasks

- [x] Lambda support
  - [x] Support lambdas of degrees 1 and 2, for now
  - [x] Add `DSL` API
  - [x] Add `QOM` API
  - [x] Add parser support (including all aliases)
- [x] Array function support
  - [x] `ALL_MATCH(x[], x -> BOOLEAN) -> BOOLEAN`
  - [x] `ANY_MATCH(x[], x -> BOOLEAN) -> BOOLEAN`
  - [x] `NONE_MATCH(x[], x -> BOOLEAN) -> BOOLEAN`
  - [x] `ARRAY_MAP(x[], x -> y) -> y[]` (or `TRANSFORM`, etc.)
    - [x] Refactor `ARRAY_REPLACE` to use this instead of plain SQL templates for DuckDB, Trino
  - [x] `ARRAY_FILTER(x[], x -> BOOLEAN) -> x[]`
  - [x] More here: https://github.com/jOOQ/jOOQ/issues/16596
- [x] Kotlin extension methods would be useful, e.g. `Field<T[]>.allMatch(Lambda<T, Boolean>)`
- [x] Emulations should be able to combine, e.g. `ARRAY_MAP(ARRAY_FILTER(...))` should produce a single subquery, not 2: See https://github.com/jOOQ/jOOQ/issues/16597
- [x] Add documentation

### Tests:

- [x] Cover array literals as well as array tables (the latter will produce correlated derived tables)
- [x] Test `NULL` arrays as well as empty arrays
- [x] Test multiple array data types, including `INT[]`, `TEXT[]`

Other array functions will be investigated as well, e.g. `ARRAY_DISTINCT()`, `ARRAY_INTERSECT()`, `ARRAY_EXCEPT()`, etc., but in a separate task.

### Related tasks:

- https://github.com/jOOQ/jOOQ/issues/16507

### Notes

- The emulation may produce correlated derived tables, which aren't supported by H2, for example

**Comment by lukaseder** [comment]
It will be imperative to be able to push down emulations into the same subquery. For example, this quick test using the new kotlin extension functions (which ar really neat!):

```kotlin
select(array("1", "2", "3", "4").map { s -> s.cast(INTEGER) } .anyMatch {  i -> i.mod(2).ne(0) })
```

Produces this monster in PostgreSQL:

```sql
select (case
  when (
    select coalesce(
      array_agg(cast(e as int)),
      case
        when array['1', '2', '3', '4'] is not null then cast(array[] as int[])
      end
    )
    from unnest(array['1', '2', '3', '4']) as t (e)
  ) is not null then exists (
    select 1 as "one"
    from unnest((
      select coalesce(
        array_agg(cast(e as int)),
        case
          when array['1', '2', '3', '4'] is not null then cast(array[] as int[])
        end
      )
      from unnest(array['1', '2', '3', '4']) as t (e)
    )) as t (e)
    where mod(e, 2) <> '0'
  )
end)
```

When it should instead generate this:

```sql
select (case
  when array['1', '2', '3', '4'] is not null then exists (
    select 1 as "one"
    from unnest(array['1', '2', '3', '4']) as t (e)
    where mod(cast(e as int), 2) <> 0
  )
end)
```

**Comment by lukaseder** [comment]
Discovered an H2 bug:

- https://github.com/h2database/h2database/issues/4033
