### ISSUE TITLE
Get MemSQL dialect up to date

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#16551]
This task updates the `SQLDialect.MEMSQL` dialect to reflect some recent improvements, including:

- [x] `DEFAULT` support in `UPDATE` (#15685)
- [x] `DELETE .. USING` support via `DELETE t1 FROM t2`
  - [x] This also fixes aliasing delete target tables, and other related problems.
- [x] https://github.com/jOOQ/jOOQ/issues/16552
- [x] `LIMIT` with expressions (https://github.com/jOOQ/jOOQ/issues/12905)
- [x] SQL/JSON support (https://github.com/jOOQ/jOOQ/issues/16557)

The list will be amended
