### ISSUE TITLE
Add ServiceLoader support to DefaultConfiguration for various SPIs

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#16720]
A lot of jOOQ SPIs could be loaded using Java's `ServiceLoader` mechanism, instead of providing them to jOOQ explicitly. For example, it will be reasonable to load our own extensions by default using `ServiceLoader`, especially when core functionality is moved into new modules, such as:

- https://github.com/jOOQ/jOOQ/issues/7585
- https://github.com/jOOQ/jOOQ/issues/16500

That way, users will only have to add the newly extracted dependency in order to achieve backwards compatibility, without the need to re-configure their configurations.

### Tasks

- [ ] Support loading these SPIs using the `ServiceLoader` API from Java:
  - [ ] `ConstructorPropertiesProvider` (see https://github.com/jOOQ/jOOQ/issues/7585)
  - [ ] to be completed
- [ ] Add a new `Settings.loadConfigurationDefaultsWithServiceLoader` to allow for turning off this feature where this isn't desired, e.g. because some third party implements jOOQ SPI, but users don't actually want those implementations.
