### ISSUE TITLE
Add support for BigQuery PERCENTILE_CONT, PERCENTILE_DISC window functions

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#16759]
BigQuery has recently added support for `PERCENTILE_CONT` and `PERCENTILE_DISC` window functions only (not aggregate functions), with their own, non-standard SQL syntax:

```
PERCENTILE_CONT (value_expression, percentile [{RESPECT | IGNORE} NULLS])
OVER over_clause
```

We won't support the `RESPECT NULLS` clause in the API, though we will be able to parse `IGNORE NULLS`, the default.

### Tasks

- [x] Add API support 
  - [x] Support `FILTER` with `CASE` and `IGNORE NULLS`
- [x] Add parser support

See:
- https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#percentile_cont

**Comment by lukaseder** [comment]
The methods were already annotated with `@Support` for BigQuery, but they weren't really supported.

**Comment by lukaseder** [comment]
Really weird. I could have sworn this worked in the past. Perhaps they changed the syntax? Though, it doesn't sound likely...
