### ISSUE TITLE
Avoid calling Typed.getType() in jOOQ internals, to be more Converter aware

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#17460]
We probably don't have enough `Converter` test coverage throughout jOOQ API to cover all sorts of edge cases as exposed by this issue here:

- https://github.com/jOOQ/jOOQ/issues/17452

The issue was caused by calling `Field.getType() == byte[].class`, when we should have called `Field.getDataType().isBinary()`. The various `DataType.isXYZ()` methods are `Converter` agnostic, meaning that the `ConvertedDataType` will call through to its delegate to find out whether the `T` type is binary, not the `U` type. When we call `Field.getType()`, we look only at the `Class<U>` type, which:

- May not be a built-in type but a user type (quite likely). In this case, such checks are never `true`
- May be a built-in type, but not stored as itself, e.g. `Converter<String, Integer>`. In this case, such checks may be true when they shouldn't be (!)

There are tons of calls to `Typed.getType()`. A non-exhaustive list is:

![image](https://github.com/user-attachments/assets/4abf208f-46d2-4632-9c60-8e2a70840378)

Let's look at each individually and assess whether it is wrong. For instance, these ones in `AbstractField.isTrue()` and `isFalse()` are certainly wrong:

```java
    public final Condition isTrue() {
        Class<?> type = getType();

        if (type == String.class)
            return ((Field<String>) this).in(BooleanValues.TRUE_VALUES);
        else if (Number.class.isAssignableFrom(type))
            return ((Field<Number>) this).equal(inline((Number) getDataType().convert(1)));
        else if (Boolean.class.isAssignableFrom(type))
            return ((Field<Boolean>) this).equal(inline(true, (DataType<Boolean>) getDataType()));
        else
            return castIfNeeded(this, String.class).in(BooleanValues.TRUE_VALUES);
    }
```

These locations are the ones reported by Eclipse:

**Confirmed issues**

- [x] `org.jooq.impl.AbstractField.isTrue()`: https://github.com/jOOQ/jOOQ/issues/17544
- [x] `org.jooq.impl.AbstractField.isFalse()`: https://github.com/jOOQ/jOOQ/issues/17544
- [x] `org.jooq.impl.AbstractDMLQuery.returningRowid()`: https://github.com/jOOQ/jOOQ/issues/17549
- [x] `org.jooq.impl.TableFieldImpl.accept(Context<?>)`: https://github.com/jOOQ/jOOQ/issues/17549
- [x] `org.jooq.util.mysql.MySQLDSL.aesDecrypt(Field<T>, Field<T>)`: https://github.com/jOOQ/jOOQ/issues/17553
- [x] `org.jooq.util.mysql.MySQLDSL.aesEncrypt(Field<T>, Field<T>)`: https://github.com/jOOQ/jOOQ/issues/17553
- [x] `org.jooq.util.mysql.MySQLDSL.compress(Field<T>)`: https://github.com/jOOQ/jOOQ/issues/17553
- [x] `org.jooq.util.mysql.MySQLDSL.decode(Field<T>, Field<T>)`: https://github.com/jOOQ/jOOQ/issues/17553
- [x] `org.jooq.util.mysql.MySQLDSL.desDecrypt(Field<T>, Field<T>)`: https://github.com/jOOQ/jOOQ/issues/17553
- [x] `org.jooq.util.mysql.MySQLDSL.desDecrypt(Field<T>)`: https://github.com/jOOQ/jOOQ/issues/17553
- [x] `org.jooq.util.mysql.MySQLDSL.desEncrypt(Field<T>, Field<T>)`: https://github.com/jOOQ/jOOQ/issues/17553
- [x] `org.jooq.util.mysql.MySQLDSL.desEncrypt(Field<T>)`: https://github.com/jOOQ/jOOQ/issues/17553
- [x] `org.jooq.util.mysql.MySQLDSL.encode(Field<T>, Field<T>)`: https://github.com/jOOQ/jOOQ/issues/17553
- [x] `org.jooq.util.mysql.MySQLDSL.password(Field<T>)`: https://github.com/jOOQ/jOOQ/issues/17553
- [x] `org.jooq.util.mysql.MySQLDSL.sha1(Field<T>)`: https://github.com/jOOQ/jOOQ/issues/17553
- [x] `org.jooq.util.mysql.MySQLDSL.sha2(Field<T>, Field<Integer>)`: https://github.com/jOOQ/jOOQ/issues/17553
- [x] `org.jooq.util.mysql.MySQLDSL.uncompress(Field<T>)`: https://github.com/jOOQ/jOOQ/issues/17553
- [x] `org.jooq.impl.Collated.binding(Field<?>)`: https://github.com/jOOQ/jOOQ/issues/17557
- [x] `org.jooq.impl.Collated.type(Field<?>)`: - [ ] `org.jooq.impl.Collated.binding(Field<?>)`: https://github.com/jOOQ/jOOQ/issues/17557
- [x] `org.jooq.impl.Like.accept0(Context<?>, Field<?>, Comparator, Field<?>, Character)`: https://github.com/jOOQ/jOOQ/issues/17561
- [x] `org.jooq.impl.BitAndAgg.accept(Context<?>)`: Fixed using #17566
- [x] `org.jooq.impl.BitOrAgg.accept(Context<?>)`: Fixed using #17566
- [x] `org.jooq.impl.BitXorAgg.accept(Context<?>)`: Fixed using #17566
- [x] `org.jooq.impl.BitCount.bitAndDivEmulation(Context<?>)`: Fixed using #17566
- [x] `org.jooq.impl.BitCount.bitAndShrEmulation(Context<?>)`: Fixed using #17566
- [x] `org.jooq.impl.AbstractRoutine.pgArgNeedsCasting(Parameter<?>)`: Fixed using #17566
- [x] `org.jooq.impl.Cast.acceptAccess(Context<?>)`: Fixed using #17566
- [x] `org.jooq.impl.CurrentDate.accept(Context<?>)`: Fixed using #17566
- [x] `org.jooq.impl.CurrentTime.accept(Context<?>)`: Fixed using #17566
- [x] `org.jooq.impl.CurrentTimestamp.accept(Context<?>)`: Fixed using #17566
- [x] `org.jooq.impl.DateAdd.accept0(Context<?>)`: Fixed using #17566
- [x] `org.jooq.impl.DateDiff.accept(Context<?>)`: Fixed using #17566
- [x] `org.jooq.impl.Diff.isSynthetic(Field<?>)`: Fixed using #17566
- [x] `org.jooq.impl.DSL.unnest0(Field<?>)`: Fixed using #17566
- [x] `org.jooq.impl.Expression.DateExpression.accept(Context<?>)`: Fixed using #17566
- [x] `org.jooq.impl.Expression.DateExpression.acceptIntervalExpression(Context<?>)`: Fixed using #17566
- [x] `org.jooq.impl.JSONTable.acceptPostgres(Context<?>)`: Fixed using #17566
- [x] `org.jooq.impl.TimestampDiff.accept(Context<?>)`: Fixed using #17566
- [x] `org.jooq.impl.Multiset.returningClob(Scope, JSONArrayAggReturningStep<J>)`: Fixed using #17566
- [x] `org.jooq.impl.Multiset.returningClob(Scope, JSONArrayReturningStep<J>)`: Fixed using #17566
- [x] `org.jooq.impl.Multiset.returningClob(Scope, JSONObjectReturningStep<J>)`: Fixed using #17566
- [x] `org.jooq.impl.DefaultParseContext.parseOp()`: Fixed using #17566
- [x] `org.jooq.impl.DefaultParseContext.parseTableFactor(BooleanSupplier)`: Fixed using #17566
- [x] `org.jooq.impl.AbstractRoutine.isRefCursorParameter(Parameter<?>)`: Fixed using #17566
- [x] `org.jooq.tools.jdbc.MockResultSetMetaData.isSigned(int)`: Fixed using #17566

**These are fine**

- `org.jooq.impl.ResultQueryTrait.fetchArray(Field<T>)` (the actual array type is needed)
- `org.jooq.impl.FieldsImpl.type(int)` (the actual type is needed)
- `org.jooq.codegen.JavaGenerator.generateSyntheticDao(...)` (the actual type is needed)
- `org.jooq.codegen.JavaGenerator.generateSyntheticDao(SyntheticDaoDefinition, JavaWriter)` (the actual type is needed)
- `org.jooq.impl.FieldsImpl.types()` (the actual type is needed)
- `org.jooq.impl.ResultImpl.intoArray(Field<T>)` (the actual array type is needed)
- `org.jooq.impl.ResultImpl.intoArray(int)` (the actual array type is needed)
- `org.jooq.impl.ResultImpl.intoArray(Name)` (the actual array type is needed)
- `org.jooq.impl.ResultImpl.intoArray(String)` (the actual array type is needed)
- `org.jooq.impl.FieldsImpl.mapper(Field<?>, Configuration, Class<? extends U>)` (the actual type is needed)
- `org.jooq.impl.FieldsImpl.mapper(int, Configuration, Class<? extends U>)` (the actual type is needed)
- `org.jooq.impl.FieldsImpl.mapper(Name, Configuration, Class<? extends U>)` (the actual type is needed)
- `org.jooq.impl.FieldsImpl.mapper(String, Configuration, Class<? extends U>)` (the actual type is needed)
- `org.jooq.impl.AbstractResult.format(Writer, TXTFormat)` (the user type is needed for formatting)
- `org.jooq.impl.AbstractResult.formatChart(Writer, ChartFormat)` (the user type is needed for formatting)
- `org.jooq.impl.AbstractRow.getType()` (the actual type is needed (just delegating the call))
- `org.jooq.impl.SelectImpl.compare(Comparator, R)` (relying on `ConverterProvider` SPI semantics)
- `org.jooq.impl.SelectImpl.values(int, R...)` (relying on `ConverterProvider` SPI semantics)
- `org.jooq.impl.AbstractRecord.get(Field<?>, Class<? extends U>)` (relying on `ConverterProvider` SPI semantics)
- `org.jooq.impl.AbstractRecord.get(int, Class<? extends U>)` (relying on `ConverterProvider` SPI semantics)
- `org.jooq.impl.DefaultRecordMapper.init(E)` (relying on `ConverterProvider` SPI semantics)
- `org.jooq.impl.AbstractField.in(Result<? extends Record1<T>>)` (relying on `ConverterProvider` SPI semantics)
- `org.jooq.impl.AbstractField.notIn(Result<? extends Record1<T>>)` (relying on `ConverterProvider` SPI semantics)

**Ignored for now** (probably not an issue, or converters not yet supported)

- `org.jooq.impl.Tools.dataType(DataType<T>, Field<?>, boolean)`
- `org.jooq.impl.Tools.embeddedFields(Field<?>)` (we don't really support converters on embeddables yet, I think?)
- `org.jooq.impl.Tools.embeddedRecordType(Field<?>)` (we don't really support converters on embeddables yet, I think?)
- `org.jooq.impl.ArrayOfValues.ArrayOfValues(Field<?>[], Name, Name[])` (we don't really support converters on UDT types yet, I think?)
- `org.jooq.impl.DefaultBinding.typeMap(Class<?>, Scope, Map<String, Class<?>>)` (we don't really support converters on UDT types yet, I think?)
- `org.jooq.impl.Collect.accept(Context<?>)` (we don't really support converters on Oracle `TABLE` types yet, I think?)

**To be investigated later** (probably an issue)

- `org.jooq.impl.AbstractRoutine.setNumber(Parameter<N>, Number)` (it looks like we should use converters here)
- `org.jooq.impl.Convert.convert(Object[], Field<?>[])` (this looks delicate. We might have converters on fields other than the ones from the `DefaultConverterProvider`)
- `org.jooq.impl.Tools.castIfNeeded(Field<?>, Class<T>)`: Will be done later: https://github.com/jOOQ/jOOQ/issues/17570
- `org.jooq.impl.LoaderImpl.executeSQL(Iterator<? extends Object[]>, DSLContext)` (difficult to say if we should be using the `T` or `U` type here, let's add tests later)
- `org.jooq.tools.jdbc.MockResultSetMetaData.getColumnClassName(int)` (to be checked with tests)
- `org.jooq.impl.ParsingConnectionFactory.ParsingR2DBCStatement.execute()` (to be checked with tests, unlikely that users use converters here, though)

**Comment by lukaseder** [comment]
A prerequisite for some of these:

- https://github.com/jOOQ/jOOQ/issues/17566

**Comment by lukaseder** [comment]
I will fix a few more issues directly under this issue here, rather than creating new issues per function.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.16 (https://github.com/jOOQ/jOOQ/issues/17571)
- 3.18.23 (https://github.com/jOOQ/jOOQ/issues/17572)
- 3.17.32 (https://github.com/jOOQ/jOOQ/issues/17573)

**Comment by lukaseder** [comment]
This change introduced a "regression" (or rather, uncovered an existing flaw that was hidden) when using vendor-specific types with converters/bindings to built-in types, such as PostgreSQL `citext`, which has a `Binding<Object, String>`:

- https://github.com/jOOQ/jOOQ/issues/17958

Before this change, no cast to `varchar` was generated, because the user-defined type of the binding is `String` and jOOQ thought, the cast wasn't necessary. Now, we're comparing the database type, which is `Object`, and jOOQ now thinks the cast is necessary.

This new problem will be discussed in #17958
