### ISSUE TITLE
Enhance API to provide access to UDT members

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#228]
Currently, UDT's can only be referenced as a whole, e.g.

``` sql
SELECT address FROM t_author;
```

But in fact, it may be a lot more interesting, if these kinds of constructs were possible as well:

``` sql
SELECT address.street.no FROM t_author;
SELECT * FROM t_author ORDER BY address.country;
SELECT address.country, count(*) FROM t_author GROUP BY address.country;
```

### Tasks

- [x] Add new API
  - [x] `UDTPathField<R, T> extends Field<R>`
    - [x] ~Check relation with `Path<R>`. Probably not related. Possibly introduce new `UDTPath<R>` marker interface~ (no new path interfaces are needed at this point)
  - [x] `UDTPathTableField<R, T> extends TableField<R, T>, UDTPathField<R, T>`. This is necessary as `TableImpl::fields` is expected to return `TableField[]` by internals. To be verified
  - [x] `Internal.createXYZ` construction methods for such references
- [x] Implementation
  - [x] In queries (`SELECT`, `WHERE`, etc.)
  - [x] In DML
    - [x] `INSERT` column lists
    - [x] `UPDATE .. SET`
    - [x] `ON DUPLICATE KEY UPDATE .. SET`
    - [x] `MERGE` (`INSERT` and `UPDATE`)
- [x] Add code generation logic
  - [x] A flag to opt out of the new feature for backwards compatibility and to work around potential bugs
  - [x] `TableImpl` field reference should be declared as `UDTPathTableField`
  - [x] A new generated class should mimick the `UDTImpl` class (which probably can't be adapted, to be verified). That class should implement `UDTPathField`
  - [x] ~Implement this also in `TablePath` implicit join path classes~ (isn't necessary)
  - [x] `GeneratorStrategy`
  - [x] Matcher strategy: https://github.com/jOOQ/jOOQ/issues/3751
  - [x] Language support
    - [x] Java
    - [x] Scala
    - [x] Kotlin
  - [x] Skip arrays of UDTs for now.
  - [x] Don't do this with package UDTs, I think?
  - [x] ~Generate paths only if the type is referenced from somewhere~ (this isn't worth it. The reference computation is laborious (could be referenced from various types, e.g. tables, functions, other UDTs, and recursively))
- [x] Tests
  - [x] Integration tests
    - [x] CockroachDB (see https://github.com/jOOQ/jOOQ/issues/15145)
      - This will be less impressive at first, due to https://github.com/cockroachdb/cockroach/issues/91779
    - [x] Oracle
    - [x] PostgreSQL
    - [x] YugabyteDB
  - [x] Code generation tests for various flag combinations
  - [x] Make sure all `instanceof TableField` checks continue working (i.e. they shouldn't assume `TableFieldImpl` as the only subtype)
  - [x] UDT paths at the end of implicit join paths

### Possibly done later:

- https://github.com/jOOQ/jOOQ/issues/15505
- https://github.com/jOOQ/jOOQ/issues/15513
  - https://github.com/jOOQ/jOOQ/issues/15506
  - https://github.com/jOOQ/jOOQ/issues/15508
- Try to get rid of the existing `UDT` class (if it's no longer necessary)
- Consider lazy initialisation of paths via methods, like with implicit joins
  - Seems like a requirement, should we ever support `REF` types?
  - The benefit would be that we could share semantics with to-one joins (which are similar in concept), and we wouldn't have to touch existing generated code, which would be binary incompatible otherwise.

**Comment by akobiakov** [comment]
Hello, Lukas. Thanks again for the great job you're doing.

As far as I can see #200 is cancelled. Is there still any chance that this feature will be implemented some day? 
We have a bunch of queries with UDT member accesses in our code, so we have to use a tiny workaround to do the trick:
```java
public static <T extends UDTRecord<T>, I> Field<I> udtSubfield(Field<T> udtField, UDTField<T, I> udtSubfield) {
    return DSL.field(String.format("(%s).\"%s\"", udtField.toString(), udtSubfield.getName()), udtSubfield.getDataType()); 
}
```

Probably it would be possible to include a snippet like the one above in a specific DSL extensions like `PostgresDSL.java`.

**Comment by lukaseder** [comment]
> Is there still any chance that this feature will be implemented some day?

Yes. "Some day" is certainly a deadline I can commit to :-)

> Probably it would be possible to include a snippet like the one above in a specific DSL extensions like

It would be, and it's certainly a viable workaround for client code, but I'm not convinced that the approach is good enough for inclusion in jOOQ:

1. It doesn't feel natural to prefix the `UDTField` path with such an auxiliary method.
2. What about triple, quadruple paths?
3. What about composite types that are returned from functions (which is probably the main use-case)?

I'd really like to be able to dereference composite type attributes in an object oriented notation. With jOOQ 3.8, we've added support for catalogs (mainly a SQL Server feature), which allows for specifying:

```java
select(CATALOG.SCHEMA.TABLE.COLUMN)
```

So, I'm sure there's a way to take this one step further to allow for arbitrary levels of composite type paths.

**Comment by lukaseder** [comment]
I might soon have a look at this, finally. jOOQ 3.19 introduces the idea of a `Path`, which is mainly used as a join path, but it will probably work for UDT paths as well, which aren't so different:
https://github.com/jOOQ/jOOQ/issues/15005

**Comment by lukaseder** [comment]
This will be a really cool addition! Given some types:

```sql
CREATE TYPE u_street_type AS (
  street VARCHAR(100),
  no VARCHAR(30),
  floors integer[],
  f_1323 bytea
);

CREATE TYPE u_address_type AS (
  street u_street_type,
  zip VARCHAR(50),
  city VARCHAR(50),
  country u_country,
  since DATE,
  code INTEGER,
);
```

I can now write:

```java
create().select(
            T_AUTHOR.ADDRESS.STREET.STREET,
            T_AUTHOR.ADDRESS.STREET.NO,
            T_AUTHOR.ADDRESS.CITY,
            T_AUTHOR.ADDRESS.COUNTRY)
        .from(T_AUTHOR)
        .orderBy(T_AUTHOR.ID)
        .fetch()
```

And that will produce something like:

```


select 
  ("public"."t_author"."address")."street"."street", 
  ("public"."t_author"."address")."street"."no", 
  ("public"."t_author"."address")."city", 
  ("public"."t_author"."address")."country"
from "public"."t_author"
order by "public"."t_author"."id"

+---------------+------+--------------+-------+
|street         |no    |city          |country|
+---------------+------+--------------+-------+
|Parliament Hill|77    |Hampstead     |England|
|Caixa Postal   |43.003|Rio de Janeiro|Brazil |
+---------------+------+--------------+-------+
```

All type safe, auto-completion capable, etc. This will definitely make it into jOOQ 3.19 (finally! one of the oldest open issues!)

**Comment by lukaseder** [comment]
To everyone interested in this feature, I'd love to hear about your power user schema layout, see also this tweet:
https://twitter.com/lukaseder/status/1694989514681278738

I'm curious about the number of UDTs in your schema, and especially the level of nesting. If you're using Oracle, can you please provide me with the result of this query?

```sql
SELECT 
  count(DISTINCT owner || '.' || type_name),
  count(DISTINCT owner || '.' || p)
FROM (
  SELECT DISTINCT owner, type_name, sys_connect_by_path(type_name, '/') AS p
  FROM all_type_attrs
  WHERE owner IN ('TEST') -- Replace by your actual schemas
  CONNECT BY PRIOR attr_type_owner = owner
  AND PRIOR attr_type_name = type_name
);
```

If you're using PostgreSQL, please provide the result of this query:

```sql
with recursive t (udt_schema, udt_name, leaf_schema, leaf_name, path) as (
  select udt_schema, udt_name, udt_schema, udt_name, '/' || udt_name
  from information_schema.attributes
  where udt_schema in ('public') -- Replace by your actual schemas
  union all
  select a.udt_schema, a.udt_name, t.leaf_schema, t.leaf_name, '/' || a.udt_name || t.path
  from information_schema.attributes as a
  join t 
  on t.udt_schema = a.attribute_udt_schema 
  and t.udt_name = a.attribute_udt_name
)
select 
  count(distinct leaf_schema || '.' || leaf_name),
  count(distinct leaf_schema || '.' || path)
from t
```

I'm wondering if attribute access should be done via Java fields (more convenient, but they have to be eager initialised, which might be expensive for large schemas with tons of UDT nesting) or Java methods (a bit weird, though similar to implicit joins, yet they can be lazy initialised).

I tend to favour attribute paths, offering method paths maybe later, if someone runs into performance limitations.

**Comment by lukaseder** [comment]
A follow-up issue covering some additional work and not-yet-covered edge cases has been created:

- https://github.com/jOOQ/jOOQ/issues/15513

**Comment by lukaseder** [comment]
Implemented in jOOQ 3.19.0

**Comment by lukaseder** [comment]
There are some curious cases of getting `equals()` correct in the implementation of `UDTPathField`

**Comment by lukaseder** [comment]
A similar feature will be implemented for embeddable types:

- https://github.com/jOOQ/jOOQ/issues/17177
