### ISSUE TITLE
Add search to manual pages

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2309]
Once a manual version is selected, it might be useful to add a Google search field to the top of the manual page, to perform a `site:http://www.jooq.org/doc/3.0 blah blah` search

Another option is to use a third party search feature:
https://github.com/jOOQ/jOOQ/issues/11084#issuecomment-738504191

### Tasks:

- [x] Search
  - [x] Use `Minisearch`: https://github.com/lucaong/minisearch
  - [x] Generate search index
  - [x] Add search form
  - [x] Improvements
    - [x] Make search version specific (i.e. only search the version currently open)
    - [x] Epic task to add more explicit titles and descriptions everywhere (tracked mostly here: https://github.com/jOOQ/jOOQ/issues/12336)
    - [x] Search text doesn't currently include `<reference>` content

**Comment by lukaseder** [comment]
Dynamic TOC has been moved to a separate issue:

- https://github.com/jOOQ/jOOQ/issues/16681
