### ISSUE TITLE
Add support for the MySQL YEAR data type, mapping to java.time.Year

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2500]
The Sakila database uses `YEAR(4)` data types, which are mapped to `TIMESTAMP` by jOOQ's code generator. However, they contain 4-letter strings, such as `'2006'`, which leads to exceptions when fetching those values.

We should add support for `SQLDataType.YEAR`, mapping it to `java.time.Year`.

## Tasks:

- [x] Add the `SQLDataType.YEAR` type
- [x] Add parser support
- [x] Add support for
  - [x] Add `DefaultYearBinding`
  - [x] Update `DefaultRecordBinding` (nesting `Year` in a UDT for PostgreSQL)
  - [x] DDL
  - [x] Casts
  - [x] Usage in `MULTISET` and `ROW`
  - [x] `DefaultConverterProvider` (conversion from/to all numeric types, strings, `Date`, `Timestamp`)
  - [x] `Val::getJavaValueString`
- [x] Add native support for:
  - [x] MariaDB
  - [x] MemSQL
  - [x] MySQL
- [x] Emulate the type using `SMALLINT` in other dialects
- [x] Code generation

## Incompatibility

This is an incompatible change for all MariaDB/MemSQL/MySQL users who are already using the `YEAR` type. In order to achieve compatibility, they should apply a forced type to all `YEAR` columns, rewriting them to date:

```xml
<configuration>
  <generator>
    <database>
      <forcedTypes>
        <forcedType>
          <name>DATE</name>
          <includeTypes>(?i:YEAR)</includeTypes>
        </forcedType>
      </forcedTypes>
    </database>
  </generator>
</configuration>
```

See: https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-forced-types/codegen-database-forced-types-rewrite/

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.18.0
