### ISSUE TITLE
Add org.jooq.Policy, to support shared-schema multi-tenancy and row level security

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2682]
With the implementation of #2665, jOOQ can implement shared-schema multi-tenancy out of the box - similar to the pre-existing separate-schema / separate-table multi-tenancy, which is currently implemented through schema-mapping and table-mapping.

However, it is very difficult to get `VisitListener` implementations right. For most use-cases, it would be much better if there were special types of tables that are "multi tenancy enabled", which essentially means that they're either replaced by views if the underlying database supports updatable views, or the SQL is transformed such that predicates are added to the local `WHERE` clause. Example:

```sql
-- Input SQL using multi-tenant table t, and single-tenant table u
SELECT t.a, u.b FROM t, u

UPDATE t
SET t.a = ?
WHERE t.b IN (SELECT b FROM u)

-- Output SQL in databases supporting updatable views
SELECT t.a, u.b FROM (SELECT * FROM t WHERE t.tenant = ?) AS t, u

UPDATE (SELECT * FROM t WHERE t.tenant = ?)
SET t.a = ?
WHERE t.b IN (SELECT b FROM u)

-- Output SQL in databases not supporting updatable views
SELECT t.a, u.b FROM t, u WHERE t.tenant = ?

UPDATE t
SET t.a = ?
WHERE t.b IN (SELECT b FROM u)
AND t.tenant = ?
```

### Features:

- [x] A `org.jooq.Policy` object to describe the policy, with these properties:
  - [x] `Table` the table to apply the policy to
  - [x] `Condition`
- [x] A `org.jooq.PolicyProvider` to provide a `Policy` for a `(Table, StatementType)` pair
  - [x] `Configuration::policyProviders` to provide multiple policies to query
    - [x] If multiple policies apply are provided for a table, then they are combined with `AND`, similar to PostgreSQL's `RESTRICTIVE` clause. We won't implement `PERMISSIVE` semantics.
  - [x] A `org.jooq.impl.DefaultPolicyProvider` with a builder API to construct policies

Opt-in features:

- [x] Allow for restricting child tables based on parent tables automatically (if necessary). E.g. when there's a restriction on `AUTHOR`, then restrict also `BOOK` based on the foreign key.

Out of scope for now:

- Linting to make sure there are no inconsistent policies between base tables and dependent objects, like views, functions, etc. Related work:
  - https://github.com/jOOQ/jOOQ/issues/15327
  - https://github.com/jOOQ/jOOQ/issues/15695
- We could transform the resulting `Condition` to remove redundant predicates using our pattern matching replacer: https://github.com/jOOQ/jOOQ/issues/15696
- `StatementType` (we'll only support `ALL` semantics. The details are too complicated, and hard to test)
    - `ALL`
    - `SELECT`
    - `INSERT`
    - `UPDATE`
    - `DELETE`
- Prevent operations that would allow for bypassing our policy checks, including:
  - Plain SQL templating
  - Using non-generated schema code (which may lack meta data necessary for some checks)
  - Querying views and stored functions
  - Access to JDBC API via jOOQ

### Tasks:

- [x] Implementations
  - [x] ~Using updatable views and `WITH CHECK OPTION` where available (e.g. Oracle)~: Out of scope for now: https://github.com/jOOQ/jOOQ/issues/15633
  - [x] Using `InlineDerivedTable` otherwise
- [x] Documentation
  - [x] The feature
    - [x] It never raises exceptions, only ever skips rows! E.g. an `INSERT` might produce an update count of `0`
  - [x] Applications for all statement types
  - [x] Path inheritance: https://github.com/jOOQ/jOOQ/issues/15644
  - [x] Add a disclaimer about policies not being 100% secure. As any security layer implemented on the client side, it will always be worse than server side security. Limitations include:
    - [x] Identity values cannot be predicted, and as such, cannot be filtered out in advance (we won't support the `CHECK` policy option from PostgreSQL, only the `USING` option
    - [x] The same is true for trigger generated values, which may produce values the user should not have been able to produce
    - [x] The above also applies to `INSERT .. DEFAULT VALUES` and similar statements
    - [x] Plain SQL templating or any other means that bypasses jOOQ's expression tree will void this feature
    - [x] Any developer can simply remove the `PolicyProvider` from the `Configuration` and run queries with that derived configuration.

### Tests:

- [x] Combinations with:
  - [x] Joins
    - [x] Outer joins may need special treatment: https://github.com/jOOQ/jOOQ/issues/15629
  - [x] Aliases
    - [x] The `PolicyProvider` should always receive the base table, even if it is aliased. We'll use `Replacer::replacingTable` to produce again the actual table name of the query
  - [x] Implicit join paths
    - [x] Path segments have to be treated differently than roots of paths
  - [x] Inline derived tables
  - [x] Subqueries of any kind
    - [x] Scalar
    - [x] Multiset
    - [x] Derived table
    - [x] Implicit path correlated subquery
  - [x] Computed columns
    - [x] Virtual
    - [x] Stored
  - [x] Embeddables
  - [x] Schema mapping
- [x] Policies containing:
  - [x] Simple predicates
  - [x] `EXISTS` semi join predicates
  - [x] Implicit joins
  - [x] Implicit joins to table with a "nested" policy
- [x] DML
  - [x] `INSERT`
    - [x] `INSERT .. VALUES` -> `INSERT .. SELECT`
    - [x] `INSERT .. DEFAULT VALUES` (not sure what to do here? Just don't insert anything?)
      - [x] This relies on emulating `DEFAULT` and `DEFAULT VALUES` in DML, first: https://github.com/jOOQ/jOOQ/issues/15682
    - [x] `INSERT .. SELECT`
    - [x] `INSERT .. ON DUPLICATE KEY UPDATE`
    - [x] `INSERT .. RETURNING`
    - [x] With aliases
  - [x] `UPDATE`
    - [x] `UPDATE .. FROM`
    - [x] `UPDATE .. RETURNING`
    - [x] `UPDATE .. SET`
    - [x] `UPDATE .. SET ROW`
    - [x] `UPDATE .. JOIN`
    - [x] `UPDATE .. ORDER BY .. LIMIT`
    - [x] With aliases
  - [x] `DELETE`
    - [x] `DELETE .. USING`
    - [x] `DELETE .. RETURNING`
    - [x] `DELETE .. JOIN`
    - [x] `DELETE .. ORDER BY .. LIMIT`
    - [x] With aliases
  - [x] `MERGE`
- [x] DDL
  - [x] `CREATE TABLE .. AS SELECT`
  - [x] `CREATE VIEW .. AS SELECT`
- [x] `SELECT .. FROM FINAL TABLE (...)`
- [x] `UNION`

----
More insight can be seen in this interesting MSDN documentation page:
http://msdn.microsoft.com/en-us/library/aa479086.aspx

This was also requested in this thread here:
https://groups.google.com/d/msg/jooq-user/xIL7_2q1QfU/7qeJ6DqTMxAJ

And in this discussion here:
https://github.com/jOOQ/jOOQ/issues/7642#issuecomment-414685844

**Comment by bretwalker** [comment]
@lukaseder is this still targeted for 3.9.0? Thanks!

**Comment by lukaseder** [comment]
@bretwalker Thanks for reaching out.

This kind of feature hasn't been discussed / requested for quite a while. Also, many databases seem to have better solutions for this problem, e.g. built-in row-level security.

What's your own use-case?

**Comment by mkurz** [comment]
SQL Server 2016 and Postgres 9.5 finally added Row-level security so probably this isn't an urgent issue anymore. However I vote +1 for this feature to land in JOOQ.

**Comment by lukaseder** [comment]
@mkurz : Interesting, do you have a pointer to the PostgreSQL feature?

**Comment by mkurz** [comment]
@lukaseder 
https://wiki.postgresql.org/wiki/What's_new_in_PostgreSQL_9.5#Row-Level_Security_Policies
https://www.depesz.com/2014/10/02/waiting-for-9-5-row-level-security-policies-rls/
https://www.postgresql.org/docs/9.5/static/ddl-rowsecurity.html

**Comment by lukaseder** [comment]
Oh, very interesting. Well, could've googled that ... :)

**Comment by tianguiyuan** [comment]
very interesting

**Comment by Zynde** [comment]
Does anyone know if the is any shared-schema multi tenancy features in JOOQ or has there been and feature added for the Row Level Security in PostgreSQL?

**Comment by lukaseder** [comment]
jOOQ doesn't support it out of the box, but you might be able to roll your own:
https://blog.jooq.org/2015/06/17/implementing-client-side-row-level-security-with-jooq

I'm not aware of such a feature in PostgreSQL thus far, unlike Oracle or SQL Server. You might be able to emulate it, however, using views and PL/PERL global variables, similar to Oracle's `SYS_CONTEXT`:
https://www.postgresql.org/docs/current/static/plperl-global.html

**Comment by mkurz** [comment]
@Zynde @lukaseder Like I pointed out a couple of comments above **PostgreSQL does support Row-Level Security** since version 9.5:

https://www.depesz.com/2014/10/02/waiting-for-9-5-row-level-security-policies-rls/
https://wiki.postgresql.org/wiki/What's_new_in_PostgreSQL_9.5#Row-Level_Security_Policies
https://www.postgresql.org/docs/10/static/ddl-rowsecurity.html
Also, PostgreSQL 10 enhances RLS by adding support for restrictive policies (besides permissive policies)

**Comment by lukaseder** [comment]
Looking into this now for jOOQ 3.19. A "fun" caveat, which jOOQ can't handle as well as any native implementation is when there's a view based on a table on which users specify a policy:

```sql
CREATE TABLE t (i int);           -- With policy i > 0
CREATE VIEW v AS SELECT i FROM t; -- Policy is hard to inherit automatically
```

The only way we can enforce a policy on a view would be to parse the view and inline the policy logic, e.g. when we have object hierarchy meta information:

- https://github.com/jOOQ/jOOQ/issues/15327

The same is true for stored functions. It's always better to implement this purely in SQL, with the native feature. Just like computed columns can be more powerful when implemented purely in SQL, rather than with jOOQ's implementation.

If the user knows about this, this can still be a useful feature, though.

**Comment by lukaseder** [comment]
This is going to be such a cool feature!

Here's an example test case:

```java
// Just some test utilities
void withLanguagePolicy(ExceptionConsumer<? super DSLContext> consumer) throws Exception {
    withPolicy(T_LANGUAGE, T_LANGUAGE.ID.eq(5), consumer);
}

void withPolicy(Table<?> table, Condition condition, ExceptionConsumer<? super DSLContext> consumer) throws Exception {
    DSLContext ctx = create();

    // Here's how to configure policies
    ctx.configuration().set(new DefaultPolicyProvider().append(table, condition));
    consumer.accept(ctx);
}

public void testPolicyOnInsert() throws Exception {
    try {
        withLanguagePolicy(ctx -> {
            assertEquals(1,
            ctx.insertInto(T_LANGUAGE)
               .columns(T_LANGUAGE.ID, T_LANGUAGE.CD)
               .values(5, "es")
               .execute());

            // Not applying the policy here
            assertEquals(seq(LANGUAGE_CDS).concat("es").toList(), fetchSorted(create(), T_LANGUAGE.CD));

            assertEquals(0,
            ctx.insertInto(T_LANGUAGE)
               .columns(T_LANGUAGE.ID, T_LANGUAGE.CD)
               .values(6, "dk")
               .execute());

            // This doesn't actually delete all rows
            assertEquals(1, ctx.deleteFrom(T_LANGUAGE).execute());

            assertEquals(1,
            ctx.insertInto(T_LANGUAGE)
               .columns(T_LANGUAGE.ID, T_LANGUAGE.CD)
               .values(5, "es")
               .values(6, "dk")
               .execute());

            // Not applying the policy here
            assertEquals(seq(LANGUAGE_CDS).concat("es").toList(), fetchSorted(create(), T_LANGUAGE.CD));
        });
    }
    finally {
        resetAuthors();
    }
}
```

According to the policy, a `T_LANGUAGE.ID = 5` predicate must be appended to all queries, such that a query can't `SELECT`, `INSERT`, `UPDATE`, `DELETE` any rows not satisfying such a predicate. For example, these statements are executed:


```sql
-- The DELETE doesn't actually delete all rows
delete from PUBLIC.T_LANGUAGE
where PUBLIC.T_LANGUAGE.ID = 5

-- While it is possible to send multiple rows to the server, 
-- only those satisfying the policy predicate will be inserted, effectively
insert into PUBLIC.T_LANGUAGE (ID, CD)
select T_LANGUAGE.ID, T_LANGUAGE.CD
from (
  select 5, 'es'
  union all
  select 6, 'dk'
) T_LANGUAGE (ID, CD)
where T_LANGUAGE.ID = 5
```

Perhaps, there will be edge cases with `MERGE` or various `UPSERT` syntaxes, we'll see.

**Comment by GavinRay97** [comment]
Really cool feature! Bit of a tangent here but this idea is similar to how Hasura's engine handles authorization policies.

The following example:
```java
withPolicy(T_LANGUAGE, T_LANGUAGE.ID.eq(5), consumer);
```

Would be equivalent to setting an auth rule in Hasura like:
```json
{ "ID" : { "_eq": 5 } }
```

<details>
<summary>Click for Screenshot 👇</summary>

![image](https://github.com/jOOQ/jOOQ/assets/26604994/7588e575-3610-493e-96fb-a993bdfdfbe7)

</details>

This new jOOQ feature makes it straightforward to map declarative config rules like the above into query predicates.
Great tool for programs that do things like expose dynamic querying/datasource access 👀

**Comment by lukaseder** [comment]
I'm not surprised that you've done prior work here, @GavinRay97 :). What kinds of custom checks can you enter in your form there? In jOOQ, there will be no limitation as long as the expression is supported by the statement (e.g. there may be some edge cases with implicit join path expressions in some DML clauses).

I'm still investigating options of what else should be feasible with jOOQ. Some open questions I have:

- I have some doubts related to the utility of being able to limit a policy to apply only to a type of statement (e.g. `DELETE`). While statement type based privileges (`GRANT`) seem reasonable, for policies, it feels overengineered. Is there a reasonable use-case, in your opinion, for restricting the possibility of deleting rows of a given tenant (but allowing updates)? I mean, I can see some very advanced use-cases, but implementing these things correctly for `UPSERT` and `MERGE` seems quite difficult. In other words, I don't doubt the utility within PostgreSQL, but I'm wondering if jOOQ should replicate this feature.
- PostgreSQL distinguishes between `USING` (applied before a DML or read operation) and `CHECK` clauses (applied after a DML operation) in their policies. The `CHECK` clause seems hard to implement correctly in a client side policy, especially if a dialect doesn't natively support updating inline views with `WITH CHECK OPTION` clause. jOOQ would somehow be able to access all `DEFAULT`, `GENERATED`, and `TRIGGER` logic to reason about the outcome of an `INSERT` or `UPDATE` statement's modified rows. Do you see any value in it for Hasura, or does the `USING` clause semantics suffice?
- I was *very* surprised that PG's policies don't automatically extend to child tables of a parent table that is restricted: https://twitter.com/lukaseder/status/1704793008099438898. This seems like a very important limitation (probably not an oversight, I guess it was deemed not worth doing out of the box?). What does Hasura do here? I'm thinking of making "policy inheritance" the default, which can be opted out of globally or on a per-policy basis.
- In jOOQ, plain SQL templating would be one way to circumvent policies for obvious reasons. This will be acceptable by design (possibly with an option to reject plain SQL templating once policies are active, by default). Do you handle such scenarios or is it impossible to circumvent Hasura's query language with native SQL, for example?

**Comment by lukaseder** [comment]
> * I was _very_ surprised that PG's policies don't automatically extend to child tables of a parent table that is restricted: https://twitter.com/lukaseder/status/1704793008099438898. This seems like a very important limitation (probably not an oversight, I guess it was deemed not worth doing out of the box?). What does Hasura do here? I'm thinking of making "policy inheritance" the default, which can be opted out of globally or on a per-policy basis.

Well, when trying to implement this, it becomes more obvious. I guess the reason is that:

1. There can be recursion
2. There can be cycles

Both are hard and expensive to filter out automatically, so the burden is left to the user. It's also not unlikely that the automation isn't necessary in a schema design that uses redundant policy relevant properties. E.g. a `TENANT_ID` may be repeated in every table that is "tenant sensitive", so it suffices to just apply a single policy to *every* such table.

This means that if jOOQ implements the feature, the defaults should probably be the other way round:

- By default, a policy applies to the table only, not recursively
- Optionally, a policy can apply also to its immediate child tables
- Optionally, a policy can recurse arbitrary levels

With the default being the same as in PostgreSQL, we can postpone this additional feature, just like the policy statement:

- https://github.com/jOOQ/jOOQ/issues/15643 (I'll postpone this until someone requests it)
- https://github.com/jOOQ/jOOQ/issues/15644 (This still looks very interesting, though!)

**Comment by GavinRay97** [comment]
> What kinds of custom checks can you enter in your form there? In jOOQ, there will be no limitation as long as the expression is supported by the statement (e.g. there may be some edge cases with implicit join path expressions in some DML clauses).

Hasura uses a custom JSON DSL that pretty closely matches the semantics of what you can compose with most SQL statements.
It supports common operators, some type-specific ones (JSON/String/Regex), the `EXISTS` operator, and composition with logical `AND/OR/NOT`.

Honestly, I had no part in designing it, but I think it's one of the most powerful and useful features of Hasura.
I'd love to see it adopted in other projects that provide dynamic data access.

https://hasura.io/docs/latest/auth/authorization/permissions/#operation-permissions

---

> PostgreSQL distinguishes between USING (applied before a DML or read operation) and CHECK clauses (applied after a DML operation) in their policies. The CHECK clause seems hard to implement correctly in a client side policy, especially if a dialect doesn't natively support updating inline views with WITH CHECK OPTION clause. jOOQ would somehow be able to access all DEFAULT, GENERATED, and TRIGGER logic to reason about the outcome of an INSERT or UPDATE statement's modified rows. Do you see any value in it for Hasura, or does the USING clause semantics suffice?

We support both pre/post checks (wrote a little more about that below, in one of the "Functionality" sections)

---

> I was very surprised that PG's policies don't automatically extend to child tables of a parent table that is restricted: [twitter.com/lukaseder/status/1704793008099438898](https://twitter.com/lukaseder/status/1704793008099438898). This seems like a very important limitation (probably not an oversight, I guess it was deemed not worth doing out of the box?). What does Hasura do here? I'm thinking of making "policy inheritance" the default, which can be opted out of globally or on a per-policy basis.

In Hasura, each policy applies to only that table, and when you traverse relationships the policies pushed into the query as it's generated.

For instance, if a role `user` has full select permissions on `blogpost`, and has ability to see a specific set of columns in `blogpost_comment`, then doing something like:
```gql
query {
  blogpost {
    blogpost_comments
```

You'll have the same policy experience as if you had issued two distinct queries, one for each table:
```gql
query {
  blogpost {}
  blogpost_comments(where: { blogpost_id: ... }) {}
}
```

One thing we do allow though is "cloning" of both roles and specific table policies to quickly iterate.
For roles, we also have an "inherited roles" feature to allow composition and stuff like cascading/hierarchical policies
- (e.g., role `employee` should be `user & employee`, role `manager` should be `user` & `employee` & `manager`)
- https://hasura.io/docs/latest/auth/authorization/inherited-roles/

---

> In jOOQ, plain SQL templating would be one way to circumvent policies for obvious reasons. This will be acceptable by design (possibly with an option to reject plain SQL templating once policies are active, by default). Do you handle such scenarios or is it impossible to circumvent Hasura's query language with native SQL, for example?

In our permissions system, there's no means to use custom SQL. We allow this as a general feature, just not for permissions:
- https://hasura.io/docs/latest/schema/postgres/native-queries/

---

Below I wrote a bit more about specific parts of our system you might find useful/inspiration from:

## Functionality - Session Variables

<details><summary>CLICK TO EXPAND</summary>
In Hasura, when you authenticate a user (either via JWT or a webhook), you can set custom claims in the token.
These claims become session-scoped variables you can then use in your policies.
- https://hasura.io/docs/latest/auth/authorization/roles-variables/#session-variables

The most common example being something like:
```json5
// Following permission set on "user" table
// Only allow users to view their own row
{ "user_id": { "_eq": "X-Hasura-User-Id" } }
```

</details>

## Functionality - Reference Related Tables

<details><summary>CLICK TO EXPAND</summary>
You can use relationships you've defined between tables in the permissions.
An example would be modeling something like:
> "Only allow users to leave reviews for products they've actually purchased"

Given tables like `user`, `product`, `order`, `order_product`, `product_review`
You can set a permission on the `product_review` table like:
```json
{
  "user": {
    // When multiple conditions are specified, they are implicitly "AND"ed together
    "id": {
      "_eq": "X-Hasura-User-Id"
    },
    "orders": {
      "order_products": {
        "product_id": {
          "_ceq": "product_id"
        }
      }
    }
  }
}
```

</details>


## Functionality - Pre/Post Update Permissions

<details><summary>CLICK TO EXPAND</summary>
In addition to be able to specify policies for INSERT/UPDATE, there's a second policy that can run after the change operation has completed:
- https://hasura.io/docs/latest/auth/authorization/permissions/row-level-permissions/#post-update-check-row-permissions

For example, suppose you've got a table `product_price`.
You might have an INSERT/UPDATE permission like:
```json
{ "price": { "_gte": 0 } }
```

(Let's ignore that this should be a CHECK constraint, for demo's sake)

Since Hasura allows operations like `_inc`,`_dec`, you might get:
```gql
update_price_by_pk(
  pk_columns: { price_id: 1 },
  _inc: { price: 123 }
)
```

Then you may want to validate again that the price is non-negative, and possibly below some upper limit:
```json
{
  "_and": [{ "price": { "_gte": 0 } }, { "price": { "_lte": 9000 } }]
}
```

</details>

**Comment by lukaseder** [comment]
Thanks a lot for the feedback and for taking the time, @GavinRay97, I really appreciate it.

Regarding the related tables, your example shows child tables of a restricted table when fetching the restricted table at the top level. In that case, it seems obvious that the restriction is inherited.

What I was wondering is what would happen if someone fetched `"orders"` alone, would the permission on the user object still apply. I guess it would from your example, but it's not obvious. Again, in PostgreSQL, it doesn't apply automatically. In jOOQ 3.19, it won't apply automatically either, but users can configure jOOQ to let child tables include a policy of a parent table:

- https://github.com/jOOQ/jOOQ/issues/15644

Regarding the `CHECK` semantics, I think PostgreSQL's `USING` applies also to results of an `UPDATE .. SET` clause as far as that is obvious from the query. E.g. when doing this:

```sql
create table t (i int primary key, j int);
alter table t enable row level security;
create policy p on t using (j > 0);
```

Then this isn't possible:

```sql
insert into t values (1, 1);
update t set j = j - 1;
```

Leading to

> SQL Error [42501]: ERROR: new row violates row-level security policy for table "t"

jOOQ will emulate this as follows:

```sql
update t
set j = j - 1
where j > 0   -- Access only data allowed by the policy
and j - 1 > 0 -- Create only data allowed by the policy
```

**Comment by lukaseder** [comment]
There's a bullet in the issue description that still causes some headaches:

> * Allow operations that would allow for bypassing our policy checks, including:

Obviously, this feature will never be 100% secure as any client side security feature. For true table based security, the feature must be implemented in the server, close to the actual table (ideally below the SQL layer).

For example, these means allow for bypassing policies from within a query:

- Plain SQL templates or custom query parts
- Views and functions (whose body is opaque, unless we parse and inline it: https://github.com/jOOQ/jOOQ/issues/15695)

Plain SQL templates and custom query parts are used also by jOOQ internally, in case of which they're fine. Hard to decide what the default should be, here.

Since the feature can also be turned off simply by removing `PolicyProvider` implementations from the `Configuration`, or by using JDBC directly, I'm not sure if we should have any hard to implement restrictions in this feature.

**Comment by GavinRay97** [comment]
Hmm, I view using Plain SQL templates/custom Query Parts as an "all-bets-are-off" scenario

It seems both really difficult and somewhat of an unreasonable expectation to want Policy to work with these since they're generally a Black Box.

Just my $0.02 though

**Comment by lukaseder** [comment]
> Hmm, I view using Plain SQL templates/custom Query Parts as an "all-bets-are-off" scenario
> 
> It seems both really difficult and somewhat of an unreasonable expectation to want Policy to work with these since they're generally a Black Box.

The point is not to make them work according to the policy. The point is to forbid using them. E.g. in the presence of a policy, this would be forbidden:

```java
ctx.selectFrom("template table").fetch();
```

Simply because the policy can't be sure what's in there.

**Comment by lukaseder** [comment]
Note, this isn't meant as a security feature, but as a way to make sure people won't accidentally bypass any policies.

**Comment by lukaseder** [comment]
Policies could also be attached to generated code, in the future:

- https://github.com/jOOQ/jOOQ/issues/15713

**Comment by GavinRay97** [comment]
Is there any possibility to get the `Policy` API, or some minimal version of it in the free jOOQ edition?

One thing I've had in my head for a while is to release an OSS project similar to Hasura, providing GraphQL + AuthZ on top of datasources using jOOQ.

Writing a `PolicyProvider` that takes declarative config like the below:
```yaml
table:
  schema: public
  name: product_review

insert_permissions:
  - role: admin
    permission:
      columns: "*"
      check: {}

  - role: user
    permission:
      columns: [product_id, rating, comment]
      check:
        user:
          id: { _eq: X-User-Id }
          orders: { products: { id: { _ceq: product_id } } }
```

And converts to a `Policy` for the given `Table`.

This can be done manually during SQL generation for a given query AST but having a `PolicyProvider` would be simpler and cleaner.

If not, that's understandable, just figured I'd ask 👍

**Comment by lukaseder** [comment]
@GavinRay97 It depends heavily on the availability of the commercial SQL transformation APIs, mainly: https://www.jooq.org/doc/latest/manual/sql-building/model-api/model-api-replacement

Keep in mind that there are tons of edge cases, especially with DML statements, which must ensure a `Policy` is observed.

If your use-case is only about `Select`, you may be able to pull off some minimal functionality by using the `InlineDerivedTable` feature (which is open source), possibly along with a `VisitListener`, though: https://www.jooq.org/doc/latest/manual/sql-building/table-expressions/inline-derived-tables. After all, a `Policy` is "just" a replacement of `T` by `T.where(policyPredicate)` (plus tons of edge cases). Do note that there are many issues with `InlineDerivedTable` that will be fixed only for jOOQ 3.19, without backports (due to the complexity).

**Comment by alirahm2** [comment]
Hello everyone, I'm new to the jOOQ community and seeking some guidance. Our team recently began incorporating jOOQ (the open-source version) in a project. This application already includes numerous jOOQ queries. Our goal is to implement row-level access and multitenancy. Initially, we attempted PostgreSQL's row-level security, but found it overly complex. While I'm aware of the possibility of using the `DefaultExecuteListener` interface, it seems that jOOQ Policies might be a more suitable option. I understand this feature is available in the commercial version of jOOQ. Could anyone provide examples or sample project? I'd like to review them to ensure they align with our project requirements.

**Comment by lukaseder** [comment]
Thanks for your message, @alirahm2. You've probably found the documentation and its subsections already?
https://www.jooq.org/doc/latest/manual/sql-building/queryparts/policies/

In particular the one about configuration:
https://www.jooq.org/doc/latest/manual/sql-building/queryparts/policies/policies-configuration/

We'll soon add examples to the demo, too:
https://github.com/jOOQ/demo

> Initially, we attempted PostgreSQL's row-level security, but found it overly complex.

jOOQ's policies implemented only the main features of PostgreSQL's policies. However, you can probably avoid the more complex features in PostgreSQL as well. There's also the possibility of applying policies both on the client and on the server.

> While I'm aware of the possibility of using the `DefaultExecuteListener` interface, it seems that jOOQ Policies might be a more suitable option

Anything you implement yourself using `ExecuteListener`, `VisitListener`, and related APIs is going to be vastly more complicated than just using out of the box policy support, although, it is obviously also possible to do that. Historically, we've recommended this approach:
https://blog.jooq.org/implementing-client-side-row-level-security-with-jooq/

But the goal of our policies is to replace any home grown solution, which typically isn't complete (e.g. doesn't cover all the variants of DML statements, subqueries, etc.)
