### ISSUE TITLE
Add support for soft-deleting

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2683]
In many cases, people will want to soft-delete records instead of hard-deleting them, i.e. execute:

``` sql
-- This:
UPDATE t SET t.deleted = true WHERE t.id = ?

-- Instead of this:
DELETE t WHERE t.id = ?
```

With the query rewriting capabilities introduced in #2665, jOOQ could add much value to users by providing this functionality out of the box. Ideally, this would be a sort of emulation of the recently supported temporal validity feature set (#9741), specifically `SYSTEM_TIME`

### Tasks

At this stage, the exact feature set is not yet too clear, but as a reminder for when this will be scheduled:

- [ ] A `Settings` must be added to turn on/off soft deletion. The default is "on", because opting into the feature is done at the code generation level, so once tables are marked as "soft deletable", the intent is for them to be "soft deletable" out of the box. Two different settings govern this for:
  - [ ] Queries (off means soft-deleted records are visible to queries)
  - [ ] DML (off means deletes are hard again)
- [ ] Queries will have a `CHECK` constraint style predicate that helps filter out deleted rows from the `WHERE` clauses in `SELECT`, `UPDATE`, `DELETE`. Code generation can be used to specify such predicates on a per-table basis.
- [ ] DML statements have a `SET` clause specification, which will be applied in an `UPDATE` statement, rather than executing the hard `DELETE` statement.
  - [ ] `MERGE` might be a bit tricky to get right, in case `MERGE` has `WHEN MATCHED THEN DELETE` clauses
  - [ ] To be defined what happens with explicit tampering with the soft deletion columns. Ideally, a `WITH CHECK OPTION` on the `CHECK` constraint should be added, but not all RDBMS may support such a mechanism. This could be opt-out, if available, too
- [ ] There are strong interactions with the audit feature. Once soft deletion is supported, an opt-in set of `DELETED_AT`, `DELETED_BY` columns must be auditable (in addition to the soft deletion criteria): https://github.com/jOOQ/jOOQ/issues/1592

**Comment by mkurz** [comment]
+1

**Comment by lukaseder** [comment]
@mkurz : Thank you very much for your feedback. If you're interested, I'd love to learn more about the kind of use-case that you're looking for as we're still quite undecided how to best position this feature request strategically in jOOQ. Any feedback would be very useful.

**Comment by mkurz** [comment]
In one of our projects we have "normal" users and admin users. The normal users can create documents and put products on this documents. Sometimes a product isn't sold anymore which means the admin marks such a product as "deleted". The product still stays in the db because of reporting stuff, etc. But the normal user can't see the "deleted" product anymore - it seems completly gone. The admin user however can re-activate the product again in case it will be needed again. Actually the admin user really clicks an button labeled "Delete" and the product will be shown as ~~strikethrough~~.
For this purpose we don't use a `deleted` flag but the opposite - an `published` flag. By default each product gets published and when `published` is `false` it's "deleted". But the point is the same - it's a soft delete.

**Comment by mkurz** [comment]
For the use-case I described we use Hibernate filters right now (because we (still) use Hibernate).
However for our next project we are thinking about to use MS Sqlserver 2016 or latest Postgres which both have row level security support - so we will evaluate if we can/will use rls for such a use case as well.

Also we are thinking about to give `jOOQ` a chance in our next project. We didn't use it before but I hope I find time to evaluate it in the next couple of weeks by setting up a test project (e.g. we need working `UUID` support).
Right now I am just going through the issues and checking out some blog posts every now and then to get a feeling of what's working and what's not working and how are experience with this library.

@lukaseder Another question: Are you a one-man show? Do you employ people?

**Comment by lukaseder** [comment]
Interesting, thanks for sharing. Those are some important points as I had always been afraid that soft deleting is really a can of worms:

- Some people just wish for a simple boolean flag (where either true or false means "deleted" / "published")
- Some people will probably want some sort of state machine to be put in place, with different "levels" of deletion and different types of queries including / excluding rows based on such values
- The impact on joins and all sorts of other queries is unclear *in general*
- This doesn't yet reflect the concept of row history (e.g. as in terms of Oracle's flashback query) at all yet

It certainly needs more thinking. Your feedback is very helpful, thanks.

> Right now I am just going through the issues and checking out some blog posts every now and then to get a feeling of what's working and what's not working and how are experience with this library.

No one ever looked back to pre-jOOQ days :)

> Are you a one-man show? Do you employ people?

Mostly / I do occasionally. If you don't mind, I'll reach out about this to you in a separate email, as it isn't strictly related to soft deleting...

**Comment by mkurz** [comment]
Sure you can drop me an email (can be in german ;). Actually I was asking because I was interested about the future of JOOQ and if it is going to maintained for the years coming.

**Comment by lukaseder** [comment]
Oh, I see. Sure! The business is a very nice success story, and there are tons of new features in the pipeline. See for example this interview on InfoQ:
https://www.infoq.com/news/2017/02/data-geekery-releases-jooq-3-9

There has also been a similar, recent discussion here:
https://groups.google.com/d/msg/jooq-user/9p-U2X_Hkb8/lTPsJXLDAAAJ

**Comment by lukaseder** [comment]
... and, of course, we would welcome your further feedback about missing features! :)

**Comment by safaci2000** [comment]
Just adding my 2 cents on this.

Most of our use cases for soft deleted are from legacy.  I'm really not a fan and I find it causes more problems then anything else.  Resurrecting deleted items never seems to work well and such.  Our initial reason for this was for historical references though having an audit table is much more useful then any gains we got from soft deleting items.  </end-rant>

Most of the new code doesn't follow this pattern.  But this is our soft delete use case.

We tend to use one of these 2 patterns depending on the schema.

update ui.foobar set active= false, is_deleted = true where pkey = ? 

update module.foobar set active='N' where pkey = ? 

The majority of the time for the UI schema is_deleted + active might as well be one boolean.  Though we have rare occasions where a record is inactive w/o being deleted.  

I did write some helper utilities to help with the conditional when reading such as:

```java
    public static Condition activeEdgeRecordCheck(Table table) {
        Field<String> active = table.field("active", String.class);
        return active.eq("Y");
    }

    public static Condition activeRecordCheck(Table table) {
        Field<Boolean> active = table.field("active", Boolean.class);
        Field<Boolean> is_deleted = table.field("is_deleted", Boolean.class);

        return active.isTrue().and(is_deleted.isFalse());
    }
```

Though I would be curious what you have in mind for this ticket.  I would imagine most people that do implement a soft delete could do it any number of ways and having dslContext.delete() perform a soft delete doesn't quiet feel right either.

**Comment by lukaseder** [comment]
Interesting, thank you very much for sharing, @safaci2000. I was afraid that the soft deletion state might also be distributed across several fields, and even inconsistently so within the same schema.

There are no concrete implementation plans yet. There are essentially three levels of versioning that people often use:

- Simple flag based deletion / active states
- Timestamp based record versions (e.g. Oracle flashback)
- Temporal validity of records (e.g. SQL:2011 temporal validity as implemented (partially) in DB2, Oracle, SQL Server)

I'm sure there's something of great value that jOOQ could implement, but the bigger picture needs to be clear, first.

**Comment by raderio** [comment]
What about querying tables with soft delete?
I mean instead of writing 
```
SELECT id, name FROM users WHERE DELETED=false
```
we can just write
 ```
select(USERS.ID, USERS.TYPE).from(USERS)
```
if we need to show and deleted rows than 
```
Users allUsers = Users.ignoreSoftDelete()
select(allUsers.ID, allUsers.TYPE).from(allUsers)
```

**Comment by lukaseder** [comment]
@raderio This is being investigated through various tasks: 

- https://github.com/jOOQ/jOOQ/issues/8012 *"Override Table.where(Condition) methods in generated tables"*
- https://github.com/jOOQ/jOOQ/issues/1969 *"Add support for views expressed in jOOQ"*
- https://github.com/jOOQ/jOOQ/issues/2682 *"Add support for shared-schema multi-tenancy"*

**Comment by lukaseder** [comment]
@raderio That's the idea right now, yes

**Comment by raderio** [comment]
Nice, waiting for it, thanks.

**Comment by raderio** [comment]
Are there any estimations when this will be available?

**Comment by lukaseder** [comment]
@raderio: This is a very complex change and jOOQ 3.12 is overdue. I cannot make any promises about when this feature will be available.

**Comment by raderio** [comment]
I want to help with this. Can you please point from where to start?

**Comment by lukaseder** [comment]
Thanks for your offer.

While your intentions are understandable, I want to again stress the fact that this is a very complex change. Having this as a first time third party contribution would bind even more resources in terms of reviewing on our side than simply doing it ourselves. We have further explained this rationale in our contribution guidelines: https://github.com/jOOQ/jOOQ/blob/master/CONTRIBUTING.md

I'm afraid, this feature will not see prioritisation for 3.12.

**Comment by raderio** [comment]
This is really needed feature, we found many bugs when someone forgot to add `deteled = FALSE` in the condition.
Hope it will get prioritization for 3.13
Thanks.

**Comment by lukaseder** [comment]
@raderio Thanks for your comment. I understand the importance of this and related features. Now that you phrased it this way, you're not really looking for soft deletion, but for the features referred from this comment: https://github.com/jOOQ/jOOQ/issues/2683#issuecomment-485868561

Do note that already today, you can implement sanity checking through the `VisitListener` SPI where you could for example log a warning if a query that runs on a given table does not also include a given predicate.

If you're using a RDBMS like Oracle or PostgreSQL, you can implement row-level security directly in the database using views, which is much safer than doing the same thing in the client. Some info here:

- Explaining `VisitListener` for this use-case: https://blog.jooq.org/2015/06/17/implementing-client-side-row-level-security-with-jooq/
- Showing an example of implementation of row level security using `SYS_CONTEXT` in Oracle: https://blog.jooq.org/2016/10/20/be-careful-when-emulating-parameterised-views-with-sys_context-in-oracle/

**Comment by lukaseder** [comment]
I'm revisiting this for jOOQ 3.17, in the context of client side computed columns (https://github.com/jOOQ/jOOQ/issues/9879) and their special case "audit columns" (https://github.com/jOOQ/jOOQ/issues/1592). It might not fit in jOOQ 3.17 anymore, but definitely in 3.18.

**Comment by lukaseder** [comment]
Specifically, once this is available, additional audit columns (as in #1592) would be very useful: `DELETED_AT`, `DELETED_BY`

**Comment by lukaseder** [comment]
While it may be enticing to go ahead and implement this now that we have audit columns (#1592) and other seemingly related features, let's wait for another minor release:

1. To make sure the other features are sound, there's still some edge cases that need to be addressed in audit columns (#1592) or client side computed columns (#9879)
2. To make sure this feature is designed well and in accordance with temporal validity emulations (https://github.com/jOOQ/jOOQ/issues/9785)

Specifically the latter bullet is important, as there are a lot of interactions with temporal validity. A soft delete is simply a dumb way of implementing temporal validity, where the `[created_at, deleted_at]` interval is finite and both dates are in the past. The implications for joins and join derived features are significant. For example, an implicit join could either:

- Produce `NULL` if the parent entity has been deleted
- Remove the child entity via `INNER JOIN` if the parent entity has been deleted

jOOQ isn't breaking new grounds here, let's investigate this topic thoroughly as of jOOQ 3.18

**Comment by ryanhamilton** [comment]
+1 for this request.
