### ISSUE TITLE
Add support for COLLATIONS

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2908]
Some database(s) support a `COLLATE` clause to define the character set to be used for string comparison. For example:

``` sql
INNER JOIN T2 ON T1.COL1 = T2.COL1 COLLATE utf8_bin
```

It makes sense to support this natively in jOOQ:

- [x] Add a `org.jooq.Collation` type and a `DSL.collation(String)` constructor: #7120
- [x] Add `Field.collate(Collation)` and `Field.collate(String)`: #7116
- [x] Add `DataType.collate(Collation)`: #7117
- [x] Add `CREATE TABLE` and `ALTER TABLE` support for explicit column collations: #7123
- [x] ~Add `CREATE TABLE` and `ALTER TABLE` support for default table collation: #7118~
- [x] ~Add code generator support: #7121~: Moved to #2908
- [x] ~Add collation information to `InformationSchema` (jooq-meta.xsd): #7122~: Moved to #2908
- [x] ~Add `SET COLLATION` statement support: #7119~: Moved to #2908
- [x] Add parser support for all of the above: #6485 (operator precedence!)
- [x] Update manual

This feature has been seen to be supported by (check = jOOQ supports it for the database):

- [x] HSQLDB
- [x] MariaDB
- [x] MySQL
- [x] Oracle
- [x] PostgreSQL
- [x] SQL Server
- [x] SQLite

----
See also:
https://groups.google.com/d/msg/jooq-user/W_LKypJrI_k/k8zLhvwhhEoJ

**Comment by schaffe** [comment]
+1

**Comment by cbossi** [comment]
Hi Lukas,
is this still intended to be implemented? If yes, is there a planned date/release?

**Comment by lukaseder** [comment]
> is this still intended to be implemented?

Everything that is not closed might be implemented at some point if there's enough traction

> If yes, is there a planned date/release?

Not yet. But you can easily work around the issue:

```java
// Beware of SQL injection risks!
static <T> Field<T> collate(Field<T> field, String collation) {
    return DSL.field("{0} collate {1}", field.getDataType(), field, DSL.sql(collation));}
```

**Comment by cbossi** [comment]
Thanks, looks like a nifty workaround

**Comment by lukaseder** [comment]
@cbossi: It'll always be your workaround of choice, once a feature is not (yet) available in jOOQ.

**Comment by lukaseder** [comment]
OK, this will make it in jOOQ 3.11. See the updated issue description for a list of subtasks
