### ISSUE TITLE
Add support for PostgreSQL RANGE types

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2968]
PostgreSQL supports vendor-specific `RANGE` types. It would be interesting to natively support them as well in jOOQ.

### Tasks

- [x] Add support for the range types documented here, which include: https://www.postgresql.org/docs/current/rangetypes.html
  - [x] `int4range`
  - [x] `int8range`
  - [x] `numrange`
  - [x] `tsrange` (supporting `java.sql` types and `java.time` types, autoconfiguration depending on `<javaTimeTypes/>`)
  - [x] `tstzrange`
  - [x] `daterange` (supporting `java.sql` types and `java.time` types, autoconfiguration depending on `<javaTimeTypes/>`)
- [x] Support arrays of the above range types
- [x] Offer converters and bindings
- [x] Auto-register those converters and bindings to the code generator, if on the classpath

### Out of scope:

- Support multirange types
- Support custom range types
- Add API for functions and operators based on range types

----
See also:
- https://www.postgresql.org/docs/current/rangetypes.html
- http://stackoverflow.com/q/21238441/521799

**Comment by lukaseder** [comment]
@Brzhk : A bit late for you, perhaps, but I've updated the Stack Overflow question with a solution using jOOQ 3.5 `org.jooq.Binding`:
http://stackoverflow.com/a/21241417/521799

`Range` type support will almost work out of the box, then

**Comment by alexpdp7** [comment]
Couldn't one do something hackish to do this without JDBC support using a subquery with bound parameters?

Suppose I had:

    Date from = ...;
    Date to = ...;

and I wanted to do the following pseudo-SQL:

    insert into foo(bar) values tstzrange(from, to);

couldn't I create a select statement:

    var subquery = dslContext.select('tstzrange(:from, :to)').bind('from', from).bind('to', to)

and then:

    dslContext.insertInto('foo', 'bar').values(subquery);

Wouldn't that work even if the JDBC driver support? Is there any way to make it work with some fiddling? I have been unable to :( [actually I would like to use this with insertInto and update's set(Map).

**Comment by lukaseder** [comment]
@alexpdp7 : Thank you very much for your suggestion. I don't think you'll need a subquery for this. A plain SQL `Field` will be much simpler:

```java
DSL.field("tstzrange(?, ?)", Object.class, from, to);
```

Or, as suggested earlier, using a data type binding that takes care of binding a Java range abstraction to a single value.

**Comment by alexpdp7** [comment]
Cool, that works! Gotta learn more jOOQ

**Comment by deinspanjer** [comment]
I am diving into JOOQ on a project, and I had the need for the json and range bindings, so I wrote implementations of them.  I would be willing to contribute the code if someone experienced with committing to JOOQ might be interested in collaborating to see about adding it to the Postgres dialect.

The only thing of note is they are sorta Google-centric.  Using the Range class from guava and the Gson JsonElement type for JSON and JSONB.

**Comment by lightoze** [comment]
@deinspanjer, because of extra dependencies, it probably will be more suitable to create a small separate project (or two) and deploy it to Maven Central. Email me if you need help with that. I have some json/range bindings implemented too.

**Comment by deinspanjer** [comment]
I figured that might be the case, but my Maven-foo isn't high enough to be sure what to do to make sure it could be imported and used in conjunction with the jooq packages.

**Comment by lukaseder** [comment]
I agree with @lightoze. While we are planning on adding an extensions project for these things (https://github.com/jOOQ/jOOQ/issues/5507), we're going to be a bit reluctant of adding "random" dependencies to it. Any `Range` or `Json` implementation would do the job and it wouldn't be "jOOQ-style" to pick one over the others.

When we started publishing to Maven Central, I've found the official guide from Sonatype quite useful: http://central.sonatype.org/pages/ossrh-guide.html

**Comment by lukaseder** [comment]
We'll look into this again via https://github.com/jOOQ/jOOQ/issues/5507, in jOOQ 3.15.

**Comment by lukaseder** [comment]
I should never promise explicit release versions 😅

Anyway. I've just implemented support for `inet` and `cidr` types: https://github.com/jOOQ/jOOQ/issues/2092, `hstore` type support was added in jOOQ 3.15: https://github.com/jOOQ/jOOQ/issues/5507, and array type support for these types has also been added just now: https://github.com/jOOQ/jOOQ/issues/13161.

Besides, these types auto-register themselves as forced types if found on the code generation classpath: https://github.com/jOOQ/jOOQ/issues/10763

I'll use the momentum right now to support range types as well.

**Comment by lukaseder** [comment]
Just saw your commits to pgjdbc related to this, @marschall, thanks a lot for this!

**Comment by lukaseder** [comment]
So, this task will:

- Add support for the range types documented here, which include: https://www.postgresql.org/docs/current/rangetypes.html
  - `int4range`
  - `int8range`
  - `numrange`
  - `tsrange`
  - `tstzrange`
  - `daterange`
- Support arrays of the above range types
- Offer converters and bindings
- Auto-register those converters and bindings to the code generator, if on the classpath

It will *not*:

- Support multirange types
- Add API for functions and operators based on range types

**Comment by lukaseder** [comment]
We'll replicate the discrete range canonicalisation for `int4range`, `int8range`, `daterange`

**Comment by lukaseder** [comment]
Looking great so far. The discrete range types are now supported. The other 3 will follow tomorrow.
