### ISSUE TITLE
Let Table<R> extend SelectField<R>

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4727]
Some SQL dialects (e.g. PostgreSQL) and some ORMs (JPA, Hibernate, [PonyORM](https://docs.ponyorm.com/queries.html)) allow for using table references in some places where column references are expected, most specifically in:
- `SELECT` clauses
- `GROUP BY` clauses (handled separately in #11834)

The semantics of such usage is straight forward and intuitive:
- In `SELECT` clauses, the semantics is that of a nested record (see #2360). All of a table's columns will be selected. If there is a `GROUP BY` clause, then this depends on selecting functionally dependent columns (see #4725).
  - PostgreSQL has native support for this
- In `GROUP BY` clauses, the semantics is that of:
  - grouping by the primary key of the table
  - grouping by all columns of the table, if there is no primary key

### Incompatible changes:

This significant API type hierarchy change seems to be implementable at the cost of only 3 relatively minor backwards incompatible changes:

- [x] `Table.as()` now conflicts with `SelectField.as()`, which has to return  `SelectField` rather than `Field` (seems cleaner but anyway, is a breaking change for some usages): https://github.com/jOOQ/jOOQ/issues/13114
- [x] `Table.getType()` already exists and needs to be renamed incompatibly to `Table.getTableType()`: https://github.com/jOOQ/jOOQ/issues/13115
- [x] `QOM.RowField` is renamed to `QOM.RowAsField` because we cannot re-declare `TableField` the name needs to be `TableAsField`: https://github.com/jOOQ/jOOQ/issues/13116

### Dependencies:

- [x] A few API methods will need to accept `SelectField` instead of `Field`: https://github.com/jOOQ/jOOQ/issues/13123
- [x] Pull up `Field.convert` methods to `SelectField`: https://github.com/jOOQ/jOOQ/issues/13118

### Tests and feature interactions

- [x] Use in ordinary queries
  - [x] `SELECT`
  - [x] `RETURNING`
- [x] Use from implicit join paths
- [x] Combine with ad-hoc converters
- [x] With embeddable records (moved to https://github.com/jOOQ/jOOQ/issues/11975)
- [x] With multisets
  - [x] And multiset agg
  - [x] And ad-hoc converters
- [x] ~With arrays and array agg~ (can't do this yet, see https://github.com/jOOQ/jOOQ/issues/11998)
- [x] With nested records

### More Opportunities:

- Generated functions that accept a `TABLE` reference could profit from this, see: https://stackoverflow.com/q/68137830/521799

---

See also:
- Nested record support: #2360
- Comparing two tables: #4724
- Selecting functionally dependent columns: #4725

**Comment by lukaseder** [comment]
The projection part would profit from this new feature where we can create ad-hoc conversions from `Field<T>` to some `<U>` type: https://github.com/jOOQ/jOOQ/issues/7100

E.g.:

```java
record MyResult(PersonPojo person, BigDecimal duration) {}

ctx.select(CALL.phone().person().convert(mapping(PersonPojo::new)), sum(CALL.DURATION))
   .from(CALL)
   .groupBy(CALL.phone().person())
   .fetch(mapping(MyResult::new));
```

This is really exciting! 😁

**Comment by lukaseder** [comment]
While the `SelectField` part is reasonable to look at in the context of #11812 (`Row[N] <: SelectField`), the `GroupField` part might still be postponed and is thus looked at separately: https://github.com/jOOQ/jOOQ/issues/11834

**Comment by lukaseder** [comment]
Removing the incompatible change tag from this issue, as all the incompatibilities ahve been extracted to external issues:

- https://github.com/jOOQ/jOOQ/issues/13114
- https://github.com/jOOQ/jOOQ/issues/13115
- https://github.com/jOOQ/jOOQ/issues/13116

**Comment by lukaseder** [comment]
A teaser blog post is available here: https://blog.jooq.org/projecting-type-safe-nested-tablerecords-with-jooq-3-17/

**Comment by lukaseder** [comment]
This feature exposes an interesting problem that prevents `Table` reference to be usable in `RETURNING` clauses in MariaDB and Firebird: https://github.com/jOOQ/jOOQ/issues/13148. To be investigated.

**Comment by lukaseder** [comment]
The native support from PostgreSQL doesn't (yet?) work on CockroachDB:
https://github.com/cockroachdb/cockroach/issues/77430

**Comment by lukaseder** [comment]
Nesting a `Table` in a `row()` of unknown degree currently fails: https://github.com/jOOQ/jOOQ/issues/15008
