### ISSUE TITLE
Add additional runtime meta information for indexes

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5181]
Currently, we offer meta information access to constraints only, not to indexes. This would probably be a useful addition for those users who use jOOQ to produce dynamic queries. Having access to index information might help upstream tools to make the right decisions when forming predicates.

We should add:
- [x] `org.jooq.Index` (with a `unique` flag) (implemented through https://github.com/jOOQ/jOOQ/issues/5638)
- [x] `Meta.getIndexes()` (see #6314)
  - [x] DDL interpretation support
  - [x] `InformationSchema` support
- [x] ~`Schema.getIndexes()`~
- [x] `Table.getIndexes()` (implemented in #5638)
- [x] Code generation support (partially implemented in #5638)
- [x] DDL export support (see also #6308)
- [x] Diff support

---

See also:
https://groups.google.com/forum/#!topic/jooq-user/Z7iQDiyxeB8

**Comment by lukaseder** [comment]
DDL interpretation already produces indexes on `Meta::getTables::getIndexes`. But there isn't yet a `Meta.getIndexes()` method, nor is this implemented in the JDBC based implementation.

**Comment by lukaseder** [comment]
Not much was missing, in fact.
