### ISSUE TITLE
Add UpdatableRecord<R>.children(ForeignKey<O, R>): Table<O>

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5216]
It would be useful to extract the existing `fetchChildren()` and `fetchChild()` functionality to a new `UpdatableRecord.children()` method, which returns a `Table<O>` expression, rather than executing the query. This would allow for fetching children with additional predicates, and sorting / limiting them, for example.

```java
ctx.selectFrom(userRecord.children(FK_COMPANY_USER)) // Select<CompanyRecord>
   .where(COMPANY.FLAG)
   .fetchOne();
```

### Subtasks:

- [x] Add `UpdatableRecord<R>.children(ForeignKey<O, R>): Table<O>`
- [x] Add `TableRecord<R>.parent(ForeignKey<R, O>): Table<O>`
- [x] Add `ForeignKey<R, O>.children(O...): Result<R>`
- [x] Add `ForeignKey<R, O>.parents(R...): Result<O>`
- [x] Add `Result<R>.children(ForeignKey<O, R>): Result<O>`
- [x] Add `Result<R>.parents(ForeignKey<R, O>): Result<O>`
- [x] Re-implement the existing `fetch` methods using the new one
- [x] For optimisation purposes, implement a new `InlineDerivedTable`, which generates a derived table if required (e.g. if outer joined), or is inlined to the outer query: https://github.com/jOOQ/jOOQ/issues/10353

---

See also:
https://groups.google.com/forum/#!topic/jooq-user/8V_aN7ZY1Qc

**Comment by mkurz** [comment]
+1
I also need to conditionally fetch children. E.g.: A user manages various companies (1...n). There is always _exactly_ one company which is the default one for a user (boolean field in companies table), which will be choosen when logging into a web app (multi-tenancy...). Now I want to use `fetchChild` to fetch that default company. Not possible right now.

**Comment by lukaseder** [comment]
Perhaps, rather than passing a few optional `QueryPart` instances to the `fetchChild(ForeignKey, ...)` or `fetchChildren(ForeignKey, ...)` methods, in addition to the existing `ForeignKey` reference, it might be more useful to have a `selectFromChildren(ForeignKey)` method that produces a `SelectWhereStep<R>`. This would allow for constructing arbitrary queries, and the degree question could be solved by calling `fetch()`, `fetchOne()`, or `fetchSingle()`, depending on your domain.

But then again, is this:

```java
userRecord.selectFromChildren(FK_COMPANY_USER).where(COMPANY.FLAG).fetchOne();
```

... really that much better than this?

```java
ctx.selectFrom(COMPANY).where(COMPANY.USER_ID.eq(userRecord.getUserId()).and(COMPANY.FLAG).fetchOne();
```

Yes, the line is shorter, but is it useful enough?

**Comment by lukaseder** [comment]
Some further thoughts: There are essentially 3 ways to implement such convenience:

### Additional `UpdatableRecord.fetchChild()` methods

in addition to `fetchChild(ForeignKey)` we could have `fetchChild(ForeignKey, Condition)` and potentially, some others. This is somewhat consistent with `DSLContext.fetch(Table)` and `DSLContext.fetch(Table, Condition)`. We'd have to think about the usual semantics of `fetch()`, `fetchOne()`, `fetchSingle()`, `fetchOptional()` (obviously, someone will want a `fetchOptionalChild()` method!)

Personally, I think this approach doesn't scale well. It didn't scale well on `DSLContext`, it won't scale well here.

### Adding DSL entry points on `UpdatableRecord`

This corresponds to the idea mentioned in my previous comment https://github.com/jOOQ/jOOQ/issues/5216#issuecomment-653154450. We could have DSL entry points from `UpdatableRecord`, such as `Updatablerecord.selectFromChildren()`

This would be completely novel to jOOQ and unidiomatic. It would be very difficult to ensure that we'll find a forward compatible, sound API design, which is discoverable, useful, (eventually) idiomatic, and won't lead to a lot of discussions about what *other*, similar API should be added for additional "convenience"

I think this approach doesn't have a chance

### Creating "views" from `UpdatableRecord`

Rather than taking the `UpdatableRecord` as a starting point, what if we found a way to create a "view" from an `UpdatableRecord`?

The convenience that you and others are really looking for is a quick way to use an `UpdatableRecord` and take:

- Its primary key
- Some foreign key
- Derive the child table for a new query's `FROM` clause
- Derive the FK -> PK predicate

And then, doing things like applying additional `WHERE`, `ORDER BY`, `LIMIT` clauses is nice to have.

So, what about this:

```java
ctx.selectFrom(userRecord.children(FK_COMPANY_USER)) // Select<CompanyRecord>
   .where(COMPANY.FLAG)
   .fetchOne();
```

The existing `rec.fetchChild(FK)` method would just be convenience for `ctx.selectFrom(rec.children(FK)).fetchOne()`

**Comment by lukaseder** [comment]
There might even be potential to generate additional methods on the generated records (see also #4210). #4210 would re-add the `UserRecord.fetchCompanies()` method, whereas this feature request could also add a `UserRecord.companies()` method, which produces a `Table<CompanyRecord>` expression.

**Comment by lukaseder** [comment]
I like how this feature turns out to be. It's very consistent with what we've already had so far, and will also allow to retrofit an unrelated existing feature (`Table.where()`) to use new infrastructure that I've added for this feature (see https://github.com/jOOQ/jOOQ/issues/10353, and https://github.com/jOOQ/jOOQ/issues/10354)

**Comment by lukaseder** [comment]
Code generation will (might) be done separately, via https://github.com/jOOQ/jOOQ/issues/4210
