### ISSUE TITLE
Add Settings.recordDirtyTracking to prefer Record.modified() over Record.touched() for dirty tracking operations

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5394]
A lot of jOOQ users don't like the existing default behaviour of setting all `Record.changed()` flags to true when calling `Record.from()` or similar methods. The wanted behaviour is to set `changed()` only to true if the actual value has changed according to `Objects.equals()`.

jOOQ 3.20 introduces new methods called:

- `Record.touched()` (renamed from `Record.changed()`)
- `Record.modified()` (values are not deep equal)

This is implemented via:

- https://github.com/jOOQ/jOOQ/issues/12494

A new `Settings` should allow for specifying whether:

- [x] `Settings.recordDirtyTracking`

The flags have the enum type `RecordDirtyTracking`:

- [x] `TOUCHED`: The default and current behaviour based on calling setters of a record
- [x] `MODIFIED`: The new behaviour based on modifying values of a record

There are two kinds of operations affected by the above `Settings`:

- [x] `TableRecord.insert()` and `UpdatableRecord.store()`, `update()`, `merge()`. Tracking is based on `Record.configuration()`
- [x] `Q.set(Record)` (with `Q <: DMLQuery`). Tracking is based on the target query, not the record

### Additional tasks

- [x] Add a new section to the manual about dirty tracking
- [x] Review all Javadoc related to `touched()`
- [x] Calling `store()` after `delete()` should re-insert the record
  - [x] `delete()` should reset `original()` values in addition to resetting the `fetched` flag and setting all `touched()` flags to `true`: https://github.com/jOOQ/jOOQ/issues/17243
  - [x] Check also `BatchCRUD`'s `DELETE` operation
- [x] Calling `store()` after `copy()` should re-insert the record

### Tests (non-obvious)

- [x] Formatting tests (The `*` in the text format should depend on the flag)
- [x] #14106

### Caveats

- Without a `Scope` available, it will not be possible to override behaviour, see: https://github.com/jOOQ/jOOQ/issues/5394#issuecomment-590922420. This may be particularly confusing in the case of `query.set(record)`, where the execution may be delayed and in a context with a `Configuration`, but the setting of the record has already happened. It might be possible to refactor the relevant `DMLQuery` implementations in order to delay the call's effects until the query is executed, thus keeping the `Record` instance in the query. This would really complicate the implementations though.

### Possible future work

It is possible, in the future, to also make things explicit with new methods, which allow for specifying the behaviour per operation, e.g.

- `TableRecord.insertTouched()` 
- `TableRecord.insertModified()`
- `InsertSetStep.setTouched(Record)`
- `InsertSetStep.setModified(Record)`

For now, these additional methods seem exaggerated, as people will more likely want to specify the behaviour globally.

---

See also:
- http://stackoverflow.com/q/38003752/521799

And earlier discussions:

- https://groups.google.com/forum/#!topic/jooq-user/KoDpSMN7OzQ
- https://groups.google.com/d/msg/jooq-user/KtYYN8hD_uo/LScpH_ysSWkJ
- https://groups.google.com/forum/#!topic/jooq-user/gtMxNzg02NA
- https://groups.google.com/forum/#!topic/jooq-user/8MBETRVrLCM
- https://groups.google.com/forum/#!topic/jooq-user/52y94BV2upY
- https://groups.google.com/forum/#!topic/jooq-user/gTixth2pAVY
- https://groups.google.com/forum/#!topic/jooq-user/bDN84EDTbhc

**Comment by lukaseder** [comment]
The change of semantics governs how the following operations work:

- [ ] `UpdatableRecord.store()`, `update()`, `insert()` only copy changed values to the respective `INSERT` or `UPDATE` query, leaving the unchanged values untouched.
- [ ] Copying record values to other records is done only for source values that are changed
- [ ] When calling `set(Record)` on an `Insert`, `Update`, or `Merge` statement, only changed values are transferred

At least the following operations will be affected by or may be modified for a semantic shift from `changed` meaning "touched" to "having a modified value":

- [ ] After `UpdatableRecord.delete()`, the entire record is `changed(true)`, such that a subsequent `store()` call will insert the entire record again
- [ ] Changing the primary key means that the entire record is `changed(true)`, because we don't update primary key values by default, we only insert such modifications.
- [ ] When records are created and values are set by jOOQ's internals (e.g. results from `INSERT .. RETURNING` calls), the records get a `changed(false)` call meaning the entire record is "untouched"

There are special cases which lie in between the two semantics

- [ ] When `null` values are loaded from POJOs into records, and there's a known `NOT NULL` constraint on the record. In that case, we already look set the `null` value as not changed (such that `DEFAULT` values can apply). See #2700, #3582
- [ ] When DAOs load POJOs into records, the assumption is that the primary key value is never changed when loading the POJO for an `UPDATE` statement

Operations that will not be affected by the change of semantics:

- [ ] Setting a changed flag to false on a column overwrites the `original()` value for that column and sets it to the current value. See #1995

**Comment by lukaseder** [comment]
A somewhat similar feature is `DSLContext::fetchByExample`, which delegates to `DSL.condition(Record)`. An "example" record produces a condition from all the non-null values. This partially matches what the expectation is here, where only non-null POJO values should be copied into new records. It is not exactly the same, because if the record is not new, there may be pre-existing values in the record, in case of which setting a value to `null` would constitute a change of value.

**Comment by lukaseder** [comment]
The difficult thing with changing the semantics globally is that while some operations have an available `Scope`, and thus `Settings`, others do not. For example, a statically created query could receive an non-attached record like this:

```java
// The record is not attached, so it doesn't have a Settings, meaning that the from() call
// will set the third column to "changed", despite it being null before and after the from() call
TRecord record = new TRecord();
record.from(new TPojo(1, 2, null));

// This call also cannot access any Settings to override the default behaviour of changed(),
// so the third column will have a "null" value being inserted explicitly
Insert insert =
DSL.insertInto(T)
   .set(record)
```

In order to apply `Settings` reasonably, we'd have to make all of the above operations lazy, which is a can of worms I don't want to open for this minor feature.

Besides, even if the operations are lazy, the behaviour of `toString()` on `Scope`-free objects would resemble the current behaviour, whereas that of `DSLContext.render()` would be different. There are probably many other, similarly confusing differences in this already quite confusing area.

**Comment by lukaseder** [comment]
For context: A non representative Twitter poll shows that the existing behaviour of *Record* types is desireable:
https://twitter.com/lukaseder/status/1232327845969629185

Setting a value to something means the intent is for that action to have a side effect in the generated query. Good reasons are:

1) that's what jOOQ is already doing
2) in SQL, NULL and DEFAULT are not the same
3) in the presence of plan caches, you don't want too many different SQL strings and hard parses (at least you want control)

This issue here is about loading POJOs / DTOs into records with `Record::from` and similar methods. Record behaviour itself will not be modified.

**Comment by lukaseder** [comment]
Note, some feedback about the expected defaults for inserting/updating unchanged records can be seen here:
https://twitter.com/lukaseder/status/1281600147575775232

**Comment by lukaseder** [comment]
This issue has grown very popular. I'll look into this for jOOQ 3.20. Will definitely implement this prerequisite first:

- https://github.com/jOOQ/jOOQ/issues/12494

Irrespective of the change (or configurability) of behaviour here, having separate flags available for "changed" ("touched") and "modified" is already useful.

**Comment by lukaseder** [comment]
The relevant section of the manual is this:

- https://www.jooq.org/doc/dev/manual/sql-building/dsl-context/custom-settings/settings-dirty-tracking/

This feature is implemented in jOOQ 3.20.
