### ISSUE TITLE
Add support for the SQL Standard WITH ORDINALITY clause

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5799]
This clause generates an ordinal (i.e. a `ROW_NUMBER()`) when unnesting arrays or selecting from table valued functions. Quite useful.

If not available, this can probably be emulated by wrapping the table in a derived table and calculating `ROW_NUMBER()` explicitly, e.g. in Oracle:

```sql
SELECT * FROM (
  SELECT column_value, row_number() over(ORDER BY NULL) ordinality
  FROM TABLE(u_string_array('a','b','c'))
)
```

Other dialects may support this as a different syntax, e.g. BigQuery `WITH OFFSET` (0 based instead of 1 based): https://cloud.google.com/bigquery/docs/reference/standard-sql/arrays

### Tasks

- [x] ~Add `TableWithOrdinalityStep<R>`~: See comment below: https://github.com/jOOQ/jOOQ/issues/5799#issuecomment-1352690493. It doesn't make sense to limit ourselves to the SQL standard or PostgreSQL's interpretation, when in principle, any type of table can have a `WITH ORDINALITY` clause.
- [x] Add `QOM.TableWithOrdinality`
- [x] Add the implementation of the `QOM` type
- [x] Implementation support:
  - [x] Let `DSL::table` and `DSL::unnest` support `withOrdinality` (standard SQL feature). Implementations include:
    - [x] `ArrayOfValues`
    - [x] `ArrayTable`
  - [x] Let `DSL::values` support `withOrdinality` (jOOQ feature), see also: https://github.com/jOOQ/jOOQ/issues/14409
  - [x] Let all generated table valued function support `withOrdinality` (PostgreSQL feature). Implementations include:
    - [x] `GenerateSeries`
    - [x] `FunctionTable`
  - [x] Other implementations to be listed
  - [x] Improved emulation for `UNNEST` or `VALUES`, where we can append the `ORDINALITY` directly in the expression, rather than calculating it later. Will be done separately: https://github.com/jOOQ/jOOQ/issues/14414
- [x] Support the syntax in the parser
- [x] Tests
  - [x] Add a test for each of the above implementation in each dialect
  - [x] Combine `WITH ORDINALITY` clause with aliases
    - [x] Table only
    - [x] Table and derived column list
  - [x] Test unnesting arrays of UDTs (PostgreSQL)
  - [x] Test unnesting table types (Oracle)
- [x] Documentation
  - [x] Indicate that the `ROW_NUMBER()` based emulation may or may not work on a given dialect, depending on whether `ROW_NUMBER() OVER (ORDER BY NULL)` can be implemented in a sort-stable way.

**Comment by katzyn** [comment]
The Standard specifies this clause only for the collection derived table (the `UNNEST` function). Db2 for z/OS, HSQLDB, and H2 also support this clause in the `UNNEST`; possibly some others too.

But PostgreSQL also has such clause for its table functions.

**Comment by lukaseder** [comment]
Thanks for the comment, @katzyn. Indeed, in the meantime, I've discovered other implementations than that of PostgreSQL.

**Comment by lukaseder** [comment]
I'm looking into this now. I think there will be numerous other fixes that have to be implemented first. This `UNNEST` support is very old, and hasn't followed up with all the various internal improvements to the `AbstractTable` hierarchy, recently. E.g. the auto aliasing feature hasn't been implemented yet.

**Comment by lukaseder** [comment]
This issue was discovered, which will be fixed as part of this new `WITH ORDINALITY` feature: https://github.com/jOOQ/jOOQ/issues/14406

**Comment by lukaseder** [comment]
H2 supports `WITH ORDINALITY` only for `UNNEST()`, not for `TABLE()`, which jOOQ is still generating. Guess we'll change that.

**Comment by lukaseder** [comment]
It appears that CockroachDB supports many more types of table expressions which can have a `withOrdinality()` clause:
https://www.cockroachlabs.com/docs/stable/table-expressions.html

<img width="941" alt="image" src="https://user-images.githubusercontent.com/734593/207805478-b0cd27c9-f397-4b4a-bc3d-c08cc20e7f4f.png">

For jOOQ, this probably means that the `withOrdinality()` method should be moved to `Table`, and not be `UNNEST()` or TVF specific

**Comment by lukaseder** [comment]
The current implementation works well on most dialects, but right now, there's a regression for the Oracle dialect, in case anyone is using the next 3.18.0-SNASPHOT build:

```
org.jooq.exception.DataAccessException: SQL [select "array_table"."ID", "array_table"."TITLE" from (select null "COLUMN_VALUE" from DUAL where 1 = 0 union all select * from table (?) "array_table") "array_table" -- SQL rendered with a free trial version of jOOQ 3.18.0-SNAPSHOT]; ORA-01789: Abfrageblock hat falsche Anzahl an Ergebnisspalten

	at org.jooq_3.18.0-SNAPSHOT.ORACLE21C.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3406)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:746)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:357)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:301)
	at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:322)
	at org.jooq.impl.SelectImpl.fetchLazyNonAutoClosing(SelectImpl.java:2861)
	at org.jooq.impl.ResultQueryTrait.collect(ResultQueryTrait.java:360)
	at org.jooq.impl.ResultQueryTrait.fetch(ResultQueryTrait.java:392)
	at org.jooq.test.OracleTest.testOracleTableTypes(OracleTest.java:1322)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.sql.SQLSyntaxErrorException: ORA-01789: Abfrageblock hat falsche Anzahl an Ergebnisspalten

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:629)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:563)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1230)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:771)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:298)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:511)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:162)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:1009)
	at oracle.jdbc.driver.OracleStatement.prepareDefineBufferAndExecute(OracleStatement.java:1270)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1148)
	at oracle.jdbc.driver.OracleStatement.executeSQLSelect(OracleStatement.java:1660)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1469)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3760)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:4135)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1013)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4625)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:236)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:343)
	... 38 more
Caused by: Error : 1789, Position : 55, Sql = select "array_table"."ID", "array_table"."TITLE" from (select null "COLUMN_VALUE" from DUAL where 1 = 0 union all select * from table (:1 ) "array_table") "array_table" -- SQL rendered with a free trial version of jOOQ 3.18.0-SNAPSHOT, OriginalSql = select "array_table"."ID", "array_table"."TITLE" from (select null "COLUMN_VALUE" from DUAL where 1 = 0 union all select * from table (?) "array_table") "array_table" -- SQL rendered with a free trial version of jOOQ 3.18.0-SNAPSHOT, Error Msg = ORA-01789: Abfrageblock hat falsche Anzahl an Ergebnisspalten

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:636)
	... 57 more
```

The problem is that the `AutoAlias` refactorings seem to have introduced a forced `"COLUMN_VALUE"` derived column list, irrespective of the number of columns.

**Comment by lukaseder** [comment]
This also affects calling pipelined functions, for example.

**Comment by lukaseder** [comment]
OK, it seems the Oracle regression was easy to fix. No snapshot build will be affected.

**Comment by lukaseder** [comment]
All tests pass. Will wrap this up. Documentation here:
https://www.jooq.org/doc/dev/manual/sql-building/table-expressions/with-ordinality/

**Comment by lukaseder** [comment]
An open question to be solved in the future is whether the `WithOrdinality` table's `fieldsRow()` references fully qualified or only table-qualified columns. Derived table based emulations can't work with fully qualified columns, which is why currently, we don't fully qualify its columns...

Other table wrappers do not have this problem, because they don't have derived table based emulations (yet).
