### ISSUE TITLE
Emulate Teradata's QUALIFY clause for window function filtering

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5810]
Teradata supports the `QUALIFY` clause, which allows for filtering on window function results. We could support that clause after the `WINDOW` clause, lexically, and emulate it for all databases by wrapping the logically preceding clauses in a derived table. Given that we already emulate the `WINDOW` clause for all databases except PostgreSQL and Sybase SQL Anywhere (which support them natively), this could give window function usage in jOOQ another boost.

### Tasks

- [x] Add a `Settings.transformQualify` flag (moved to #9767)
- [x] Log a warning in the OSS edition, if the `QUALIFY` emulation needs to be triggered
- [x] Collect all window functions from `QUALIFY`, `SELECT`, `ORDER BY` clauses if `QUALIFY` is present, but not supported
- [x] Creating a derived table with all clauses before `QUALIFY` (`FROM`, `WHERE`, `GROUP BY`, `HAVING`, `WINDOW`), and the original projection as well as the above window functions
- [x] Filter on the `QUALIFY` clause from outside of the derived table, replacing all qualifications with the one from the derived table
- [x] Make sure only window functions are moved around, not aggregate functions
- [x] Simplification for cases where `QUALIFY` does not contain window functions (in case of which, its contents can be moved into `HAVING`
- [x] Alias all columns in the derived table to avoid ambiguities
  - [x] But only if ambiguities are possible (check the `FROM` clause). Otherwise, project `*` (make sure this works: https://github.com/jOOQ/jOOQ/issues/10307)
- [x] Move the entire `QUALIFY` clause into the projection as a `BOOLEAN` column, and filtering by that directly, rather than by individual window functions

----
See also:
http://jrandrews.net/the-joy-of-qualify/

**Comment by lukaseder** [comment]
Given the promising results of transforming `ROWNUM` and the first draft of transforming `DISTINCT ON` (https://github.com/jOOQ/jOOQ/issues/3564), I'll try to tackle this emulation again for 3.14. `QUALIFY` would be an awesome feature to offer to all RDBMS supporting window functions!

**Comment by lukaseder** [comment]
This needs more thought than #3564, because we have to transform the `QUALIFY` condition in order to extract and replace all predicates containing window functions

**Comment by lukaseder** [comment]
The implementation will be done in the context of the new SQL transformations framework of the jOOQ Professional and Enterprise Edition (#9767)

**Comment by lukaseder** [comment]
Obviously, if an OSS dialect has native support (e.g. H2), this will continue to work.

**Comment by lukaseder** [comment]
This is implemented in jOOQ 3.15.0. A blog post is coming up soon to show how this works.

**Comment by lukaseder** [comment]
A few edge cases still need to be addressed. Will update the issue description

**Comment by lukaseder** [comment]
Remaining work moved to https://github.com/jOOQ/jOOQ/issues/12098
