### ISSUE TITLE
Various parser bugs / missing features

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5955]
Some features were not yet supported in the jOOQ 3.9 parser. We'll fix them all in this single issue in order not to create too many issues. Here's the list of fixed things (incomplete, because GitHub screwed up this list with their eventual consistency :( ):

### SELECT features

- [x] `SELECT * INTO table` (SQL Server feature)
- [x] `ORDER SIBLINGS BY` syntax support
- [x] `FOR UPDATE` support
- [x] `LIMIT` is parsed as bind variable
- [x] Some keywords after table references don't work (e.g. `select * from t for update`)
- [x] Derived column lists (`t AS t1(a, b)`)
- [x] Ingres `OFFSET m FETCH NEXT n ROWS ONLY` variant (no `ROWS` after `OFFSET`)
- [x] Informix `SKIP m FIRST n` syntax (for `LIMIT`)
- [x] `OFFSET` only, without `LIMIT`
- [x] `DISTINCT ON`
- [x] Reject column named "FROM": `SELECT FROM a` (where `FROM could be a column reference and `a` its alias) or `SELECT FROM a FROM x`
reserved syntax.
- [x] `WITH TIES` (both standard and T-SQL syntax)
- [x] `WITH` for `SELECT`
- [x] `WITH RECURSIVE`
- [x] `WITH` with unquoted column names (see #6021 and #6022)
- [x] `WITH` without column lists (e.g. `with a as (select 0 as x) select * from a`)
- [x] Set operation (`UNION`, `INTERSECT`, `EXCEPT`) precedence is incorrect (`INTERSECT` has a higher precedence)

### Other statements

- [x] `CREATE UNIQUE INDEX`
- [x] `CREATE SEQUENCE`
- [x] `ALTER SEQUENCE`
- [x] `CREATE [ GLOBAL ] TEMPORARY TABLE`
- [x] `INSERT .. ON CONFLICT`
- [x] `INSERT .. ON DUPLICATE KEY IGNORE`
- [x] `{ INSERT | UPDATE | DELETE } RETURNING`
- [x] `INSERT` without column list, e.g. `INSERT INTO t VALUES (1, 2, 3)`
- [x] `CREATE TABLE`: Foreign key specification `ON DELETE` and `ON UPDATE` actions
- [x] `CREATE TEMPORARY TABLE`: `ON COMMIT` clause
- [x] `ALTER TABLE`: Foreign key specification `ON DELETE` and `ON UPDATE` actions
https://github.com/jOOQ/jOOQ/issues/5318)
- [x] `ALTER TABLE`: Modify columns

### Table expressions

- [x] `JOIN .. USING`
- [x] `OUTER JOIN .. PARTITION BY`
- [x] `CROSS APPLY` and `OUTER APPLY`
- [x] `LEFT { SEMI | ANTI } JOIN`
- [x] MySQL `STRAIGHT_JOIN`
- [x] Oracle flashback query
- [x] `VALUES` constructor (in `FROM` clause)
- [x] `VALUES` constructor (as top-level query)
- [x] `PIVOT`

### Column expressions (and predicates)

- [x] `ARRAY` constructor (by enumeration)
- [x] `MODE` aggregate function
- [x] `MEDIAN` aggregate function
- [x] Unary `+` and `-` operators
- [x] Exponentiation operator
- [x] `ROW` constructors
- [x] `ROW` constructors (Oracle doubly parenthesised)
- [x] `OVERLAPS`
- [x] PostgreSQL cast syntax
- [x] `KEEP`
- [x] `GROUP_CONCAT` aggregate function
- [x] `LISTAGG` aggregate function
- [x] Sequence `currval` and `nextval` expressions

### Literals and data types

- [x] Oracle quoted string literals (e.g. `q'[ ... ]'`). See also https://github.com/jOOQ/jOOQ/issues/5587
- [x] Binary literals
- [x] All data types

### Predicates

- [x] Large `IN` lists
- [x] Boolean column expressions (e.g. `SELECT EXISTS (SELECT 1)`)
- [x] `DISTINCT` predicate
- [x] MySQL `NOT DISTINCT` predicate (`<=>`)

### Functions

- [x] Inverse distribution function support `PERCENTILE_CONT` and `PERCENTILE_DISC`
- [x] Hypothetical set functions `RANK`, `DENSE_RANK`, `PRECENT_RANK`, `CUME_DIST`
- [x] Arithmetic with aggregate functions
- [x] Parse function names only if they're followed by `(`

### Language features

- [x] Multi line comments
- [x] Single line comments
- [x] Quoted identifiers are not recognised, e.g. `1 AS "a"`
- [x] Unquoted names shouldn't be quoted  (depends on #5993 (specifying (un)quotedName) and #5996 (passing (un)quotedName to `as()` methods)
- [x] Quoted qualified identifiers (such as `"a"."b"`)
- [x] Support trailing `;` in `parse()` (currently returns a `null;` statement)

### New features
