### ISSUE TITLE
Add Setting to auto-inline all bind variables that participate in predicates on certain fields

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5970]
When using unions with discriminator columns as such:

```sql
CREATE VIEW v AS (
  SELECT 'A' AS discriminator, id
  FROM t_book
  UNION ALL
  SELECT 'B' AS discriminator, id
  FROM t_author
);
```

... then a typical pattern is to query this view including a predicate on the discriminator column:

```sql
SELECT *
FROM v
WHERE discriminator = 'A'
```

"Smarter" databases like SQL Server or Oracle will push down the predicate into the `UNION ALL` and detect that not all subqueries are really necessary. For instance in Oracle runs the dummy `NULL IS NOT NULL` predicate to prevent the execution of the second subquery:

**Oracle:**

![image](https://cloud.githubusercontent.com/assets/734593/23948449/4c7f1036-0983-11e7-812e-5e33c5d7d0a3.png)

**SQL Server:**

![image](https://cloud.githubusercontent.com/assets/734593/23949050/ec94b3bc-0985-11e7-992e-01677b04f637.png)

**PostgreSQL:**

![image](https://cloud.githubusercontent.com/assets/734593/23949198/a1893446-0986-11e7-9be2-e9a19881633a.png)

When using bind variables, however:

```sql
SELECT *
FROM v
WHERE discriminator = :B1
```

Then, the plan is far less optimal:

**Oracle:**

![image](https://cloud.githubusercontent.com/assets/734593/23948481/70244146-0983-11e7-9d2a-699d0f1a8be1.png)

**SQL Server:**

![image](https://cloud.githubusercontent.com/assets/734593/23949077/0bd303a0-0986-11e7-8485-bd27f10cee5b.png)

**PostgreSQL:**

![image](https://cloud.githubusercontent.com/assets/734593/23949180/9579e308-0986-11e7-932d-bf25e133ff2d.png)

We might be able to depend on bind peeking or Oracle 12c adaptive execution plans, but why not just inline the discriminator variable to force / optimise the execution plan on a per-descriminator basis?

Users can do this manually, but it would be nice to be able to register a list of columns (or regular expression matching columns) for which all predicates would inline their bind variables automatically, such that developers won't forget this.

Also, we could discover some cases (e.g. enum types with few values, or gather statistics about distinct values per column) where the flag could be enabled automatically, or at least users would be alerted: https://twitter.com/stelling_simon/status/1392811243916890113

### Tasks

- [x] Add `Settings.transformInlineBindValuesForFieldComparisons` to turn on the feature (turned off by default, because the traversal is costly)
- [x] Add a `TransformProvider` SPI which will contain this SPI and future SQL transformation SPIs (to have only one extension point)
- [x] Add `TransformProvider::inlineBindValuesForFieldComparisons`
- [x] Implementations for
  - [x] `Eq`
  - [x] `Ne`
  - [x] `Gt`
  - [x] `Ge`
  - [x] `Lt`
  - [x] `Le`
  - [x] `InList`
  - [x] `NotInList`

Feature interactions:

- The batch and other `bind()` APIs are unaware of this transformation. Users will have to adapt their code accordingly

Explicitly excluded are:

- Row comparisons
- Comparisons with scalar subqueries
- Comparisons with quantified selects
- Comparisons with embeddables
- MULTISET comparisons

**Comment by lukaseder** [comment]
A simple workaround is to use a `Binding`:

```java
public class BindingTest extends AbstractTest {

    static class AlwaysInlineIntegerBinding implements Binding<Integer, Integer> {

        final Binding<?, Integer> delegate = INTEGER.getBinding();

        @Override
        public Converter<Integer, Integer> converter() {
            return Converters.identity(Integer.class);
        }

        @Override
        public void sql(BindingSQLContext<Integer> ctx) throws SQLException {
            ctx.render().visit(inline(ctx.value()));
        }

        @Override
        public void register(BindingRegisterContext<Integer> ctx) throws SQLException {
            delegate.register(ctx);
        }

        @Override
        public void set(BindingSetStatementContext<Integer> ctx) throws SQLException {
            delegate.set(ctx);
        }

        @Override
        public void set(BindingSetSQLOutputContext<Integer> ctx) throws SQLException {
            delegate.set(ctx);
        }

        @Override
        public void get(BindingGetResultSetContext<Integer> ctx) throws SQLException {
            delegate.get(ctx);
        }

        @Override
        public void get(BindingGetStatementContext<Integer> ctx) throws SQLException {
            delegate.get(ctx);
        }

        @Override
        public void get(BindingGetSQLInputContext<Integer> ctx) throws SQLException {
            delegate.get(ctx);
        }
    }

    @Test
    public void testAlwaysInlineBinding() {
        DSLContext ctx = DSL.using(DEFAULT);
        DataType<Integer> t = INTEGER.asConvertedDataType(new AlwaysInlineIntegerBinding());

        Field<Integer> i = field("i", INTEGER);
        Field<Integer> j = field("j", t);
        Param<Integer> a = val(1);
        Param<Integer> b = val(1, INTEGER.asConvertedDataType(new AlwaysInlineIntegerBinding()));

        assertEquals("?", ctx.render(a));
        assertEquals("1", ctx.renderInlined(a));
        assertEquals("1", ctx.render(b));
        assertEquals("1", ctx.renderInlined(b));

        assertEquals("i = ?", ctx.render(i.eq(a)));
        assertEquals("i = 1", ctx.renderInlined(i.eq(a)));
        assertEquals("i = 1", ctx.render(i.eq(b)));
        assertEquals("i = 1", ctx.renderInlined(i.eq(b)));
        assertEquals("i = ?", ctx.render(i.eq(1)));
        assertEquals("i = 1", ctx.renderInlined(i.eq(1)));

        assertEquals("j = 1", ctx.render(j.eq(a)));
        assertEquals("j = 1", ctx.renderInlined(j.eq(a)));
        assertEquals("j = 1", ctx.render(j.eq(b)));
        assertEquals("j = 1", ctx.renderInlined(j.eq(b)));
        assertEquals("j = 1", ctx.render(j.eq(1)));
        assertEquals("j = 1", ctx.renderInlined(j.eq(1)));
    }
}
```

Or, with https://github.com/jOOQ/jOOQ/issues/11964 even better:

```java
static class AlwaysInlineBinding<T> extends DefaultBinding<T, T> {
    public AlwaysInlineBinding(DataType<T> type) {
        super(DefaultBinding.binding(type));
    }

    @Override
    public void sql(BindingSQLContext<T> ctx) throws SQLException {
        ctx.render().visit(inline(ctx.value()));
    }
}
```

**Comment by lukaseder** [comment]
See also: https://blog.jooq.org/2021/06/04/how-to-prevent-execution-plan-troubles-when-querying-skewed-data-with-jooq/

**Comment by lukaseder** [comment]
With the workaround in mind, I think I'll postpone implementing this for a while. It adds complexity, when all the tools to implement this on the user side are already there.

**Comment by lukaseder** [comment]
I've implemented this now. While the workaround is viable too, and can still be added, this feature is a pure runtime feature, not a codegen time feature. So it can be active only for a certain part of the application, not for all queries.

The feature description has been updated, and a manual section will be available shortly.
