### ISSUE TITLE
Several DB2 fixes

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6119]
- [x] #6117 DB2 doesn't support qualified column references in FOR UPDATE OF
- [x] #6118 RESTRICT is a mandatory keyword in DB2's DROP SCHEMA command
- [ ] ~~#6120 Add support for DB2 RENAME INDEX statement~~
- [ ] ~~#6121 Add support for DB2 RENAME TABLE statement~~
- [ ] ~~#6122 Fix DDL Support annotations for DB2~~
- [x] #6127 DELETE RETURNING must be emulated on DB2 with OLD TABLE() not FINAL TABLE()
