### ISSUE TITLE
Add SQLDialect.JAVA to generate Java code from a SQL statement

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6277]
This was already implemented in the past by the https://github.com/sqlparser/sql2jooq third party module, but it suffered from several flaws:

1. It didn't produce very good jOOQ code
2. It worked only for MySQL and PostgreSQL
3. It depended on a third party parser (by Gudu Soft), which was proprietary and not under our control
4. It was hard to use

Yet, clearly, people wanted this tool - perhaps not as a standalone library but as a website. We should offer this feature ourselves, given that we now have a full-fledged parser in jOOQ itself, which can generate this kind of code.

### Tasks for 3.15

- [x] Implement experimental support for `SELECT`
  - [x] ~Some API could be discovered using reflection (e.g. `DSL.substring(Field, int)` vs `DSL.substring(Field, Field)`)~
  - [x] Better than using reflection, we re-use our meta model for the generated DSL parts.
  - [x] Test and document interaction with existing flags
    - [x] Transformations would be useful here, too - e.g. `ROWNUM` to `limit()`
    - [x] Some stylistic options work as well, e.g. `INNER` or `OUTER` keyword
- [x] Offer the dialect on https://www.jooq.org/translate
  - [x] Disable the flags that aren't supported with this dialect (e.g. transformations)
    - [x] Keywords
    - [x] `AS` keyword can't be omitted
  - [x] Add `/translate` specific hints
    - [x] Append `fetch()` or `execute()`
    - [x] Document import assumptions
- [x] Add error messages hinting at the state of progress and the known issues: https://github.com/jOOQ/jOOQ/issues/11911

### Future work (tracked as https://github.com/jOOQ/jOOQ/issues/11911)

- Pull up CTE, derived tables, and aliases to be declared before the query itself
- Offer support for other statements than `SELECT`
- Offer the feature as a special build only (if the amount of extra byte code is excessive)
- Implement also `SQLDialect.SCALA` and `SQLDialect.KOTLIN`

----
See also:
- https://groups.google.com/forum/#!topic/jooq-user/eY7ukm9Vdyc
- https://github.com/jOOQ/jOOQ/issues/10087

**Comment by KaRkY** [comment]
I would recommend to release a tool like this as a jar. I can see myself using a thing like this in a maven plugin. To me SQL is tidier than java code.

I imagine a tool like that would work like this:
 * SQL file would equal a single class
 * every SQL inside a file would produce a method
 * return type of this methods would be Query or ResultQuery
 * DSLContext would be constructor injected

**Comment by lukaseder** [comment]
@KaRkY Thanks for joining the conversation. Those are some interesting ideas, indeed. So, essentially, there could be some sort of SQLJ-style syntax where the SQL language is enriched with:

- Bind variable capabilities (e.g. named parameters such as `:param1`) which map to actual method parameters
- Fetching capabilities (e.g. PL/SQL style `SELECT .. INTO` or `SELECT .. BULK COLLECT INTO`, or simply `SELECT` in case of which the result will just be returned from the generated method.

That could be really interesting, indeed!

**Comment by KaRkY** [comment]
Yes something like that also parameters could be specified as optional  (`:?param1`) so search queries could be made easier. For naming methods I was thinking there could be simple syntax with SQL comments I imagine an SQL file written like this:

```
-- name: selectById
-- selects user
select *
from users
where id = :id;

-- name: selectByName
-- selects user
select *
from users
where name = :name;

-- name: searchUsers
-- selects user
select *
from users
where 
  name like :?name
  or email like :?email;
```
And it would produce a class something like this:
```
public class UsersRepository{
  private DSLContext context;
  public UsersRepository(DSLContext context) {
    this.context = context;
  }

  public Query<...> selectById(Integer id){
    ...
  }

  public Query<...> selectByName(String name){
    ...
  }

  public Query<...> searchUsers(String name, String email){
    ...
  }
}
```

The benefit of SQL file like this is that all SQL editors can edit it and DBA can tweak SQL-s inside without problems. For more advanced cases I have no idea how this would work like batching.

It is funny that if this gets implemented we would come full circle as SQL could be written as SQL again.

**Comment by lukaseder** [comment]
> also parameters could be specified as optional

What do you mean by this? There's no such thing in static SQL as an optional parameter... Do you mean that there's some implied dynamic SQL going on in the absence of a specific parameter? But how would that work?

> And it would produce a class something like this

Yes, that's how I understood you, except for the fact that these methods won't return a `Query` but a `Result<...>`.

> It is funny that if this gets implemented we would come full circle as SQL could be written as SQL again.

Yes indeed. However, it's important not to have too high expectations from this feature. At some point, parsing SQL will "break", e.g. if a vendor-specific feature like `MODEL` or `MATCH_RECOGNIZE` or even `UNPIVOT` is used, which jOOQ currently doesn't support. Sure, that query could then just be copied into the method verbatim...

**Comment by KaRkY** [comment]
>What do you mean by this? There's no such thing in static SQL as an optional parameter... Do you mean that there's some implied dynamic SQL going on in the absence of a specific parameter? But how would that work?

Yes I was thinking about dynamic SQL but now when I think about it I do not think it is a good idea. Simple cases are not so hard to cover but what about sorting etc. Maybe after first release of basic features.

Yes I understand and I think if basic CRUD and things like recursive SQL are covered is enough for 90% of cases and rest can still be done by hand.

I must say you've done a superb job with JOOQ.

**Comment by lukaseder** [comment]
> Yes I was thinking about dynamic SQL but now when I think about it I do not think it is a good idea. Simple cases are not so hard to cover but what about sorting etc. Maybe after first release of basic features.

There are other tools out there, including e.g. MyBatis which implement a templating language for branching and loops. If we parse SQL strings, we might as well support such additional features, e.g. to help people migrate from MyBatis to jOOQ.

> Yes I understand and I think if basic CRUD and things like recursive SQL are covered is enough for 90% of cases and rest can still be done by hand.

I'd say 99.5%. jOOQ goes far beyond basic. I just wanted to list a couple of extreme examples :)

> I must say you've done a superb job with JOOQ.

Thanks for your nice words

**Comment by lukaseder** [comment]
For the record, the ideas mentiond by @KaRkY will be immplemented in jOOQ 3.15 as "synthetic views", "synthetic table valued functions": https://github.com/jOOQ/jOOQ/issues/11054, which can in turn be used in "synthetic daos" (name may change), which essentially map method parameters to bind variables and result sets to POJOs for specific SQL statements: https://github.com/jOOQ/jOOQ/issues/11071

**Comment by lukaseder** [comment]
I'm having a go at prototyping this. Seems simple to get promising results, but I can't say I like how this entirely new use-case produces code all over the code base. Perhaps this is a good opportunity to review the new query object model and if we should separate the object model from the visit/accept algorithm, using an actual visitor pattern instead.

**Comment by lukaseder** [comment]
On the other hand, all of the tools work out of the box, e.g. formatting. This code is generated:

```java
assertEquals(expected, render(
    select(
      T_AUTHOR.ID,
      row(
        T_AUTHOR.FIRST_NAME,
        T_AUTHOR.LAST_NAME,
        array(
          select(row(T_BOOK.ID, T_BOOK.TITLE))
          .from(T_BOOK)
          .where(T_BOOK.AUTHOR_ID.eq(T_AUTHOR.ID))
          .orderBy(T_BOOK.ID)
        ),
        array(
          select(row(T_BOOK.ID, T_BOOK.TITLE))
          .from(T_BOOK)
          .where(T_BOOK.AUTHOR_ID.eq(T_AUTHOR.ID))
          .orderBy(T_BOOK.ID)
        )
      )
    )
    .from(T_AUTHOR)
    .orderBy(T_AUTHOR.ID)
));
```

This seems *very* promising!

**Comment by lukaseder** [comment]
Well. It's not that much different from having yet another dialect, after all - with the exception that almost every `QueryPart` requires special attention.

**Comment by lukaseder** [comment]
A realistic roadmap to achieve something useful for jOOQ 3.15 would be to offer an experimental implementation for `SELECT` only, and then offer other DML, DDL, and procedural support in jOOQ 3.16

**Comment by lukaseder** [comment]
One option would be to offer the feature in a special "tooling" build only. That way, all the extra byte code could be avoided in ordinary distributions

**Comment by rossetti** [comment]
It is interesting to see that there may be a roadmap for this. To me, I am more interested in the DDL -> jooq java use case. Capturing DDL from some database specific SQL syntax into agnostic jooq DDL statements, would facilitate java code base migration.  The "script" would be in the jooq DDL java code.  It could be executed on any supported platform.  DB platforms will already make creation scripts from an existing database, but they tend to be specific to that platform.  Writing the script out into a jooq based DDL java code would allow the java code to recreate the database on any supported SQL dialect.

**Comment by lukaseder** [comment]
Thanks, @rossetti. You can already do that today using the parser and/or parsing connection (https://www.jooq.org/doc/latest/manual/sql-execution/parsing-connection/), have you tried it?

Creating jOOQ API DDL scripts might be interesting as a second step of this issue (e.g. in jOOQ 3.16), but it doesn't seem to be strictly necessary for your use-case. The biggest value proposition for now is to offer SQL-to-Java translation support for `SELECT` and other DML statements.

**Comment by lukaseder** [comment]
Hah. So, I've been working on this for the past 2 days and it is still *very* promising (tough nuts still to crack: CTE, derived tables, and aliasing).

In order to test this, we'll translate all integration test queries to Java, print the output into a JUnit test file, which must compile obviously, and re-generate all the printed queries to see if the output is about the same as the original query. This will never reach 100%, but we can still reach decent quality with this approach.

**Comment by rossetti** [comment]
> Thanks, @rossetti. You can already do that today using the parser and/or parsing connection (https://www.jooq.org/doc/latest/manual/sql-execution/parsing-connection/), have you tried it?
> 
> Creating jOOQ API DDL scripts might be interesting as a second step of this issue (e.g. in jOOQ 3.16), but it doesn't seem to be strictly necessary for your use-case. The biggest value proposition for now is to offer SQL-to-Java translation support for `SELECT` and other DML statements.

I have not tried the parsing connection.  I'm going to restate my understanding of what this can do. It sounds like this will take in SQL in one dialect, parse it, and spit it out in another dialect.  SQL to SQL.  Is that correct?  I was hoping for SQL to jooq java statements.  I want to "persist" the SQL DDL script in jooQ java statements.  I realize that I can obviously write the jooq to start with, but the use case was to parse the SQL DDL to java.  Perhaps the parsing connection uses jooq as the intermediary in the SQL to SQL conversion. If so, I wan access to the intermediate jooq java generated code.

**Comment by lukaseder** [comment]
> Is that correct?

Yes

> I was hoping for SQL to jooq

Your idea and use-case is understood, but since you don't have this yet, and you won't get it for jOOQ 3.15 yet, I thought I might as well offer a workaround.

**Comment by rossetti** [comment]
> > Is that correct?
> 
> Yes
> 
> > I was hoping for SQL to jooq
> 
> Your idea and use-case is understood, but since you don't have this yet, and you won't get it for jOOQ 3.15 yet, I thought I might as well offer a workaround.

Now I understand.  Thanks for the clarification. I look forward to testing this new functionality.

**Comment by lukaseder** [comment]
Further work will be done in jOOQ 3.16: https://github.com/jOOQ/jOOQ/issues/11911
