### ISSUE TITLE
Add support for Oracle TYPE .. UNDER type hierarchies

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#644]
Type inheritance might be something of interest to jOOQ:
https://docs.oracle.com/en/database/oracle/oracle-database/19/lnpls/CREATE-TYPE-statement.html#GUID-389D603D-FBD0-452A-8414-240BBBC57034

### New API

- [x] jOOQ
  - [x] `UDT.getSupertype()`
  - [x] `UDT.getSubtypes()` (these must be considered when registering the type map)
  - [x] `UDT.isAssignableFrom(UDT)` (akin to `Class.isAssignableFrom(Class)` of the JDK)
- [x] jOOQ-meta
  - [x] `UDTDefinition.getSupertype()`
  - [x] `UDTDefinition.getSubtypes()`

### Code generation

- [x] `UDT.getSupertype()` and `UDT.getSubtypes()`: https://github.com/jOOQ/jOOQ/issues/11371
- [x] A new set of interfaces to model subtype relationship via `Mode.RECORD_TYPE`
  - [x] Make sure all `@Override` annotations are generated accordingly.
    - [x] In these new types
    - [x] In the `UDTRecord` types
- [x] Support POJO hierarchies
- [x] Generator strategy support
  - [x] Programmatic (should work out of the box, with `Mode.RECORD_TYPE`)
  - [x] Matcher for `<udts>`:
    - [x] `recordTypeClass`
    - [x] `recordTypeImplements`
    - [x] `recordTypeGetterOverride`
    - [x] `recordTypeSetterOverride`
    - [x] `recordTypeMemberOverride`

### Tests

The following usage scenarios should be tested:

- [x] Handle synonym supertype references
- [x] `NON INSTANTIABLE` types should map to `abstract` types
  - [x] There are multiple problems when doing this
    - [x] We cannot instantiate the `UDTRecord` in order to access its `UDT` meta data: See https://github.com/jOOQ/jOOQ/issues/17155
    - [x] We cannot map from POJOs to `UDTRecord` (which has been skipped anyway)
- [x] 3 levels of hierarchy
- [x] ~Member methods on the type hierarchy~
  - [x] This will be postponed, for now: https://github.com/jOOQ/jOOQ/issues/17188
- [x] Types being accepted as `IN`, `IN/OUT`, `OUT` parameter
- [x] Nesting of these types with table types and vice versa
- [x] `ScalaGenerator`
- [x] `KotlinGenerator`
- [x] Interactions with converters / bindings
- [x] POJO hierarchies
  - [x] It seems unnecessary (and way too complex) to call `super` in all relevant methods. All methods are overridden, and field access is not possible from outside the class, so the redundant field sets are probably irrelevant. To be verified
  - [x] Interaction with special class types which don't allow inheritance (we'll just omit inheritance)
    - [x] `<pojosAsJavaRecordClasses/>`
      - [x] Prerequisite: https://github.com/jOOQ/jOOQ/issues/17232
    - [x] `<pojosAsScalaCaseClasses/>`
    - [x] `<pojosAsKotlinDataClasses/>`
  - [x] Interaction with `<immutablePojos/>` and `<interfaces/>`, which will probably cause issues as well
  - [x] ScalaGenerator limitation: https://github.com/jOOQ/jOOQ/issues/17189
- [x] Interaction with `<interfaces/>`
  - [x] See also: https://github.com/jOOQ/jOOQ/issues/8209
  - [x] We'll have to downcast supertypes to their relevant known subtypes in setters, `into()` methods, cosntructors, etc.
- [x] ~Auto conversion should be able to upcast~ (no, the conversion to the super type is legitimate. We should just avoid it when reading `UDTRecord` values from an `ArrayRecord`)
- [x] The POJO constructor in the `UDTRecord` doesn't really make sense with type hierarchies. Let's just skip it.

----
See also:
- https://github.com/jOOQ/jOOQ/issues/11215
- http://groups.google.com/group/jooq-user/browse_thread/thread/62e4e9f7ee4af5fb
- https://github.com/jOOQ/jOOQ/issues/2777

**Comment by lukaseder** [comment]
No one is using these ORDBMS features in Oracle yet. We'll potpone implementation until a customer has concrete requests.

**Comment by lukaseder** [comment]
Related:

- https://github.com/jOOQ/jOOQ/issues/2777

**Comment by lukaseder** [comment]
It seems that if we change:

- `UDT<R extends UDTRecord<R>>` to `UDT<R extends UDTRecord<? super R>>` (and all related API)
- `UDTRecord<R extends UDTRecord<R>>` to `UDTRecord<R extends UDTRecord<? super R>>` (and all related API)

Then it would be possible to have a generated subtype extend its generated supertype. E.g. for this schema:

```sql
CREATE OR REPLACE TYPE a AS OBJECT (a VARCHAR2 (140)) NOT FINAL;
CREATE OR REPLACE TYPE b UNDER a (b VARCHAR2 (140));
```

We could generate:

```java
public class ARecord extends UDTRecordImpl<ARecord> { ... }
public class BRecord extends ARecord { ... }
```

When using these types as follows.

```sql
CREATE OR REPLACE TYPE c AS OBJECT (x a)
CREATE OR REPLACE FUNCTION f (p VARCHAR2)
RETURN c IS
BEGIN
  RETURN c(b('a', 'b'));
END;
```

And then, writing the following program:

```java
CRecord c = Routines.f(configuration, "a");
System.out.println(c);
System.out.println(c.getX().getA());

System.out.println(c.getX().getUDT());
System.out.println(c.getX().getUDT().getRecordType());
System.out.println(c.getX().getUDT().newRecord() instanceof BRecord);
```

We get:

```
"TEST"."C"("TEST"."B"('a', 'b'))
a
"TEST"."B"
class org.jooq.test.oracle.generatedclasses.test.udt.records.BRecord
true
```

So, it seems that the change is sound. Just like in PL/SQL, the `C` type declares a dependency on the super type `A`, but the actual type may as well be a subtype. I'll investigate this a bit further.

**Comment by lukaseder** [comment]
The change in generics is a backwards incompatible change. Consider this code, which compiles:

```java
void m1() {
    X<?> x = null;
    m2(x);
}

<R extends X<R>> void m2(X<R> x) {}
interface X<R extends X<R>> {}
```

Now, if the interface `X` is changed to this:

```java
interface X<R extends X<? super R>> {}
```

Then the `m2(x)` call no longer compiles, unless `m2()` is changed to this:

```java
<R extends X<? super R>> void m2(X<R> x) {}
```

In other words, any user who refers to the `UDT` or `UDTRecord` types in their code would have compilation errors and would have to update their type declarations to the very unintuitive new generic signature. For developers who aren't very fluent with generics, this might take a few hours of head scratching, so let's explore other options of implementing this feature here, that don't introduce such an incompatibility.

For example, we could generate interfaces for all non-final `OBJECT` types, and accept / return those instead of the record type itself. Benefits, include:

- The interfaces don't have to be generic
- Existing code isn't affected as this would affect only references to non-final `OBJECT` types with known subtypes

**Comment by lukaseder** [comment]
So, this seems to work just as well:

```java
public interface ARecordInterface<R extends UDTRecord<R>> extends UDTRecord<R> {
    void setA(String value);
    String getA();
}

public class ARecord extends UDTRecordImpl<ARecord> implements ARecordInterface<ARecord> { .. }
public class BRecord extends UDTRecordImpl<BRecord> implements ARecordInterface<BRecord> { .. }

public class CRecord extends UDTRecordImpl<CRecord> {
    public void setX(ARecordInterface value) {
        set(0, value);
    }
    public ARecordInterface getX() {
        return (ARecordInterface) get(0);
    }
    ...
}
```

The original program would still compile:

```java
CRecord c = Routines.f(configuration, "a");
System.out.println(c);
System.out.println(c.getX().getA());

System.out.println(c.getX().getUDT());
System.out.println(c.getX().getUDT().getRecordType());
System.out.println(c.getX().getUDT().newRecord() instanceof BRecord);
```

And produce the same output:

```
"TEST"."C"("TEST"."B"('a', 'b'))
a
"TEST"."B"
class org.jooq.test.oracle.generatedclasses.test.udt.records.BRecord
true
```

I like this much more than the original, which included this flawed hierarchy:

```java
public class ARecord extends UDTRecordImpl<ARecord> { ... }
public class BRecord extends ARecord { ... }
```

Where `BRecord` doesn't actually implement `UDTRecord<BRecord>` but only `UDTRecord<ARecord>`, a flaw in the type hierarchy that is related to recursive generics:
https://blog.jooq.org/the-dangers-of-correlating-subtype-polymorphism-with-generic-polymorphism/

I'll try to implement this with interfaces.

Note that the interfaces are not the same ones as the ones generated by `<interfaces/>`, which can still be generated separately. Those don't have a dependency on `UDTRecord<R>`

**Comment by lukaseder** [comment]
I would still intuitively prefer to be able to generate this:

```java
public class ARecord extends UDTRecordImpl { ... }
public class BRecord extends ARecord { ... }
```

Without the recursive generics on `UDTRecord` (and related types), it would seem to be possible. Removing those generics is a difficult, and incompatible change. But I'll still put it on the roadmap for future consideration:

- https://github.com/jOOQ/jOOQ/issues/17141

**Comment by lukaseder** [comment]
The interaction with the `<interfaces/>` flag will be checked via:

- https://github.com/jOOQ/jOOQ/issues/8209

**Comment by lukaseder** [comment]
In fact, I wonder if we really need these extra `RecordType` interface types if we're also generating interfaces. It seems that the additional hierarchy is redundant!

**Comment by lukaseder** [comment]
There is a regression in the generation of constructor signatures due to https://github.com/jOOQ/jOOQ/issues/17180. The constructors no longer accept the `RecordType` types, but fall back to accepting `Record` types.

I will investigate this tomorrow.

**Comment by lukaseder** [comment]
Fixed. Will deploy new snapshot builds right away

**Comment by lukaseder** [comment]
Member procedure support and overriding support is discussed in a separate issue and will probably be postponed, unless there's explicit need for this functionality:

- https://github.com/jOOQ/jOOQ/issues/17188

(It's likely existing member procedure support already works out of the box)

**Comment by lukaseder** [comment]
Hmm, POJO type hierarchies don't seem so simple in Scala, due to this error:

> Mutable variable cannot be overridden

E.g. this isn't possible:

```scala
class U31(
  var a: Integer
)

class U32(
  override var a: Integer,
  var b: Integer
) extends U31
```

So, I wonder if POJO hierarchies are possible in Scala (for mutable POJOs)...

**Comment by lukaseder** [comment]
I found a `-Yoverride-vars` flag here:
https://stackoverflow.com/a/41850773/521799

But it doesn't seem to work:

> [ERROR] bad option: '-Yoverride-vars'

**Comment by lukaseder** [comment]
Moving this to a separate issue:

- https://github.com/jOOQ/jOOQ/issues/17189

**Comment by lukaseder** [comment]
All known issues are now addressed for jOOQ 3.20.0
