### ISSUE TITLE
Add procedural language abstraction API

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6475]
#6474 and previous similar issues show that we will need more and more procedural language abstraction in jOOQ's internals. Rather than creating ad-hoc tools, we could think about this topic more thoroughly and support these abstractions also for end users. Most procedural languages have the same elements, with different syntaxes:

- blocks (e.g. `declare .. begin .. exception .. end`)
- try (e.g. `begin try .. end try begin catch .. end catch`)
- if-else
- loops

If we can find a common denominator, we can "easily" abstract over these languages.

If a database doesn't support anonymous blocks, we can generate stored procedures in a configurable schema.

This could be a very interesting new feature to send logic to remote servers. Together with the jOOQ 3.10 parser, this could be a killer feature for the commercial editions.

Subtasks include:

- [x] #7305 `DECLARE` support
- [x] #7306 `SET` (assignment) support
- [x] #8135 `IF-ELSE` support
- [x] #8174 `WHILE` loops support
- [x] #8176 `FOR` loops (indexed) support
- [x] #8285 `REPEAT` loops support
- [x] #8175 `LOOP` loops (infinite) support
- [x] #8186 `EXIT` statement support
- [x] #8187 `CONTINUE` statement support
- [x] #8188 label support
- [x] #8189 `GOTO` statement support

Subtasks postponed to version 3.13 include (see also #8450)

- #8292 `CASE` support
- #8166 `SELECT .. INTO <variables>` support
- #8167 `SELECT` expression emulation in procedural blocks
- #8171 `SELECT` statement emulation in procedural blocks
- #8177 `FOR` loops (implicit cursor) support
- #8202 `EXIT <label>` and `CONTINUE <label>` emulation for SQL Server
- #8284 `LEAVE` (no label) and `ITERATE` (no label) emulation for DB2
- #8200 `GOTO` statement emulation
- #8201 `EXECUTE IMMEDIATE` statement support
- #8216 Record types support
- #8228 Record types emulation
- #8229 Exception handling support
- #8230 `RAISE` statement support
- #8307 Variable block scope emulation
- #8314 Work around lack of T-SQL's block scope
