### ISSUE TITLE
Various parser bugs / missing features

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6485]
This is a continuation of https://github.com/jOOQ/jOOQ/issues/5955

----

Some features were not yet supported in the jOOQ 3.9 parser. We'll fix them all in this single issue in order not to create too many issues. Here's the list of fixed things (incomplete, because GitHub screwed up this list with their eventual consistency :( ):

### SELECT features

- [x] `WITH` for other statements than `SELECT`
- [x] `SELECT t.*` expressions where `t` is a table. (support it in jOOQ, first: #1677)
- [x] `SELECT *` (support it in jOOQ first: #2769)

### Other statements

- [x] `UPDATE .. FROM`
- [x] `CREATE TABLE AS SELECT .. WITH [ NO ] DATA` (Support in jOOQ first: #7139 7139)
- [x] `RETURNING *` and `RETURNING t.*` clauses
- [x] `CREATE INDEX ON` (no index name). (Support in jOOQ first: #7107)
- [x] Incomplete aliasing syntax in `MERGE`
- [x] `MERGE` statement with `USING table` rather than `USING (SELECT ..)`
- [x] `INSERT .. VALUES ()` with empty `VALUES` should be parsed as `DEFAULT VALUES` (see #6936)
- [x] `ON CONFLICT ON CONSTRAINT` clause (support in jOOQ first: #6906)
- [x] `CREATE TABLE`: Vendor-specific storage clauses (support in jOOQ first: https://github.com/jOOQ/jOOQ/issues/6131)
  - [x] MySQL storage options: https://dev.mysql.com/doc/refman/5.7/en/create-table.html (see also #6708)
- [x] `CREATE TABLE`: Various `IDENTITY` syntaxes
  - [x] SQL Server's `IDENTITY` and `IDENTITY(x, y)` syntax
- [x] `CREATE TABLE`: `UNIQUE { KEY | INDEX }` syntax, where the additional keywords are meaningless in MySQL
- [x] `CREATE TABLE`: MySQL `ENUM` and `SET` types (see #7017)
- [x] `CREATE TABLE` and `ALTER TABLE`: MySQL `TINYINT(1)` data types and other integer types with "length" (which can be ignored by jOOQ)
- [x] `CREATE TABLE`: Comments (see #7018)
- [x] `ALTER TABLE`: Make `COLUMN` keyword optional on drop column command
- [x] `ALTER TABLE`: Allow for optionally wrapping dropped columns in parentheses (Oracle style)
https://github.com/jOOQ/jOOQ/issues/5318)
- [x] `ALTER TABLE`: Multiple columns dropped in one statement (support in jOOQ first: https://github.com/jOOQ/jOOQ/issues/5319)
- [x] `DELIMITER` pseudo statement
- [x] Oracle sqlplus commands (parse and ignore most of them, mostly `SET` commands. This works for other DBs, too)
- [x] `SET SCHEMA` and `SET CATALOG` commands (support in jOOQ first: #7087)
- [x] `GRANT` and `REVOKE` statements (support in jOOQ first: #6812)
  - [x] `WITH GRANT OPTION` (see #6913)
  - [x] `REVOKE GRANT OPTION` (see #6931)
- [x] Procedural blocks (support in jOOQ first: #6474)
- [x] `GENERATOR` as a synonym for `SEQUENCE` in Firebird DDL
- [x] `ALTER TABLE .. ALTER COLUMN .. TO newname` for renaming columns in Firebird DDL
- [x] `sp_rename` calls on SQL Server
- [x] `COMMENT ON` statements (support in jOOQ first: #6324)
- [x] `COMMENT ON VIEW` statement (support in jOOQ first: #7086)
- [x] Parse and ignore these statements:
  - [x] `COMMENT ON DATABASE` (PostgreSQL)
  - [x] `COMMENT ON EXTENSION` (PostgreSQL)
  - [x] Other `COMMENT ON` statements: https://www.postgresql.org/docs/10/static/sql-comment.html
  - [x] `ALTER SCHEMA .. OWNER TO` (PostgreSQL)
  - [x] `ALTER DOMAIN .. OWNER TO` (PostgreSQL)
  - [x] Other `ALTER DOMAIN` statements: https://www.postgresql.org/docs/current/static/sql-alterdomain.html

### Column expressions (and predicates)

- [x] `ARRAY_AGG` aggregate function
- [x] `TRANSLATE` function (support this in jOOQ, first: #6978)
- [x] `ABS` function
- [x] PostgreSQL array contains operator: `@>`
- [x] SQL Server `LEN()` function
- [x] All sorts of vendor-specific functions that are generated by jOOQ internals
  - [x] `TRUNC()` for date / timestamp

### Literals and data types

- [x] PostgreSQL escape syntax for string literals (see #6704)
- [x] MySQL and SQL Server `DATETIME` types
- [x] SQL Server `(max)` data type length (applicable to several types: https://docs.microsoft.com/en-us/sql/t-sql/data-types/data-types-transact-sql)
- [x] JDBC escape syntax for date time literals: `{d '...'}`, `{t '...'}`, `{ts '...'}`
- [x] JDBC escape syntax for function calls: `{fn ...}`
- [x] PostgreSQL `smallserial` and `bigserial` (see #7074)

### Language features

- [x] Support dangling semicolons (T-SQL), i.e. like in Java, semicolons can appear without a statement
- [x] T-SQL `GO` command to send a batch to the server
- [x] `FETCH { FIRST | NEXT } { ROW | ROWS } ONLY` without an explicit number of rows is possible, too.

### Other improvements

- [x] Show line and column numbers in error message
- [x] Compound keywords aren't parsed correctly when they contain line breaks
