### ISSUE TITLE
Add support for computed columns

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6492]
Some databases support the following syntax to add computed columns to a table:

```sql
ALTER TABLE actor ADD last_name_upper AS (upper (last_name))
```

This is both available in `ALTER TABLE` and `CREATE TABLE` statements. In DB2, we must add some additional statements, apparently, to prevent errors:

```sql
SET INTEGRITY FOR actor OFF;
ALTER TABLE actor ADD last_name_upper GENERATED ALWAYS AS (upper (last_name));
SET INTEGRITY FOR actor IMMEDIATE CHECKED FORCE GENERATED;
```

### Caveats

Dialects have 3 types of generated content: `DEFAULT`, `GENERATED BY DEFAULT AS`, `GENERATED ALWAYS AS`. They're essentially the same thing: A computed expression, and a directive when to compute it (including whether to store the computation result or calculate it on read, if it's always computed).

It may be tempting to reuse the newly introduced `DataType::readonly` flag to decide whether `DataType::default_` is really `GENERATED ALWAYS AS`, but that's too clever. The readonly flag might be set for other reasons, including a synthetic readonly flag.

While it doesn't seem to be possible (nor make sense) to provide both a `DEFAULT` and a `GENERATED ALWAYS AS` expression, PostgreSQL keeps the two things separate, and also the identity, see:

```sql
create table t (
  a serial4,
  b int generated by default as identity,
  c int generated always as identity,
  d int generated always as (1) stored
);

select column_name, column_default, is_generated, generation_expression
from information_schema.columns where table_name = 't';
```

Resulting in:

```
|column_name|column_default              |is_generated|generation_expression|
|-----------|----------------------------|------------|---------------------|
|a          |nextval('t_a_seq'::regclass)|NEVER       |                     |
|b          |                            |NEVER       |                     |
|c          |                            |NEVER       |                     |
|d          |                            |ALWAYS      |1                    |
```

It is not unlikely I'm overlooking some subtle difference (other than historic context) between the SQL language features. So, in order to be able to cleanly distinguish between them, best represent them separately.

### Tasks

- [x] Add `DataType<T>.generatedAlwaysAs(Field<T>)`
- [x] Add a `STORED` / `VIRTUAL` flag, if supported by the RDBMS
  - [x] In DDL and the parser
  - [x] In the meta data (see: https://github.com/jOOQ/jOOQ/issues/12664)
- [x] Add meta support
  - [x] Generated
  - [x] Database meta data (`DatabaseMetaData::getColumns` contains a `IS_GENERATEDCOLUMN` flag and `COLUMN_DEF` might contain the expression) (postponed: https://github.com/jOOQ/jOOQ/issues/12719)
  - [x] Interpreted
  - [x] XML
- [x] ~Implement `<readonlyComputedColumns/>`~ (see https://github.com/jOOQ/jOOQ/issues/9864). This isn't necessary, as computed columns are always readonly in the runtime meta model
- [x] Add DDL support
  - [x] `CREATE TABLE`
  - [x] `ALTER TABLE .. ADD`
  - [x] ~`ALTER TABLE .. ALTER`~ (postponed: https://github.com/jOOQ/jOOQ/issues/12665)
- [x] Add parser support

### Dialects

- [x] CockroachDB (ddl, codegen)
- [x] Db2 (ddl, codegen)
- [x] Derby (ddl, codegen)
- [x] Firebird (ddl, codegen)
- [x] H2 (ddl, codegen)
- [x] HANA (ddl, codegen)
- [x] HSQLDB (ddl, codegen)
- [x] MariaDB (ddl, codegen)
- [x] MySQL (ddl, codegen)
- [x] Oracle (ddl, codegen)
- [x] PostgreSQL 12 (ddl, codegen)
- [x] SQLite (ddl, codegen) (we must use `pragma_table_xinfo` to get access to the "hidden" columns)
- [x] SQL Server (ddl, codegen)

These dialects support the feature but we haven't implemented it yet.

- Sybase ASE
- Sybase SQL Anywhere

These dialects don't have support yet (dialects not listed haven't been checked):

- BigQuery
- EXASOL
- Informix
- Redshift
- Snowflake
- Teradata
- Vertica
- Yugabyte
