### ISSUE TITLE
Add support for type DOMAINs

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#681]
As documented here:

http://www.postgresql.org/docs/current/static/sql-createdomain.html

This is also part of the SQL 92 standard (chapter 11.21):

http://www.contrib.andrew.cmu.edu/~shadow/sql/sql1992.txt

Interesting features to be taken into consideration for domains:
- Domains can restrict other domains (we'll need recursive querying to find the top-most non-domain base type!)
- Domains can restrict (some) user-defined types, but apparently not recursively.

Note, SQL Server 2016 calls these `TYPE ALIAS`:
https://msdn.microsoft.com/en-us/library/ms190232.aspx

### Tasks

- [x] Add `org.jooq.Domain` type supporting:
  - [x] `TYPE`
  - [x] `DEFAULT`
  - [x] `CHECK` constraints
  - [x] ~`NOT NULL` constraints~ (implemented separately: #10239)
  - [x] ~`COLLATION`~ (implemented separately: #10240)
- [x] Add an improved `DataType` model
  - [x] ~Supporting a better data type registry (see also #650)~ (We don't seem to need this yet)
  - [x] Allowing for `org.jooq.Name` as identifiers (see also #10230)
- [x] Add `DSL` API to construct domain references
- [x] Add meta model for domains
- [x] Support exporting DDL from `Meta.ddl()`
  - [x] For `CatalogMetaImpl` and `SchemaMetaImpl`
  - [x] For `InformationSchemaMetaImpl` (add to XSD)
  - [x] For `Interpreter`
  - [x] ~For `MetaImpl`~ (doesn't work through JDBC `DatabaseMetaData` API)
- [x] Add code generator support for domains
  - [x] H2
  - [x] HSQLDB
  - [x] Firebird
  - [x] PostgreSQL
  - [x] SQL Server
  - [x] ~Support in arrays, udts, domains, procedures~: #10475
  - [x] Generate also `Schema.getDomains()`
- [x] Add DDL support for domains
  - [x] `CREATE`
  - [x] `ALTER`
  - [x] `DROP`
- [x] Add parser support
- [x] Add interpreter support
  - [x] `CREATE`
  - [x] `ALTER`
  - [x] `DROP`
- [x] Add diff support
- [x] Add dialect support
  - [x] H2
  - [x] HSQLDB
  - [x] Firebird
  - [x] PostgreSQL
  - [x] SQL Server
- [x] Documentation

### Known limitations (#10615):

- Support generating domain references in:
  - Casts
  - DDL

---

See also
- #3382 
- #3486 (domains need to be considered in the code generator configuration)
- https://msdn.microsoft.com/en-us/library/ms190232.aspx

**Comment by lukaseder** [comment]
@axelfontaine: I'm implementing this feature for jOOQ 3.8. I remember that we have talked about it a long time ago. What would be your typical expectations towards this feature? What would you want from the source code generator?

**Comment by axelfontaine** [comment]
The minimal version would be to be able to match as the domain data type name in the converter and forced type specification.

Example:
```
<forcedType>
  <name>AwsRegion</name>
  <expression>.*aws_region</expression>
  <types>aws_region_type</types>
</forcedType>
```

where `aws_region_type` is defined as follows

```
CREATE DOMAIN aws_region_type TEXT CONSTRAINT valid_aws_region CHECK (
  VALUE IN ('ap-northeast-1', 'ap-southeast-1', 'ap-southeast-2', 'eu-west-1', 'sa-east-1', 'us-east-1', 'us-west-1', 'us-west-2'));
```

The next step would be to automatically generate Java enums as well not have to register EnumConverter subclasses. Now I fully understand this wouldn't work for all types of enums, but it would certainly work for a subset like the one presented (TEXT CONSTRAINT CHECK VALUE IN). 

The reason I feel strongly about this is that it encourages type safety and moves users away from using strings for everything or having to write boilerplate code themselves.

**Comment by lukaseder** [comment]
Thanks for the info, Axel. Interesting points. I definitely see the use-case of being able to specify the name in `<types/>`. 

I wonder what happens in the case of nested definitions (an edge case), e.g. when you do:

```sql
CREATE DOMAIN aws_us_region_type AS aws_region_type CHECK (
  VALUE IN ('us-east-1', 'us-west-1', 'us-west-2');
```

Would be interesting if such nesting should be formally represented (e.g. through inheritance), or ignored.

As far as generated enums are concerned, we've already discussed this: #2102 :) However, the jOOQ-meta API certainly makes available the check constraint definition strings (even recursively, in case of nested domains), so user-defined code generators could use the domain knowledge to generate their own enums...

**Comment by lukaseder** [comment]
... in fact, there will be a generated class per domain. I'm just not yet 100% sure about what should be in it to accommodate domains in a generic way...

**Comment by axelfontaine** [comment]
Now this may be a stupid idea (known to happen before with a raw thought that just occurred to me :-) ), but would it make sense to translate the constraint code to Java in combination maybe with constants for the values?

Example:
```
public class AwsRegionType {
  public static final AwsRegionType US_EAST_1 = new AwsRegionType("us-east-1);
  public static final AwsRegionType EU_WEST_1 = new AwsRegionType("eu-west-1);

  private final String name;

  /* or maybe protected */
  public AwsRegionType(String name) {
    if (!"us-east-1".equals(name) && !"eu-west-1".equals(name)) {
      throw new DomainContraintValidationException();
    }
    this.name = name;
  }
}

// Inheritance is messier, but who says this needs to be supported from day 1. You can always figure out how to do this cleanly later.
public class AwsUsRegionType extends AwsRegionType {
  public static final AwsUsRegionType US_EAST_1 = new AwsUsRegionType("us-east-1);

  /* or maybe protected */
  public AwsUsRegionType(String name) {
    super(name);
    if (!"us-east-1".equals(name)) {
      throw new DomainContraintValidationException();
    }
  }
}
```

**Comment by lukaseder** [comment]
I had thought about something similar. This would allow for having "enums" that extend each other.

Yet, the problem with this approach is what I had discussed in #2102. The constraint code is really too complex to parse and translate to Java. A silly example would be a regex in the constraint code, which uses different regex syntax in PostgreSQL than in Java...

**Comment by lukaseder** [comment]
Hmm, I've noticed, we had already discussed the matching use-case as well, in the past: #3486. I think I have a clear picture about what can be done right now.

**Comment by ben-manes** [comment]
What is the status of this? I was trying to use domains in H2 to interop with Postgres, but unfortunately domains are not recognized by `forcedType` yet.

**Comment by lukaseder** [comment]
Domains are a very cool SQL feature and indeed, this issue here would be nice to have with a PostgreSQL integration. However, I have seen very little traction out in the wild for PostgreSQL domains themselves, so I don't want to prioritise these efforts right now (thorough support for domains takes quite a bit of thought).

From what I understood, H2's domains are still a bit of a moving target, so I prefer not to invest there either, right now. I prefer waiting for H2 1.4.198 to be released and then wait for this very big release to stabilise (it changed a lot of stuff!), perhaps in 1.4.199 before taking any further steps towards domains, enums, etc. (I've spent way too much time on H2's enums already...)

**Comment by katzyn** [comment]
@lukaseder 
H2 1.4.198 was released 11 days ago and 1.4.199 with some bugfixes will be released soon (may be in a week), so if you want to test something it's better to do it now.

**Comment by lukaseder** [comment]
Oh, great news. Thanks for letting me know, @katzyn! Will upgrade jOOQ integration tests and get in touch if I find something.

**Comment by katzyn** [comment]
Unfortunately, there are some critical regressions in 1.4.198 that were already resolved. Some expressions (functions, arithmetic, etc.) in `ON` conditions of some joins throw NPE or AssertionError, for example. If you have them in your tests you may need to compile H2 from its current sources.

**Comment by lukaseder** [comment]
@katzyn Hadn't noticed any of those...

**Comment by lightoze** [comment]
> Domains are a very cool SQL feature and indeed, this issue here would be nice to have with a PostgreSQL integration. However, I have seen very little traction out in the wild for PostgreSQL domains themselves, so I don't want to prioritise these efforts right now (thorough support for domains takes quite a bit of thought).

Mine use case is JSON. Using domain to determine forced type would be very useful. With domain constraints it is useful on database side too, e.g. check that particular column is always an object (not a scalar value).

**Comment by lukaseder** [comment]
@lightoze Indeed, that does sound very useful. You mean this issue: #3486.

I'm just thinking that not only should we be able to match domains by name (like any other type), but also check constraints. E.g. we should be able to write patterns that match the check constraint SQL expression, and apply a forced type as soon as we find such a constraint. I've added another feature request for this: #8843

**Comment by lukaseder** [comment]
I'm giving this a shot now, for jOOQ 3.14. The fact that a `DOMAIN` could be used in the code generator to encode a certain synthetic data type is very compelling

**Comment by lukaseder** [comment]
Domain support has now been added to jOOQ. Additional features (e.g. code generation features) may be added on top of this support, in other issues.

**Comment by lukaseder** [comment]
Reopening this. Not all dialects have their code generator integration tested yet...

**Comment by lukaseder** [comment]
HSQLDB has a bug in its `ALTER DOMAIN` implementation: https://sourceforge.net/p/hsqldb/bugs/1582/

**Comment by lukaseder** [comment]
Code generation support is incomplete. Domains are generated but not linked from tables.

**Comment by lukaseder** [comment]
... and of course, the documentation is still missing 😀

**Comment by lightoze** [comment]
Please also test how domains and code generation play with arrays. I have just hit an issue with Postgres domain extending JSONB being treated as `SQLDataType.JSONB` normally but as `DefaultDataType.getDefaultDataType("jsonb_domain_type").getArrayDataType()` when in an array, instead of just `SQLDataType.JSONB.getArrayDataType()`.

**Comment by lukaseder** [comment]
@lightoze Thanks for your report. Can you please create a new issue with some help to reproduce this?

**Comment by lukaseder** [comment]
Looking into code generation now. The usual catch-22 when it comes to static initialisation of the generated code applies here:

- Domains are created with a schema singleton reference
- Schemas initialise table singletons
- Tables reference domain singletons (which aren't initialised yet, at this point)
- -> NPE

A related issue is: https://github.com/jOOQ/jOOQ/issues/7172. Perhaps it's time to solve this once and for all...

**Comment by ben-manes** [comment]
Sounds like you’d want to use the initialization-on-demand holder idiom for lazy static init?

**Comment by lukaseder** [comment]
It's already done

**Comment by lukaseder** [comment]
Our old friends, the H2 enum types get in the way of code generation support for domains, again, see #7917. In 1.4.200, `ENUM` types are also domains, and should thus be excluded from domain code generation.

Perhaps, we can instead use the domain information to generate the `ENUM` type properly, hoping that there won't be a regression in 1.4.201: https://github.com/jOOQ/jOOQ/issues/7917#issuecomment-652898474

**Comment by katzyn** [comment]
In H2 enum types aren't required to be domains. But domain may be based on enum data type.

**Comment by lukaseder** [comment]
```sql
create type e as enum ('a', 'b', 'c');
select * from information_schema.domains where domain_name = 'E';
```

This produces one entry in H2 1.4.200, right?

**Comment by katzyn** [comment]
Yes, just like with any other domain.

But, please, use only `CREATE DOMAIN` for H2 in jOOQ. `CREATE TYPE` is not expected to work outside of PostgreSQL compatibility mode (it currently works, but it's actually a bug).

**Comment by lukaseder** [comment]
> But, please, use only `CREATE DOMAIN` for H2 in jOOQ

Are you telling me, or are you telling our common users? :) Because users will use what's there and will come here to ask for support for it... jOOQ isn't really opinionated in these things.

**Comment by katzyn** [comment]
If jOOQ somehow generates data type definition by itself, it should use the supported SQL command for that purpose.

**Comment by lukaseder** [comment]
This here is about code generation from existing meta data. If we discover that someone has created an enum type using `CREATE TYPE`, I don't think we should generate a `DOMAIN` for that.

**Comment by lukaseder** [comment]
With code generation support, this feature is now complete (we'll support domains referenced from procedures and other UDTs in a later step: #10475)

**Comment by lukaseder** [comment]
See also #7070 (UDTs referencing domains in PG)

**Comment by lukaseder** [comment]
Reopening for the missing support in casts, DDL

**Comment by lukaseder** [comment]
I've moved the known limitations to a new issue: #10615
