### ISSUE TITLE
Add support for GRANT and REVOKE statements

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6812]
Many databases have some way of granting (and revoking) object rights to users / roles. It would be useful to have these statements as well in our repertoire.

We'll probably need a new top level type `org.jooq.User`, and perhaps `org.jooq.Role`. It’s currently unclear how these two types should relate to each other. Once we have the types, we’ll need:

- [x] Ways to construct them using DSL.user() and DSL.role()
- [x] ~Perhaps, code generation support~ (separate issue: see #6902)
- [x] The actual API and its implementation
- [x] Parser support (#6485) and documentation in grammar

Additional improvements in separate issues:

- [x] Granting to and revoking from `PUBLIC`: #6911
- [x] `GRANT .. [ WITH GRANT OPTION ]`: #6913
- [x] `REVOKE [ GRANT OPTION FOR ] ..`: #6931

We should collect all the related features / syntaxes from different vendors – and especially the little quirks that each has to them. This subset of vendors should be a good starter:

- [x] ~DB2 LUW~ (We'll do this later)
- [x] Derby
- [x] H2
- [x] HSQLDB
- [x] MySQL / MariaDB
- [x] Oracle
- [x] PostgreSQL
- [x] SQL Server
- [x] ~SQLite~ (does not support grants)

**Comment by timur-sh** [comment]
There is a common denominator to use GRANT statement for above database. Except is SQLite, it doesn't support any accession control

It is separated on two possibles:
First one is `GRANT PRIVILEGES`
`GRANT <privilege> ON <objectName> TO <grantees> [<PRIVILEGE OPTIONS>]`
`<privilege>`  = ACTION [, ...] - this is an action specific to particular database. You can find whole list below  
`<objectName>` - OBJECT this can be table, schema, view, etc. You can find whole list below  
`<PRIVILEGE OPTIONS>` -  PRIVILEGE_OPTIONS options that may be depend on certain database. You can find them below

The second one is `GRANT ROLES`
`GRANT roleName TO <grantees> [<ROLE_OPTIONS>]`
`<ROLE_OPTIONS>` -  ROLE_OPTIONS options that may be depend on certain database. You can find them below
`<grantees>` = user | role | PUBLIC 

> `<grantees>`  may be changed by specific database

**DB2 LUW**

**Derby** https://db.apache.org/derby/docs/10.5/ref/rrefsqljgrant.html
1. ACTIONS:  ` { ALL PRIVILEGES | DELETE | INSERT | REFERENCES [column list] | SELECT [column list] | TRIGGER | UPDATE [column list] } `
2. OBJECT: ` [TABLE]  { table-Name | view-Name }`

There are some additional GRANT statements:
`GRANT EXECUTE ON { FUNCTION | PROCEDURE } <routine-designator> TO <grantees>`
`GRANT roleName [, ... ] TO <grantees>` 

**H2** http://www.h2database.com/html/grammar.html#grant_right
1. ACTIONS:  `{ SELECT | INSERT | UPDATE | DELETE | ALL  } `
2. OBJECT: `SCHEMA schemaName | tableName `

**HSQLDB** http://hsqldb.org/doc/guide/accesscontrol-chapt.html
1. ACTIONS: `ALL PRIVILEGES | SELECT | SELECT <left paren> <privilege column list> <right paren> | DELETE | INSERT [ <left paren> <privilege column list> <right paren> ] | UPDATE [ <left paren> <privilege column list> <right paren> ] | REFERENCES [ <left paren> <privilege column list> <right paren> ] | USAGE | TRIGGER | EXECUTE`
2. OBJECT:  `[ TABLE ]<table name> | DOMAIN <domain name> | COLLATION <collation name> | CHARACTER SET <character set name> | TRANSLATION <transliteration name> | TYPE <user-defined type name> | SEQUENCE <sequence generator name> | <specific routine designator> | ROUTINE <routine name> | FUNCTION <function name> | PROCEDURE <procedure name> `
3. PRIVILEGE_OPTIONS: `[ WITH GRANT OPTION ] [ GRANTED BY <grantor> ]`

There is additional GRANT statement:
`GRANT roleName [, ... ] TO <grantees> [ ,... ] [ WITH ADMIN OPTION ] [ GRANTED BY <grantor> ]`
`<grantor>` = CURRENT_USER | CURRENT_ROLE

**MariaDB** https://mariadb.com/kb/en/library/grant/

**MySQL** https://dev.mysql.com/doc/refman/8.0/en/grant.html

**PostgreSQL** https://www.postgresql.org/docs/10/static/sql-grant.html


**Oracle** https://docs.oracle.com/cd/B19306_01/server.102/b14200/statements_9013.htm
**SQL Server**

**Comment by lukaseder** [comment]
Thank you very much for this overview. That's kind of what I feared - it's a very vast territory. In any case, we don't have to (and probably shouldn't) implement all of it. Thus far, jOOQ's DDL API allows for creating objects like tables, sequences, views, etc. We should focus on actions that are possible on those objects that can be created by jOOQ. For instance, a privilege to create or access a table space or to connect to databases or to create objects is currently out of scope (which I would consider system privileges). We'll focus only on object access privileges right now. Also, granting access to roles seems out of scope right now.

So, how about the following subset:

```
grantStatement ::=
  GRANT { SELECT | INSERT | UPDATE | DELETE } ON <table> TO { <user> | <role> }

revokeStatement ::=
  REVOKE { SELECT | INSERT | UPDATE | DELETE } ON <table> FROM { <user> | <role> } 
```

The `<table>` reference is already available from the jOOQ API through `org.jooq.Table`. The `<user>` and `<role>` references will need to be created as new types: `org.jooq.User` and `org.jooq.Role`. I'm creating separate tasks for those types (let's focus on `User` first (#6838), and maybe do `Role` (#6839) later).

The DSL API should have convenience methods for the above four actions. Later on, when we decide that other types of actions should be supported as well, we can still introduce a new type `org.jooq.Privilege` or `org.jooq.Action`. So, I'm suggesting the following syntax that will be available from `DSL` and from `DSLContext`:

```java
// Examples
grantSelectOn(table).to(user).execute();
revokeInsertOn(table).from(user).execute();
```

We can then add additional tasks as we go for things like `WITH GRANT OPTION`.

So, immediate steps:

1. Implement `org.jooq.User` (through #6838)
2. Implement the above simple API
3. Update the parser (through #6485)

**Comment by timur-sh** [comment]
Thank you for reply! I agree with you. But, I would extend the clause by `SEQUENCE` and `REFERENCES` statements either will add them future (within next tasks).

```
grantStatement ::=
  GRANT { SELECT | INSERT | UPDATE | DELETE | SEQUENCE | REFERENCES } ON <table> TO { <user> | <role> }

revokeStatement ::=
  REVOKE { SELECT | INSERT | UPDATE | DELETE | SEQUENCE | REFERENCES } ON <table> FROM { <user> | <role> } 
```

**Comment by lukaseder** [comment]
Let's add convenience API for the 4 actions mentioned, and then look into a `org.jooq.Action` (or so) type to model the more rare / complex cases to prevent the API from exploding. For instance, `REFERENCES` takes arguments in some databases. It could look like this:

```java
grant(references(T.COL1, T.COL2)).on(T).to(user).execute();
```

**Comment by timur-sh** [comment]
What must be next step either`Perhaps, code generation support` or `The actual API and its implementation`

Could you create appropriate task?

**Comment by lukaseder** [comment]
This task talks about the statement and API implementation. Code generation support will be in another task.

**Comment by timur-sh** [comment]
I plant to start to work on implementation the mentioned API, I suggest one of kind of implementation to be looked like:
```
grant(EnumPrivilege privilege).on(Table).to(user | role).execute();
grant(EnumPrivilege... privileges).on(Table).to(user | role).execute();


revoke(EnumPrivilege privilege).on(Table).from(user | role).execute();
revoke(EnumPrivilege... privileges).from(Table).from(user | role).execute();
```

Where 
My suggestion also is, we should add another one Interface, that will be used in the `from()` method.

**Comment by lukaseder** [comment]
I'd really prefer the privilege not to be an enum. We don't know what sorts of privileges we'll have in the future, and how they're composed. However, you're right. there should be an overload allowing for passing several privileges. There's usually also an overload for `Collection<? extends Privilege>`, for convenience.

I prefer not to add another interface for the from() method. The number of interfaces would explode if we did things this way. The fact that we really have a union type `user | role` (if Java supported them) is best emulated through overloads, again.

**Comment by lukaseder** [comment]
I added parser support for these statements

**Comment by lukaseder** [comment]
Alright. Only DB2 and MySQL / MariaDB missing in the integration tests for now. I'll do those a bit later. Their users are a bit of a pain to set up.

**Comment by lukaseder** [comment]
MySQL is done. DB2 will be done in a later release / upon customer request. Thanks again for all your help implementing this feature, @timur-sh !

**Comment by timur-sh** [comment]
You're welcome! :)
