### ISSUE TITLE
Support various DDL statements in Firebird

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6969]
The Firebird dialect integration has been a bit lagging behind since we've added many DDL features to jOOQ. This issue will improve the DDL statement (and parser) support for Firebird.

Implemented improvements are:

- [x] Support for `GENERATOR` in the parser
- [x] `ALTER TABLE .. ALTER COLUMN .. TO newname` for renaming columns
- [x] Anonymous block support (#6474)
- [x] `ALTER TABLE .. DROP .., DROP .., ..` for dropping multiple columns (#5319)
- [x] Firebird doesn't support `ON { DELETE | UPDATE } RESTRICT`
- [x] `DEFAULT` clause before `NOT NULL` constraint in `CREATE TABLE` statement
- [x] `ALTER TABLE .. ALTER COLUMN .. TYPE`
- [x] `IF EXISTS` emulation needs to wrap `EXECUTE STATEMENT` in an `EXECUTE BLOCK` (see #6973)
