### ISSUE TITLE
Add support for MariaDB 10.3 Features

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7006]
There are a few new features coming up in 10.3, including:

- [x] #7004: Sequences
- [x] #7005: `INTERSECT` and `EXCEPT`
- [x] #9294 `WAIT` and `NOWAIT` clauses
- [x] #9213: New `SQLDialect` version numbers
- [x] #9310: `PERCENTILE_CONT`, `PERCENTILE_DISC`, and `MEDIAN` functions
- [x] #9309: `CREATE PACKAGE` (!) https://mariadb.com/kb/en/library/create-package/

All changes here:
https://mariadb.com/kb/en/library/changes-improvements-in-mariadb-103/

**Comment by lukaseder** [comment]
All changes have been made in separate issues

**Comment by lukaseder** [comment]
There is more...

**Comment by lukaseder** [comment]
Closing this as all changes will be made in separate issues.
