### ISSUE TITLE
Add Settings.parseWithMetaLookups

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7163]
In some situations, it might be useful for the parser to be able to discover actual objects from the catalog through a `MetaProvider` (see #5296). For instance:

- Does a schema / table / column really exist?
- What's the data type of the object?

We need to add a setting with the following options:

- No lookups (current behaviour, default)
- Lookups, ignoring failures
- Lookups, throwing errors on failures

Current implementation state:

- [x] Support qualified table lookups in `FROM`
- [x] Support unqualified table lookups in `FROM` (We'll need a new `Settings` flag to define a search path: #8616)
- [x] Support qualified field lookups in all clauses
- [x] ~Support unqualified field lookups in all clauses - this is going to be quite difficult to get right as the `FROM` clause may not have been parsed yet and we need to decide already what fields we'll put in the projection. Also, we need more sophisticated scope maps, where, at any given subquery level, we can define what's in scope and what isn't.~ (moved to #9061)
  - [x] ~A subtask of this is to ensure that unqualified field lookups will be correctly resolved also from correlated subqueries.~ (moved to #9061)
- [x] Unqualified asterisk resolution
- [x] Qualified asterisk resolution
- [x] ~Aliased tables and field lookups from aliased tables~ (moved to #9061)
- [x] ~Aliased column references (e.g. in `ORDER BY`)~ (moved to #9061)
- [x] ~Sequence and other identifiers are not looked up yet~ (moved to #9061)

The caveats exposed here make it clear that perhaps we cannot achieve all the parsing in a single go as we did until now, but will need to run two passes. The first one can already resolve all table references, whereas we will have to wait for the second pass to resolve the column references.
