### ISSUE TITLE
Various parser bugs / missing features

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7171]
This is a continuation of https://github.com/jOOQ/jOOQ/issues/6485

----

Some features were not yet supported in the jOOQ 3.9 parser. We'll fix them all in this single issue in order not to create too many issues. Here's the list of fixed things:

### SELECT features

- [x] `SEL` as a synonym for the `SELECT` keyword (Teradata)
  - [x] `DEL` for `DELETE`
  - [x] `UPD` for `UPDATE`
  - [x] `INS` for `INSERT`
- [x] `SEEK` clause
- [x] `WITH` with `UNION`: e.g. `WITH t(a) AS (SELECT 1) SELECT a FROM t UNION SELECT 1`
- [x] `WITH` with parenthesised `UNION`: e.g. `WITH t(a) AS (SELECT 1) (SELECT a FROM t UNION SELECT 1)`
- [x] Hints
  - [x] Oracle style
    - [x] Table hints: https://docs.microsoft.com/en-us/sql/t-sql/queries/hints-transact-sql-table
- [x] `FETCH n PERCENT ROWS` or `TOP n PERCENT` clauses (support in jOOQ, first: #5594)
- [x] `COUNT(t.*)` (support in jOOQ, first: #7288)
- [x] Nested unions cannot be parsed, e.g.
  - [x] `select x from ((select 1 as x) union (select 2 as x)) t`
  - [x] `select ((select 1) union (select 2))`
- [x] Support parsing identifiers as predicates (see: #7266)
- [x] `VALUES` in CTE: `WITH a AS (VALUES (1)) SELECT * FROM a`
- [x] `VALUES` wherever a query primary can be used, e.g. `VALUES(1, 2) UNION VALUES(2, 1)`
- [x] `WINDOW` clause
- [x] `LIMIT` / `FETCH` etc shouldn't parse an `DSL.inline()` param, but a constant

### Other statements

- [x] `CREATE INDEX .. ON t (a [ ASC | DESC ])`: Explicit sort clause in indexes
- [x] `CREATE INDEX .. INCLUDE` (support in jOOQ first: #7412)
- [x] `CREATE [ SPATIAL | FULLTEXT ] INDEX` (Unsupported in jOOQ: MySQL index types)
- [x] `CREATE TABLE AS WITH .. SELECT`
- [x] `CREATE TABLE`: `KEY` clause is MySQL's equivalent for an index. The keyword `INDEX` can also be used. See: #7347, #7348
- [x] `CREATE TABLE` quoted data types
- [x] `CREATE TABLE` with `REFERENCES` clauses directly on column specification
- [x] `CREATE OR REPLACE VIEW` (support in jOOQ first: #7286)
- [x] `ALTER TABLE`: Multiple columns added in one statement (support in jOOQ first: #5318)
- [x] `ALTER TABLE .. RENAME TO` should accept qualified target table names
- [x] `ALTER TABLE .. ADD INDEX` (MySQL synonym for creating the index using `CREATE INDEX`)
- [x] `ALTER TABLE .. RENAME INDEX` (MySQL synonym for creating the index using `RENAME INDEX`)
- [x] `ALTER TABLE .. DROP INDEX` (MySQL synonym for creating the index using `DROP INDEX`)
- [x] `USE` command (support in jOOQ first: #7087)
- [x] Support `ON CONFLICT DO` (without constraint specification)
- [x] `MERGE` without `INTO` (possible in SQL Server)
- [x] `MERGE` with `WHERE` clauses (or SQL Server alternative with `AND` clause)
- [x] `ENABLE` clause on constraints (Oracle)
- [x] `INSERT table ...` (without `INTO`, SQL Server)

### Table expressions

- [x] Oracle outer join `(+)`
- [x] SQL Server outer join `*=` (see also: #7300). We'll simply translate this to `(+)` for now. Emulation will follow
- [x] `UNNEST` operator
- [x] PostgreSQL `generate_series()`

### Column expressions (and predicates)

- [x] Row `DISTINCT` predicate (support in jOOQ first: #2051)
- [x] All sorts of vendor-specific functions
  - [x] SQL SERVER `getdate()`t
  - [x] MySQL `FIELD` function: https://dev.mysql.com/doc/refman/5.7/en/string-functions.html#function_field
  - [x] Oracle `DECODE` function
  - [x] Oracle `TO_NUMBER()` function (single argument, convert to `CAST(x AS NUMBER)`)
  - [x] Oracle `TO_CHAR()` function (single argument, convert to `CAST(x AS VARCHAR)`)
  - [x] Oracle `TO_DATE` and `TO_TIMESTAMP` functions (see also: #7320)
  - [x] SQL Server `IIF` (support in jOOQ first: #7275): https://docs.microsoft.com/en-us/sql/t-sql/functions/logical-functions-iif-transact-sql
  - [x] `DATEADD` et al.: https://docs.microsoft.com/en-us/sql/t-sql/functions/dateadd-transact-sql
- [x] `now()` function (see #7237)
- [x] `current_timestamp()`, `current_time()`, and `current_date()` can be functions, not just literals
- [x] `BIT_COUNT` function (MySQL)
- [x] `BIT_AND`, `BIT_OR`, `BIT_NOT`, `BIT_XOR`, `BIT_NAND`, `BIT_NOR`, `BIT_XNOR` functions
- [x] `SHL` and `SHR` functions
- [x] `DATE`, `TIME`, `TIMESTAMP`, `INTERVAL` column references (not literals)
- [x] MySQL `CAST` types (see https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#function_cast)

### Literals and data types

- [x] PostgreSQL array data types
- [x] PostgreSQL `SERIAL2` data type alias
- [x] Oracle `VARCHAR2(n BYTE)` and `VARCHAR2(n CHAR)` syntax (simply ignore the setting for now)
- [x] Various interval literals
  - [x] PostgreSQL interval literals (various syntaxes are possible: (https://www.postgresql.org/docs/current/static/datatype-datetime.html, see also #7445)

### Other improvements

- [x] Better exception formatting (adding `...` around abbreviated SQL strings)
- [x] Improve `unexpectedToken()` error messages (see #7261)

### New features

- [x] Parse and fail clauses available only in the pro edition

**Comment by kevinsimard** [comment]
Any plans on supporting FULLTEXT? I get an error whenever I have ```ALTER TABLE `<table>` ADD FULLTEXT INDEX `<name>`(`<column>`);``` in my migration.sql file.

**Comment by lukaseder** [comment]
Alright, the syntax is now supported in jOOQ 3.11. Thanks again for reporting!

**Comment by kevinsimard** [comment]
Thank you! Any idea when 11 is going to be released?

**Comment by lukaseder** [comment]
April / May 2018.

**Comment by mkmatis** [comment]
Hi, I discovered that DDLDatabase fails when script contains `CREATE INDEX` and column name is the same as H2 data type, e.g.:

```sql
CREATE TABLE TASK_HISTORY
(
    TIMESTAMP TIMESTAMP NOT NULL
);

CREATE INDEX TASK_HISTORY_TIMESTAMP_INDEX ON TASK_HISTORY(TIMESTAMP);
```
The same thing happens for `DATE`.

**Comment by lukaseder** [comment]
Interesting, thanks for reporting. The parser parses the `TIMESTAMP` keyword as the beginning of a `TIMESTAMP` literal. The workaround would be to quote the identifier:

```sql
CREATE INDEX TASK_HISTORY_TIMESTAMP_INDEX ON TASK_HISTORY("TIMESTAMP");
```

If H2 accepts the syntax, we'll have to, as well, of course

**Comment by lukaseder** [comment]
Remaining tasks moved to #7518
