### ISSUE TITLE
Add Setting to transform table lists to ansi join

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7312]
In some legacy code, it is not unlikely that there still are table lists (sometimes also referred to "implicit join") as follows:

```sql
-- Cross join
SELECT a.actor_id, a.first_name, a.last_name, f.title
FROM actor a, film_actor fa, film f

-- Inner join
SELECT a.actor_id, a.first_name, a.last_name, f.title
FROM actor a, film_actor fa, film f
WHERE a.actor_id = fa.actor_id
AND fa.film_id = f.film_id

-- Outer join (Oracle, DB2)
SELECT a.actor_id, a.first_name, a.last_name, f.title
FROM actor a, film_actor fa, film f
WHERE a.actor_id = fa.actor_id(+)
AND fa.film_id = f.film_id(+)

-- Outer join (T-SQL)
SELECT a.actor_id, a.first_name, a.last_name, f.title
FROM actor a, film_actor fa, film f
WHERE a.actor_id *= fa.actor_id
AND fa.film_id *= f.film_id
```

We should have a setting that tries to transform the above queries to their ANSI join equivalents:

```sql
-- Cross join
SELECT a.actor_id, a.first_name, a.last_name, f.title
FROM actor a 
CROSS JOIN film_actor fa 
CROSS JOIN film f

-- Inner join
SELECT a.actor_id, a.first_name, a.last_name, f.title
FROM actor a
JOIN film_actor fa ON a.actor_id = fa.actor_id
JOIN film f ON fa.film_id = f.film_id

-- Outer join
SELECT a.actor_id, a.first_name, a.last_name, f.title
FROM actor a
LEFT JOIN film_actor fa ON a.actor_id = fa.actor_id
LEFT JOIN film f ON fa.film_id = f.film_id
```

While this may not really be very useful in ordinary jOOQ API usage (assuming that people will already use the appropriate ANSI join syntax), it can be very useful when parsing and translating legacy SQL.

### Tasks

The above lists cases of very simple queries, but there are many possible edge cases that we need to consider.

Simple cases:

- [x] `WHERE .. AND ..` predicates are the simplest.
- [x] Comparison predicates `A = B`
- [x] Predicates on composite keys
- [x] Missing `(+)` on composite keys (turning `OUTER JOIN` back into `INNER JOIN`)
- [x] Table list is not in join order (e.g. `T1, T4, T2, T3` but joins are between `T1 : T2`, `T2 : T3`, `T3 : T4`)
- [x] Enable this flag (and the inverse transformation) on https://www.jooq.org/translate
- [x] To emulate `(+)`, the flag needs to be activated lazily even when `Settings.transformTableListsToAnsiJoin == false`, on dialects without native support. We can use a `ControlFlowSignal` to abort rendering the SQL string and attempt to re-render it with the flag turned on. In `SQLDialect.DB2_10`, we'll assume the relevant ["compatibility vector"](https://www.ibm.com/support/knowledgecenter/SSEPGG_10.1.0/com.ibm.db2.luw.apdv.porting.doc/doc/r0052878.html) is active

Edge cases:

- [x] The list has been moved to a separate issue: #10697

----
See also: #7300

**Comment by lukaseder** [comment]
The trivial cases seem simpler to support than thought, at first. We can already add value by supporting them, documenting a set of known issues and limitations

**Comment by lukaseder** [comment]
The current implementation seems to modify `CombinedCondition` during rendering, which has not been detected during our tests and integration tests.

As long as our query object model is mutable, we will keep running into this issue when implementing transformations. A few suggested fixes:

- Fix this for this particular transformation (a better transformation implementation is available here: https://github.com/jOOQ/jOOQ/issues/9017)
- Think about more internal transformation API
- Enhance integration tests, trying to generate the SQL string for each query instance twice in a row. The strings must be identical. If this approach helps discover new issues, I'll create a new one here on github.

**Comment by lukaseder** [comment]
The transformation is no longer mutating.

**Comment by lukaseder** [comment]
We can ship this and collect more user feedback, mostly from https://www.jooq.org/translate

**Comment by lukaseder** [comment]
The known issues will be addressed separately in https://github.com/jOOQ/jOOQ/issues/10697
