### ISSUE TITLE
Add new flags to Settings to govern parser behaviour

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7336]
It is currently not possible to configure parser behaviour - it always behaves the same way.

We need new `Settings` flags, which govern a few parser-specific behaviours, including (list will be extended):

- [x] Input `SQLDialect` (see #7337)
- [x] Catalog lookup (see #7163)
- [x] Known but unsupported syntax behaviour (#5917)
- [x] Unknown function behaviour (see #7344)
- [x] Ignore comments (SQL sections that are executed by the SQL engine, but ignored by the jOOQ parser, see #8325)

### Out of scope for jOOQ 3.12:

- [x] Optimise expressions (see #7284)
- [x] Input `SQLDialect` strictness (see #8826)
- [x] Unknown operator behaviour (currently no separate ticket. We'll think about this when users encounter this problem)
