### ISSUE TITLE
Add Settings for each individual diagnostic

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7398]
The new `DiagnosticsListener` SPI (#5960) can only either be turned on or off completely. There's no way to e.g. turn off the collection of duplicate or repeated SQL (which may be expensive). We need settings for these. Also, there needs to be a setting to turn on diagnostics for use in jOOQ. Currently, manual wrapping of jOOQ in a `DSLContext.diagnosticsConnection()` is required.

### Tasks

- [x] Add a `Settings.diagnosticsConnection` flag to turn on the entire feature. This is a three valued flag, which acts independently of the presence of `DiagnosticsListeners`:
  - [x] `DEFAULT`: The current behaviour. Off by default, but on if users use the `DiagnosticsConnection` explicitly
  - [x] `OFF`: Completely off, including in the `DiagnosticsConnection`
  - [x] `ON`: Completely on, including automatically creating a `DiagnosticsConnection` for every query
- [x] Add a flag for each individual diagnostic
