### ISSUE TITLE
Various parser bugs / missing features

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7518]
This is a continuation of https://github.com/jOOQ/jOOQ/issues/7171

----

Some features were not yet supported in the jOOQ 3.9 parser. We'll fix them all in this single issue in order not to create too many issues. Here's the list of fixed things:

### SELECT features

- [x] SQL Server alias syntax (`SELECT alias = 1` instead of `SELECT 1 AS alias`) (needs input dialect feature to disambiguate from standard boolean expression: #7337)
- [x] `TOP (n)` in SQL Server (see: #7267)
- [x] `MINUS` (Oracle) as a synonym for `EXCEPT`(see also: #7886)

### Other statements

- [x] `INSERT INTO (SELECT ..)`
- [x] `UPDATE (SELECT ..)`
- [x] `DELETE FROM (SELECT ..)`
- [x] `INSERT INTO t [ [ AS ] alias ] ...` (support in jOOQ, too: #8384)
- [x] `CREATE TABLE t(a, b, ...) AS SELECT` (support in jOOQ first: #5309)
- [x] `CREATE TABLE`: `UNIQUE [index_name]` clause, where an index is named differently from the constraint (support in jOOQ first: #7268)
- [x] `NUMBER(*, scale)` data types in Oracle, where `*` simply means `38`
- [x] `NUMBER(2, -1)` negative scale numeric types (see #7902)
- [x] `BOOL` as a synonym for `BOOLEAN` (see #8397)
- [x] Other vendor specific type aliases in DDL, such as e.g. `INT4` or `INT8` in PostgreSQL
- [x] `CREATE TABLE`: Allows (named) inline constraints to be placed between any `NOT NULL`, `DEFAULT`, etc. clause in PostgreSQL. Example: `CREATE TABLE x (a INT NOT NULL CONSTRAINT x CHECK (a = a) DEFAULT 0)` (see #8386)
- [x] `CREATE TABLE` with `DEFAULT CHARSET` storage clause (MySQL, undocumented: #7769)
- [x] `ALTER TABLE .. ADD .. IF NOT EXISTS`
- [x] `ALTER TABLE .. DROP .. IF EXISTS`
- [x] `ALTER TABLE .. MODIFY (  ...  )` (parenthesised modify clause. See #7898)
- [x] `ALTER TABLE .. MODIFY i [ NOT ] NULL` (Oracle syntax of setting / dropping `NOT NULL`)
- [x] Add support for `CREATE TYPE .. AS ENUM` (support in jOOQ first: #7570)
- [x] Add support for `DROP TYPE` (support in jOOQ first: #7774)
- [x] `UPDATE table [ [ AS ] alias ]`

### Table expressions

- [x] `CROSS JOIN` with `ON` (Support this in jOOQ first #5875)

### Column expressions (and predicates)

- [x] `TRIM` standard syntax: `TRIM ( [ LEADING | TRAILING | BOTH  ] [ <character> ] FROM expr )`. (Support trimming non-space characters in jOOQ first #8261)
- [x] `RESPECT NULLS` / `IGNORE NULLS` alternative syntax (see: #7907)
- [x] `CURRENT DATE` as a synonym for `CURRENT_DATE`. Same for `TIME[STAMP]` (e.g. in DB2)
- [x] `[ NOT ] SIMILAR TO` predicate (implement in jOOQ, first: #1725)
- [x] `col REGEXP col` expressions (see #8401)
- [x] `regexp_like(...)` functions (see also #8401 for the expression)
- [x] All sorts of vendor-specific functions
  - [x] SQL Server `CONVERT()` (see https://docs.microsoft.com/en-us/sql/t-sql/functions/cast-and-convert-transact-sql?view=sql-server-2017) (support in jOOQ first: #8238)
  - [x] `DATEDIFF` (MySQL version) https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_datediff 
  - [x] `DATEPART` et al.: https://docs.microsoft.com/en-us/sql/t-sql/functions/datepart-transact-sql
  - [x] `DAYOFMONTH` et al. See #7525
  - [x] `CURTIME()` and `CURDATE()` (see https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html)
  - [x] `CURRENT_DATE` and `CURRENT_DATE()` are both possible (and similar functions, too)
  - [x] `DAYOFWEEK()` and `DAYOFYEAR()` (see #7792, #7793)
  - [x] `EPOCH()` (see #7794)
- [x] SQL Server `STDEVP()` https://docs.microsoft.com/en-us/sql/t-sql/functions/stdevp-transact-sql?view=sql-server-2017

### Operators

- [x] Bitwise shifting operators `>>` and `<<`
- [x] Oracle `^=` not equals operator

### Literals and data types

- [x] Various interval literals
  - [x] DB2 interval literals
  - [x] PostgreSQL interval literals (see #7445)
- [x] PostgreSQL dollar-quoted string constants (see #6778)
- [x] Custom data type references (#7776)

### New features

**Comment by lukaseder** [comment]
This issue is being continued in #8452
