### ISSUE TITLE
Add support for COLLATIONS

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7534]
This is a continuation of #2908, with the remaining features left to implement:

- [ ] Add code generator support: #7121
- [ ] Add collation information to `InformationSchema` (jooq-meta.xsd): #7122
- [ ] Add `SET COLLATION` statement support: #7119
