### ISSUE TITLE
Implicit JOIN improvements

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7536]
jOOQ 3.11 introduced implicit joins (#1502). This issue tracks further improvements on the feature. Further work in #12037:

### Improvements

- [x] Generate inner join on non-nullable foreign keys: #7507

### Bugs

- [x] Table name redefinition in nested scope: Fixed via #10992
- [x] Possible column ambiguities in the join graph: Fixed via #10603 and others
