### ISSUE TITLE
Add support for SQL Server style DATEDIFF(datepart, date, date)

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7900]
We already support calculating the date difference between two dates in number of days. That's the MySQL version of the method:
https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_datediff

But SQL Server has an additional method that also takes a date part: 
https://docs.microsoft.com/en-us/sql/t-sql/functions/datediff-transact-sql?view=sql-server-2017

### Related functions

HANA has useful functions, like these:

- `YEARS_BETWEEN`: https://help.sap.com/viewer/4fe29514fd584807ac9f2a04f6754767/2.0.02/en-US/7c0d2c161ea34def86de3f5eadd6a0af.html
- `MONTHS_BETWEEN`: https://help.sap.com/viewer/4fe29514fd584807ac9f2a04f6754767/2.0.02/en-US/9f9eb73468b04bbc9d6014d22d2bfb90.html
- `DAYS_BETWEEN`: https://help.sap.com/viewer/4fe29514fd584807ac9f2a04f6754767/2.0.02/en-US/20e16ca5751910148da4fc7ec69bae03.html

They're not exactly the same. `DATEDIFF()` counts the number of date part instances spanned by the interval `[trunc(d1, part), trunc(d2, part)[` (e.g. `DATEDIFF(YEAR, '2000-03-01', '2002-01-01') = 2`) whereas these functions, or interval arithmetic in PostgreSQL produce `[d1, d2[`, e.g.  `YEARS_BETWEEN('2000-03-01', '2002-01-01') = 1`

### Tasks

- [x] Add API for `DATEDIFF`
- [x] Add API for `TIMESTAMPDIFF`
- [x] Add parser support (beware of order of arguments!)
- [x] Add convenience functions, such as from HANA (will be done in a later release: https://github.com/jOOQ/jOOQ/issues/11947)
- [x] Add documentation section (still due, see https://github.com/jOOQ/jOOQ/issues/10078)
- [x] Dialect support
  - [x] BigQuery
  - [x] CockroachDB
  - [x] Db2
  - [x] Derby
  - [x] Firebird
  - [x] H2
  - [x] HANA
  - [x] HSQLDB
  - [x] MariaDB
  - [x] MemSQL
  - [x] MySQL
  - [x] Oracle
  - [x] PostgreSQL
  - [x] Redshift
  - [x] SQL Server

----
See also: https://github.com/jOOQ/jOOQ/issues/10233

**Comment by katzyn** [comment]
For information: H2 also has the same function, but its example in current documentation may be confusing:
http://h2database.com/html/functions.html#datediff
Actually first argument may (and usually should) be a plain name of datetime field (`DATEDIFF(YEAR, a, b)`) as it specified in grammar. String literals (as shown in the example) or other expressions are also accepted.

**Comment by lukaseder** [comment]
Thanks for the pointer. The approach with adding support for such functionality is usually to look around all other databases to see if the functionality has an exact representation or if it can be emulated. So, in this case, the feature will definitely be supported for H2 as well.

**Comment by michael-simons** [comment]
I'd love to see this, too.

**Comment by lukaseder** [comment]
Thanks, @michael-simons. This would be useful, no doubt. Until we ship it as part of the API, you can already roll your own: https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating

**Comment by lukaseder** [comment]
HANA has useful functions, like these:

- `YEARS_BETWEEN`: https://help.sap.com/viewer/4fe29514fd584807ac9f2a04f6754767/2.0.02/en-US/7c0d2c161ea34def86de3f5eadd6a0af.html
- `MONTHS_BETWEEN`: https://help.sap.com/viewer/4fe29514fd584807ac9f2a04f6754767/2.0.02/en-US/9f9eb73468b04bbc9d6014d22d2bfb90.html
- `DAYS_BETWEEN`: https://help.sap.com/viewer/4fe29514fd584807ac9f2a04f6754767/2.0.02/en-US/20e16ca5751910148da4fc7ec69bae03.html

Will revisit this. It has good chances to be implemented in 3.14, finally.

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.15.0

**Comment by lukaseder** [comment]
Reopening ot make sure this also works in Redshift: #11955
