### ISSUE TITLE
Override Table.where(Condition) methods in generated tables

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8012]
With #8010 implemented, we should now generate an overridden version of the `Table.where(Condition)` overloads in order to be able to covariantly return a typed table from the generated classes.

Use case (in Kotlin):

```kotlin
inline fun Customer.fromCountry(country : String) : Customer {
    return this.where(c -> c.address().city().country().eq(country));
}

inline fun Customer.speaksAnyOf(vararg language : String) : Customer {
    return this.where(c -> exists(
        selectOne()
        .from(CUSTOMER_LANGUAGE)
        .where(CUSTOMER_LANGUAGE.LANGUAGE_CD.in(language))
        .and(CUSTOMER_LANGUAGE.CUSTOMER_ID.eq(c.CUSTOMER_ID))
    ));
}
```

Given that the type of the table doesn't really change, we can now chain these methods as follows:

```kotlin
Customer c = CUSTOMER.as("c");
ctx.select(c.FIRST_NAME, c.LAST_NAME)
   .from(c.fromCountry("Switzerland").speaksAnyOf("DE", "FR"))
   .fetch();
```

### Tasks

- [x] Runtime implementation
- [x] Feature interactions:
  - [x] Implicit path joins (the root table can have a `where()` clause)
    - [x] This required a fix for https://github.com/jOOQ/jOOQ/issues/14875
  - [x] Explicit path joins (the path table can have a `where()` clause, too, starting from 3.19)
  - [x] `LEFT JOIN` and other types of join require generating derived tables, which can cause issues with full qualification of columns in the `where()` clause
  - [x] `ON KEY` might look up the wrong table name
  - [x] Things to do before and after setting a `where()` clause:
    - [x] Aliasing tables
    - [x] Using derived column lists
    - [x] ~Using `AbstractDelegatingTable` subtypes (e.g. `WithTable`)~: Postponing this to be implemented with https://github.com/jOOQ/jOOQ/issues/15101
- [x] Code generation implementation
  - [x] Java
  - [x] Kotlin
  - [x] Scala
  - [x] A `<whereMethodOverrides/>` code generation flag to allow for turning off the codegen feature
  - [x] Generate all the overrides, not just `where(Condition)`

**Comment by raderio** [comment]
```
return this.where(c -> c.address().city().country().eq(country));
```
Unresolved reference _where_
JOOQ 3.11.11

**Comment by lukaseder** [comment]
@raderio Thank you for your comment. I'm not sure what you're expecting :) This stuff is being worked on for jOOQ 3.12, including the new `Table.where()` method: https://github.com/jOOQ/jOOQ/issues/8010

**Comment by raderio** [comment]
Oh, 3.12 is not released yet, understood, thanks.

**Comment by lukaseder** [comment]
This would be very useful for https://github.com/jOOQ/jOOQ/issues/13063

**Comment by alf** [comment]
We’ve just stumbled upon the need for this feature. We thought we’d found a really nice pattern by having methods that return `Table.where`. Unfortunately it’s a no go until this issue is resolved.

For now we’ll fall back to having methods that take the table and return conditions. Not quite as elegant. 🤷‍♂️

**Comment by lukaseder** [comment]
Thanks for the ping, @alf. I'll review this again, soon. If I remember correctly, it didn't appear simple to implement at the time. But a year later, we have a lot of improved SQL transformation capabilities.

However, I'm not sure if it will still be as beneficial to you, given the discussion in https://github.com/jOOQ/jOOQ/issues/13063, and given the fact that to-many path joins will ship with 3.19 (https://github.com/jOOQ/jOOQ/issues/13639).

A lot of these `Table.where(Condition)` expressions are probably used to correlate subqueries? And those can now be implemented elegantly. Picking up on your original suggestion of #13063:

```java
dsl.select(
    ALBUM.TITLE,
    ALBUM.tracks(
        TRACK.NUMBER,
        TRACK.TITLE,
        TRACK.LENGTH
    )
).from(ALBUM)
```

With jOOQ 3.19:

```java
dsl.select(
    ALBUM.TITLE
    multiset(
        select(
            ALBUM.track().NUMBER,
            ALBUM.track().TITLE,
            ALBUM.track().LENGTH)
        .from(ALBUM.track())
    )
)
.from(ALBUM)
```

**Comment by alf** [comment]
Thank you for the hint, however I believe we still need this feature to create derived tables.

I’d like to create Java methods that take some arguments and return a pre-filtered table, leaving projection and pagination up to the calling code. Kind of like a view. 

While this is already possible, the calling code looses the ability to call implicit join-methods and such on the resulting table.

**Comment by lukaseder** [comment]
I'll have another look later today.

**Comment by lukaseder** [comment]
Hmm, I think the main show stoppers at the time were implemented with https://github.com/jOOQ/jOOQ/issues/10353 in jOOQ 3.14. When rendering a `SelectQueryImpl`, we now transform all `InlineDerivedTable` parts to in the join tree to their equivalent derived table or table reference / `WHERE` clause additions.

This would be no different for generated code. So, I think this can definitely make it to jOOQ 3.19

**Comment by lukaseder** [comment]
There are a few fun caveats and feature interactions that need additional thought. Probably the problems already exist with the existing `Table::where` methods, but people didn't run into them as often, as the feature is probably not used as much as it will be, once generated table have more type safe `where()` overrides.

Some of these interactions include:

- Implicit path joins (the root table can have a `where()` clause)
- Explicit path joins (the path table can have a `where()` clause, too, starting from 3.19)
- `LEFT JOIN` and other types of join require generating derived tables, which can cause issues with full qualification of columns in the `where()` clause
- `ON KEY` might look up the wrong table name
- Aliasing tables before or after setting a `where()` clause

These can probably all be solved. Will report progress in the issue header.

**Comment by lukaseder** [comment]
Oh boy, I just realised that people can create tables with an "implicit" join in the `WHERE` clause. E.g.

```java
Book b = BOOK.where(BOOK.ID.eq(2));
Author a = AUTHOR.where(AUTHOR.ID.eq(BOOK.ID)); // Implicit join here

ctx.select(b.ID, a.ID)
   .from(b, a)
```

I mean, why not.

**Comment by lukaseder** [comment]
Fun fact. These aren't the same:

```java
T.as("a").where(...)
T.where(...).as("a")
```

While the former can be inlined, the latter must produce a derived table.

**Comment by lukaseder** [comment]
A first draft has been pushed and will be available in tomorrows 3.19.0-SNAPSHOT version. I'll complete this next week with more tests for feature interactions, and more generated overloads of the various `where()` methods (the current draft only overrides `where(Condition)`, not the others.

**Comment by lukaseder** [comment]
Done for jOOQ 3.19.0. In case you get to test this before the release, let me know about any feedback, as always.

Let me know if there's any other, similar feature that would add value in this area.

**Comment by lukaseder** [comment]
The inline derived table feature (`Table.where()`) now has a section in the manual: https://www.jooq.org/doc/dev/manual/sql-building/table-expressions/inline-derived-tables/

**Comment by alf** [comment]
I read through the manual and it looks good.

While it might be obvious, the fact that creating the derived table can be done inside a method isn’t mentioned. I guess I can expect a blog post in the future here. :)

I’m also exited about how this works together with path expressions. Happy to see that you’re exploring this and ironing out the kinks.

**Comment by lukaseder** [comment]
> While it might be obvious, the fact that creating the derived table can be done inside a method isn’t mentioned. I guess I can expect a blog post in the future here. :)

Yeah, subroutines were a powerful invention of the 1950s by David Wheeler! Though, I think that by now, the concept does not need re-introduction?

**Comment by alf** [comment]
You’d be surprised. 😂

It’s taken me a while to learn how to leverage jOOQ QueryParts to enable easy testing and re-use of business logic. 

The feature we’re discussing here is a new addition to my toolbox that I believe will be way easier for people to understand.

**Comment by lukaseder** [comment]
> It’s taken me a while to learn how to leverage jOOQ QueryParts to enable easy testing and re-use of business logic.

I know, this is something that has to "click" with users. The fact that *every* jOOQ query is a dynamic SQL query. But I don't know how I could better explain this. I don't want to repeat this fact on every page of the manual...

Also, SQL itself has similar tools: views and table valued functions. Oracle even has macros. I hardly see them being used in the wild, by Java developers. I don't understand why, especially views are so powerful, and they've been around since the very beginning (they're essential to [Codd's Rules](https://en.wikipedia.org/wiki/Codd%27s_12_rules)). Why do people not use them abundantly? Even with jOOQ, they're super powerful.

I don't think individual manual pages can help users embrace (or even discover) the way of thinking that you have in mind here. Though, if I ever discover a reliable way to get those "clicks", I'll definitely go all in on it, marketing wise!

> The feature we’re discussing here is a new addition to my toolbox that I believe will be way easier for people to understand.

I think this feature here is quite the power user feature. I don't want to direct too much user focus on it.

But you have a different perspective on things, which I probably couldn't reproduce in blog posts. So, why not write your own?

**Comment by alf** [comment]
I agree that this does not belong in the reference manual. I also agree that this all is hard to communicate.

I was not aware of SQL_MACRO, that’s very cool.

I’ll let you know when I publish a post about this.

**Comment by lukaseder** [comment]
> I was not aware of SQL_MACRO, that’s very cool.

I knew you'd like that :) Have you had a look at 23c JSON duality views?

- https://oracle-base.com/articles/23c/json-relational-duality-views-23c
- https://github.com/jOOQ/jOOQ/issues/14912

**Comment by lukaseder** [comment]
Huh, I just realised, this already works:

```java
ctx.select(
      AUTHOR,
      AUTHOR.book().asMultiset())
   .from(AUTHOR);
```

So, this now works as well:

```java
ctx.select(
      AUTHOR,
      AUTHOR.book().where(AUTHOR.book().TITLE.like("A%")).asMultiset())
   .from(AUTHOR);
```

**Comment by alf** [comment]
I’m glad you held off on the previous iteration for multiset implicit joins.

**Comment by lukaseder** [comment]
You mean this? https://github.com/jOOQ/jOOQ/issues/13069

**Comment by alf** [comment]
Yes, the one with lambdas. :)

**Comment by lukaseder** [comment]
Yeah, my intuition told me already then, that all of this has much more to do with paths, and correlating paths, than with the specific type of projection (e.g. `MULTISET`, `ROW`).

For example, a correlated subquery that counts the books per author is just:

```java
ctx.select(
      AUTHOR,
      field(
        selectCount()
        .from(AUTHOR.book())
        .where(AUTHOR.book().TITLE.like("A%"))
      )
   .from(AUTHOR);
```

So, the real feature here is the fact that `AUTHOR.book()` produces an "implicit correlation" (as per https://github.com/jOOQ/jOOQ/issues/14985), which I'll document in the manual, soon.
