### ISSUE TITLE
Fix known limitations of embeddable types

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8353]
jOOQ 3.12 adds support for embeddable types (#2530). The feature is very far reaching, and as such will have known limitations as of jOOQ 3.12, which are out of scope for now, but will be implemented in a later release.

### Runtime library

- [x] Subquery usages
  - [x] `SELECT (SELECT embeddable)` (scalar subquery)
  - [x] `SELECT (SELECT (SELECT embeddable))` (doubly nested scalar subquery)
- [x] Overlapping embeddables can cause difficulties with various statements and their emulations see #10499
- [x] A `NULL` value is wrapped as a non-null `Embeddable(null)` in results where it is never `null`, but we should support `NULL` as well as input
- [x] `Record1<SomeEmbeddable>.values(new SomeEmbeddable())` doesn't work (it calls `fromArray()`, which also doesn't work)
- [x] Support for `UPDATE .. SET emb1 = (SELECT emb2 ..)`. 
  - [x] Canonical, embeddable specific emulation
- [x] Predicates
  - [x] `row(emb) <op> (select emb)` emulations
- [x] `EmbeddableRecord` is somewhat of an emulation of `UDTRecord`. Perhaps, we can merge parts of the implementations or API?. Moved to #10525

### Code generator

- [x] Support placing comments on embeddables
- [x] Embeddables should have their own matcher strategy configuration
  - [x] A prerequisite seems to be to rename the XSD type `Embeddable` to `EmbeddableDefinitionType` to prevent ambiguities in Maven, similar to https://github.com/jOOQ/jOOQ/issues/7747
- [x] Embeddables referencing columns with converters must inherit their type
- [x] When an embeddable configuration never matches, a warning should be logged, as that is usually a mistake (typo, outdated config, etc)
- [x] An embeddable configuration *must* have at least one field. Otherwise, a warning should be logged.
- [x] Generate interfaces if requested (currently, the `IXYZ` interface is declared on the `EmbeddableRecord`, but not generated)
  - [x] Mutable interfaces
  - [x] ~Immutable interfaces~ (not yet tested: #10527)
- [x] Generate POJOs if requested
  - [x] Mutable POJOs
  - [x] ~Immutable POJOs~ (not yet tested: #10527)

Other limitations which are out of scope of this issue:

- #8879 Out-of-the-box operators are not always well defined in the presence of embeddable types

**Comment by lukaseder** [comment]
The embeddable type feature (#2530) proves to be a lot more difficult to implement than first expected. We'll postpone the feature, and features built on top of it, to 3.13.

**Comment by lukaseder** [comment]
To be continued in 3.15: #10527
