### ISSUE TITLE
Add code generation option to generate a synthetic, readonly ROWID column

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8388]
Since the introduction of `Table.rowid()` through #7885, we could add a code generation option that makes all records `UpdatableRecord` even in the absence of any primary keys, because the update could be done based on the `rowid()` where this is supported.

Such records would need some special flag indicating that they depend on an additional `rowid()` value to be fetched in order to be able to `store()`, `update()`, `delete()`, and `refresh()` themselves. This should be done transparently.

In addition to the above, users can opt in to prefer `rowid()`s over primary keys in predicates through an additional flag: #6168

### Tasks

- [x] Add `<readonlyRowids>` regex that matches all relevant tables that should have a synthetic, readonly `ROWID` generated
  - [x] Generated tables should override `Table.rowid()` to produce this column, rather than the default `QualifiedRowid` expression
  - [x] Generated tables should have a synthetic `ROWID` unique key on the `ROWID` column, which can be changed into a primary key using the existing `<syntheticObjects>` feature
  - [x] ~An open question is how to subtype the `QOM.QualifiedRowid` type in that case~ (moved issue to https://github.com/jOOQ/jOOQ/issues/12425)
- [x] Document the feature and its interaction with synthetic primary keys.

Related work:

- https://github.com/jOOQ/jOOQ/issues/12584

Full dialect support (including `INSERT .. RETURNING`):

- [x] Oracle
- [x] PostgreSQL
- [x] SQLite

Dialects without support for usage in `INSERT .. RETURNING` so far:

- [x] Db2 (it seems that `ROWID` cannot be projected on a data change delta table)
- [x] EXASOL
- [x] H2 (limited `RETURNING` support prior to using data change delta tables)
- [x] Informix
- [x] SQL Server (cannot use `%%physloc%%` in `OUTPUT` clause, it seems)

**Comment by lukaseder** [comment]
The tricky part here is to make sure we can return generated `ROWID` values from `INSERT` statements. E.g. with ojdbc, we can't specify `statement.executeUpdate("insert ...", new String[] { "ROWID" })`. Instead, we must activate our PL/SQL `INSERT .. RETURNING` emulation...

**Comment by lukaseder** [comment]
It's looking good for the Oracle dialect. Let's see if this works in all dialects that currently support `Table.rowid()`

**Comment by lukaseder** [comment]
@simasch: Done for jOOQ 3.16. This feature will ship with the next nightly build. It should work in Oracle, PostgreSQL, and SQLite for `UpdatableRecord`

**Comment by simasch** [comment]
@lukaseder Great can't wait to test it!

**Comment by lukaseder** [comment]
Tomorrow! :) Let me know how it goes and if you find any issues.

I'll still improve a bit on the readonly feature itself, to make sure these columns aren't doing anything they shouldn't be doing in various types of statement: https://github.com/jOOQ/jOOQ/issues/9864

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.16.0

**Comment by lukaseder** [comment]
Current state of the documentation: https://www.jooq.org/doc/dev/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-synthetic-objects/codegen-database-synthetic-readonly-rowids/
