### ISSUE TITLE
Improve procedural language abstraction API

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8450]
This issue continues the work of #6475 from version 3.12. Continued in #10528 from version 3.15

Additional subtasks include (features):

- [x] #8201 `EXECUTE` statement support (and also #9950)
- [x] #9194 `RETURN` statement support
- [x] #9192 Plain SQL statement API

Dialects:

- [x] #9952 Firebird support
