### ISSUE TITLE
Various parser bugs / missing features

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8452]
This is a continuation of https://github.com/jOOQ/jOOQ/issues/7518

----

Some features were not yet supported in the jOOQ 3.9 parser. We'll fix them all in this single issue in order not to create too many issues. Here's the list of fixed things:

### SELECT features

- [x] H2 / BigQuery `* EXCEPT (fields)` syntax (support in jOOQ first: #7921)

### Other statements

- [x] `CREATE [ index type ] INDEX` (MySQL style index types)
- [x] `ALTER TABLE .. ADD .. [ BEFORE | AFTER ]` (support in jOOQ first: #7241)
- [x] Parse and ignore some clauses of these statements:
  - [x] `ALTER TABLE ONLY ...` (`ONLY` clause in PostgreSQL)
- [x] `PRIMARY KEY CLUSTERED` and `NONCLUSTERED` (see #9561)
- [x] `PRIMARY KEY | UNIQUE (a ASC)` (can be ignored, without implementing #7899)

### Column expressions (and predicates)

- [x] All sorts of vendor-specific functions
  - [x] `RAND()`
