### ISSUE TITLE
Add support for schema DDL statements in Informix

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8459]
In informix, a schema is a `DATABASE`. We can emulate some DDL statements by operating on the `DATABASE` objects, e.g.

- [ ] `DROP SCHEMA` (see #8438)
- [ ] `ALTER SCHEMA` (see #8438)
- [ ] `CREATE SCHEMA` (see #8438)

Behind the scenes, there are some caveats when creating and dropping a database, as it is really a bit more than a schema. For example, we cannot drop the "current database". Because of these possible emulations, this will be done separately from #8421
