### ISSUE TITLE
Add support for CREATE TYPE AS <member list>

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8474]
jOOQ 3.12 has started adding DDL statement support for types with the `CREATE TYPE .. AS ENUM` statement (#7570), as well as `DROP TYPE` statements (#7774).

An important user defined type is the composite type (PostgreSQL terminology) or object type (Oracle terminology).

The SQL standard syntax is:

```
<user-defined type definition> ::=
CREATE TYPE <user-defined type body>

<user-defined type body> ::=
<schema-resolved user-defined type name>
 [ AS <representation> ]
 ...

<representation> ::=
<predefined type>
| <collection type>
| <member list>

<member list> ::=
<left paren> <member> [ { <comma> <member> }... ] <right paren>
```

I.e. the same syntax as PostgreSQL implements. We'll also support this syntax

### Tasks

- [x] Add a new `Type` meta data type? https://github.com/jOOQ/jOOQ/issues/15516
  - [x] Refactor existing `CREATE TYPE` / `DROP TYPE` support (for enums). 
- [x] DSL and QOM support
  - [x] `DROP TYPE`
  - [x] `CREATE TYPE`
  - [x] ~`ALTER TYPE`~ (will be done later: https://github.com/jOOQ/jOOQ/issues/15518)
- [x] Parser support

Future work:

- Support member functions / procedures
- Support static functions / procedures
- Support constructors

**Comment by lukaseder** [comment]
I forgot to implement `CREATE TYPE IF NOT EXISTS`
