### ISSUE TITLE
Add synthetic DDL

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9526]
In the future, we will want to provide a few synthetic DDL features, which we'll support both as DDL (in the API and parser), and through other future API related to DDL. This issue is here to track all the different efforts, and to possibly find syntactic and semantic synergies between different ideas, in order not to add "quick wins" prematurely, which could be better represented in some more generic syntax.

There are different categories of synthetic DDL:

### Dropping

Some objects are more difficult to drop than others, e.g. unnamed constraints. Some dialects support native syntax for this (`DROP PRIMARY KEY` (MySQL) or `DROP UNIQUE (a, b)` (Oracle)). Additional synthetic syntax might include.

- [ ] #9440 Dropping an unnamed `FOREIGN KEY`
- [ ] #9518 Dropping all constraints of a table
- [ ] #9519 Dropping all indexes of a table

### Moving and copying

Moving stuff with DDL is quite difficult in SQL, the same is true for copying. Some dialects support copying tables using `CREATE TABLE AS SELECT` (standard SQL) or `CREATE TABLE (LIKE ...)` (PostgreSQL). We might support:

- [ ] #9515 Moving a column between tables (or within a table)

More issues will be linked from here.
