### ISSUE TITLE
Parser cannot parse WITH in EXISTS() and other subqueries

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9553]
A similar problem as https://github.com/jOOQ/jOOQ/issues/9545. This cannot be parsed:

```sql
select exists (with a (x) as (select 1) select x from a)
```

The error is:

```
Keyword 'SELECT' expected: [1:16] select exists ([*]with a (x) as (select 1) select x from a)
```

There are numerous other places where we should be able to parse `WITH`, not just `SELECT`. These will be listed here:

- [x] `EXISTS( ... )`
- [x] `UNIQUE( ... )`
- [x] `IN ( ... )`
- [x] Quantified comparison predicates (e.g. `X = ANY ( ... )`)
- [x] `INSERT .. WITH .. SELECT` (see #11042)
- [x] Derived tables (are quite tricky as we're already having issues with unions there) (see #11602)
- [x] Scalar subqueries (are quite tricky as we're already having issues with unions there) (see #11602)
- [x] ~`MERGE .. USING` (edge case)~ (Let's fix this some time in the future, if needed)

This is just an implementation problem. The parser grammar doesn't distinguish between `WITH` and `SELECT`.

**Comment by lukaseder** [comment]
I'm expecting the derived tables and scalar subqueries to be a bit more tricky to get right. Will postpone the remaining parts of the fix for next week.
