### ISSUE TITLE
Add Table.getChecks() to return a list of check constraints

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9562]
We need a new `Check` type that models a meta model `CHECK` constraint. In the future, it could have a common super type with `Key`, which models `PRIMARY KEY`, `UNIQUE`, and `FOREIGN KEY` constraints. Currently this isn't necessary.

We need this `Check` type to be able to:

- [x] Recreate `CHECK` constraints from `Meta`, using `Meta.ddl()` (see #7629)
- [x] Create diffs for modified `CHECK` constraints (see #9425)
- [x] Support generating `CHECK` constraints in the code generator (see #7639)
- [x] ~Return `CHECK` constraints from `DatabaseMetaData` based `Meta` tables~ (JDBC's `DatabaseMetaData` doesn't support fetching `CHECK` constraints. Postponing this until we have moved 'jOOQ-meta` content to the core `jOOQ` library: #8655)
- [x] Return `CHECK` constraints from `InformationSchema` based `Meta` tables (see #9565)

**Comment by lukaseder** [comment]
All related issues will be implemented through separate tickets
