### ISSUE TITLE
Add CheckConstraint XSD type to jooq-meta.xsd

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9565]
In order to support `CHECK` constraints also from the `InformationSchema` / from `jooq-meta.xsd`, we need a new type that represents the `INFORMATION_SCHEMA.CHECK_CONSTRAINTS` table. It will be used:

- [x] #9562 To import `org.jooq.Check` at runtime (in `DSLContext.meta(InformationSchema)`)
- [x] #9562 To export `InformationSchema` at runtime (in `DSLContext.informationSchema(Table)` etc)
- [x] #7639 To generate `CHECK` constraints from `XMLDatabase`
- [x] #7639 To generate `CHECK` constraints with `XMLGenerator`

**Comment by knutwannheden** [comment]
The code generator currently generates wrong code for inline check constraints on H2, since the check name also needs escape sequences for double quotes, as the constraint name is the same as the check expression.

**Comment by knutwannheden** [comment]
> The code generator currently generates wrong code for inline check constraints on H2, since the check name also needs escape sequences for double quotes, as the constraint name is the same as the check expression.

With the `DDLDatabase` (used by the internal code generation testing) this does not appear to be a problem, since the parser "translates" the inline check constraint to a normal table constraint (i.e. using `CREATE TABLE ... CONSTRAINT` clause), in which case H2 assigns it a name (like `CONSTRAINT_2`).

**Comment by lukaseder** [comment]
> as the constraint name is the same as the check expression.

Oh wow, that's... interesting :)

**Comment by knutwannheden** [comment]
See also here: https://github.com/h2database/h2database/issues/2286
