### ISSUE TITLE
Add org.jooq.Synonym

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9574]
Some dialects support synonyms for a variety of objects. We should support them as well:

- [x] As `DSL` API (`DSL.synonym`)
- [x] As DDL statements `CREATE SYNONYM` and `DROP SYNONYM`
- [x] In the interpreter
  - [x] Make sure synonyms and tables are in the same namespace, i.e. prevent hiding each other
    - [x] Except for `PUBLIC` synonyms, which can be hidden by tables
  - [x] Make sure foreign keys can reference synonyms (the synonym will be resolved and the interpreted reference won't store it)
  - [x] ~Make sure syonyms can reference synonyms~ Postponed: https://github.com/jOOQ/jOOQ/issues/17404
  - [x] Correctly implement `CASCADE` / `RESTRICT` semantics in:
    - [x] `DROP SCHEMA` (synonyms from other schemas referencing objects in the dropped schema)
    - [x] `DROP TABLE` (synonyms referencing the dropped table)
    - [x] ~`DROP SYNONYM` (synonyms or foreign keys referencing the dropped synonym)~ We resolve synonyms at creation time of the FK. Synonyms referencing synonyms aren't supported yet, see https://github.com/jOOQ/jOOQ/issues/17404
- [x] DDL export
- [x] In the parser
  - [x] ~Add parse meta lookup support~: Postponed: https://github.com/jOOQ/jOOQ/issues/17407
- [x] Meta API
  - [x] `FilteredMeta`
  - [x] `Snapshot`
- [x] Code generation
  - [x] ~Special treatment of the `PUBLIC` pseudo synonym, if necessary~: Postponed: https://github.com/jOOQ/jOOQ/issues/17406
  - [x] Language support:
    - [x] Java
    - [x] Kotlin
    - [x] Scala

Parts of this task have been moved to a different issue, which can be implemented earlier:

- https://github.com/jOOQ/jOOQ/issues/15335
- https://github.com/jOOQ/jOOQ/issues/17382
- https://github.com/jOOQ/jOOQ/issues/17383
- https://github.com/jOOQ/jOOQ/issues/17387
- https://github.com/jOOQ/jOOQ/issues/17404
- https://github.com/jOOQ/jOOQ/issues/17405
- https://github.com/jOOQ/jOOQ/issues/17406
- https://github.com/jOOQ/jOOQ/issues/17407

This includes support:

- As meta information (`org.jooq.Synonym`)
- In the code generator
- In all meta implementations
  - Code generation based
  - XML based
  - JDBC `DatabaseMetaData` based

### Dialect support

- [x] Db2 https://www.ibm.com/docs/en/ias?topic=statements-create-alias
  - [x] DDL
  - [x] Code generation
- [x] Derby https://db.apache.org/derby/docs/10.1/ref/rrefsqljcreatesynonym.html
  - [x] DDL
  - [x] Code generation
- [x] H2 (undocumented!) https://stackoverflow.com/a/57472679/521799
  - [x] DDL
  - [x] Code generation
  - Some bugs found:
    - https://github.com/h2database/h2database/issues/4131
    - https://github.com/h2database/h2database/issues/4132
    - https://github.com/h2database/h2database/issues/4133
- [x] HANA https://help.sap.com/docs/SAP_HANA_PLATFORM/4fe29514fd584807ac9f2a04f6754767/20d5412b75191014bc7ec7e133ce5bf5.html
  - [x] DDL
  - [x] Code generation
- [x] HSQLDB https://hsqldb.org/doc/guide/databaseobjects-chapt.html#dbc_synonyms
  - [x] DDL
  - [x] Code generation
- [x] Informix https://www.ibm.com/docs/en/informix-servers/14.10?topic=statements-create-synonym-statement
  - [x] DDL
  - [x] Code generation
- [x] Oracle https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/CREATE-SYNONYM.html
  - [x] DDL
  - [x] Code generation
- [x] SQL Server https://learn.microsoft.com/en-us/sql/t-sql/statements/create-synonym-transact-sql?view=sql-server-ver16
  - [x] DDL
  - [x] Code generation

In other dialects we could:

- https://github.com/jOOQ/jOOQ/issues/17380

### Documentation

- [x] `includeSynonyms`
- [x] `generateSynonyms`
- [x] `globalSynonymReferences`
- [x] DDL
- [x] ~generateSynonymReferencesClassFooter~ (we don't have any references class footer content in the manual yet)
