### ISSUE TITLE
Add sequence flag support on jooq-meta.xsd

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9603]
Sequence flags have been introduced with jOOQ 3.13 (#7752), and will now have to be added to `jooq-meta.xsd` as well. This includes support for:

- [x] Reading them in `XMLDatabase`
- [x] Producing them in `XMLGenerator`
- [x] Reading them in `DSLContext.meta(InformationSchema)`
- [x] Producing them in `Meta.informationSchema()`

**Comment by knutwannheden** [comment]
For the `Meta.informationSchema()` part, as implemented by `InformationSchemaExport` I am unsure how we should implement this for the sequence flags. The problem is that the sequence flags are only accessible as `Field` objects (see e.g. `Sequence#getStartWith()` which returns a `Field<Number>`).

The only thing I can think of is doing an `instanceof Param`. But what should happen when this isn't the case?

**Comment by lukaseder** [comment]
Use this for now:

```java
Convert.convert(field instanceof Param ? ((Param<?>) field).getValue() : field.toString(), dataType);
```

**Comment by lukaseder** [comment]
99% of these fields are `Param`. We can think about the 1% when it happens.

**Comment by knutwannheden** [comment]
Some method names will change ro align with the SQL standard.

**Comment by lukaseder** [comment]
As discussed, we should probably allow for `BigInteger` values for these sequence flags
