### ISSUE TITLE
Add SQLDialect.H2_2_0_202

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9609]
H2 version 2.0.202 has been released on Nov 25, 2021:
http://www.h2database.com/html/changelog.html

Tasks and improvements:

- [x] Add a `SQLDialect.H2_2_0_202` and support that as the default in jOOQ
- [x] Update the built-in H2 dependency used by the `DDLDatabase`, `JPADatabase`, etc.
- [x] Aggregate function support
  - [x] Statistical functions (e.g. linear regressions)
  - [x] Bitwise aggregate functions (the naming has been streamlined and new functions have been added)
- [x] `ResultSetMetaData` changes (affects also `INFORMATION_SCHEMA.COLUMNS` queries, list may be incomplete). This means users will have to adapt their `<forcedType/>` patterns if using `H2Database`, `DDLDatabase`, `JPADatabase`, or `LiquibaseDatabase`
  - [x] The type reported for `VARCHAR` is now `CHARACTER VARYING`
  - [x] The type reported for `CLOB` is now `CHARACTER LARGE OBJECT`
  - [x] The type reported for `BLOB` is now `BINARY LARGE OBJECT`
- [x] Data change delta table support now works: https://github.com/jOOQ/jOOQ/issues/9676
  - [x] Check if this is still an issue: https://github.com/jOOQ/jOOQ/issues/12192
  - [x] This now works: https://github.com/jOOQ/jOOQ/issues/3035
  - [x] This change has shown a bug that Db2 might have already had: https://github.com/jOOQ/jOOQ/issues/12689
- [x] Review existing `ENUM` type related problems (the dictionaries are now cleaned up):
  - [x] https://github.com/jOOQ/jOOQ/issues/9162
  - [x] https://github.com/jOOQ/jOOQ/issues/11722

Known issues:

- [x] https://github.com/h2database/h2database/issues/3221 (workaround is a cast in the tests, no fix in generated SQL will be done)
- [x] https://github.com/h2database/h2database/issues/3227
- [x] `YEAR` is now a reserved word (a test uses `YEAR` as a column name). Others are, too, see: http://www.h2database.com/html/advanced.html#keywords

Backwards incompatible changes in H2:

- [x] `EXTRACT(DAY_OF_WEEK FROM ..)` now seems to return the ISO day of week, not the American, Sunday=1 based one. We won't adapt anything here, other than our test assertions.
- [x] `ALTER TABLE .. DROP .. CASCADE` has changed semantics. `CASCADE` used to be the default, but the keywords weren't supported. Now the keywords are supported as expected.
- [x] `BIT_LENGTH` now returns utf-8 length, not utf-16 length (e.g. `BIT_LENGTH('abc')` is now 24, not 48). We don't address this, just change the test assertion
- [x] `sequence.CURRVAL` no longer works, only the standard SQL syntax `CURRENT VALUE FOR sequence` works
- [x] `IDENTITY()` has been removed, see: https://github.com/h2database/h2database/issues/2763. This means `DSLContext.lastID()` won't work for H2 anymore.
- [x] `TRUNC` no longer accepts negative precisions: https://github.com/h2database/h2database/issues/3223 (will be restored, so no action needed)
- [x] `TO_DATE` and `TO_TIMESTAMP` have been removed and are available in Oracle compatibility mode only: https://github.com/h2database/h2database/issues/2511
- [x] The new `VARCHAR` length limit is `2 ^ 20`, not `2 ^ 32` anymore.
- [x] `DECIMAL` without precision / scale now means `DECIMAL(100000)` when it used to mean `DECIMAL(65535, 32767)`
- [x] `IN` with empty lists no longer works as expected, and should only work in compatibility modes: https://github.com/h2database/h2database/issues/3235
- [x] `ARRAY` types have been changed incompatibly
  - [x] The type declaration is now like in HSQLDB / the standard (e.g. `INTEGER ARRAY`), not just `ARRAY`
  - [x] The literal notation has changed incompatibly from `(1, 2)` (conflicting with `ROW`!) to the standard array literal `ARRAY[1, 2]`
- [x] `INFORMATION_SCHEMA` changes
  - [x] `INFORMATION_SCHEMA.CONSTRAINTS` has been removed, see also: https://github.com/h2database/h2database/issues/2286. This means that none of the constraints can be loaded as they could be, before. At least, the new `INFORMATION_SCHEMA` seems to be very standards compliant, so we might be able to re-use HSQLDB's queries
  - [x] `INFORMATION_SCHEMA.DOMAINS` has been changed incompatibly (we can use HSQLDB's queries, it seems)
    - [x] `TYPE_NAME` is now `DATA_TYPE`
    - [x] `PRECISION` is now `NUMERIC_PRECISION`
    - [x] `SCALE` is now `NUMERIC_SCALE`
    - [x] `IS_NULLABLE` is no longer supported, it seems that `NULL` constraints are no longer allowed on domains
  - [x] `INFORMATION_SCHEMA.COLUMNS` has a lot of incompatible changes
    - [x] New semantics of `DATA_TYPE`, which used to be the JDBC `java.sql.Types` value, and is now standards conformant (but instead, `COLUMN_TYPE` and `TYPE_NAME` are gone!)
    - [x] `IS_COMPUTED` is gone, and replaced by the standard `IS_GENERATED`
    - [x] `IS_VISIBLE` is now a `BOOLEAN` column, not a `VARCHAR` column containing `TRUE` / `FALSE`
    - [x] `SEQUENCE_NAME` is gone, and replaced by `IS_IDENTITY`
    - [ ] `CHARACTER_MAXIMUM_LENGTH` is now of type `BIGINT` and may return `Long.MAX_VALUE`, which breaks our reading of an `Integer` value.
  - [x] `INFORMATION_SCHEMA.INDEXES` has been changed incompatibly
    - [x] `NON_UNIQUE` is now `INDEX_TYPE_NAME`
    - [x] `COLUMN_NAME` is now gone and there's a new `INDEX_COLUMNS` table to properly normalise the data
  - [x] `INFORMATION_SCHEMA.FUNCTION_ALIASES` has been replaced by `ROUTINES`
  - [x] `INFORMATION_SCHEMA.SEQUENCES` has been changed incompatibly
    - [x] `MIN_VALUE` is now `MINIMUM_VALUE`
    - [x] `MAX_VALUE` is now `MAXIMUM_VALUE`
    - [x] `CYCLE` is now `CYCLE_OPTION`
- [x] Update tests to be able to test both 1.4 and 2.0 versions (our test suite doesn't account for incompatible changes, such as the array syntax yet)
- [x] R2DBC integration tests stop working
  - [x] There's a regression because of an incompatible change in the `ConnectionInfo` type (change of constructor), see: https://github.com/r2dbc/r2dbc-h2/issues/203
  - [x] The tests just never halt (!)

**Comment by katzyn** [comment]
H2 2.0.202 was released with many incompatible changes since 1.4.200.

**Comment by lukaseder** [comment]
Thanks a lot for the ping, @katzyn. Will reserve some time this week to add a new dialect to jOOQ and look into the changes. jOOQ 3.16 should then support 2.0.202.

**Comment by lukaseder** [comment]
And congrats to the release! :)

**Comment by katzyn** [comment]
> * The literal notation has changed incompatibly from `(1, 2)` (conflicting with `ROW`!) to the standard array literal `ARRAY[1, 2]`

Literal was changed in 1.4.198 I guess.

> * `INFORMATION_SCHEMA` changes

H2 2.0.202 has two independent and incompatible variants of `INFORMATION_SCHEMA`:
1. Modern one (see https://h2database.com/html/systemtables.html for documentation). It is more or less compliant with SQL/Schemata (but has various extensions).
2. Legacy one from older versions, it is used for old TCP clients and can also be toggled with `;OLD_INFORMATION_SCHEMA=TRUE` appended to JDBC connection URL, this parameter affects only this connection (session), others may use different value. I don't think you want to support it, I just want to warn you about this compatibility feature. Actually it only exists because old TCP clients can't work with modern implementation.

**Comment by lukaseder** [comment]
> Literal was changed in 1.4.198 I guess.

Yes, I remember, though I think both still worked as arrays?

> H2 2.0.202 has two independent and incompatible variants of `INFORMATION_SCHEMA`:

Thanks for the pointer. I'll move to the new one. The old one should probably still be supported when users use `SQLDialect.H2_1_4_200`, e.g. in the code generator.

**Comment by katzyn** [comment]
> Yes, I remember, though I think both still worked as arrays?

No, row values (only values) were introduced in H2 1.4.198 Beta and since this version `ARRRAY[…]` is an array literal and `ROW(…)`, `(…, …)` etc. are row value literals.

The [`ROW`](https://www.h2database.com/html/datatypes.html#row_type) data type was introduced in 2.0.202.

Casts between values of these data types were intentionally incorrect in old versions of H2 and they provided a some limited compatibility for legacy applications, but in 2.0.202 casts work as they should and `(1, 2)` is not compatible with `INT ARRAY`.

**Comment by lukaseder** [comment]
Yeah, that's what I meant. :)

**Comment by katzyn** [comment]
> * only the standard SQL syntax `CURRENT VALUE FOR sequence` works

This is actually a vendor-specific syntax supported by few database systems. Standard has only `NEXT VALUE FOR`.

`NEXT VALUE FOR` was also changed to return the same value within a processed row as required by the Standard, but it depends on compatibility mode.



> * `DECIMAL` without precision / scale now means `DECIMAL(100000)`

It actually means `NUMERIC(100000)`, but H2 2.0.202 provides information about the real data type and declared numeric type in separate standard columns in `INFORMATION_SCHEMA` (real is `NUMERIC` and declared is `DECIMAL` in this case). But H2 doesn't preserve original definitions any more, they are always normalized.

> * when it used to mean `DECIMAL(65535, 32767)`

No, it was reported in that way in JDBC metadata, but actually it meant a numeric type without fixed scale.

[`DECFLOAT`](https://www.h2database.com/html/datatypes.html#decfloat_type) can be used in H2 2.0 as an approximate replacement for old PostgreSQL-style `NUMERIC` / `DECIMAL` without parameters (but `DECFLOAT` additionally supports infinities and NaN values).

**Comment by lukaseder** [comment]
> This is actually a vendor-specific syntax supported by few database systems. Standard has only `NEXT VALUE FOR`.

Right. I first thought the problem was about `NEXT VALUE FOR`, but jOOQ already generated that for H2 before... Didn't edit the entire comment, it seems.

> No, it was reported in that way in JDBC metadata, but actually it meant a numeric type without fixed scale.

OK. But the point is that when a table is created without fixed scale (or used to be), that now truncates all values, which is quite the incompatible change! I guess there was a good reason for this?

**Comment by katzyn** [comment]
H2 2.0 is a one big incompatible change, sorry. But it is better to accumulate such changes in one major release.

Default scale is expected to be 0 for `NUMERIC` / `DECIMAL` as required by the Standard, and also various functions of H2 need to know the exact scale for these fixed-precision fixed-scale data types. There were various problems with this special case and some other weird features in many places, and every fix uncovered other issues. In H2 2.0 for every expression (with exception for JDBC parameters) its type can be determined so these problematic cases are closed.

**Comment by lukaseder** [comment]
Yeah, I've seen the standard specification in the meantime. Who would have thought :) Well, let's hope that these changes don't escalate into a Python 2 vs 3 situation.

Anyway. I can make some additional money through continued commercial-only support of H2 1.4, so I'm not necessarily on the "losing side" here ;-)

**Comment by katzyn** [comment]
[DATA_TYPE_SQL](https://h2database.com/html/functions.html#data_type_sql) may be useful to construct complete SQL definition of data type of existing column, domain, constant, etc.

**Comment by lukaseder** [comment]
Yeah, from my previous experience with H2's `INFORMATION_SCHEMA`, I'm not sure if I'm going to trust that function :)

I can manage. Sure, half of my `INFORMATION_SCHEMA` queries need to be adapted due to the incompatible changes. I guess I wouldn't have minded if things like `INDEXES.NON_UNIQUE` would have stuck around as computed columns for compatibility purposes, but anyway - this is jOOQ, and jOOQ is about dynamic SQL, so these queries are dynamic already anyway. It's not too hard to adapt.

The good thing is, that the new version has cleaned up many mistakes of the previously implemented, more "ad-hoc" interpretation of the `INFORMATION_SCHEMA`. Being standards compliant definitely helps, so I can reuse some queries from the HSQLDB, MySQL, PostgreSQL, or SQL Server integrations...

**Comment by katzyn** [comment]
Please note that `ELEMENT_TYPES` and `FIELDS` may need recursive processing, because arrays and rows may contain other arrays and rows. There is also a and non-standard `ENUM_VALUES` table for `ENUM` elements.

**Comment by katzyn** [comment]
`DATA_TYPE_SQL` was created for third-party tools and libraries, it returns internal SQL of data type and it is officially supported.

If you need to distinguish whether some column was declared as `TIMESTAMP` or `TIMESTAMP(6)` only this function and `DB_OBJECT_SQL` are able to tell you that. In all other aspects these definitions are equivalent and `INFORMATION_SCHEMA` returns 6 as `DATETIME_PRECISION` for both. Of course, they weren't created just for this purpose, some tools aren't advanced enough to re-construct definition of some object properly by themselves.

**Comment by lukaseder** [comment]
> returns internal SQL

Yeah, that can change at any time. I'm also reluctant of using such functions in PostgreSQL, for example. Anyway, I can query the dictionary, no problem...

> Of course, they weren't created just for this purpose, some tools aren't advanced enough to re-construct definition of some object properly by themselves.

Yeah, I get it, but when I read the docs of that function, I have 1000 questions, which just means I'll code against some possibly wrong assumptions (or unspecified behaviour) which will break again in 2.0.203.

**Comment by lukaseder** [comment]
> If you need to distinguish whether some column was declared as `TIMESTAMP` or `TIMESTAMP(6)`

Luckily, we don't have to distinguish between those...

**Comment by lukaseder** [comment]
Irrespective of the `INFORMATION_SCHEMA` incompatibilities (which mainly result from the fact that the previous "`INFORMATION_SCHEMA`" should have been called something like `SYS`, instead), I must say I really like how everything is now nice and clean and normalised. No regular expressions anymore to reverse engineer any data formats.

**Comment by katzyn** [comment]
H2 2.0 needs standard `<override clause>` when `GENERATED ALWAYS AS IDENTITY` column is specified in insert with some value different from `DEFAULT`, jOOQ may need to check `INFORMATION_SCHEMA.COLUMNS.IDENTITY_GENERATION`.

**Comment by lukaseder** [comment]
> H2 2.0 needs standard `<override clause>` when `GENERATED ALWAYS AS IDENTITY` column is specified in insert with some value different from `DEFAULT`, jOOQ may need to check `INFORMATION_SCHEMA.COLUMNS.IDENTITY_GENERATION`.

That's interesting, I haven't seen this clause yet. Might be a new feature in the (far away) future. Not sure if it's too useful...

**Comment by katzyn** [comment]
`OVERRIDING SYSTEM VALUE` is used in SQL dumps (`pg_dump --inserts` in PostgreSQL, `SCRIPT` in H2 2.0, possibly in others). Some data move or copy operations may need it too. `OVERRIDING USER VALUE` is also useful when rows are moved into another table with identical structure, but new keys are needed. For other operations this clause shouldn't be needed, unless someone tries to override value of identity column for a some reason. I think override clause is rarely used outside of data dumps.

**Comment by lukaseder** [comment]
Yeah, makes sense to use it in dumps. The use-case where you move data to another table with identical structure is usually archive related, where the archive table doesn't have an identity, so it won't be needed there...

Anyway, I've created a feature request for this: https://github.com/jOOQ/jOOQ/issues/12695. There was already a feature request to support SQL Server's `IDENTITY_INSERT` flag: https://github.com/jOOQ/jOOQ/issues/1818, which does the same thing, but not on a per-statement level.

Thanks a lot for letting me know!

**Comment by lukaseder** [comment]
H2 2.0 support is now integrated in jOOQ 3.16. Again, the only real challenge was to re-implement the `INFORMATION_SCHEMA` queries. It was worth the price to pay, now that domains, enum types, and some other edge cases can be generated much more easily.

The fix of the data change delta table also resolved quite a few issues with generated identities.

**Comment by katzyn** [comment]
@lukaseder
H2 2.0.204 was released with various fixes. `PARSEDATETIME` and `FORMATDATETIME` were also reimplemented. Their behavior is close to their old behavior, but `PARSEDATETIME` now returns `TIMESTAMP(9) WITH TIME ZONE` and they both support nanosecond resolution, earlier it was limited to milliseconds.

**Comment by lukaseder** [comment]
Thanks for the heads-up, @katzyn
