### ISSUE TITLE
Add more ErrorProne and Refaster checks / refactorings

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9630]
We already support a few checker-framework and ErrorProne (see #5899) checks in the `jOOQ-checker` module. We could provide additional checks and refactorings (e.g. using https://errorprone.info/docs/refaster), which do the following things:

### ErrorProne

- [x] ~Warnings when queries are run on tables missing indexes~ (moved to #9771)
- [x] ~Warnings when `update` or `delete` statements are missing a where clause~ (moved to #9771)
- [x] ~Mutable usage of DSL API~ (moved to #9771)

### Refaster

- [x] Automatic replacement of deprecated API usage. Relevant API includes:
  - [x] `RenderKeywordStyle` and `RenderNameStyle` usage
  - [x] `DSL.xyzByName()` methods
  - [x] `DSL.queryPart()` methods
  - [x] ~`DSL.not(Boolean)` method could be but should probably not be rewritten to `DSL.not(Field<Boolean>)`, as it indicates a bug (someone called `Field.equals` rather than `Field.equal`) *maybe as an error prone warning*?~ (moved to #9771)
  - [x] `DSL.groupConcat()`
  - [x] ~`JooqLogger.Level`~
    - Refactorings not easily expressed using Refaster (moved to #9771)
  - [x] `Reflect.on()` methods 
  - [x] `ArrayRecord` methods
  - [x] `Cursor.fetch(int)` and various `Cursor.fetchOneXYZ()` methods
  - [x] `Field.xyz()` methods that are deprecated and link to an alternative
  - [x] `PivotForStep.on`
  - [x] `Queries.stream()`
  - [x] `Query.getSQL(boolean)`
  - [x] ~`Record.getValue` or `Result.getValue` methods with `defaultValue` (produce conditional expression, perhaps? Or local variable)~ (moved to #9771)
  - [x] `Result.intoArray()`
  - [x] `ResultQuery.fetchLazy(int)`
  - [x] ~`SQLDialect.SQL99`~
    - Refactoring not easily expressed using Refaster (moved to #9771)
- [x] ~Rogue `COUNT(*)` usages (e.g. `ctx.fetchCount(...) == 0` to `!ctx.fetchExists(...)`)~~  (moved to #9771)

Some of these features will be offered in all editions, others in commercial editions only. The decision will be made later, once we have an overview of what we're going to offer

**Comment by knutwannheden** [comment]
> * [ ]  `DSL.not(Boolean)` method could be but should probably not be rewritten to `DSL.not(Field<Boolean>)`, as it indicates a bug (someone called `Field.equals` rather than `Field.equal`) _maybe as an error prone warning_?

Or should we just rewrite any `DSL.not(field.equals(other))` to `DSL.not(field.equal(other))`?

**Comment by lukaseder** [comment]
> Or should we just rewrite any `DSL.not(field.equals(other))` to `DSL.not(field.equal(other))`?

Not sure about rewriting, but we could definitely emit a warning! Despite the deprecation, users might not have noticed the mistake...

**Comment by lukaseder** [comment]
... but I think we can still do that later, too, e.g. in #9771

**Comment by lukaseder** [comment]
This one should not have been moved to 3.14 yet. We're almost ready to ship this. I'll check if there's anything missing to ship.

**Comment by knutwannheden** [comment]
AFAICT refactorings for almost all listed deprecated methods have been implemented. For the remaining cases the refactorings were non-trivial to implement, at least using Refaster.

As part of the documentation we still need to describe how to apply the refactorings. And as part of that I still need to figure out how to do this for Java 8.

Also note that the Java 11 support is provided by an unoffical build by @Stephan202 (see https://jitpack.io/p/PicnicSupermarket/error-prone and https://mvnrepository.com/artifact/com.github.PicnicSupermarket.error-prone).

**Comment by lukaseder** [comment]
> AFAICT refactorings for almost all listed deprecated methods have been implemented. For the remaining cases the refactorings were non-trivial to implement, at least using Refaster.

OK, I've moved the remaining ones to https://github.com/jOOQ/jOOQ/issues/9771

> As part of the documentation we still need to describe how to apply the refactorings

Right. I've created this separate issue: https://github.com/jOOQ/jOOQ/issues/9825

I'm closing this issue for 3.13. The remaining work is in other issues.

**Comment by knutwannheden** [comment]
The `ArrayRecord` and `PivotForStep` Refaster templates only make sense for the commercial editions. I need to make sure that the `.refaster` files also work with the OSS edition. Otherwise we may have to temporarily remove those templates again.
