### ISSUE TITLE
Improve Meta.diff() implementation

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9656]
jOOQ 3.13 introduced a `Meta.diff()` utility (#9425). It implements quite a few diff changes, but some things are not yet supported. These include:

### Functionality

- [ ] Changing collations of a data type
- [ ] Changing character sets of a data type

### Optimisation

- [ ] When dropping graphs of objects, there is often an "ideal" drop order which produces the fewest possible statements, dropping tables with referencing keys first, only then dropping tables with referenced keys. This could be implemented as a `DDLDiffConfiguration` flag

More issues will be added
