### ISSUE TITLE
Support logical XOR operator

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9720]
At least MySQL and derivatives support the logical `XOR` operator and for other dialects emulation is trivial.

### Tasks

- [x] Add the API
- [x] Implementation
  - [x] Native
    - [x] MS Access: https://support.microsoft.com/en-us/office/table-of-operators-e1bc04d5-8b76-429f-a252-e9223117d6bd
    - [x] MariaDB
    - [x] MemSQL
    - [x] MySQL
  - [x] Emulation with boolean `!=` (all the others)
- [x] Add parser support (operator precedence between `AND` and `OR`)

----
See also:
- https://dev.mysql.com/doc/refman/8.0/en/logical-operators.html

**Comment by lukaseder** [comment]
While rarely useful, I agree this could be a nice enhancement for completeness' sake

**Comment by lukaseder** [comment]
This was brought up on Stack Overflow: https://stackoverflow.com/a/61774165/521799

A fun idea on PostgreSQL:

```sql
with t (v) as (values (true), (false), (null))
select v1, v2, (v1::int # v2::int)::boolean
from 
  t as t1 (v1), 
  t as t2 (v2)
```

Producing:

```
v1   |v2   |bool |
-----|-----|-----|
true |true |false|
true |false|true |
true |     |     |
false|true |true |
false|false|false|
false|     |     |
     |true |     |
     |false|     |
     |     |     |
```

**Comment by katzyn** [comment]
`v1 <> v2` when `v1` and `v2` are already boolean values is fully equivalent to logical `XOR` operation, doesn't need any casts, and hypothetically can be used in any database system that supports `BOOLEAN` data type.

**Comment by katzyn** [comment]
I just wondering why bitwise XOR (existing in many databases as `BITXOR()`) may be needed to emulate such simple logical operation.

**Comment by lukaseder** [comment]
Now that you put it this way, that's quite cunning :)

> I just wondering why bitwise XOR (existing in many databases as BITXOR()) may be needed to emulate such simple logical operation.

In German, we say "I didn't see the forest because of all the trees"

**Comment by lukaseder** [comment]
Looking into this now for jOOQ 3.18. As far as the parser and operator precedence is concerned, the precedence in MySQL is `AND` > `XOR` > `OR`, as can be seen here: https://dev.mysql.com/doc/refman/8.0/en/operator-precedence.html

Can also be tested with this query:

```sql
with t(c) as (select 1 union select 0 union select null)
select 
  t1.c, t2.c, t3.c,
  t1.c or t2.c xor t3.c,
  t3.c xor t2.c or t1.c,
  t1.c and t2.c xor t3.c,
  t3.c xor t2.c and t1.c
from t t1, t t2, t t3
order by 1 desc, 2 desc, 3 desc
```

Producing:

```
|c  |c  |c  |t1.c or t2.c xor t3.c|t3.c xor t2.c or t1.c|t1.c and t2.c xor t3.c|t3.c xor t2.c and t1.c|
|---|---|---|---------------------|---------------------|----------------------|----------------------|
|1  |1  |1  |1                    |1                    |0                     |0                     |
|1  |1  |0  |1                    |1                    |1                     |1                     |
|1  |1  |   |1                    |1                    |                      |                      |
|1  |0  |1  |1                    |1                    |1                     |1                     |
|1  |0  |0  |1                    |1                    |0                     |0                     |
|1  |0  |   |1                    |1                    |                      |                      |
|1  |   |1  |1                    |1                    |                      |                      |
|1  |   |0  |1                    |1                    |                      |                      |
|1  |   |   |1                    |1                    |                      |                      |
|0  |1  |1  |0                    |0                    |1                     |1                     |
|0  |1  |0  |1                    |1                    |0                     |0                     |
|0  |1  |   |                     |                     |                      |                      |
|0  |0  |1  |1                    |1                    |1                     |1                     |
|0  |0  |0  |0                    |0                    |0                     |0                     |
|0  |0  |   |                     |                     |                      |                      |
|0  |   |1  |                     |                     |1                     |1                     |
|0  |   |0  |                     |                     |0                     |0                     |
|0  |   |   |                     |                     |                      |                      |
|   |1  |1  |                     |                     |                      |                      |
|   |1  |0  |1                    |1                    |                      |                      |
|   |1  |   |                     |                     |                      |                      |
|   |0  |1  |1                    |1                    |1                     |1                     |
|   |0  |0  |                     |                     |0                     |0                     |
|   |0  |   |                     |                     |                      |                      |
|   |   |1  |                     |                     |                      |                      |
|   |   |0  |                     |                     |                      |                      |
|   |   |   |                     |                     |                      |                      |
```

**Comment by lukaseder** [comment]
There's a lot of potential to adding these methods also to convenience API, such as `SelectConditionStep`. I'm reluctant to do so. These convenience API always had a weird feeling to them, given how much API duplication they caused, all the while being completely unnecessary. The only thing they do is move around parentheses:

```java
ctx.select(...)
   .from(...)
   .where(A.and(B))
```

vs.

```java
ctx.select(...)
   .from(...)
   .where(A).and(B)
```

The convenience API only support left-associativity, whereas the actual `Condition::and`, `Condition::or`, and `Condition::xor` API allow for putting parentheses on both sides, explicitly.

Given the fact that hardly anyone was missing this feature, I'll postpone adding convenience API until someone asks for it. Even then, we might re-consider.

**Comment by lukaseder** [comment]
Just noticed, MemSQL doesn't have native `XOR` support
