### ISSUE TITLE
Move org.jooq.meta.tools.FilePattern API to core library

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9725]
`jOOQ-meta` has a useful `FilePattern` API used internally for resolving relative file paths containing patterns, akin to the ant syntax:

```
src/main/resources/**/*.sql
```

It would be useful to move this API to the core library to allow for resolving resources, and `Source` objects and offer this API to the entire jOOQ API.

Differences to the existing API:

- [x] The new API will be more generic, less focused on the usage by `XMLDatabase` and `DDLDatabase`
- [x] A `${basedir}` feature will allow for overriding resolving relative paths from the JVM's working directory: #8335

The following features will also be moved to the core library:

- [x] Sorting algorithms (including "alphanumeric", "none", "flyway")

**Comment by lukaseder** [comment]
This is an incompatible change because of API changes and package name changes

**Comment by knutwannheden** [comment]
If we thinks this incompatibility potentially breaks a lot, we could keep a "wrapper" in jOOQ-meta in place.

**Comment by lukaseder** [comment]
I don't think that's necessary:

https://github.com/jOOQ/jOOQ/blob/3f4ffd72e6fbff8b18fb6bf4211a3fcccc45d41d/jOOQ-meta/src/main/java/org/jooq/meta/tools/FilePattern.java#L54-L59

But formally, it's still an incompatible change.

**Comment by lukaseder** [comment]
Thinking about it, I think I might still prefer to maintain this as `@Internal` API, even when it is in the core library. This isn't really key jOOQ API, but useful across a number of jOOQ auxiliary libraries, like `jOOQ`, `jOOQ-meta`, and `jOOQ-meta-extensions`.

We can remove the `@Internal` annotation once we see it is useful functionality for users as well.
