### ISSUE TITLE
Rework formatting of SQL

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9764]
Existing formatting of SQL is a mess. It works for debug logs, but is not formal at all. Sometimes, there are trailing whitespaces, sometimes there aren't. Sometimes, there are trailing newlines at the
end of the statement, sometimes there aren't.

The following tests show a few cases where formatting is quite inconsistent.

```java
@Test
public void testSelect() {
    assertFormattingEquals(
        "select 1",
        ctx.select(one())
    );

    assertFormattingEquals(
        "select \n"
      + "  1, \n"
      + "  2\n",
        ctx.select(one(), two())
    );
}

@Test
public void testSelectUnion() {
    assertFormattingEquals(
        "select 1\n"
      + "union \n"
      + "select 2",
        ctx.select(one()).union(select(two()))
    );

    assertFormattingEquals(
        "select \n"
      + "  1, \n"
      + "  2\n"
      + "union \n"
      + "select \n"
      + "  2, \n"
      + "  1\n",
        ctx.select(one(), two()).union(select(two(), one()))
    );
}
```

This issue aims at listing all the different shortcomings of formatted SQL, and tries to fix them thoroughly:

- [x] Inconsistent newlines at the end of a statement
- [x] Inconsistent whitespace at the end of lines (there should never be such whitespace)
  - [x] In `QueryPartList` (see also #9985)
- [x] https://github.com/jOOQ/jOOQ/issues/5488 Excess newline in subqueries without from clause
- [x] https://github.com/jOOQ/jOOQ/issues/3479 "Short" functions
- [x] #1962 window function formatting
- [x] #9985 Various places where a `QueryPartList` could be used, but is not used yet

This issue has synergies with #6526, where new formatting options will be introduced.

**Comment by lukaseder** [comment]
This issue can be piggybacked to implement a variety of refactorings that make some redundant code obsolete. For example, `FieldMapsForInsert::toSQLReferenceKeys` re-implements parts of the formatting logic of `QueryPartList`, but unnecessarily so.

**Comment by lukaseder** [comment]
There are probably still many missing formatting improvements, which we'll implement through new issues.
