### ISSUE TITLE
Built in SQL transformations

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9767]
The new query object model (#9163) will allow for more sophisticated pattern matching, and thus SQL transformations than we already do today. Work will be continued in #12062

This issue lists all built-in SQL transformations that will be made available out of the box via the new query object model:

### jOOQ Professional and Enterprise Editions

- [x]  #5810 `QUALIFY` support
- [x] #7265 Emulate Oracle outer join in other dialects (special case of #7312)
- [x] #7312 Transform table lists to ANSI join
- [x] #8521 Transform MySQL IN (SELECT .. LIMIT) to derived table
- [x] #11660 Oracle `CONNECT BY` support (special case)

### Flags managing transformations

- [x] `Settings.transformAnsiJoinToTableLists`
- [x] `Settings.transformInConditionSubqueryWithLimitToDerivedTable`
- [x] `Settings.transformQualify`
- [x] `Settings.transformRownum`
- [x] `Settings.transformTableListsToAnsiJoin`
- [x] `Settings.transformUnneededArithmeticExpressions`

Some flags have been published already in 3.14 as `Boolean`, when they should in fact be a 3-valued enum: `ALWAYS`, `WHEN_NEEDED`, `NEVER`, see https://github.com/jOOQ/jOOQ/issues/11802

This list will be enhanced as we identify more use cases
