### ISSUE TITLE
Various parser bugs / missing features

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9775]
This is a continuation of https://github.com/jOOQ/jOOQ/issues/8452

----

Some features were not yet supported in the jOOQ 3.9 parser. We'll fix them all in this single issue in order not to create too many issues. Here's the list of fixed things:

### SELECT features

- [x] Firebird `ROWS a TO b` syntax (for `LIMIT`)
- [x] `FOR XML` and `FOR JSON` (support in jOOQ first: #7273)

### Other statements

- [x] `NOT NULL` enforcement
- [x] `CREATE SCHEMA .. AUTHORIZATION` clauses (See #10168)
- [x] `CREATE DOMAIN ...` (PostgreSQL)
- [x] Parse and ignore these statements:
  - [x] `ALTER { SEQUENCE | TABLE | TYPE | VIEW } .. OWNER TO` (PostgreSQL) (see #10105, #10108)

### Table expressions

- [x] `TABLE()` operator

### Column expressions (and predicates)

- [x] `x = ANY(y, z)`
- [x] Oracle, PostgreSQL (and others?) `TO_CHAR` functions with formatting (see #8378, #8381)
- [x] Oracle's `TRUNC()` function (with only one argument) (see #9044)

### Literals and data types

- [x] Standard `N'...'` NVARCHAR string literal
- [x] MySQL `INSERT()` function: #10165

### Other improvements

- [x] SQL Server style optional delimiters in statement batches: `select 1 select 2`: #10164

**Comment by lukaseder** [comment]
Reopening to add some additional parser improvements for 3.14, still
