### ISSUE TITLE
Add support for spatial extensions

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#982]
This task collects all related subtasks to add support for SQL spatial extensions of various vendors. This includes:

- [x] Data types
  - [x] Geometric types (see https://www.postgresql.org/docs/current/datatype-geometric.html, (though we might be able to ignore those for now, see: https://twitter.com/lukaseder/status/1459195654119563266))
    - [x] `Geometry` (a geometry of unknown type)
    - [x] ~A geometry hierarchy~. There's no benefit of offering that in jOOQ. If users want to parse a WKT or WKB representation, they can use JTS or some other library for further processing. We could even offer out of the box data type bindings in an extension: https://github.com/jOOQ/jOOQ/issues/12738. Core jOOQ will only store the serialised form, just as for `JSON`, `JSONB`, `XML`
  - [x] Geographic types
    - [x] `Geography` (a geography of unknown type)
  - [x] `SQLDataType` type references
  - [x] Wrappers for common GIS types in jOOQ, similar to `JSON`, `JSONB`, `XML`
  - [x] ~An `SRID` class for common IDs~ Doesn't seem necessary for now
    - [x] ~A `Settings` flag that configures the default `SRID` to use when not given explicitly, but required by the server, usually `4326` (?)~
- [x] Bind variable support
  - [x] Bind types
    - [x] Bind
    - [x] Inline
    - [x] Null
  - [x] Formats
    - [x] WKT
    - [x] WKB
  - [x] In `PreparedStatement`
  - [x] In `ResultSet`
  - [x] ~In `SQLOutput` and `SQLInput` (Oracle UDTs)~ (postponed: https://github.com/jOOQ/jOOQ/issues/12736)
  - [x] ~In `CallableStatement` (stored procedures)~ (postponed: https://github.com/jOOQ/jOOQ/issues/12736)
- [x] DML support
- [x] DDL support
- [x] Function support (currently taken from PostGIS, see http://postgis.net/workshops/postgis-intro/geometries.html, http://postgis.net/workshops/postgis-intro/postgis-functions.html, check what others exist, and what good names to standardise on)
  - [x] `ST_Area`
  - [x] `ST_AsBinary`
  - [x] `ST_AsText`
  - [x] `ST_Centroid`
  - [x] `ST_Contains`
  - [x] `ST_Crosses`
  - [x] `ST_Difference`
  - [x] `ST_Distance`
  - [x] `ST_EndPoint`
  - [x] `ST_Equals`
  - [x] `ST_ExteriorRing`
  - [x] `ST_GeometryN`
  - [x] `ST_GeomFromText`
  - [x] `ST_GeomFromWKB`
  - [x] `ST_GeometryType`
  - [x] `ST_InteriorRingN`
  - [x] `ST_Intersects`
  - [x] `ST_Intersection`
  - [x] `ST_IsClosed`
  - [x] `ST_IsEmpty`
  - [x] `ST_Length`
  - [x] `ST_NumGeometries`
  - [x] `ST_NumInteriorRing`
  - [x] `ST_NumPoints`
  - [x] `ST_Overlaps`
  - [x] `ST_PointN`
  - [x] `ST_StartPoint`
  - [x] `ST_Touches`
  - [x] `ST_Union`
  - [x] `ST_Within`
  - [x] `ST_X`
  - [x] `ST_Y`
  - [x] `ST_Z`
- [x] Code generation support
- [x] Parser support
- [x] Dialect support
  - [x] CockroachDB
  - [x] MariaDB
  - [x] MySQL
    - https://dev.mysql.com/doc/refman/8.0/en/spatial-types.html
  - [x] Oracle
    - https://docs.oracle.com/en/database/oracle/oracle-database/21/spatl/
  - [x] PostgreSQL
    - Built-in geometric types: https://www.postgresql.org/docs/current/datatype-geometric.html
    - PostGIS extension: http://postgis.net/workshops/postgis-intro/index.html
  - [x] Redshift
  - [x] SQL Server
    - https://docs.microsoft.com/en-us/sql/relational-databases/spatial/spatial-data-sql-server?view=sql-server-ver15
- [x] Documentation
  - [x] Manual
    - [x] Functions
    - [x] Predicates
  - [x] https://stackoverflow.com/q/22132914/521799
  - [x] https://stackoverflow.com/q/68366928/521799

More work to be continued in jOOQ 3.17: https://github.com/jOOQ/jOOQ/issues/12736

----
See also:
- https://www.iso.org/standard/60343.html
- https://www.ogc.org/standards
- http://docs.geotools.org/latest/userguide/geotools.html#supported-formats
- https://groups.google.com/d/topic/jooq-user/saaOD4_tz4c/discussion
- https://groups.google.com/d/topic/jooq-user/sMYVnGEuLLI/discussion

**Comment by sdeleuze** [comment]
+1 for this feature request!

**Comment by lolobosse** [comment]
+1 for this feature request

**Comment by simonemurzilli** [comment]
+1 for this request

**Comment by maratynsky** [comment]
+1

**Comment by relgames** [comment]
Hi, I assume there are no plans to implement PostGIS support, as the issue remains open since 2012.
What is the current approach for GEOGRAPHY type? Custom converter?

**Comment by lukaseder** [comment]
@relgames Indeed, there's currently not a satisfactory solution to unify GIS support across major RDBMS. Unfortunately, this is all very vendor-specific, so it's quite hard for jOOQ to offer a solution.

In PostgreSQL, custom data type bindings are the way to go forward:
https://www.jooq.org/doc/latest/manual/sql-building/queryparts/custom-bindings

**Comment by JonasTaulienSolutions** [comment]
Hi @lukaseder,
I almost finished implementing a Binder for a POINT in mysql.
My Binder can successfully insert `POINT`s into the table. The problem is, that I'm not able to get JOOQ to read out `POINT` columns in their WKT (Well Known Text) representations (currently the `databaseObject` is a byte array which is the 'internal representation' of mysql. I can not find any reference to parse that.). 

I would like to modify JOOQ to read out columns of type `POINT` using `ST_AsText(<column-name>) as <column-name>`. 

If that is currently not possible could you extend the Binder interface to allow customizing how the respective SelectFieldList entry gets created?

I already found your answer to [this StackOverflow question](https://stackoverflow.com/a/44136850/4099380). But I don't think
> you might need to adapt your converter (the one inside the binding) to be able to read any type that comes back from the JDBC driver

is possible because I can not find any reference on how to parse the byte array which is the internal representation of the `POINT` in mysql.

My code so far:

```java
public class MySqlPointBinding implements Binding<Object, MySqlPointBinding.MySqlPoint> {
    @Override
    public Converter<Object, MySqlPoint> converter() {
        return new Converter<>() {
            @Override
            public MySqlPoint from(Object databaseObject) {
                if (databaseObject == null) {  return null; }

                final var dbObjAsStr = databaseObject.toString();
                final var matcher = Pattern.compile("POINT\\((.*) (.*)\\)").matcher(dbObjAsStr);
                if (matcher.matches()) {
                    final var latStr = matcher.group(1);
                    final var longStr = matcher.group(2);

                    return new MySqlPoint(Double.parseDouble(latStr), Double.parseDouble(longStr));

                } else {
                    // My code always fails here because databaseObject is a byte array
                    throw new RuntimeException("Expected " + dbObjAsStr + " to match POINT(lat long)");
                }
            }

            @Override
            public Object to(MySqlPoint userObject) {
                return "POINT(" + userObject.latitude + " " + userObject.longitude + ")";
            }

            @Override
            public Class<Object> fromType() { return Object.class; }

            @Override
            public Class<MySqlPoint> toType() { return MySqlPoint.class;}
        };
    }

    @Override
    public void sql(BindingSQLContext<MySqlPoint> ctx) throws SQLException {
        if (ctx.render().paramType() == ParamType.INLINED) {
            ctx.render().visit(DSL.function(
                "ST_PointFromText",
                Object.class,
                DSL.inline(ctx.convert(this.converter()).value()),
                DSL.inline(4326),
                DSL.inline("axis-order=lat-long")
            ));

        } else {
            ctx.render().sql("ST_PointFromText(?, 4326, 'axis-order=lat-long')");
        }
    }

    @Override
    public void register(BindingRegisterContext<MySqlPoint> ctx) throws SQLException {
        ctx.statement().registerOutParameter(ctx.index(), Types.VARCHAR);
    }

    @Override
    public void set(BindingSetStatementContext<MySqlPoint> ctx) throws SQLException {
        ctx.statement().setString(ctx.index(), Objects.toString(ctx.convert(converter()).value(), null));
    }

    @Override
    public void get(BindingGetResultSetContext<MySqlPoint> ctx) throws SQLException {
        ctx.convert(converter()).value(ctx.resultSet().getString(ctx.index()));
    }

    @Override
    public void get(BindingGetStatementContext<MySqlPoint> ctx) throws SQLException {
        ctx.convert(converter()).value(ctx.statement().getString(ctx.index()));
    }

    @Override
    public void set(BindingSetSQLOutputContext<MySqlPoint> ctx) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

    @Override
    public void get(BindingGetSQLInputContext<MySqlPoint> ctx) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

    public static class MySqlPoint {
        public final double latitude;
        public final double longitude;
        public MySqlPoint(double latitude, double longitude) {
            this.latitude = latitude;
            this.longitude = longitude;
        }
    }
}
```

Relevant section from my pom.xml:
```xml
<forcedType>
    <userType>com.example.MySqlPointBinding.MySqlPoint</userType>
    <binding>com.example.MySqlPointBinding</binding>
    <expression>.*.*</expression>
    <types>POINT</types>
</forcedType>
```

Kind regards

**Comment by lukaseder** [comment]
I'm probably way too late for your comment, @JonasTaulienSolutions. Sorry for the delay.

> I would like to modify JOOQ to read out columns of type `POINT` using `ST_AsText(<column-name>) as <column-name>`.

You should use plain SQL templating for that, currently, and write an API for this functionality:
https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating

> If that is currently not possible could you extend the Binder interface to allow customizing how the respective SelectFieldList entry gets created?

I don't think we should abuse the `org.jooq.Binding` SPI, which is strictly about bind variables. We have a feature request for rewriting entire column expressions (not just bindings) to produce new expressions: https://github.com/jOOQ/jOOQ/issues/8842, but there are still a lot of open questions about this feature.

**Comment by JonasTaulienSolutions** [comment]
Hey @lukaseder,
thanks for your reply!
You are not too late because until now, I never had to read out the `POINT` column directly. 
And when I have to read it out I will use the `DSL#function` instead of plain sql templating:
```java
dslContext.select(
    MY_TABLE.X,
    DSL
        .function(
            "ST_AsText",
            String.class,
            MY_TABLE.COORDINATES
        )
        .as("coordinates")
    MY_TABLE.Y
)
```
And then I will parse the POINT using the regex from my `MySqlPointBinding`-class.
But if I had multiple queries that read out the `MY_TABLE.COORDINATES`-column (or other columns of a `POINT`-type) I would have to write much boiler plate code.

I would like to configure JOOQ _once_ to use `ST_AsText(<column-name>)`, so in my whole Application I could write:
```java
dslContext.select(MY_TABLE.COORDINATES)
```
and get a `MySqlPoint` back as a result.

**Comment by lukaseder** [comment]
I've postponed this for a long time now. The 3.15 ship has sailed again, as we're going to support at least 4 new SQL dialects, some of which as sponsored projects.

But I'll elevate GIS support as a high priority for 3.16, recognising that this would add a lot of value to a lot of users.

**Comment by zhangjiayi1** [comment]
I finally waited for you All these years I have written native SQL in jooq to achieve

**Comment by lukaseder** [comment]
Beginning work... Will update the issue description over the next weeks. A first draft should definitely ship in jOOQ 3.16

**Comment by lukaseder** [comment]
[ISO/IEC 13249-3:2016](https://www.iso.org/standard/60343.html) only has 1350 pages, how hard can it be 😅

**Comment by lukaseder** [comment]
Can't deny, this stuff is fun

![image](https://user-images.githubusercontent.com/734593/141489698-092779b5-e93a-4f8b-877e-88e49360758c.png)

**Comment by lukaseder** [comment]
More fun with PostGIS for anyone interested: https://blog.jooq.org/fun-with-postgis-mandelbrot-set-game-of-life-and-more/

**Comment by lukaseder** [comment]
Currently looking into how to bind to `SDO_GEOMETRY` in Oracle. From a JDBC perspective, it's a simple UDT, which we could generate and translate from/to WKT. Oracle offers a `JGeometry` type, which can load a `java.sql.Struct` via `JGeometry.loadJS(Struct)`.

The jar is "hidden" in the Oracle installation:

![image](https://user-images.githubusercontent.com/734593/141963858-d3cadb99-7443-4201-aad9-0e71a6db8f8b.png)

... but not yet available from Maven Central or the usual JDBC downloads, see:

- https://www.oracle.com/database/technologies/appdev/jdbc-ucp-21-3-downloads.html
- https://twitter.com/lukaseder/status/1460538091299651586

It's probably not strictly part of ojdbc. Without the Maven Central dependency, we won't add a compile time dependency to the library, as it would complicate compiling jOOQ for our commercial customers. So, let's try reading the UDT directly.

**Comment by lukaseder** [comment]
As jOOQ 3.16 is getting towards a release, I've extracted remaining work to a new issue to be done in jOOQ 3.17: https://github.com/jOOQ/jOOQ/issues/12736

Like many others of these vast features, this is more of an epic task with continued support over several releases.

**Comment by nielsmeijer** [comment]
Great to see developments on the spatial extensions! 

For Oracle SDO_Geometry, here a code sample from the Geotools library that is used for conversion from SDO_Geometry to JTS Geometry. No dependency needed on sdoapi.jar or JGeometry.. 

See https://github.com/geotools/geotools/blob/main/modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/sdo/GeometryConverter.java

**Comment by lukaseder** [comment]
Thanks for the hint, @nielsmeijer. To bind `SDO_Geometry`, we can simply use `SDO_GEOMETRY(wkt => ?, srid => null)`. To read it, I'm currently looking at options:

- Either convert the UDT contents to WKT myself, at least for the more basic WKB types
- Alternatively, we could wrap everything in a `ST_AsText()`, call (for now), and serialise only the WKT representation, making this configurable in the future. The performance will be worse, but the correctness much better, which is probably a good tradeoff for 3.16

In either case, I'll roll my own. The LGPL of geotools isn't too compatible with jOOQ's ASL 2.0 or commercial license, especially if the files need to be tweaked.

sdoapi might be an option in the future, but it's not on Maven Central yet, so hard to add as a modular dependency. I'm in touch with Oracle regarding that: https://twitter.com/lukaseder/status/1460536666372857859 (would be the preferred approach, I'm doing that for SQL Server, which ships the spatial extensions in their JDBC driver)

There might be an out of the box binding for JTS types in the future: https://github.com/jOOQ/jOOQ/issues/12738

The problem here is (as with any custom binding) that all the built-in functions won't work with those types, in a type safe way. E.g. [`DSL.stIntersection(Field<Spatial>, Field<Spatial>):Field<Spatial>`](https://www.jooq.org/javadoc/3.16.0-SNAPSHOT/org.jooq/org/jooq/impl/DSL.html#stIntersection(org.jooq.Field,org.jooq.Field)) accepts and returns a `Field<T>` with `T extends org.jooq.Spatial`.

A future jOOQ version might implement this incompatible change here: https://github.com/jOOQ/jOOQ/issues/11088, where we retrofit `Field<T, U>` to reference both the `T` type (jOOQ/database type) and the `U` type (user defined type)

**Comment by lukaseder** [comment]
The documentation suggests that while a bit weird, parsing the `SDO_GEOMETRY` contents isn't too hard:
https://docs.oracle.com/en/database/oracle/oracle-database/21/spatl/spatial-datatypes-metadata.html

I think that's the way I'll go for now. Patching generated SQL to produce `ST_AsText()` calls everywhere seems to have too many side effects (e.g. `VARCHAR2` length limitation, implications for `DISTINCT`, `ORDER BY`, `UNION`, etc. usage outside of jOOQ's execution...)

**Comment by lukaseder** [comment]
Huh, we'll have to parse / produce these values anyway, given that `SDO_GEOMETRY` may also appear in an `OBJECT` type, in case of which the serialisation happens via `SQLInput` and `SQLOutput`... I guess that won't fit in jOOQ 3.16 anymore...

**Comment by lukaseder** [comment]
Some useful correspondences between standard SQL and Oracle: https://github.com/darold/ora2pg/issues/62

**Comment by lukaseder** [comment]
The status quo will be released. Known issues and future improvements are listed here: https://github.com/jOOQ/jOOQ/issues/12736

As mentioned before, this is still a lot of work in progress, as the topic is vast, but it's a great start and future versions will continue to improve on spatial support.

**Comment by taven** [comment]
Prior to jOOQ 3.16 I was able to parse my SQL scripts in order to generate my data models. Now with this data support it fails to parse as it requires the pro edition to support the "GEOMETRY" data type. I am using my own binding so is there a way to still parse the scripts while applying my binding without the need for the pro edition?

**Comment by lukaseder** [comment]
Thanks for your comment, @taven. I think that could qualify as a bug. I've registered https://github.com/jOOQ/jOOQ/issues/13108 for this.

The parser tends to parse commercial only features and throws an exception because the binding logic isn't available in the jOOQ Open Source Edition. But in the case of data types, we could probably simply ignore the reference as before. This is especially interesting for what I assume to be `DDLDatabase` usage?

I'll fix #13108 for jOOQ 3.16.5, which should be released this week.

**Comment by lukaseder** [comment]
Another new feature would be a new `Settings.parseIgnoreCommercialOnlyFeatures` flag, which would allow for opting out of getting these kinds of exceptions where it makes sense, syntactically (e.g. data types, built-in functions): https://github.com/jOOQ/jOOQ/issues/13109

**Comment by taven** [comment]
@lukaseder thanks as always for your speedy replies and fixes. This is indeed for `DDLDatabase` usage. I'll be on the lookout for the new version.

**Comment by lukaseder** [comment]
So, folks... This used to be one of the more popular feature requests. But now, the community is almost all tumbleweeds about it

![image](https://media.giphy.com/media/1Zbeweu52ZaQE/giphy.gif)

I'd love to hear some feedback about the implementation / design. What else needs to be done in this area? Surely, it's not complete yet. E.g. there exist many more spatial functions that need support. Emulations, perhaps, etc. Would love to get some feedback!
