### ISSUE TITLE
Add new SQL transformations

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9831]
jOOQ 3.13 introduced a first SQL transformation feature to transform ANSI JOINs to table lists (#8800). A lot of additional new SQL transformations could be added. Existing and future emulations could be retrofitted to use these transformations, instead of using some internal API.

Some new transformations include:

- [ ] #3173 Inline non-recursive CTEs
- [ ] #7265 Emulate Oracle outer join in other dialects
- [ ] #7312 Transform table lists to ANSI join

More transformations will be listed here

**Comment by lukaseder** [comment]
Closing as duplicate of #9767
