### ISSUE TITLE
Add support for readonly columns

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9864]
When working with `UpdatableRecord`, it is desireable to be able to automatically exclude some columns from the generated `INSERT` or `UPDATE` statements, because they are readonly columns. There may be different reasons for a column to be `readonly`:

- The column is marked `READONLY` in the database (if the dialect supports this)
- The column is from a view and either the entire view, or just that particular column is not updatable
- The user lacks `INSERT` or `UPDATE` grants to the column
- The column is computed using `[ GENERATED ALWAYS ] AS <expr>` (`GENERATED BY DEFAULT` does not imply readonly), see also: #9592, #11073
- There is a trigger that prevents writing to the column

Some of the above can be detected automatically by the code generator. Others have to be supplied explicitly by the user in code generation configuration, using the usual regular expression / SQL query features to match qualified or unqualified column names:

```xml
<syntheticReadonlyColumns>schema\.table\.column</syntheticReadonlyColumns>
```

### Feature set

The following features will be implemented through this issue:

- [x] Runtime meta information `DataType.readonly()` (`DataType` will be preferred over `Field` since we already have nullability and default expressions in the `DataType`)
- [x] ~DDL support to make columns readonly (To be decided. I haven't found any native `READONLY` support yet, but we might still want synthetic support for this)~ Let's skip this for now
- [x] Code generation
  - [x] Synthetic readonly configuration in code generator
  - [x] Auto-detection of readonly fields (including configuration to opt out of this)
    - [x] `ROWID` support: https://github.com/jOOQ/jOOQ/issues/8388
    - [x] For `GENERATED ALWAYS AS` columns (depends on https://github.com/jOOQ/jOOQ/issues/6492)
    - [x] For `IDENTITY` columns
    - [x] For view columns of non-updatable views
    - [x] For non-updatable columns of otherwise updatable views
  - [x] `DataTypeDefinition.readonly()`
  - [x] Code generation logic (some of these with configuration to opt out)
    - [x] `DataType.readonly()` meta data
    - [x] Generate an additional constructor without the readonly fields
      - [x] Turning this off can be made configurable: https://github.com/jOOQ/jOOQ/issues/12610
- [x] `Settings` to enable / disable runtime readonly behaviour, including error handling when users try to write to `READONLY` columns, explicitly
  - [x] For usage in `UpdatableRecord`
  - [x] For usage in DML statements
  - [x] ~For usage in `Record.set()` methods~ (This would work only with attached records, and doesn't add too much value)
  - [x] ~For usage with pessimistic locks~ (postponed: https://github.com/jOOQ/jOOQ/issues/12595)
- [x] ~`Settings` (or some other mechanism in `Configuration`) that allows for specifying which columns are read only at runtime, overriding the code-gen time specification~: Postponed: https://github.com/jOOQ/jOOQ/issues/12588
- [x] Metadata support
  - [x] Add support for `READONLY` parser syntax (along with `[ NOT ] NULL`, `DEFAULT`, etc.)
  - [x] `InformationSchema` support
- [x] Add documentation

Unaffected features (so far):

- Optimistic locking: At first, it seems that record version or timestamps should be readonly columns, at least within a record. But they definitely aren't readonly columns in queries, as jOOQ's internals will have to set and update them, so *if* there needs to be a feature interaction, it will have to work differently from the one designed here. It would be possible to create a new `Settings` flag that implements user-oriented readonly behaviour of those columns. Let's do this only if users actually request it: https://github.com/jOOQ/jOOQ/issues/12609
- Code generation of setters. Users can still set a value on a record using `Record.set(Field<T>, T)`, so turning off the generation of setters may not really be too interesting.

Tests:

- [x] DML
  - [x] `INSERT .. DEFAULT VALUES` emulation
  - [x] `INSERT .. VALUES` single row
  - [x] `INSERT .. VALUES` multiple rows
  - [x] ~`INSERT` without column list (the column list might have to be re-added?)~ (postponed, see https://github.com/jOOQ/jOOQ/issues/12775)
  - [x] `INSERT .. SELECT`
  - [x] `INSERT .. ( ON CONFLICT [ DO NOTHING | DO UPDATE ] | ON DUPLICATE KEY [ IGNORE | UPDATE ] )`
  - [x] `UPDATE`
  - [x] ~`UPDATE` multi tables~ (postponed, see https://github.com/jOOQ/jOOQ/issues/12775)
  - [x] `UPDATE .. SET (a, b) = ...` row syntax
  - [x] `UPDATE .. SET (a, b) = ...` query syntax
  - [x] `MERGE`
  - [x] `MERGE` (upsert, H2 style)
  - [x] `RETURNING` clauses
  - [x] `WITH .. RETURNING`
  - [x] Data change delta tables
- [x] Feature interactions
  - [x] ~Embeddable records~ Moved to the embeddables known issues task: https://github.com/jOOQ/jOOQ/issues/11975
  - [x] Batching
- [x] `THROW` configuration (currently can't be tested because generating SQL should not throw)

### Further work

- https://github.com/jOOQ/jOOQ/issues/12587

**Comment by lukaseder** [comment]
See also: https://github.com/jOOQ/jOOQ/issues/11073
