### ISSUE TITLE
Offer a public Maven repository for commercial distributions

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9906]
Occasionally, customers do not want to set up their local / company wide Maven repositories for simple, non mission critical projects, where external repositories do just fine.

For those customers, a hosted, password protected Maven repository would be useful, from which we'd serve our commercial distributions.

### Tasks:

- [x] Set up a Maven repository with existing content
- [x] Update build to deploy also to this repository
  - [x] For historic versions
  - [x] For published versions
  - [x] For snapshots
  - [x] ~For trial builds~ (Only available with extended trials, for now, due to license key requirement)
- [x] Update projects
  - [x] ~Integration tests~ (they're currently building locally)
  - [x] jOOQ-mcve
  - [x] ~demo~ (this will continue working with the free trial for now, which is still the ZIP download)
- [x] Add hints to ZIP file's `maven-install.sh` script et al to make sure existing users are informed
- [x] Update documentation and make this the recommended way

**Comment by CyborTronik** [comment]
Fuk I want to refund for this bullshit!!!!
How is supposed to work, shall we copy libs as in "90

**Comment by lukaseder** [comment]
Thanks for your thoughtful message and for your patience, @CyborTronik. I understand that this represents an inconvenience to our paying customers, and we'll address this in the future. In the meantime, please accept our apology and our full refund for 1 license of the jOOQ Express Edition (Monthly).

In the future, may I recommend checking out our free trial prior to making any significant purchase decisions to validate whether jOOQ will add sufficient value to your business.

**Comment by lukaseder** [comment]
Backporting the hints added to `maven-install.sh` and `maven-deploy.sh`:

- 3.18.8 (https://github.com/jOOQ/jOOQ/issues/15793)
- 3.17.17 (https://github.com/jOOQ/jOOQ/issues/15794)
- 3.16.23 (https://github.com/jOOQ/jOOQ/issues/15795)

**Comment by lukaseder** [comment]
The repository is now available at https://repo.jooq.org:

- All historic releases starting from 3.4.2 are available from https://repo.jooq.org/repo (older versions had quite a different layout in their ZIP files. I'll add those upon request, though, it's unlikely someone still needs this)
- Snapshot builds are available from https://repo.jooq.org/snapshots
- The next set of patch releases will automatically be published both as ZIP file as well as in this repo

Future work might include:

- More `maven-metadata.xml` files (currently only for snapshots, where it's more important)
- Mirroring to S3, for faster transfer. The current repository is located at Infomaniak in Switzerland, just like the website.
