### ISSUE TITLE
Some BooleanDataKey values should be reset when entering a new scope

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9981]
Our internal `BooleanDataKey` set of flags (and some other data keys) act as a stack, which is available to all `QueryPart` instances. It is used to enable / disable some specific "modes" of SQL generation, which may be context dependent.

One such example is the new `BooleanDataKey.DATA_AS_REQUIRED` flag, which indicates that when fields are aliased, the `AS` keyword is mandatory regardless of the dialect and/or `Settings`. This was introduced for #9925, where `XMLATTRIBUTES(field AS alias)` requires an `AS` keyword in both DB2 and PostgreSQL (but not in Oracle).

This flag is set in `XMLAttributesImpl` prior to generating the argument list. But if the `field` argument is a scalar subquery, then the flag should be removed again, as the scalar subquery might use other types of aliases, which should not have this `DATA_AS_REQUIRED` flag set.

This issue will investigate all of these flags, and document the ones that need to be reset to some value whenever entering a subquery (i.e. a new scope).

### Tasks

- [x] Generic implementation of the improvement
- [x] Application to:
  - [x] `BooleanDataKey`
    - [x] `DATA_AS_REQUIRED` (reset / restore wasn't implemented)
    - [x] `DATA_MANDATORY_WHERE_CLAUSE` (reset / restore wasn't implemented)
  - [x] `SimpleDataKey`
    - [x] `DATA_WINDOW_DEFINITIONS` (reset / restore was implemented manually)

These applications will not be refactored yet:

- `BooleanDataKey`
  - `DATA_RENDER_TRAILING_LIMIT_IF_APPLICABLE` (reset / restore was implemented manually)
- `SimpleDataKey`
  - `DATA_SELECT_ALIASES` (reset / restore was implemented manually)

Before implementing the above, a refactoring will be needed where `Context::data` can access the current data as well as the data that has been pushed on a `ScopeStackElement` by the `reset` call.

A part of the problem is that union subqueries are a bit special in terms of what scope they define.

**Comment by lukaseder** [comment]
Looking into this now, as I've had yet another one of these keys (`DATA_MANDATORY_WHERE_CLAUSE` from #13468), which doesn't get auto-removed in subquery scopes, producing silly queries, e.g. when rendering this:

```sql
INSERT INTO t (a, b) SELECT 1 FROM (VALUES (1)) ON CONFLICT DO NOTHING;
```

We're getting:

```sql
INSERT INTO t (a, b)
SELECT 1
FROM (
  SELECT null AS c1
  WHERE 1 = 0
  UNION ALL
  SELECT *
  FROM (VALUES (1)) AS v
  WHERE 1 = 1 -- Unwanted side-effect
) AS v
WHERE 1 = 1   -- Deliberate fix from #13468
ON CONFLICT
DO NOTHING;
```
